### ISSUE TITLE
502 bad gateway on remote server

### ISSUE THREAD

**Issue by jcdusse1981** [askmike/gekko#1026]
Hello !

I'm trying to install the bot on a debian remote server.

I followed the instructions (reverse with nginx and certbot) but i got a 502 bad gateway when i try to go on my sub.domain.tld.

Gekko is installed in /home/gekko

Here is my nginx default file : 
```
server {
    listen 80;
    listen [::]:80;
    server_name sub.domain.tld;
    return 301 https://$server_name$request_uri;
}

upstream websocket {
    server localhost:3000; // i tried 127.0.0.1 too
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    root /home/gekko; // i tried /var/www/html ; /home/gekko ; /home/gekko/web ; /home/gekko/web/vue

    ssl_certificate     /etc/letsencrypt/live/sub.domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sub.domain.tld/privkey.pem;
    add_header          Strict-Transport-Security "max-age=31536000";

    location / {
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;

            proxy_pass http://websocket;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;

            auth_basic "Restricted Content";
            auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
```

Here is my UIconfig.js : 
```
const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',
    port: 3000,
  },
  ui: {
    ssl: true,
    host: 'x.x.x.x', // my server public IP address
    port: 443,
    path: '/'
  },
  adapter: 'sqlite'
}
```

Does somebody have any idea ?

Thanks!

**Comment by askmike** [comment]
Bad gateway indicates that nginx was unable to upstream the connection (to the gekko UI). Could you make sure the UI is running on the server (the `node gekko --ui` process)? After you've checked that, can you try to access it from within the same server by doing something like:

    curl http://localhost:3000/

**Comment by adamjv90** [comment]
Is there a way to run node gekko --ui as a daemon? pm2 is popular with node application, I am unsure how the pipeline would fit in though.

**Comment by gweedobtc** [comment]
@adamjv90  you would just run it once as
````
pm2 start gekko.js --name gekko -- --ui
````
Then if an error occurs or it exits for any reason, then pm2 will just restart.

**Comment by jcdusse1981** [comment]
@askmike When i run `node gekko --ui`, i got this error : 
```
TAlib is disabled
/home/gekko/web/server.js:81
server.listen(config.api.port, config.api.host, '::', () => {
                        ^

TypeError: Cannot read property 'port' of undefined
    at Object.<anonymous> (/home/gekko/web/server.js:81:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gekko/gekko.js:43:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

Does it help ?

**Comment by jcdusse1981** [comment]
Ok, i have resolved my problem adding back this part in the UIconfig.js :
```
if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;
```

Thank you for your help :)

**Comment by holeyness** [comment]
I had a similar error, 502 gateway error. 
I was running on cent os 7 on google cloud.
Here's the fix: https://unix.stackexchange.com/questions/196907/proxy-nginx-shows-a-bad-gateway-error

**Comment by yokrysty** [comment]
@holeyness thank you 👍 
setsebool -P httpd_can_network_connect true solved my problem
