### ISSUE TITLE
Telegram :: gekko crash

### ISSUE THREAD

**Issue by netcoding** [askmike/gekko#1031]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken**
```screen -dmS gekko-BTC nodejs /opt/gekko/gekko.js --config='config-BTC.js'```

```
config.telegrambot = {
  enabled: true,
  emitUpdates: true,
  token: 'MyToken',
  botName: 'gekk0_bot'
}
```

* **Expected result**
No crash ;-)

* **Actual result**
```
    at /opt/gekko.GIT/node_modules/node-telegram-bot-api/lib/telegramPolling.js:133:17
    at tryCatcher (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Unhandled rejection Error: 502 <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

    at /opt/gekko.GIT/node_modules/node-telegram-bot-api/lib/telegramPolling.js:133:17
    at tryCatcher (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/gekko.GIT/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)`

```

**Comment by askmike** [comment]
Could you format the output/error a bit more?

Are you seeing the 502 errors in your terminal?

**Comment by netcoding** [comment]
@askmike 
sure, i see this here.

```
Unhandled rejection Error: 502 <html>
<head><title>502 Bad Gateway</title></head>
```
but is this a reason with "502 Bad Gateway" why the application crashes ?

Also i've observed in the last month that the telegram-plugin does not work reliably. the best test for this ist the application-start and the first message to the telegram-bot.

if i can help you, with anyway, please give me reply. THX.
