### ISSUE TITLE
Unsupported exchange: kraken

### ISSUE THREAD

**Issue by pushkarnagle** [askmike/gekko#1036]
I am getting `Unsupported exchange: kraken` error when trying to run Gekko via CLI. I have made changes in config.js with Kraken API and `exchange: 'kraken'`

**Comment by askmike** [comment]
Are you sure you are on the latest version of Gekko? It's working for me:

    2017-08-24 16:26:27 (INFO): Setting up Gekko in realtime mode
    2017-08-24 16:26:27 (INFO): 
    2017-08-24 16:26:27 (INFO): Setting up:
    2017-08-24 16:26:27 (INFO):    Candle writer
    2017-08-24 16:26:27 (INFO):    Store candles in a database
    2017-08-24 16:26:27 (INFO): 

    2017-08-24 16:26:27 (INFO): Setting up:
    2017-08-24 16:26:27 (INFO):    Trading Advisor
    2017-08-24 16:26:27 (INFO):    Calculate trading advice
    2017-08-24 16:26:27 (INFO):    Using the strategy: toggle-advice
    2017-08-24 16:26:27 (INFO): 

    2017-08-24 16:26:27 (INFO): Setting up:
    2017-08-24 16:26:27 (INFO):    Trader
    2017-08-24 16:26:27 (INFO):    Follows the advice and create real orders.
    2017-08-24 16:26:27 (DEBUG):  getting ticker, balance & fee from kraken
    2017-08-24 16:26:27 (INFO): 

    2017-08-24 16:26:29 (INFO): trading at kraken ACTIVE
    2017-08-24 16:26:29 (INFO): kraken trading fee will be: 0.2%
    2017-08-24 16:26:29 (INFO): kraken portfolio:
    2017-08-24 16:26:29 (INFO):    EUR: 97.745500000000
    2017-08-24 16:26:29 (INFO):    XBT: 0.000000000000
    2017-08-24 16:26:29 (INFO): Setting up:
    2017-08-24 16:26:29 (INFO):    Performance Analyzer
    2017-08-24 16:26:29 (INFO):    Analyzes performances of trades
    2017-08-24 16:26:29 (INFO): 

    2017-08-24 16:26:29 (INFO): Starting to watch the market: Kraken XBT/EUR
    2017-08-24 16:26:29 (DEBUG):  scheduling ticks
    2017-08-24 16:26:29 (DEBUG):  Requested XBT/EUR trade data from Kraken ...

**Comment by discosultan** [comment]
I have also had no issues with `kraken` identifier during past 3 releases.

**Comment by askmike** [comment]
Ah I think I got the issue:

Gekko just updated the version of the kraken dependency. Can you manually run: `npm install` to install the now required version of the kraken dep?

**Comment by pushkarnagle** [comment]
Thanks @askmike, issue is resolved now!

**Comment by pushkarnagle** [comment]
I thought this would close the issue, but I am still getting the error even after manually doing `npm install`

**Comment by askmike** [comment]
Can you try the following:

    npm list | grep kraken-api

(it should output `├─┬ kraken-api@1.0.0`)

    npm install kraken-api@1.0.0

And try again?

**Comment by decoye** [comment]
Does the same thing after 

> 

> Can you try the following:
> 
> npm list | grep kraken-api
> (it should output ├─┬ kraken-api@1.0.0)
> 
> npm install kraken-api@1.0.0
> And try again?

**Comment by askmike** [comment]
@decoye @discosultan @pushkarnagle Can you download this branch and try again?

https://github.com/askmike/gekko/tree/debug/kraken

**Comment by discosultan** [comment]
@askmike Command line with `kraken` is working fine for me

**Comment by askmike** [comment]
cool, can @decoye or @pushkarnagle try the above branch?

**Comment by decoye** [comment]
same happens here with the debug version.
From the command line.

2017-08-25 19:12:14 (INFO):     Setting up Gekko in realtime mode
2017-08-25 19:12:14 (INFO):
2017-08-25 19:12:14 (INFO):     Setting up:
2017-08-25 19:12:14 (INFO):              Trading Advisor
2017-08-25 19:12:14 (INFO):              Calculate trading advice
2017-08-25 19:12:14 (INFO):              Using the strategy: MACD
/root/debug/node_modules/kraken-api/kraken.js:31
const rawRequest = async (url, headers, data, timeout) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/debug/exchanges/kraken.js:1:76)


Gekko encountered an error and can't continue

Error:

Unsupported exchange: kraken 



Meta debug info:

Gekko version: v0.5.5
Nodejs version: v6.11.2

**Comment by askmike** [comment]
Ahhh the new version of the kraken dependency requires a newer version of
node. I'll change the dep!

**Comment by discosultan** [comment]
Makes sense. I'm running node 8.4.0.

**Comment by decoye** [comment]
But i had problems with higher node versions to run gekko in general on this server. You remember mike, i had 8.4.0 installed.
null

**Comment by askmike** [comment]
@decoye and @pushkarnagle can you try latest develop?

**Comment by decoye** [comment]
works for me as expected.
will make tests with the trader on kraken now.

**Comment by pushkarnagle** [comment]
@askmike How do I pull latest develop? I tried `git pull` and `npm install` and checked after that, but still getting Unsupported exchange: kraken error.

**Comment by decoye** [comment]
> 
> npm list | grep kraken-api
> (it should output ├─┬ kraken-api@1.0.0)
> 
> npm install kraken-api@1.0.0
> And try again?

**Comment by decoye** [comment]
hey hey, 

still im getting wrong dema candles.

> 2017-08-26 11:39:06 (DEBUG):    calculated DEMA properties for candle:
> 2017-08-26 11:39:06 (DEBUG):             long ema: 277.47685116
> 2017-08-26 11:39:06 (DEBUG):             short ema: 276.60756691
> 2017-08-26 11:39:06 (DEBUG):             diff: -0.31377
> 2017-08-26 11:39:06 (DEBUG):             DEMA age: 6 candles
> 2017-08-26 11:39:06 (DEBUG):    we are currently in a downtrend @ 274.90032000 (-0.31377)

but we have:

Long: 277.326
Short: 278.127
Diff: 0,801

**Comment by askmike** [comment]
@pushkarnagle you can run:

> git checkout develop
> git pull

@decoye not sure where the data from "we have" is from, but this is unrelated from this issue. Please open a new issue and post all relevant details.

**Comment by pushkarnagle** [comment]
@askmike Thanks! All looks good now!

**Comment by askmike** [comment]
I've actually released a new version of Gekko now (on the default stable branch). So if you want you can switch back and still have this fix :)
