### ISSUE TITLE
Postgresql error: query.on is not a function

### ISSUE THREAD

**Issue by pushkarnagle** [askmike/gekko#1041]
I am trying to use Postgresql as DB adapter. I have installed latest version, created new user and database and have granted all privileges to the new user.
But while running Gekko, I am getting below error:
```
2017-08-25 13:34:22 (DEBUG):	Check database exists: gekko
/root/gekko/plugins/postgresql/handle.js:47
  query.on('row', function(row) {
        ^

TypeError: query.on is not a function
    at /root/gekko/plugins/postgresql/handle.js:47:9
    at Connection.<anonymous> (/root/gekko/node_modules/pg/lib/client.js:153:7)
    at Connection.g (events.js:292:16)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/root/gekko/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

```

**Comment by pushkarnagle** [comment]
I installed old version of pg by `npm install pg@6.4.0` and the issue is solved!

**Comment by askmike** [comment]
great :)

**Comment by davidlondono** [comment]
Add it to the Dockerfile, is causing issues

**Comment by pushkarnagle** [comment]
Well, installing an old version gave rise to another problem. I am now using version 6.4.0 of pg, but getting below error -
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

error: syntax error at or near "ON"
    at Connection.parseE (/home/pi/gekko/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/home/pi/gekko/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/home/pi/gekko/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

EDIT: This might be helpful https://node-postgres.com/guides/upgrading
There are some changes in pg@7.0.0 onwards.

**Comment by pushkarnagle** [comment]
@askmike Can you please fix this? `query.on` is not supported in pg 7.2.0

**Comment by siedi** [comment]
I replaced pg with pg@6 in the Dockerfile and it worked like a charm. (though the library throws some deprecated warnings now)

**Comment by askmike** [comment]
@siedi would you mind submitting a PR? Thanks!
