### ISSUE TITLE
Genetic Algorithm Implementation

### ISSUE THREAD

**Issue by Gab0** [askmike/gekko#1095]
This is a simple genetic algorithm implementation for gekko.
More of an idea on how to implement GA on this bot.. actual info on readme.
Someone who actually knows about evolution methods should give a help ^^ results I already got with it are kinda ok.
https://github.com/Gab0/gekkoJaponicus

**Comment by stefangordon** [comment]
The Gekko API will spawn a new node instance for each backtest, allowing you to do as many in parallel as you want.  They are pretty slow, but at least they scale linearly.  I use a bunch of 32 core boxes and spawn 32 parallel backtests per endpoint from my GA.  Definitely something you can play with.

**Comment by thegamecat** [comment]
Very cool stuff

**Comment by Gab0** [comment]
haa so parallel backtesting just works this way... relevant changes have been made on the script.

**Comment by gweedobtc** [comment]
@Gab0 What Python version this works with? Also can you add a requirements.txt for pip

**Comment by thegamecat** [comment]
Yes so gekko supports parallel backtesting.

**Comment by Gab0** [comment]
@gweedobtc I use Python3.6; added requirements.txt there

@thegamecat Can you give some direction about GAs? Papers, modules.. Disclose secrets about your implementation : 3 
Tonight I will work on a proper algorithm..

**Comment by stefangordon** [comment]
Also worth noting that there are plenty of excellent GA implementations in all major languages.  Given you are just testing a range of float parameters you can likely use any of them without much work.  e.g. https://github.com/DEAP/deap is popular for Python.

I use https://github.com/giacomelli/GeneticSharp with the FloatingPointChromosome with a c# client myself. 

It is useful to pick a way to scale out the gekko database to a cluster to get reasonable performance.  I just have a script that downloads the gekko folder with database to each VM when it is deployed, and in my GA client I spread the HTTP calls across the array of IP addresses of my Gekko instances.

Obviously a lot of money can be saved on compute with a more thoughtful bulk backtest API implementation on the Gekko side, but there is another thread for that and it was easier to just use more compute than help implement it right now :)

**Comment by thegamecat** [comment]
I've put my latest gekko node version up here for downloading:
http://gekkowarez.com/gekko-genetic-algorithm/

**Comment by evseevnn-zz** [comment]
@thegamecat I try download it but that not full version. In the pack i cannot find run-ga-parallel-test-all.js

**Comment by thegamecat** [comment]
Ah, the page was incorrect - run-ga-parallel.js is the correct version.

**Comment by imkane** [comment]
Hey @thegamecat - thanks for sharing this :)

I'm getting an error at this step though:

```
[gekko]$ node run-ga-parallel.js
/home/gekko/run-ga-parallel.js:206
            "data": {
            ^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```
Any ideas?

**Comment by krieghof** [comment]
@imkane 
1. `git clone https://github.com/Gab0/gekkoJaponicus.git `
2. `pip install deap requests numpy `
3. Than run gekko with the ui
4. Finally cd into the cloned folder and `python evolution.py`

**Comment by imkane** [comment]
@krieghof I was referring to @thegamecat's node implementation here:
http://gekkowarez.com/gekko-genetic-algorithm/

Not the python one :)

**Comment by thegamecat** [comment]
@imkane  can you move those questions to https://github.com/askmike/gekko/issues/1102

I think I'll get this up on it's own repo shortly.

**Comment by imkane** [comment]
Done :)

**Comment by mnoseworthy** [comment]
@imkane 
There is a missing comment closure around the date range selection config line.

@thegamecat The provided version doesn't report its profit unless gekkoConfig -> paperTrader -> reportInCurrency == true

Can confirm this works great though, great work !

**Comment by thegamecat** [comment]
Thats brilliant thanks @mnoseworthy - I've updated the file.

Also the GA is now on github again in this repo: https://github.com/thegamecat/gekko-trading-stuff

**Comment by Gab0** [comment]
This GA came up with these PPO settings. How good is this?
```
{ PPO }
short = 4.000000
long = 24.000000
signal = 9.000000

[thresholds]
down = -0.550000
up = 0.666667
persistence = 4.000000


```

**Comment by jrodan** [comment]
Registration at http://gekkowarez.com/gekko-genetic-algorithm/ is not working. E-Mails will not be send out.
