### ISSUE TITLE
How long did your gekko bot last?

### ISSUE THREAD

**Issue by infohoard** [askmike/gekko#1114]
I am running gekko on a pi trading on BitFinex. Unfortunately it often doesn't successfully run longer than a few hours or few days. Often I'd wake up in the morning to find out my bot stopped running. I encountered errors such as:

-  Version 5.4: 'failed to tick in time'  (as far as I know pi doesn't have power management settings or standby mode)
-  Version 5.6: 'unable to sell Error: Invalid order: not enough exchange balance for -X.XXXXXXXX LTCUSD at XX.XX' ( I definitely have enough)

How did you guys set up your gekko?
Which version of gekko are you using?
Were you able to keep it running for a long period of time?

**Comment by UfukTogay** [comment]
I also have the same issue. Bot gave an error and quit after 3rd transaction with error message 'unable to sell Error: Invalid order: not enough exchange balance for -X.XXXXXXXX LTCUSD at XX.XX'

I'd also have enough balance and I was on BitFinex. 

Possible bug?

**Comment by askmike** [comment]
I will run a live gekko on finex, and let you guys know! Anyone else running on finex (either succesfull or logs available)?

**Comment by infohoard** [comment]
Thanks Mike.

Anyways I have an output of the 'Not enough exchange balance' error, hopefully it helps.

```
2017-09-12 12:30:30 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-12 12:30:32 (DEBUG):    Processing 6 new trades. From 2017-09-12 04:30:14 UTC to 2017-09-12 04:30:29 UTC. (a few seconds)
2017-09-12 12:30:37 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-09-12 12:30:40 (INFO):     Attempting to SELL X.XXXXXXXX LTC at Bitfinex price: XX.XX
2017-09-12 12:30:41 (ERROR):    unable to sell Error: Invalid order: not enough exchange balance for -X.XXXXXXXX LTCUSD at XX.XX
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
/home/trader/gekko/exchanges/bitfinex.js:126
        return this.retry(this.submit_order, args);
                    ^

TypeError: this.retry is not a function
    at /home/trader/gekko/exchanges/bitfinex.js:126:21
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:20)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
```

**Comment by askmike** [comment]
@hoarderjohn2 that specific bug is fixed in the develop branch (you can download it here: https://github.com/askmike/gekko/tree/develop )

Can you see if that works better?

**Comment by UfukTogay** [comment]
2017-09-14 11:29:32 (DEBUG):    we are currently in a downtrend @ 0.01565400 (-0.11507)
2017-09-14 11:29:32 (INFO):     Trader Received advice to go short. Selling  LTC
2017-09-14 11:29:33 (INFO):     Attempting to SELL X.XXXXXXXX LTC at Bitfinex price: 0.015664
2017-09-14 11:30:33 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
2017-09-14 11:30:34 (INFO):     Attempting to SELL X.XXXXXXXX LTC at Bitfinex price: 0.015638
2017-09-14 11:30:34 (ERROR):    unable to sell Error: Invalid order: not enough exchange balance for -X.XXXXXXXX LTCBTC at 0.015638
    at Request._callback (/public_html/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/public_html/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/public_html/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/public_html/gekko/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20) undefined

**Comment by infohoard** [comment]
Sure thing, trying out the dev branch's version now. Will keep you updated! :)

@KufuT 
Is that the output for the dev branch?

**Comment by infohoard** [comment]
Just received this:

' ERROR: Failed to tick in time, see https://github.com/askmike/gekko/issues/514 for details'

Hmm... what is causing this? My internet connection is stable (using ethernet cable) and i don't think there are any standby mode for raspbian on pi.

**Comment by askmike** [comment]
> ' ERROR: Failed to tick in time, see #514 for details'

That is definitely related to your rasppi not being able to run run the fetch the exchange in time, might be because of a few different reasons. Can you post full debug logs?

**Comment by infohoard** [comment]
Ah didn't managed to keep the logs.
Though I do remember there wasn't any full error trace produced for this "Failed to tick in time" error.

In any case, now running the bot for the second time. Been 10 hours and doing fine so far!

**Comment by askmike** [comment]
How Gekko works is that it asks the exchange for recent market data. It needs to ask this in an interval so that it won't miss any data. But if you see that error it means that Gekko missed that data. See #514 for details of the issue. In your case this means that for some reason Gekko was unable to ask the exchange in time.

**Comment by UfukTogay** [comment]
@hoarderjohn2 No, I am running on stable.

Using Gekko v0.5.2 and Gekko UI v0.2.0.

**Comment by infohoard** [comment]
With dev version, just received a flurry of continuous error this morning:

```
    at Request.self.callback (/home/trader/gekko-dev/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-18 06:36:07 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-18 06:36:10 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-18 06:36:12 (DEBUG):    No new trades.
2017-09-18 06:36:17 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-18 06:36:18 (ERROR):    unable to buy Error: Invalid order: not enough exchange balance for 0.01858802 LTCUSD at 51.51
    at Request._callback (/home/trader/gekko-dev/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko-dev/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-18 06:36:18 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-18 06:36:28 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-18 06:36:29 (ERROR):    unable to buy Error: Invalid order: not enough exchange balance for 0.01858802 LTCUSD at 51.51
    at Request._callback (/home/trader/gekko-dev/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko-dev/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko-dev/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined

```

It was continuously attempting to buy LTC, but the fact is, LTC was already purchased. This time however, the bot did not exit, but continuously outputting the above error for every candle update. 

Also, the dev branch sometimes i noticed the bot does not fully complete an order, and I may end up with half of my asset being USD and half in LTC.

**Comment by infohoard** [comment]
Unfortunately the latest commit for stable didn't seem to fix the issue.
Getting continuous errors and no trades.
This time though, the application does not exit upon encountering the error. 

```
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-21 07:41:27 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-21 07:41:31 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-21 07:41:32 (DEBUG):    Processing 18 new trades. From 2017-09-20 23:41:25 UTC to 2017-09-20 23:41:25 UTC. (a few seconds)
2017-09-21 07:41:39 (ERROR):    unable to buy Error: Invalid order: minimum size for LTC/USD is 0.1
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-21 07:41:39 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-21 07:41:50 (ERROR):    unable to buy Error: Invalid order: minimum size for LTC/USD is 0.1
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-21 07:41:50 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-21 07:41:51 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-21 07:41:53 (DEBUG):    Processing 22 new trades. From 2017-09-20 23:41:38 UTC to 2017-09-20 23:41:51 UTC. (a few seconds)
2017-09-21 07:42:02 (ERROR):    unable to buy Error: Invalid order: minimum size for LTC/USD is 0.1
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-21 07:42:02 (DEBUG):    Bitfinex returned an error, retrying..
2017-09-21 07:42:11 (DEBUG):    Requested LTC/USD trade data from Bitfinex ...
2017-09-21 07:42:12 (DEBUG):    Processing 5 new trades. From 2017-09-20 23:41:58 UTC to 2017-09-20 23:41:58 UTC. (a few seconds)
2017-09-21 07:42:13 (ERROR):    unable to buy Error: Invalid order: minimum size for LTC/USD is 0.1
    at Request._callback (/home/trader/gekko/node_modules/bitfinex-api-node/rest.js:66:23)
    at Request.self.callback (/home/trader/gekko/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/trader/gekko/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) undefined
2017-09-21 07:42:13 (DEBUG):    Bitfinex returned an error, retrying..
```

**Comment by askmike** [comment]
@hoarderjohn2 do you have logs that include the amount? Are you trying to trade less than 0.1 LTC?

**Comment by infohoard** [comment]
Ah didn't managed to take the entire console output.

Anyways, I am definitely trading more than 0.1 LTC.

If I'm not wrong I think it was continuously retrying the purchase even though the purchase already went through.

**Comment by HaziqDan** [comment]
Hello!
I am using gekko UI to trade BTC with trade bot.
Set StorchRSI with strategy as you like in Live Gekkos UI.
And I did set candle size 1 day and 5 day as a history data. How much time do I wait for first trade?
Because, I can't see strat spawn graph.
Please let me know.
Thanks
