### ISSUE TITLE
non-error thrown: Child process has died.       at Object.onerror (node_modules/koa/lib/context.js:105:40)       at process._tickCallback (internal/process/next_tick.js:109:7)

### ISSUE THREAD

**Issue by Dennuzzz** [askmike/gekko#1149]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Added a new strategy

* **Expected result** (what you hoped would happen)
Run the strategy

* **Actual result** (unexpected outcome)
Error while running strategy

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I installed talib 1.0.2 library already.

My log:
2017-09-21 23:33:46 (INFO):     Setting up Gekko in backtest mode
2017-09-21 23:33:46 (INFO):
2017-09-21 23:33:46 (INFO):     Setting up:
2017-09-21 23:33:46 (INFO):              Trading Advisor
2017-09-21 23:33:46 (INFO):              Calculate trading advice
2017-09-21 23:33:46 (INFO):              Using the strategy: errorstrat
2017-09-21 23:33:46 (INFO):

2017-09-21 23:33:46 (INFO):     Setting up:
2017-09-21 23:33:46 (INFO):              Paper Trader
2017-09-21 23:33:46 (INFO):              Paper trader that simulates fake trades.
2017-09-21 23:33:46 (INFO):

2017-09-21 23:33:46 (INFO):     Setting up:
2017-09-21 23:33:46 (INFO):              Performance Analyzer
2017-09-21 23:33:46 (INFO):              Analyzes performances of trades
2017-09-21 23:33:46 (INFO):

2017-09-21 23:33:46 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2017-09-21 23:33:46 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
  xxx POST /api/backtest 500 631ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/mnt/c/Users/Dennis/Desktop/linuxHomeGekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

My strategy as stated in one of the indicator examples:

//--------------------------------------------------------
var log = require('../core/log');

// Let's create our own strat
var strat = {};

// Prepare everything our method needs
strat.init = function() {
}

// What happens on every new candle?
strat.update = function(candle) {
  var settings = {
    short: 10,
    long: 21,
    signal: 9
  };

  // add the indicator to the strategy
  this.addIndicator('mymacd', 'MACD', settings);
}

// For debugging purposes.
strat.log = function() {
}

// Based on the newly calculated
// information, check if we should
// update or not.
strat.check = function() {
}

module.exports = strat;

**Comment by Dennuzzz** [comment]
Sorry, found the error. Should have used the init function instead of update..

**Comment by askmike** [comment]
great!
