### ISSUE TITLE
ReferenceError: config is not defined, with CCI from UI , fresh installation 

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#1153]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

CCI Backtest on any exchange import (launched from UI) using default settings
CCI Paper Trader on exchange exchange (launched from UI) using default settings

Similar to https://github.com/askmike/gekko/issues/1117

Same fix worked 

this.requiredHistory = config.tradingAdvisor.historySize; // line 28
Fix : this.requiredHistory = this.tradingAdvisor.historySize; // line 28

* **Expected result** (what you hoped would happen)

Normal CCI Backtest result
Normal CCI Paper Trader behavior

* **Actual result** (unexpected outcome)

Errors in both cases , only when using CCI 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Similar issue to https://github.com/askmike/gekko/issues/1117

`/home/user/gekko/strategies/CCI.js:11
  this.requiredHistory = config.tradingAdvisor.historySize;
                         ^

ReferenceError: config is not defined
    at Base.method.init (/home/user/gekko/strategies/CCI.js:11:26)
    at Base.bound [as init] (/home/user/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/user/gekko/plugins/tradingAdvisor/baseTradingMethod.js:118:8)
    at Actor.setupTradingMethod (/home/user/gekko/plugins/tradingAdvisor/tradingAdvisor.js:62:17)
    at Actor.bound [as setupTradingMethod] (/home/user/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/home/user/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/home/user/gekko/core/pluginUtil.js:95:22)
    at /home/user/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/user/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/home/user/gekko/node_modules/async/dist/async.js:1015:17)

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/user/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)

/home/user/gekko/strategies/CCI.js:11
  this.requiredHistory = config.tradingAdvisor.historySize;
                         ^

ReferenceError: config is not defined
    at Base.method.init (/home/user/gekko/strategies/CCI.js:11:26)
    at Base.bound [as init] (/home/user/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/user/gekko/plugins/tradingAdvisor/baseTradingMethod.js:118:8)
    at Actor.setupTradingMethod (/home/user/gekko/plugins/tradingAdvisor/tradingAdvisor.js:62:17)
    at Actor.bound [as setupTradingMethod] (/home/user/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/home/user/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/home/user/gekko/core/pluginUtil.js:95:22)
    at /home/user/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/user/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/home/user/gekko/node_modules/async/dist/async.js:1015:17)`

**Comment by ghost** [comment]
Oops missed https://github.com/askmike/gekko/issues/1139 

Sorry

**Comment by askmike** [comment]
Note that the fix is only applied to develop, it will be part of the next release!
