### ISSUE TITLE
getting error non-error child process has died when adding more than one talib indicator

### ISSUE THREAD

**Issue by jderiz** [askmike/gekko#1202]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

I am trying to implement my own custom strategy using multiple Indicators.

what happens when I try to backtest it is that i get the following error:

```
2017-10-12 15:06:45 (INFO):     Setting up:
2017-10-12 15:06:45 (INFO):              Performance Analyzer
2017-10-12 15:06:45 (INFO):              Analyzes performances of trades
2017-10-12 15:06:45 (INFO):     

2017-10-12 15:06:45 (INFO):             WARNING: BACKTESTING FEATURE NEEDS PROPER TESTING
2017-10-12 15:06:45 (INFO):             WARNING: ACT ON THESE NUMBERS AT YOUR OWN RISK!
  xxx POST /api/backtest 500 257ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/PycharmProjects/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)


```
the error only occurs when I add the CCI Indicator. I dont get any error from the talib core tho... any ideas?

thats my CCI config part:
`[CCI]
optInTimePeriod = 1`

**Comment by askmike** [comment]
`Child process has died.` only means the childprocess has crashed, which means there was a bug in your strat. The best way to work on strats is using the CLI interface: https://gekko.wizb.it/docs/commandline/about_the_commandline.html
