### ISSUE TITLE
ERROR LOADING DEPENDENCY talib

### ISSUE THREAD

**Issue by p0ntsNL** [askmike/gekko#1203]
Got the following error while checking a backtest.

2017-10-13 09:47:25 (INFO):     Setting up Gekko in backtest mode
2017-10-13 09:47:25 (INFO):
2017-10-13 09:47:25 (INFO):     Setting up:
2017-10-13 09:47:25 (INFO):              Trading Advisor
2017-10-13 09:47:25 (INFO):              Calculate trading advice
2017-10-13 09:47:25 (INFO):              Using the strategy: CCI
2017-10-13 09:47:25 (ERROR):    ERROR LOADING DEPENDENCY talib
  xxx POST /api/backtest 500 165ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/opt/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by askmike** [comment]
What is your OS? How did you install Talib? What version of Gekko are you running?

**Comment by p0ntsNL** [comment]
My bad, this ticket can be closed.
