### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cryptodigger** [askmike/gekko#1211]
Hello,
I am getting the following error in the installation:

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@8.7.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
```

After exiting it and trying to run "node gekko --ui" I am getting the following error:

```
TAlib is disabled
Serving Gekko UI on http://localhost:3000/

(node:1297) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:1297) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also when I am trying to run "npm install sqlite3" I am getting this error:

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.7.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/root/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
```

This might help as well: when I run "npm start" I get the following errors:

```
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-10-17T04_36_36_317Z-debug.log
```

Thanks for your help!

**Comment by askmike** [comment]
> After exiting it and trying to run "node gekko --ui" I am getting the following error:

That's not an error, it means you are installing Gekko on something without a UI (server, rasp pi) and you didn't configure the UI accordingly. See the docs.

For your other problems: Please download nodejs LTS, if that still fails manually compile sqlite, see here: https://github.com/mapbox/node-sqlite3#building-from-the-source

**Comment by cryptodigger** [comment]
I am now left with the following message:

```
TAlib is disabled
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

**Comment by askmike** [comment]
Yes: mapbox does not have precompiled binaries for your OS and your node version. You might have more luck with the nodejs LTS. And if that also fails just compile yourself. See the link I posted above.
