### ISSUE TITLE
Error: Cannot find module 'ws' after fresh installation 

### ISSUE THREAD

**Issue by lbrito1** [askmike/gekko#1238]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed gekko following the instructions in docs.

* **Expected result** (what you hoped would happen)
Web UI up and running

* **Actual result** (unexpected outcome)
```
	I'm gonna make you rich, Bud Fox. 


module.js:472
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lbrito/work/gekko/web/server.js:12:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

* **Other information**
Using Ubuntu 16.06 and Node 7.10.

**Comment by Guceri** [comment]
Did you type this after the install?
`npm install --only=production`

**Comment by askmike** [comment]
I am also confident that that is the problem, please reply here if that's not the case.
