### ISSUE TITLE
Posting to API: RequestError ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by generalectric** [askmike/gekko#1246]
My strat works fine and posts to the API for backtesting... but seldom it brakes and stops and more so when I test smaller candles. Im assuming its doing just as it says.... Timing out. I've given it a good look but I'm unable to figure out how to adjust and give it a longer timeout. Also would it make sense to have this as a config option in UIconfig.js?

    name: 'RequestError',
    message: 'Error: ESOCKETTIMEDOUT',
    cause:
     { Error: ESOCKETTIMEDOUT
         at ClientRequest.<anonymous> (/home/adm1n/gekko/node_modules/request/request.js:782:21)
         at Object.onceWrapper (events.js:293:19)
         at emitNone (events.js:86:13)
         at ClientRequest.emit (events.js:188:7)
         at Socket.emitTimeout (_http_client.js:679:10)
         at Object.onceWrapper (events.js:293:19)
         at emitNone (events.js:86:13)
         at Socket.emit (events.js:188:7)
         at Socket._onTimeout (net.js:352:8)
         at ontimeout (timers.js:386:14)
         at tryOnTimeout (timers.js:250:5)
         at Timer.listOnTimeout (timers.js:214:5) code: 'ESOCKETTIMEDOUT', connect: false },
    error:
     { Error: ESOCKETTIMEDOUT
         at ClientRequest.<anonymous> (/home/adm1n/gekko/node_modules/request/request.js:782:21)
         at Object.onceWrapper (events.js:293:19)
         at emitNone (events.js:86:13)
         at ClientRequest.emit (events.js:188:7)
         at Socket.emitTimeout (_http_client.js:679:10)
         at Object.onceWrapper (events.js:293:19)
         at emitNone (events.js:86:13)
         at Socket.emit (events.js:188:7)
         at Socket._onTimeout (net.js:352:8)
         at ontimeout (timers.js:386:14)
         at tryOnTimeout (timers.js:250:5)
         at Timer.listOnTimeout (timers.js:214:5) code: 'ESOCKETTIMEDOUT', connect: false },
    options:
     { url: 'http://localhost:3001/api/backtest',
       json: true,
       body: { gekkoConfig: [Object], data: [Object] },
       headers: { 'Content-Type': 'application/json' },
       timeout: 90000,
       method: 'POST',
       callback: [Function: RP$callback],
       transform: undefined,
       simple: true,
       resolveWithFullResponse: false,
       transform2xxOnly: false },
    response: undefined }

**Comment by generalectric** [comment]
Not 100% sure but i think this is resolved. The answer was smacking me in the face.... timeout: 90000 (90 seconds) doh!

**Comment by generalectric** [comment]
after timing with a stopwatch i found that it timed out at exactly 2 minutes every time no matter how high i set my request timeout. doing some research i found server.timeout to default to 2 minutes. adding server.timeout = 300000 (5 minutes) solved my problem. going to submit PR to have timeout option added to uiconfig
