### ISSUE TITLE
error getting trades { HTTPError

### ISSUE THREAD

**Issue by Kirbylix** [askmike/gekko#1262]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
run a tradebot at kraken with EUR <-> XBT

* **Expected result** (what you hoped would happen)
buy/ sell XBT

* **Actual result** (unexpected outcome)
```java
2017-10-29 12:34:26 (ERROR):	error getting trades { HTTPError: Response code 522 (undefined)
at stream.catch.then.data (/home/pi/gekko/node_modules/got/index.js:182:13)
at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: 'api.kraken.com',
  hostname: 'api.kraken.com',
  method: 'POST',
  path: '/0/public/Trades',
  protocol: 'https:',
  url: 'https://api.kraken.com/0/public/Trades',
  statusCode: 522,
  statusMessage: undefined,
  headers: 
   { date: 'Sun, 29 Oct 2017 12:34:26 GMT',
     'content-type': 'text/html; charset=UTF-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'set-cookie': 
      [ '__cfduid=xxxxxxxxxxxx; expires=Mon, 29-Oct-18 12:34:11 GMT; path=/; domain=.kraken.com; HttpOnly' ],
     expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
     'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
     pragma: 'no-cache',
     'x-frame-options': 'SAMEORIGIN',
     server: 'cloudflare-nginx',
     'cf-ray': 'xxxxxxxxx-DUS' } }
```

**Comment by cmroche** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out

Kraken's API is highly unreliable, this is a common error to receive. Try again later.
