### ISSUE TITLE
Bittrex: Cannot read property 'result' of null

### ISSUE THREAD

**Issue by John1231983** [askmike/gekko#1287]
I am using newest Gekko in the develop branch. I used StochRSI to trade BCC/BTC. I have very small BTC in Bittex. I used terminal and it worked well during 8 hours. However, after running about 8 hours, I got an error as below. Note that, I am using the newest bittrex API. How should i fix it?
```

2017-11-04 13:31:06 (DEBUG):	calculated StochRSI properties for candle:
2017-11-04 13:31:06 (DEBUG):		 rsi: 33.86042926
2017-11-04 13:31:06 (DEBUG):	StochRSI min:		33.47271559
2017-11-04 13:31:06 (DEBUG):	StochRSI max:		66.20333354
2017-11-04 13:31:06 (DEBUG):	StochRSI Value:		1.18
2017-11-04 13:31:06 (DEBUG):	In low since 5 candle(s)
2017-11-04 13:31:25 (DEBUG):	Requested BCC/BTC trade data from bittrex ...
2017-11-04 13:31:25 (DEBUG):	getTrades called! { descending: false }
2017-11-04 13:31:25 (DEBUG):	No new trades.
2017-11-04 13:31:45 (DEBUG):	Requested BCC/BTC trade data from bittrex ...
2017-11-04 13:31:45 (DEBUG):	getTrades called! { descending: false }
2017-11-04 13:31:46 (DEBUG):	Processing 5 new trades. From 2017-11-04 04:31:08 UTC to 2017-11-04 04:31:17 UTC. (a few seconds)
2017-11-04 13:32:05 (DEBUG):	Requested BCC/BTC trade data from bittrex ...
2017-11-04 13:32:05 (DEBUG):	getTrades called! { descending: false }
2017-11-04 13:32:05 (DEBUG):	No new trades.
2017-11-04 13:32:25 (DEBUG):	Requested BCC/BTC trade data from bittrex ...
2017-11-04 13:32:25 (DEBUG):	getTrades called! { descending: false }
2017-11-04 13:32:26 (DEBUG):	Processing 5 new trades. From 2017-11-04 04:31:38 UTC to 2017-11-04 04:31:57 UTC. (a few seconds)
2017-11-04 13:32:32 (DEBUG):	checkOrder called
/home/john/gekko/exchanges/bittrex.js:227
    var stillThere = _.find(result.result, function(o) { return o.OrderUuid === order });
                                  ^

TypeError: Cannot read property 'result' of null
    at Trader.<anonymous> (/home/john/gekko/exchanges/bittrex.js:227:35)
    at Request._callback (/home/john/gekko/node_modules/node.bittrex.api/node.bittrex.api.js:124:15)
    at Request.self.callback (/home/john/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/john/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/john/gekko/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)

```

**Comment by askmike** [comment]
Woops that's a bug! Will look at it asap. ping @imperator6
