### ISSUE TITLE
Gekko genetic algorithm v2.0 available

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#1302]
Just letting you know there is a new version of the Gekko GA.

It's much easier to use and much easier to grab now from the new Gekkowarez github. 

Contributions to this new version from Generalectric, Jules, MNoseworthy who did some really cool stuff with the original version. 

You can now get the GA here:
https://github.com/gekkowarez/gekkoga

Updated instructions etc are being added to:
http://gekkowarez.com/gekko-genetic-algorithm/

**Comment by ms121** [comment]
This is awesome, thanks for the update!

**Comment by wassimchelfi** [comment]
Hi, i'm trying to instal it, thats look awesome. Thanks

**Comment by tommypeps** [comment]
I'm trying I have error:
  async loadBreakPoint() {
        ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
what it's the node version to exec?

**Comment by uipko** [comment]
I just started to play around with Gekko. First thing (well almost) I did was writing some bash scripts to run backtests based on a range of values for the different variables.

@thegamecat would GA make backtesting more efficient compared to a number of loops over some lists for the TA variables? These loops create a config for each situation and run a backtest on it. At the end I compare the profit of each run.

**Comment by thegamecat** [comment]
Node version I use 7.6 typically. 

@uipko Pretty much the point of the GA is the find optimal thresholds quicker so I think the answer is yet. The GA does all the comparison for you and outputs the global winner across the epochs.

**Comment by uipko** [comment]
That's what I thought but couldn't find a reason why it should be faster after a short glance at the code. Comparing log files of my shell script is not totally automated but is as simple as 
`grep "simulated profit:" $1 | sed -r 's/(.*.log):.*profit:\s*(.*) USD \((.*)\)/\2\t\3\t\1/' | sort -n`

I'll try to install the GA and do some comparison.

**Comment by mxmzb** [comment]
@thegamecat do you mind having a chat with me on the discord from the gekko readme? my name is maxim there, just bump me up when you feel like it!

**Comment by blastbeng** [comment]
i'm trying to use this but i only get error on the server like this:

> 2017-11-23 16:51:41 (INFO):     Scanning local history for backtestable dateranges.
  xxx POST /api/backtest 500 827ms -
  Error: non-error thrown: Child process has died.
      at Object.onerror (/media/SATADisk/bitcoin/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  xxx POST /api/backtest 500 818ms -
  Error: non-error thrown: Child process has died.
      at Object.onerror (/media/SATADisk/bitcoin/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  xxx POST /api/backtest 500 823ms -
  Error: non-error thrown: Child process has died.
      at Object.onerror (/media/SATADisk/bitcoin/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


and on gekkoga:

> node run -c config/config.js
No previous run data, starting from scratch!
Starting training with: 4 units
{ StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/media/SATADisk/bitcoin/gekko/gekkoga/node_modules/r                                                                                            equest-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/media/SATADisk/bitcoin/gekko/gekkoga/node_mod                                                                                            ules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/media/SATADisk/bitcoin/gekko/gekkoga                                                                                            /node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/media/SATADisk/bitcoin/gekko/gekkoga/node_modules                                                                                            /request/request.js:186:22)
    at emitTwo (events.js:135:13)
    at Request.emit (events.js:224:7)
    at Request.<anonymous> (/media/SATADisk/bitcoin/gekko/gekkoga/node_modules/r                                                                                            equest/request.js:1163:10)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at IncomingMessage.<anonymous> (/media/SATADisk/bitcoin/gekko/gekkoga/node_m                                                                                            odules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',


What could be the reason?

normal gekko backtesting from cmd "node gekko.js -c config.js -b" works

**Comment by generalectric** [comment]
If you get internal server error with no relevant error info on server side or non-error its because gekko isn't even making it into processing strategy.. Usually because of invalid dataset or daterange for currency asset pair. Make sure you have your DB configured correctly and have the correct date range.

**Comment by haqpl** [comment]
**I'm trying I have error:
async loadBreakPoint() {
^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
what it's the node version to exec?**

async is an object not type as far as I know...

any sugestions?

**Comment by sombraSoft** [comment]
@haqpl use node 7.x, that should fix your problem.
