### ISSUE TITLE
Problem getting started

### ISSUE THREAD

**Issue by christhorp** [askmike/gekko#1334]
I've download and installed everything with GIT, but when I run node gekko --ui I get the following: 

	Gekko v0.5.9
	I'm gonna make you rich, Bud Fox. 

```
TAlib is disabled
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/...path.../gekko/web/../SECRET-api-keys.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at Object.<anonymous> (/Applications/MAMP/htdocs/gekko/web/apiKeyManager.js:12:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

I'm not sure if it's picking up my config.js, so tried running node gekko --config config.js and this returns the following:

```
Gekko encountered an error and can't continue

Error:

Do you understand what Gekko will do with your money? Read this first:

https://github.com/askmike/gekko/issues/201 



Meta debug info:

Gekko version: v0.5.9
Nodejs version: v8.9.1
```

Any idea what I need to do?

**Comment by christhorp** [comment]
Sorted it with some chmod :)

**Comment by askmike** [comment]
awesome!
