### ISSUE TITLE
TypeError: Cannot read property 'utc' of undefined

### ISSUE THREAD

**Issue by greenbigfrog** [askmike/gekko#1387]
https://github.com/askmike/gekko/blob/c86ce48d539a5f45cab2f2b14b59743ccccb8719/plugins/performanceAnalyzer/logger.js#L52-L53

```
/root/gekko/plugins/performanceAnalyzer/logger.js:52
    rt.entryAt.utc().format('YYYY-MM-DD HH:mm'),
               ^

TypeError: Cannot read property 'utc' of undefined
    at Logger.logRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:52:16)
    at Logger.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:131:10)
    at PerformanceAnalyzer.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:119:16)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:72:8)
    at Trader.bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at Trader.emit (events.js:211:7)
```

**Comment by greenbigfrog** [comment]
Bit more log context:
```
2017-11-30 17:59:55 (DEBUG):    Requested DOGE/BTC trade data from bittrex ...
2017-11-30 17:59:55 (DEBUG):    getTrades called! { descending: false }
2017-11-30 17:59:55 (DEBUG):    No new trades.
2017-11-30 18:00:01 (DEBUG):    checkOrder called
2017-11-30 18:00:01 (DEBUG):    checkOrder result undefined
2017-11-30 18:00:01 (INFO):     SELL was successfull
2017-11-30 18:00:01 (DEBUG):    getPortfolio called
2017-11-30 18:00:01 (DEBUG):    getPortfolio result: [ { name: 'DOGE', amount: 0 },
  { name: 'BTC', amount: 0.00946529 } ]
2017-11-30 18:00:01 (DEBUG):    getTicker called
2017-11-30 18:00:01 (DEBUG):    getTicker result { Bid: 2e-7, Ask: 2.1e-7, Last: 2.1e-7 }
2017-11-30 18:00:01 (INFO):     (PROFIT REPORT) original simulated balance:      0.00946529 BTC
2017-11-30 18:00:01 (INFO):     (PROFIT REPORT) current simulated balance:       0.00946529 BTC
2017-11-30 18:00:01 (INFO):     (PROFIT REPORT) simulated profit:                0.00000000 BTC (0.00000000%)
2017-11-30 18:00:01 (INFO):     (ROUNDTRIP) entry date (UTC)    exit date (UTC)         exposed duration        P&L     profit
/root/gekko/plugins/performanceAnalyzer/logger.js:52
    rt.entryAt.UTC().format('YYYY-MM-DD HH:mm'),
               ^

TypeError: Cannot read property 'UTC' of undefined
    at Logger.logRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:52:16)
    at Logger.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:131:10)
    at PerformanceAnalyzer.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:119:16)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:72:8)
    at Trader.bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at Trader.emit (events.js:211:7)
```

**Comment by greenbigfrog** [comment]
~~(In case anyone else runs into this issue: You can temporarily fix it, by disabling the Logger in your config file)~~ Nevermind

**Comment by greenbigfrog** [comment]
Still errors after each roundtrip:
```
2017-12-02 04:17:32 (DEBUG):    getTicker result { Bid: 0.0000374, Ask: 0.00003743, Last: 0.0000374 }
2017-12-02 04:17:32 (INFO):     (PROFIT REPORT) original simulated balance:      0.01899287 BTC
2017-12-02 04:17:32 (INFO):     (PROFIT REPORT) current simulated balance:       0.01972477 BTC
2017-12-02 04:17:32 (INFO):     (PROFIT REPORT) simulated profit:                0.00073190 BTC (3.85355136%)
2017-12-02 04:17:32 (INFO):     (ROUNDTRIP) entry date (UTC)    exit date (UTC)   exposed duration P&L     profit
/root/gekko/plugins/performanceAnalyzer/logger.js:52
    rt.entryAt.UTC().format('YYYY-MM-DD HH:mm'),
               ^

TypeError: rt.entryAt.UTC is not a function
    at Logger.logRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:52:16)
    at Logger.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/logger.js:131:10)
    at PerformanceAnalyzer.handleRoundtrip (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:119:16)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (/root/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:72:8)
    at Trader.bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:116:13)
    at Trader.emit (events.js:211:7)
    at Trader.bound [as emit] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.Trader.manager.on.trade (/root/gekko/plugins/trader/trader.js:24:10)
    at emitOne (events.js:116:13)
    at Manager.emit (events.js:211:7)
    at Manager.bound [as emit] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at async.series (/root/gekko/plugins/trader/portfolioManager.js:343:12)
    at /root/gekko/node_modules/async/dist/async.js:3853:9
    at /root/gekko/node_modules/async/dist/async.js:484:16
    at replenish (/root/gekko/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
```

**Comment by tisawe** [comment]
I solved this issue by installing installing 'utc and' 'moment' from npm.

Update: Installing 'utc' and 'moment' has caused gecko to report some values in a time format instead of a percentage. It doesn't happen all the time, but I'm sure that it's not random. It a;so seems that gekko still works correctly.

**Comment by askmike** [comment]
I think this was part of another bug that has since been fixed, if someone still experiences please reopen.

**Comment by coachdesign** [comment]
Hi, I have the same problem with Gekko 0.6.5

**Comment by askmike** [comment]
@coachdesign could you please open a new issue with some details (like what you were doing, full error log, etc)?
