### ISSUE TITLE
Cannot find module './handle'

### ISSUE THREAD

**Issue by KasperVildner** [askmike/gekko#1408]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trying to import local data

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
 Error: Cannot find module './handle'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lxrun/gekko/plugins/sqlite/writer.js:4:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
RECEIVED ERROR IN GEKKO 561570205936179
Child process has died.

Anyone with the same problem ?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by greenbigfrog** [comment]
You sure you've got all dependencies installed? `npm install --only=production`

**Comment by askmike** [comment]
Like @greenbigfrog asked, but also please share more information:

- how did you download gekko?
- what version of gekko are you running?
- can you post your UIConfig?
- what type of system do you have (OS)?

**Comment by priyochatterjee** [comment]
delete node modules.downgrade node version to 8. npm install
