### ISSUE TITLE
module.js:471 throw error #533

### ISSUE THREAD

**Issue by brtakane** [askmike/gekko#1409]
Hi,

I have just recently installed gekko, but seems that i am receiving an error when trying to open it. Error is received when trying opening with UI option or it. Any advice? a bit lost here.

module.js:471
    throw err;
    ^

Error: Cannot find module '/home/nkamikaze/gekko'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by brtakane** [comment]
I was at the wrong address. The error is:

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nkamikaze/gekko/core/util.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by greenbigfrog** [comment]
You didn't pay attention to the docs.
https://gekko.wizb.it/docs/installation/installing_gekko.html#Installing-Gekko-dependencies stat3es that you have to run `npm install --only=production` to install required dependencies
