### ISSUE TITLE
Raspberry pi starting after reboot

### ISSUE THREAD

**Issue by gigirk** [askmike/gekko#1433]
Hello good, I have a problem in doing that gekko runs after restart I have tried several ways but I can not do it correctly I always get erores type : 

I want to place it in crontab, gekko folder is in direction:
`/gekko/`

i placing

```

sudo crontab -e

@reboot sudo /usr/local/bin/node /gekko/gekko.js & 

```

with error  

```


/gekko/gekko.js:23
console.log(`
            ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:903:3
^C
[1]+  Exit 8                  sudo /usr/local/bin/node /gekko/gekko.js

```
or
```

node /gekko/gekko.js

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

module.js:544
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/gekko/core/util.js:1:76)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

```

I have already tried 

I see that it can not connect with other libraries but I do not know how to do it in a way that works. I'm not very good at Linux but I've managed to install everything correctly connecting by ssh, everything works fine but it always shuts down when closing ssh. I ask you please do a manul as I do it step by step because I have already tried and create self-executing file that ends .sh in /etc/init.d/gekko.sh but it's not going. 

thank you very much.

**Comment by michalstanko** [comment]
What is your version of Node?

`$ node --version`

**Comment by michalstanko** [comment]
Also, looks like you have to run

`$ npm install --only=production`

to install modules form package.json, such as "moment".

**Comment by gigirk** [comment]
that I did when executing it by ssh do I need to do it every time I execute it?  mi version is v9.2.0

**Comment by gigirk** [comment]
I tried with PM2 but it seems to have some problem it has also been subtracted 1700 times 
`pm2 start /gekko/gekko.js --name gekko`
with result
```

PM2        | Starting execution sequence in -fork mode- for app name:gekko id:1
PM2        | App name:gekko id:1 online
1|gekko    |     ______   ________  __    __  __    __   ______
1|gekko    |    /      \ /        |/  |  /  |/  |  /  | /      \
1|gekko    |   /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
1|gekko    |   $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
1|gekko    |   $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
1|gekko    |   $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
1|gekko    |   $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
1|gekko    |   $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
1|gekko    |    $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/
1|gekko    | Error: Cannot find module 'moment'
1|gekko    |     at Function.Module._resolveFilename (module.js:542:15)
1|gekko    |     at Function.Module._load (module.js:472:25)
1|gekko    |     at Function._load (/home/pi/.nvm/versions/node/v9.2.0/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
1|gekko    |     at Module.require (module.js:585:17)
1|gekko    |     at require (internal/module.js:11:18)
1|gekko    |     at Object.<anonymous> (/gekko/core/util.js:1:76)
1|gekko    |     at Module._compile (module.js:641:30)
1|gekko    |     at Object.Module._extensions..js (module.js:652:10)
1|gekko    |     at Module.load (module.js:560:32)
1|gekko    |     at tryModuleLoad (module.js:503:12)

```

**Comment by askmike** [comment]
> Cannot find module 'moment'

Means the dependencies are not installed. To fix run `npm install --only=production` like @michalstanko suggested. After that try running it without pm2, if that works but it doesn't with pm2 it's a problem with your nodejs installation/binary.

**Comment by gigirk** [comment]
I found the correct thing would be this command using 
`pm2 start /home/pi/gekko/gekko.js -f --name gekko -x -- --ui`
running it without `/home/pi/`
you will not find all the libraries although the main part starts
Thank you
