### ISSUE TITLE
Errors have no real stacktrace

### ISSUE THREAD

**Issue by fredericcambon** [askmike/gekko#1448]
I often have these kind of errors

```
gekko_1       |   xxx POST /api/backtest 500 774ms -
gekko_1       |
gekko_1       |   Error: non-error thrown: Child process has died.
gekko_1       |       at Object.module.exports.onerror (/usr/src/app/node_modules/koa/lib/context.js:105:40)
gekko_1       |       at process._tickCallback (internal/process/next_tick.js:103:7)
```

But they are very hard to debug without actual proper stacktrace that indicates me where the code failed :/

Any idea regarding the possibilities of improving that ? I've been using gekko only for some days so I'm not yet familiar with its inner structure.

**Comment by askmike** [comment]
I will update the docs, but this is what I am thinking:

If you are working on your own plugins or strats, it's a lot easier to use the commandline interface for Gekko. This way everything runs in a single process and debugging behaves the same as any other nodejs project. Refer how to set that up here: https://gekko.wizb.it/docs/commandline/about_the_commandline.html

Could you let me know if that would solve your problem?

**Comment by fredericcambon** [comment]
Hi ! Yes I've been using the commande line interface for my plugins and strats, it made things easier indeed :)

As for my problem specifically, I got these errors with Gekkoga which uses the Gekko API to run its backtests. Depending on the date range and/or dataset I use to run my tests, I get these errors, even though the same test setup works from the backtest CLI or the UI which is odd.

I'll try later today if I can find a way to print more info in the stacktrace and debug that.

Thanks for your help though!

**Comment by askmike** [comment]
Woa that is strange, a temp workaround for your issue would be this:

https://github.com/askmike/gekko/blob/448900d9099ff2daf5511b0a3a47f1081669bc1e/core/log.js#L34-L37

Replace those 4 lines with `this.output = console;`, this forces Gekko to log everything that happens inside the child process.

**Comment by fredericcambon** [comment]
Thanks ! It helped. Looks like there was an issue in the data I pulled from Poloniex, I was getting `Simulation based on incomplete market data` errors.

I pulled the data several times and it ended up working (pure luck). If this is of any help, here is a sample of imported data log

```
2017-12-11 19:58:22 (DEBUG):	No end date specified for importing, setting to 2017-12-11 19:58:22
2017-12-11 19:58:23 (INFO):	BTC LTC Requesting data from 2017-12-10 00:00:00, to 2017-12-10 02:00:00
2017-12-11 19:58:25 (DEBUG):	Processing 3782 new trades. From 2017-12-10 00:00:01 UTC to 2017-12-10 02:00:00 UTC. (2 hours)
2017-12-11 19:58:26 (INFO):	BTC LTC Requesting data from 2017-12-10 01:50:00, to 2017-12-10 03:50:00
2017-12-11 19:58:28 (DEBUG):	Processing 3828 new trades. From 2017-12-10 02:00:01 UTC to 2017-12-10 03:49:59 UTC. (2 hours)
2017-12-11 19:58:29 (INFO):	BTC LTC Requesting data from 2017-12-10 03:40:00, to 2017-12-10 05:40:00
2017-12-11 19:58:32 (DEBUG):	Processing 4203 new trades. From 2017-12-10 03:50:01 UTC to 2017-12-10 05:39:47 UTC. (2 hours)
2017-12-11 19:58:33 (INFO):	BTC LTC Requesting data from 2017-12-10 05:30:00, to 2017-12-10 07:30:00
2017-12-11 19:58:35 (DEBUG):	Processing 2387 new trades. From 2017-12-10 05:40:05 UTC to 2017-12-10 07:29:58 UTC. (2 hours)
2017-12-11 19:58:36 (INFO):	BTC LTC Requesting data from 2017-12-10 07:20:00, to 2017-12-10 09:20:00
2017-12-11 19:58:37 (DEBUG):	Processing 1978 new trades. From 2017-12-10 07:30:09 UTC to 2017-12-10 09:19:59 UTC. (2 hours)
2017-12-11 19:58:38 (INFO):	BTC LTC Requesting data from 2017-12-10 09:10:00, to 2017-12-10 11:10:00
2017-12-11 19:58:40 (DEBUG):	Processing 2295 new trades. From 2017-12-10 09:20:38 UTC to 2017-12-10 11:09:55 UTC. (2 hours)
2017-12-11 19:58:41 (INFO):	BTC LTC Requesting data from 2017-12-10 11:00:00, to 2017-12-10 13:00:00
2017-12-11 19:58:43 (DEBUG):	Processing 2129 new trades. From 2017-12-10 11:10:02 UTC to 2017-12-10 12:59:59 UTC. (2 hours)
2017-12-11 19:58:44 (INFO):	BTC LTC Requesting data from 2017-12-10 12:50:00, to 2017-12-10 14:50:00
2017-12-11 19:58:47 (DEBUG):	Processing 6901 new trades. From 2017-12-10 13:00:02 UTC to 2017-12-10 14:49:58 UTC. (2 hours)
2017-12-11 19:58:48 (INFO):	BTC LTC Requesting data from 2017-12-10 14:40:00, to 2017-12-10 16:40:00
2017-12-11 19:58:52 (DEBUG):	Processing 3934 new trades. From 2017-12-10 14:50:05 UTC to 2017-12-10 16:39:55 UTC. (2 hours)
2017-12-11 19:58:53 (INFO):	BTC LTC Requesting data from 2017-12-10 16:30:00, to 2017-12-10 18:30:00
2017-12-11 19:58:56 (DEBUG):	Processing 6936 new trades. From 2017-12-10 16:40:02 UTC to 2017-12-10 18:29:57 UTC. (2 hours)
2017-12-11 19:58:57 (INFO):	BTC LTC Requesting data from 2017-12-10 18:20:00, to 2017-12-10 20:20:00
2017-12-11 19:59:00 (DEBUG):	Processing 3600 new trades. From 2017-12-10 18:30:02 UTC to 2017-12-10 20:19:53 UTC. (2 hours)
2017-12-11 19:59:01 (INFO):	BTC LTC Requesting data from 2017-12-10 20:10:00, to 2017-12-10 22:10:00
2017-12-11 19:59:03 (DEBUG):	Processing 1906 new trades. From 2017-12-10 20:20:04 UTC to 2017-12-10 22:09:40 UTC. (2 hours)
2017-12-11 19:59:04 (INFO):	BTC LTC Requesting data from 2017-12-10 22:00:00, to 2017-12-11 00:00:00
2017-12-11 19:59:06 (DEBUG):	Processing 3700 new trades. From 2017-12-10 22:10:12 UTC to 2017-12-11 00:00:00 UTC. (2 hours)
2017-12-11 19:59:07 (INFO):	BTC LTC Requesting data from 2017-12-10 23:50:00, to 2017-12-11 01:50:00
2017-12-11 19:59:09 (DEBUG):	Processing 3345 new trades. From 2017-12-11 00:00:12 UTC to 2017-12-11 01:49:59 UTC. (2 hours)
2017-12-11 19:59:10 (INFO):	BTC LTC Requesting data from 2017-12-11 01:40:00, to 2017-12-11 03:40:00
2017-12-11 19:59:12 (DEBUG):	Processing 3605 new trades. From 2017-12-11 01:50:01 UTC to 2017-12-11 03:40:00 UTC. (2 hours)
2017-12-11 19:59:13 (INFO):	BTC LTC Requesting data from 2017-12-11 03:30:00, to 2017-12-11 05:30:00
2017-12-11 19:59:15 (DEBUG):	Processing 3043 new trades. From 2017-12-11 03:40:02 UTC to 2017-12-11 05:30:00 UTC. (2 hours)
2017-12-11 19:59:16 (INFO):	BTC LTC Requesting data from 2017-12-11 05:20:00, to 2017-12-11 07:20:00
2017-12-11 19:59:18 (DEBUG):	Processing 6110 new trades. From 2017-12-11 05:30:01 UTC to 2017-12-11 07:19:52 UTC. (2 hours)
2017-12-11 19:59:19 (INFO):	BTC LTC Requesting data from 2017-12-11 07:10:00, to 2017-12-11 09:10:00
2017-12-11 19:59:24 (DEBUG):	Processing 2517 new trades. From 2017-12-11 07:20:02 UTC to 2017-12-11 09:09:55 UTC. (2 hours)
2017-12-11 19:59:25 (INFO):	BTC LTC Requesting data from 2017-12-11 09:00:00, to 2017-12-11 11:00:00
2017-12-11 19:59:27 (DEBUG):	Processing 1826 new trades. From 2017-12-11 09:10:03 UTC to 2017-12-11 10:59:55 UTC. (2 hours)
2017-12-11 19:59:28 (INFO):	BTC LTC Requesting data from 2017-12-11 10:50:00, to 2017-12-11 12:50:00
2017-12-11 19:59:30 (DEBUG):	Processing 2637 new trades. From 2017-12-11 11:00:02 UTC to 2017-12-11 12:49:56 UTC. (2 hours)
2017-12-11 19:59:31 (INFO):	BTC LTC Requesting data from 2017-12-11 12:40:00, to 2017-12-11 14:40:00
2017-12-11 19:59:35 (DEBUG):	Processing 14683 new trades. From 2017-12-11 12:50:15 UTC to 2017-12-11 14:40:00 UTC. (2 hours)
2017-12-11 19:59:36 (INFO):	BTC LTC Requesting data from 2017-12-11 14:30:00, to 2017-12-11 16:30:00
2017-12-11 19:59:39 (DEBUG):	Processing 8279 new trades. From 2017-12-11 14:40:01 UTC to 2017-12-11 16:30:00 UTC. (2 hours)
2017-12-11 19:59:40 (INFO):	BTC LTC Requesting data from 2017-12-11 16:20:00, to 2017-12-11 18:20:00
2017-12-11 19:59:43 (DEBUG):	Processing 8979 new trades. From 2017-12-11 16:30:01 UTC to 2017-12-11 18:19:59 UTC. (2 hours)
2017-12-11 19:59:44 (INFO):	BTC LTC Requesting data from 2017-12-11 18:10:00, to 2017-12-11 20:10:00
2017-12-11 19:59:48 (DEBUG):	Processing 7153 new trades. From 2017-12-11 18:20:03 UTC to 2017-12-11 19:58:22 UTC. (2 hours)
2017-12-11 19:59:48 (INFO):	Done importing!

```

I saw in the code that there is an `overlapSize` between batches, and if you look and the `Requesting data` and `Processing X new trades` logs, the timestamp is quite different, as if the overlap size was not respected.
