### ISSUE TITLE
Bug: Death during buy attempt

### ISSUE THREAD

**Issue by Ali1** [askmike/gekko#1462]
Command line Gekko has been so good at not failing recently however failed me today!

```
2017-12-11 09:57:20 (INFO):	Trader Received advice to go long. Buying  XRP
2017-12-11 09:57:20 (INFO):	Pushbullet Message Sent
2017-12-11 09:57:20 (INFO):	Attempting to BUY 944.64226014714 XRP at Bitstamp price: 0.19866
2017-12-11 09:57:22 (INFO):	Send advice via email.
2017-12-11 09:58:21 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 09:58:21 (INFO):	Attempting to BUY 944.3586831440438 XRP at Bitstamp price: 0.19850
2017-12-11 09:59:21 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 09:59:22 (INFO):	Attempting to BUY 947.6777125069036 XRP at Bitstamp price: 0.19857
2017-12-11 10:00:22 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:00:23 (INFO):	Attempting to BUY 948.1537650072839 XRP at Bitstamp price: 0.19895
2017-12-11 10:01:23 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:01:24 (INFO):	Attempting to BUY 943.8392339233925 XRP at Bitstamp price: 0.19917
2017-12-11 10:02:24 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:02:25 (INFO):	Attempting to BUY 947.2021378029809 XRP at Bitstamp price: 0.19900
2017-12-11 10:03:25 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:03:26 (INFO):	Attempting to BUY 947.5349899598394 XRP at Bitstamp price: 0.19903
2017-12-11 10:04:26 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:04:26 (INFO):	Attempting to BUY 943.8392339233925 XRP at Bitstamp price: 0.19943
2017-12-11 10:05:27 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:05:27 (INFO):	Attempting to BUY 945.3046025942807 XRP at Bitstamp price: 0.19896
2017-12-11 10:06:28 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:06:28 (INFO):	Attempting to BUY 943.8864329649448 XRP at Bitstamp price: 0.19967
2017-12-11 10:07:28 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:07:29 (INFO):	Attempting to BUY 943.8392339233925 XRP at Bitstamp price: 0.19921
2017-12-11 10:08:29 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:08:30 (INFO):	Attempting to BUY 944.3114368621174 XRP at Bitstamp price: 0.19887
2017-12-11 10:09:30 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:09:30 (INFO):	Attempting to BUY 945.1625938908364 XRP at Bitstamp price: 0.19900
2017-12-11 10:10:31 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:10:31 (INFO):	Attempting to BUY 944.3114368621174 XRP at Bitstamp price: 0.19916
2017-12-11 10:11:32 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:11:32 (INFO):	Attempting to BUY 944.0752763467215 XRP at Bitstamp price: 0.19918
2017-12-11 10:12:32 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:12:33 (INFO):	Attempting to BUY 944.2169584792397 XRP at Bitstamp price: 0.19941
2017-12-11 10:13:34 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:13:34 (INFO):	Attempting to BUY 943.74485 XRP at Bitstamp price: 0.19942
2017-12-11 10:14:35 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:14:35 (INFO):	Attempting to BUY 943.7920396019802 XRP at Bitstamp price: 0.19943
2017-12-11 10:15:35 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:15:36 (INFO):	Attempting to BUY 943.74485 XRP at Bitstamp price: 0.19946
2017-12-11 10:16:36 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:16:37 (INFO):	Attempting to BUY 943.6976651167442 XRP at Bitstamp price: 0.20000
2017-12-11 10:17:37 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:17:37 (INFO):	Attempting to BUY 939.18977956909 XRP at Bitstamp price: 0.20002
2017-12-11 10:18:38 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:18:38 (INFO):	Attempting to BUY 939.1430490596081 XRP at Bitstamp price: 0.20010
2017-12-11 10:19:39 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:19:39 (INFO):	Attempting to BUY 939.0963232001593 XRP at Bitstamp price: 0.20010
2017-12-11 10:20:39 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:20:40 (INFO):	Attempting to BUY 939.0496019900497 XRP at Bitstamp price: 0.20028
2017-12-11 10:21:40 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:21:41 (INFO):	Attempting to BUY 939.0496019900497 XRP at Bitstamp price: 0.20032
2017-12-11 10:22:41 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:22:42 (INFO):	Attempting to BUY 939.5170233947239 XRP at Bitstamp price: 0.20029
2017-12-11 10:23:42 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:23:42 (INFO):	Attempting to BUY 938.582645450025 XRP at Bitstamp price: 0.20049
2017-12-11 10:24:43 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:24:43 (INFO):	Attempting to BUY 936.3941558763705 XRP at Bitstamp price: 0.20075
2017-12-11 10:25:43 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:25:44 (INFO):	Attempting to BUY 936.2548115079366 XRP at Bitstamp price: 0.20157
2017-12-11 10:26:44 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:26:45 (INFO):	Attempting to BUY 936.2548115079366 XRP at Bitstamp price: 0.20157
2017-12-11 10:27:45 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:27:46 (INFO):	Attempting to BUY 936.4406132169082 XRP at Bitstamp price: 0.20071
2017-12-11 10:28:46 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:28:47 (INFO):	Attempting to BUY 936.3941558763705 XRP at Bitstamp price: 0.20070
2017-12-11 10:29:47 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:29:47 (INFO):	Attempting to BUY 939.0496019900497 XRP at Bitstamp price: 0.20071
2017-12-11 10:30:48 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:30:48 (INFO):	Attempting to BUY 939.0496019900497 XRP at Bitstamp price: 0.20039
2017-12-11 10:31:49 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:31:49 (INFO):	Attempting to BUY 936.7194540942928 XRP at Bitstamp price: 0.20100
2017-12-11 10:32:49 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:32:50 (INFO):	Attempting to BUY 936.7194540942928 XRP at Bitstamp price: 0.20102
2017-12-11 10:33:50 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:33:51 (INFO):	Attempting to BUY 936.3941558763705 XRP at Bitstamp price: 0.20150
2017-12-11 10:34:51 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:34:52 (INFO):	Attempting to BUY 936.3941558763705 XRP at Bitstamp price: 0.20150
2017-12-11 10:35:52 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:35:52 (INFO):	Attempting to BUY 934.4008415841585 XRP at Bitstamp price: 0.20150
2017-12-11 10:36:53 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:36:53 (INFO):	Attempting to BUY 934.4008415841585 XRP at Bitstamp price: 0.20184
2017-12-11 10:37:53 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:37:54 (INFO):	Attempting to BUY 934.4471013416506 XRP at Bitstamp price: 0.20157
2017-12-11 10:38:54 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:38:55 (INFO):	Attempting to BUY 934.4471013416506 XRP at Bitstamp price: 0.20157
2017-12-11 10:39:55 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:39:55 (INFO):	Attempting to BUY 934.4933656797704 XRP at Bitstamp price: 0.20157
2017-12-11 10:40:56 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:40:56 (INFO):	Attempting to BUY 934.4008415841585 XRP at Bitstamp price: 0.20198
2017-12-11 10:41:56 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:41:57 (INFO):	Attempting to BUY 934.3545864066136 XRP at Bitstamp price: 0.20200
2017-12-11 10:42:57 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:42:58 (INFO):	Attempting to BUY 933.8460815357214 XRP at Bitstamp price: 0.20202
2017-12-11 10:43:58 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:43:59 (INFO):	Attempting to BUY 933.8460815357214 XRP at Bitstamp price: 0.20202
2017-12-11 10:44:59 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:44:59 (INFO):	Attempting to BUY 933.9384957941613 XRP at Bitstamp price: 0.20207
2017-12-11 10:46:00 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:46:00 (INFO):	Attempting to BUY 933.8922863787046 XRP at Bitstamp price: 0.20207
2017-12-11 10:47:01 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:47:01 (INFO):	Attempting to BUY 933.8922863787046 XRP at Bitstamp price: 0.20207
2017-12-11 10:48:01 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:48:02 (INFO):	Attempting to BUY 932.0936790123457 XRP at Bitstamp price: 0.20208
2017-12-11 10:49:02 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:49:03 (INFO):	Attempting to BUY 931.9095981040783 XRP at Bitstamp price: 0.20236
2017-12-11 10:50:03 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:50:04 (INFO):	Attempting to BUY 929.797881773399 XRP at Bitstamp price: 0.20255
2017-12-11 10:51:04 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:51:04 (INFO):	Attempting to BUY 930.714842209073 XRP at Bitstamp price: 0.20255
2017-12-11 10:52:05 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:52:05 (INFO):	Attempting to BUY 929.797881773399 XRP at Bitstamp price: 0.20281
2017-12-11 10:53:06 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:53:06 (INFO):	Attempting to BUY 929.797881773399 XRP at Bitstamp price: 0.20257
2017-12-11 10:54:07 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:54:07 (INFO):	Attempting to BUY 927.103344958004 XRP at Bitstamp price: 0.20350
2017-12-11 10:55:08 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:55:08 (INFO):	Attempting to BUY 927.0578094302555 XRP at Bitstamp price: 0.20350
2017-12-11 10:56:10 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:56:10 (INFO):	Attempting to BUY 927.103344958004 XRP at Bitstamp price: 0.20351
2017-12-11 10:57:11 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:57:11 (INFO):	Attempting to BUY 926.6481908782955 XRP at Bitstamp price: 0.20359
2017-12-11 10:58:11 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:58:12 (INFO):	Attempting to BUY 926.6481908782955 XRP at Bitstamp price: 0.20365
2017-12-11 10:59:12 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 10:59:20 (INFO):	Attempting to BUY 925.6484233240155 XRP at Bitstamp price: 0.20351
2017-12-11 11:00:20 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:00:21 (INFO):	Attempting to BUY 925.240049019608 XRP at Bitstamp price: 0.20352
2017-12-11 11:01:21 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:01:21 (INFO):	Attempting to BUY 925.240049019608 XRP at Bitstamp price: 0.20360
2017-12-11 11:02:22 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:02:22 (INFO):	Attempting to BUY 925.240049019608 XRP at Bitstamp price: 0.20362
2017-12-11 11:03:23 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:03:23 (INFO):	Attempting to BUY 925.240049019608 XRP at Bitstamp price: 0.20352
2017-12-11 11:04:24 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:04:24 (INFO):	Attempting to BUY 925.240049019608 XRP at Bitstamp price: 0.20352
2017-12-11 11:05:24 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:05:25 (INFO):	Attempting to BUY 925.2854061473602 XRP at Bitstamp price: 0.20350
2017-12-11 11:06:26 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:06:26 (INFO):	Attempting to BUY 925.2854061473602 XRP at Bitstamp price: 0.20350
2017-12-11 11:07:27 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:07:27 (INFO):	Attempting to BUY 925.830038750184 XRP at Bitstamp price: 0.20350
2017-12-11 11:08:27 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:08:28 (INFO):	Attempting to BUY 925.830038750184 XRP at Bitstamp price: 0.20350
2017-12-11 11:09:28 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:09:29 (INFO):	Attempting to BUY 924.3791076938146 XRP at Bitstamp price: 0.20355
2017-12-11 11:10:29 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:10:30 (INFO):	Attempting to BUY 924.107564259486 XRP at Bitstamp price: 0.20409
2017-12-11 11:11:30 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:11:31 (INFO):	Attempting to BUY 922.977848410758 XRP at Bitstamp price: 0.20410
2017-12-11 11:12:31 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:12:31 (INFO):	Attempting to BUY 925.2854061473602 XRP at Bitstamp price: 0.20350
2017-12-11 11:13:32 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:13:32 (INFO):	Attempting to BUY 925.3307677223258 XRP at Bitstamp price: 0.20350
2017-12-11 11:14:33 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:14:33 (INFO):	Attempting to BUY 925.830038750184 XRP at Bitstamp price: 0.20350
2017-12-11 11:15:34 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:15:34 (INFO):	Attempting to BUY 926.1480372914623 XRP at Bitstamp price: 0.20351
2017-12-11 11:16:35 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:16:35 (INFO):	Attempting to BUY 925.3761337451587 XRP at Bitstamp price: 0.20352
2017-12-11 11:17:35 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:17:36 (INFO):	Attempting to BUY 927.5133660933662 XRP at Bitstamp price: 0.20317
2017-12-11 11:18:36 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:18:37 (INFO):	Attempting to BUY 925.4668791370435 XRP at Bitstamp price: 0.20362
2017-12-11 11:19:37 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:19:38 (INFO):	Attempting to BUY 925.6938205002454 XRP at Bitstamp price: 0.20323
2017-12-11 11:20:38 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:20:39 (INFO):	Attempting to BUY 923.022984008998 XRP at Bitstamp price: 0.20387
2017-12-11 11:21:39 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:21:39 (INFO):	Attempting to BUY 925.7392221295798 XRP at Bitstamp price: 0.20320
2017-12-11 11:22:40 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:22:40 (INFO):	Attempting to BUY 924.7867221950025 XRP at Bitstamp price: 0.20392
2017-12-11 11:23:40 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:23:42 (INFO):	Attempting to BUY 923.022984008998 XRP at Bitstamp price: 0.20411
2017-12-11 11:24:42 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:24:43 (INFO):	Attempting to BUY 923.0681240219093 XRP at Bitstamp price: 0.20413
2017-12-11 11:25:43 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:25:43 (INFO):	Attempting to BUY 922.977848410758 XRP at Bitstamp price: 0.20448
2017-12-11 11:26:44 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:26:45 (INFO):	Attempting to BUY 922.977848410758 XRP at Bitstamp price: 0.20375
2017-12-11 11:27:45 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:27:45 (INFO):	Attempting to BUY 921.625830078125 XRP at Bitstamp price: 0.20382
2017-12-11 11:28:46 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:28:47 (INFO):	Attempting to BUY 921.5358363441071 XRP at Bitstamp price: 0.20409
2017-12-11 11:29:47 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:29:48 (INFO):	Attempting to BUY 922.0310194909873 XRP at Bitstamp price: 0.20415
2017-12-11 11:30:48 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:30:48 (INFO):	Attempting to BUY 921.9409466126118 XRP at Bitstamp price: 0.20450
2017-12-11 11:31:49 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:31:49 (INFO):	Attempting to BUY 922.7522366169641 XRP at Bitstamp price: 0.20252
2017-12-11 11:32:49 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:32:50 (INFO):	Attempting to BUY 925.830038750184 XRP at Bitstamp price: 0.20252
2017-12-11 11:33:50 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:33:51 (INFO):	Attempting to BUY 927.0578094302555 XRP at Bitstamp price: 0.20253
2017-12-11 11:34:51 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:34:52 (INFO):	Attempting to BUY 927.467790280576 XRP at Bitstamp price: 0.20255
2017-12-11 11:35:52 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:35:53 (INFO):	Attempting to BUY 931.9556115143437 XRP at Bitstamp price: 0.20250
2017-12-11 11:36:53 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:36:54 (INFO):	Attempting to BUY 932.0936790123457 XRP at Bitstamp price: 0.20247
2017-12-11 11:37:54 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:37:54 (INFO):	Attempting to BUY 932.0476519678042 XRP at Bitstamp price: 0.20247
2017-12-11 11:38:55 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:38:55 (INFO):	Attempting to BUY 932.2317874252976 XRP at Bitstamp price: 0.20202
2017-12-11 11:39:56 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:39:56 (INFO):	Attempting to BUY 930.2561360275998 XRP at Bitstamp price: 0.20248
2017-12-11 11:40:57 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:40:57 (INFO):	Attempting to BUY 927.0578094302555 XRP at Bitstamp price: 0.20251
2017-12-11 11:41:57 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:41:58 (INFO):	Attempting to BUY 932.0936790123457 XRP at Bitstamp price: 0.20247
2017-12-11 11:42:58 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:42:59 (INFO):	Attempting to BUY 932.0936790123457 XRP at Bitstamp price: 0.20232
2017-12-11 11:43:59 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:43:59 (INFO):	Attempting to BUY 930.76073770896 XRP at Bitstamp price: 0.20215
2017-12-11 11:45:00 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:45:00 (INFO):	Attempting to BUY 932.0936790123457 XRP at Bitstamp price: 0.20228
2017-12-11 11:46:01 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:46:01 (INFO):	Attempting to BUY 932.5541996047432 XRP at Bitstamp price: 0.20210
2017-12-11 11:47:01 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:47:02 (INFO):	Attempting to BUY 930.2561360275998 XRP at Bitstamp price: 0.20270
2017-12-11 11:48:02 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:48:03 (INFO):	Attempting to BUY 931.7715851310659 XRP at Bitstamp price: 0.20250
2017-12-11 11:49:03 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-11 11:49:04 (INFO):	Attempting to BUY 932.1397106029927 XRP at Bitstamp price: 0.20248
/home/pi/gekko/exchanges/bitstamp.js:93
      log.error('unable to buy:', err, result.reason, 'retrying...');
                                             ^

TypeError: Cannot read property 'reason' of undefined
    at Trader.<anonymous> (/home/pi/gekko/exchanges/bitstamp.js:93:46)
    at ClientRequest.<anonymous> (/home/pi/gekko/node_modules/bitstamp/bitstamp.js:78:5)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketCloseListener (_http_client.js:377:9)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:545:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

**Comment by Ali1** [comment]
using develop branch from a few days ago

**Comment by Ali1** [comment]
I noticed #1454 so I checked the buy price for the above. Think the price was appropriate in my case so my issue does not reproduce his - just unfortunately xrp was going up so quickly.
