### ISSUE TITLE
Bitfinex: BUY order was not (fully) filled - ordering at wrong amount

### ISSUE THREAD

**Issue by magicdude4eva** [askmike/gekko#1469]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Auto-trade. Buy was not fulfilled

* **Expected result** (what you hoped would happen)
New order should have had correct quantity.

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
```
2017-12-13 19:41:35 (INFO):	We have new trading advice!
2017-12-13 19:41:35 (INFO):		 Position: long
2017-12-13 19:41:35 (INFO):		 Market price: 0.41339
2017-12-13 19:41:35 (INFO):		 Based on market time: 2017-12-13 17:40:00

2017-12-13 19:41:35 (INFO):	Trader Received advice to go long. Buying  XRP
2017-12-13 19:41:36 (INFO):	Attempting to BUY 764.6142323602439 XRP at Bitfinex price: 0.4145

2017-12-13 19:42:38 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-13 19:42:40 (INFO):	Attempting to BUY 0.5937004705882354 XRP at Bitfinex price: 0.4249
2017-12-13 19:42:41 (ERROR):	unable to buy Error: Invalid order: minimum size for XRP/USD is 52.0
    at Request.request [as _callback] (/Users/gekko/node_modules/bitfinex-api-node/rest.js:61:17)
    at Request.self.callback (/Users/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/gekko/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) undefined
```

**Comment by Paulovms** [comment]
I had have a similar issue at Bitfinex when the order was not fulfilled.
```
2017-12-16 20:06:29 (INFO):	We have new trading advice!
2017-12-16 20:06:29 (INFO):		 Position: long
2017-12-16 20:06:29 (INFO):		 Market price: 0.015243
2017-12-16 20:06:29 (INFO):		 Based on market time: 2017-12-16 22:06:00
2017-12-16 20:06:29 (INFO):	Trader Received advice to go long. Buying  LTC
2017-12-16 20:06:30 (INFO):	Attempting to BUY 0.6207308272649741 LTC at Bitfinex price: 0.015228
2017-12-16 20:07:33 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-16 20:07:35 (ERROR):	Wanted to buy LTC but the amount is too small (0.000610772158) at Bitfinex
```
It’s seems that the amount has a new division by 1000 on the second order. This leads the second order to be too small to be executed and the trade fails.
The issue had already happened before.

**Comment by Paulovms** [comment]
Maybe #1385 and #1232  are related to this issue.

**Comment by Paulovms** [comment]
I'd changed portfolio.js to report amount, currency and ticker ask. I’d forced the new order to wait 10 seconds after cancellation, too.
```
// This function makes sure the limit order gets submitted
// to the exchange and initiates order registers watchers.
Manager.prototype.trade = function(what, retry) {
  // if we are still busy executing the last trade
  // cancel that one (and ignore results = assume not filled)
  if(!retry && _.size(this.orders))
    return this.cancelLastOrder(() => this.trade(what));

  this.action = what;

  var act = function() {
    var amount, price;

    if(what === 'BUY') {

      amount = this.getBalance(this.currency) / this.ticker.ask;
      log.info('amount', amount, 'currency', this.getBalance(this.currency),
          ' ask', this.ticker.ask);
      if(amount > 0){
          price = this.ticker.bid;
          this.buy(amount, price);
      }
```
```
var handleCancelResult = function(alreadyFilled) {p
    if(alreadyFilled)
      return;

    if(this.exchangeMeta.forceReorderDelay) {
        //We need to wait in case a canceled order has already reduced the amount
        var wait = 10;
        log.info(`Waiting ${wait} seconds before starting a new trade on ${this.exchangeMeta.name}!`);

        setTimeout(
            () => this.trade(this.action, true),
            +moment.duration(wait, 'seconds')
        );
        return;
    }
    setTimeout(
        () => this.trade(this.action, true), 10000
    );
  }
```
And Gekko  has reported this:

```
2017-12-28 22:20:31 (INFO):	We have new trading advice!
2017-12-28 22:20:31 (INFO):		 Position: long
2017-12-28 22:20:31 (INFO):		 Market price: 247.2
2017-12-28 22:20:31 (INFO):		 Based on market time: 2017-12-29 00:19:00
2017-12-28 22:20:31 (INFO):	Trader Received advice to go long. Buying  LTC
2017-12-28 22:20:32 (INFO):	amount 0.6920163668418924 currency 171.13564752  ask 247.3
2017-12-28 22:20:32 (INFO):	Attempting to BUY 0.6920163668418924 LTC at Bitfinex price: 247.11
2017-12-28 22:21:32 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
2017-12-28 22:21:42 (INFO):	amount 0.0003692072217296688 currency 0.09161508  ask 248.14
2017-12-28 22:21:42 (ERROR):	Wanted to buy LTC but the amount is too small (0.000369207222) at Bitfinex
```
At 22:21:42, after the order was partially executed, the correct currency balance was US$ 131.22606056 at Bitfinex but Gekko reported US$ 0.09161508, so the amount was too small to buy, and the order wasn’t executed.

@cmroche may the #1549 fix this?

**Comment by cmroche** [comment]
@Paulovms Yes it is possible, when I made the changes for #1549 I noticed that many of the minimum were in fact wrong in the bitfinex markets.

**Comment by cmroche** [comment]
@Paulovms Sorry I was referring to #1550

**Comment by Paulovms** [comment]
#1550 fixed my issue.
