### ISSUE TITLE
Child process has died

### ISSUE THREAD

**Issue by clownfish44** [askmike/gekko#1487]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Started a new live gekko

* **Expected result** (what you hoped would happen)
works

* **Actual result** (unexpected outcome)

```
  --> POST /api/backtest 200 1,739ms 75.41kb
  <-- GET /api/configPart/candleWriter
  <-- GET /api/configPart/performanceAnalyzer
  --> GET /api/configPart/candleWriter 200 7ms 47b
  --> GET /api/configPart/performanceAnalyzer 200 2ms 144b
  <-- GET /api/configPart/paperTrader
  <-- GET /api/strategies
  --> GET /api/configPart/paperTrader 200 1ms 132b
  --> GET /api/strategies 200 4ms 2.02kb
  <-- POST /api/startGekko
Gekko 952000211642462 started
  --> POST /api/startGekko 200 128ms 147b
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
  <-- POST /api/startGekko
Gekko 96166583974958 started
  --> POST /api/startGekko 200 123ms 388b
C:\Users\Reid\Downloads\gekko-stable\gekko-stable\exchanges\binance.js:193
    callback(err.message, ticker);
                 ^

TypeError: Cannot read property 'message' of null
    at Trader.setTicker (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\exchanges\binance.js:193:18)
    at bound (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Request.request [as _callback] (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\node_modules\binance\lib\rest.js:61:21)
    at Request.self.callback (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Reid\Downloads\gekko-stable\gekko-stable\node_modules\request\request.js:1091:12)
RECEIVED ERROR IN GEKKO 96166583974958
Child process has died.
  <-- GET /api/imports
  --> GET /api/imports 200 16ms 547b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 530b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 530b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 11b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 7ms 64.46kb
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 548ms 2.53kb
  <-- POST /api/getCandles
  <-- POST /api/getCandles
  --> POST /api/getCandles 200 647ms 2.69kb
  --> POST /api/getCandles 200 528ms 2.69kb
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by pahanishe** [comment]
I have the same problem on Binance
