### ISSUE TITLE
Error: SQLITE_MISUSE: Database is closed

### ISSUE THREAD

**Issue by wupeng1211** [askmike/gekko#1497]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

`2017-12-17 12:16:58 (INFO):             Usable local data available, trying to match with exchange data..
2017-12-17 12:16:58 (INFO):             Full history locally available. Seeding the trading method with all required historical candles.
2017-12-17 12:17:18 (INFO):     Setting up:
2017-12-17 12:17:18 (INFO):              Mailer
2017-12-17 12:17:18 (INFO):              Sends you an email everytime Gekko has new advice.
2017-12-17 12:17:18 (INFO):

2017-12-17 12:17:20 (INFO):     Send advice via email.
2017-12-17 12:17:20 (INFO):     Setting up:
2017-12-17 12:17:20 (INFO):              Advice logger
2017-12-17 12:17:20 (INFO):
2017-12-17 12:17:20 (INFO):     Setting up:
2017-12-17 12:17:20 (INFO):              Paper Trader
2017-12-17 12:17:20 (INFO):              Paper trader that simulates fake trades.
2017-12-17 12:17:20 (INFO):

2017-12-17 12:17:20 (INFO):     Setting up:
2017-12-17 12:17:20 (INFO):              Performance Analyzer
2017-12-17 12:17:20 (INFO):              Analyzes performances of trades
2017-12-17 12:17:20 (INFO):

2017-12-17 12:17:20 (INFO):     Starting to watch the market: Poloniex BTC/USDT
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_MISUSE: Database is closed
    at Error (native)
    at Database.run (/home/ka/gekko/node_modules/sqlite3/lib/sqlite3.js:20:25)
    at Store.transaction (/home/ka/gekko/plugins/sqlite/writer.js:56:13)
    at Database.bound (/home/ka/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Store.writeCandles (/home/ka/gekko/plugins/sqlite/writer.js:88:11)
    at Store.bound [as writeCandles] (/home/ka/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Store.processCandle (/home/ka/gekko/plugins/sqlite/writer.js:94:10)
    at Store.bound [as processCandle] (/home/ka/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/ka/gekko/core/gekkoStream.js:26:7
    at Function.forEach (/home/ka/gekko/node_modules/lodash/dist/lodash.js:3298:15)`

**Comment by wupeng1211** [comment]
but i can import and backtest

**Comment by wupeng1211** [comment]
but i can import and backtest

**Comment by wupeng1211** [comment]
`2017-12-17 12:21:20 (WARN):     The plugin Mailer does not support the mode backtest. It has been disabled.
2017-12-17 12:21:20 (WARN):     The plugin Advice logger does not support the mode backtest. It has been disabled.
2017-12-17 12:21:20 (INFO):     Setting up:
2017-12-17 12:21:20 (INFO):              Paper Trader
2017-12-17 12:21:20 (INFO):              Paper trader that simulates fake trades.
2017-12-17 12:21:20 (INFO):

2017-12-17 12:21:20 (INFO):     Setting up:
2017-12-17 12:21:20 (INFO):              Performance Analyzer
2017-12-17 12:21:20 (INFO):              Analyzes performances of trades
2017-12-17 12:21:20 (INFO):

2017-12-17 12:21:21 (INFO):     Scanning local history for backtestable dateranges.
2017-12-17 12:21:21 (INFO):     The database has 76289 candles missing, Figuring out which ones...
2017-12-17 12:21:22 (INFO):     Gekko detected multiple dateranges in the locally stored history. Please pick the daterange you are interested in testing:
2017-12-17 12:21:22 (INFO):                      OPTION 1:
2017-12-17 12:21:23 (INFO):              from: 2016-01-01 00:20:00
2017-12-17 12:21:23 (INFO):              to: 2016-11-23 15:20:00
2017-12-17 12:21:23 (INFO):                      OPTION 2:
2017-12-17 12:21:23 (INFO):              from: 2017-01-15 15:20:00`

**Comment by cmroche** [comment]
@wupeng1211 Maybe PR #1518 fixes this, can you test?

**Comment by cmroche** [comment]
@wupeng1211 Could you please provide a configuration file that leads you to this error, also which operating system are you using? Windows, Windows with Bash?

**Comment by wupeng1211** [comment]
@cmroche  i find changed candleWriter  is false ,then is ok.but candle can not save.
config.candleWriter = {
  enabled: true
}

**Comment by mmeisel** [comment]
I'm also getting this error on Linux.

**Comment by mmeisel** [comment]
FWIW, I confirmed that this issue does not exist in 0.5.10, so it must have been introduced in 0.5.11.

**Comment by cmroche** [comment]
@wupeng1211 @mmeisel I am still unable to reproduce this on any OS. The database is only closed when the plugins shut down, so I am not sure how you guys are managing to get this error.

What actions are you doing when you get this? Live trading, paper, backtest, import?

Are you using the UI, or working on command line?

I'll need to know if any other modules could potentially be trying to access the DB, what other modules do you have active, and what is their configuration (copying and pasting your config file would help).

Thanks.

**Comment by wupeng1211** [comment]
@cmroche  @mmeisel  Import, back to test, UI,　all no problem, I found that the error is the first import, and then  run .


 1、`cd gekko`
２、`mv history history.bak`
３、`node gekko -c config.js` 
４、` node gekko -c config.js -i`　import data from 2017-11-01
５、` node gekko -c config.js`　config set
config.candleWriter = {
  enabled: true
}

if  No usable local data available, trying to get as much as possible from the exchange.. then is ok.

else if use import data then
 Usable local data available, trying to match with exchange data..
...
...

Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_MISUSE: Database is closed

**Comment by mmeisel** [comment]
That's exactly my case as well -- I have local data available, but I shut down gekko for a while, so it has to fill in the last hour or so from the exchange. This error happens as soon as it finishes fetching the data. Here's the relevant portion of my log file:

```
2017-12-20 20:09:34 (DEBUG):    Scan finished: data found:3900
2017-12-20 20:09:34 (DEBUG):    Processing 3900 new trades. From 2017-12-21 03:19:17 UTC to 2017-12-21 04:09:32 UTC. (an hour)
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/
#/warnings/add-inverted-param/ for more info.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_MISUSE: Database is closed
    at Error (native)
    at Database.<anonymous> (/home/michael/gekko/node_modules/sqlite3/lib/sqlite3.js:20:25)
    at Database.object.(anonymous function) [as run] (/home/michael/gekko/node_modules/sqlite3/lib/trace.js:31:20)
    at Store.transaction (/home/michael/gekko/plugins/sqlite/writer.js:56:13)
    at Database.bound (/home/michael/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Store.writeCandles (/home/michael/gekko/plugins/sqlite/writer.js:88:11)
    at Store.bound [as writeCandles] (/home/michael/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Store.processCandle (/home/michael/gekko/plugins/sqlite/writer.js:94:10)
    at Store.bound [as processCandle] (/home/michael/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/michael/gekko/core/gekkoStream.js:26:7
```

**Comment by cmroche** [comment]
Ok, thank you for the info. I'll come back to this in a few days (after the holidays).

**Comment by cmroche** [comment]
@wupeng1211 @mmeisel Try the change here and confirm if this resolves your problem please https://github.com/cmroche/gekko/tree/origin/sqlite_ro

**Comment by wupeng1211** [comment]
@cmroche thanks,now is ok, @mmeisel

**Comment by mmeisel** [comment]
Works for me, too, thanks!

**Comment by cmroche** [comment]
Thanks, I'll make a formal PR for this change then.

**Comment by cmroche** [comment]
#1591
