### ISSUE TITLE
Child process has died ... 

### ISSUE THREAD

**Issue by blasthim9** [askmike/gekko#1517]
Gekko 874487814048984 started
  --> POST /api/startGekko 200 3ms 389b
C:\Users\Derek\Desktop\gekko-stable\exchanges\binance.js:193
    callback(err.message, ticker);
                 ^

TypeError: Cannot read property 'message' of null
    at Trader.setTicker (C:\Users\Derek\Desktop\gekko-stable\exchanges\binance.js:193:18)
    at bound (C:\Users\Derek\Desktop\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Request.request [as _callback] (C:\Users\Derek\Desktop\gekko-stable\node_modules\binance\lib\rest.js:61:21)
    at Request.self.callback (C:\Users\Derek\Desktop\gekko-stable\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Derek\Desktop\gekko-stable\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Derek\Desktop\gekko-stable\node_modules\request\request.js:1091:12)
RECEIVED ERROR IN GEKKO 874487814048984
Child process has died.

**Comment by cmroche** [comment]
@blasthim9 PR #1508 will address this. Don't forget to rerun `npm i` if you use the pull request as your binance modules need to be updated.
