### ISSUE TITLE
Binance order cancellation problem..

### ISSUE THREAD

**Issue by brerdem** [askmike/gekko#1524]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started live trade mode from the CLI

* **Expected result** (what you hoped would happen)
Smooth buy and order operations based on the strategy given

* **Actual result** (unexpected outcome)
It crashed when it decided to cancel SELL order 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Hi, 
Following the issue [#1481](https://github.com/askmike/gekko/issues/1481) I was able to run trade mode successfully. It analyzes trades and successfully places BUY and SELL orders. However it stopsand throws the error below when it tries to cancel the last order.

`C:\Users\Burak.Erdem\Desktop\gekko\gekko\exchanges\binance.js:295
  util.retryCustom(retryForever, _.bind(handler, this), _.bind(check, this));
                                                               ^

ReferenceError: check is not defined
    at Trader.cancelOrder (C:\Users\Burak.Erdem\Desktop\gekko\gekko\exchanges\binance.js:295:64)
    at Trader.bound [as cancelOrder] (C:\Users\Burak.Erdem\Desktop\gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.handleCheckResult (C:\Users\Burak.Erdem\Desktop\gekko\gekko\plugins\trader\portfolioManager.js:278:21)
    at bound (C:\Users\Burak.Erdem\Desktop\gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Trader.check (C:\Users\Burak.Erdem\Desktop\gekko\gekko\exchanges\binance.js:269:5)
    at bound (C:\Users\Burak.Erdem\Desktop\gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at C:\Users\Burak.Erdem\Desktop\gekko\gekko\core\util.js:28:7
    at C:\Users\Burak.Erdem\Desktop\gekko\gekko\exchanges\binance.js:66:12
    at Request.request [as _callback] (C:\Users\Burak.Erdem\Desktop\gekko\gekko\node_modules\binance\lib\rest.js:75:21)
    at Request.self.callback (C:\Users\Burak.Erdem\Desktop\gekko\gekko\node_modules\request\request.js:188:22)
2017-12-19 15:54:58 (DEBUG):	[binance.js] entering "checkOrder" callback after api call, err null data: {"symbol":"NEOBTC","orderId":15692806,"clientOrderId":"UCF9MaNdO8TmVMpkul7BB9","price":"0.00416000","origQty":"3.70000000","executedQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"SELL","stopPrice":"0.00000000","icebergQty":"0.00000000","time":1513688048108,"isWorking":true}
2017-12-19 15:54:58 (INFO):	SELL order was not (fully) filled, cancelling and creating new order`

**Comment by cmroche** [comment]
Copy and paste error, fixed now on PR #1508
