### ISSUE TITLE
Unable to build web/vue

### ISSUE THREAD

**Issue by hoshsadiq** [askmike/gekko#1551]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
```
RUN set -ex; \
    cd ./web/vue; \
    npm install -g --production cross-env@3.X; \
    npm install --production; \
    npm run build; \
    du -h -d 1; \
    node-prune; \
    du -h -d 1
```

* **Expected result** (what you hoped would happen)
```
exit code 0
```

* **Actual result** (unexpected outcome)
```
/usr/src/app/web/vue # npm run build
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle vue@0.2.0~prebuild: vue@0.2.0
npm info lifecycle vue@0.2.0~build: vue@0.2.0

> vue@0.2.0 build /usr/src/app/web/vue
> cross-env NODE_ENV=production webpack --progress --hide-modules

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm info lifecycle vue@0.2.0~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue@0.2.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-24T23_57_39_434Z-debug.log
```

* **Other information** 
Trying to run it in docker. No luck. Everything up until `npm run build` runs fine.

**Comment by hoshsadiq** [comment]
Never mind! Below solved the issue:
```
RUN set -ex; \
    cd ./web/vue; \
    apk add --no-cache git; \
    npm install -g --production cross-env@3.X; \
    npm install; \
    npm run build; \
    du -h -d 1; \
    node-prune; \
    du -h -d 1
```
