### ISSUE TITLE
[bug report ]  Can not import local data on NEO/USDT BINANCE

### ISSUE THREAD

**Issue by karmamaster** [askmike/gekko#1579]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report

* **Action taken** (what you did)
I have try to import the local data but there is bugs when running this processs. Further more, i have added my binance key and secret key too

* **Actual result** (unexpected outcome)
This is the error on server:

```
N:\WorkingCodes\trading_bot\gekko\exchanges\binance.js:35
  if (!error || !error.message.match(recoverableErrors)) {
                               ^

TypeError: Cannot read property 'match' of undefined
    at Trader.retry (N:\WorkingCodes\trading_bot\gekko\exchanges\binance.js:35:32)
    at Trader.bound [as retry] (N:\WorkingCodes\trading_bot\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Trader.process (N:\WorkingCodes\trading_bot\gekko\exchanges\binance.js:70:19)
    at bound (N:\WorkingCodes\trading_bot\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Request.request [as _callback] (N:\WorkingCodes\trading_bot\gekko\node_modules\binance\lib\rest.js:52:21)
    at Request.self.callback (N:\WorkingCodes\trading_bot\gekko\node_modules\request\request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (N:\WorkingCodes\trading_bot\gekko\node_modules\request\request.js:1171:10)
    at emitOne (events.js:116:13)
RECEIVED ERROR IN IMPORT 623213634867971
Child process has died.
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
I am running gekko on window 10 x64 and followed the guide on gekko document, everything just fine till i try to import local data to do backtest.

**Comment by karmamaster** [comment]
I just firgure out that all of the process need to do with binance are error

**Comment by cmroche** [comment]
Binance recently changed their API, check #1568 for the fix.
