### ISSUE TITLE
Cannot read property 'time' of undefined, Child process has died

### ISSUE THREAD

**Issue by haihosilver** [askmike/gekko#1580]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Trying to import data from GDAX.

* **Expected result** (what you hoped would happen)
.. importing data :)

* **Actual result** (unexpected outcome)
Child process crash.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
`  --> POST /api/scansets 200 604ms 426b
/home/rolf/gekko/exchanges/gdax.js:251
                if (moment.utc(last.time) < moment.utc(since)) {
                                    ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/home/rolf/gekko/exchanges/gdax.js:251:37)
    at Request._callback (/home/rolf/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/home/rolf/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/rolf/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/rolf/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
RECEIVED ERROR IN IMPORT 4485296146017044
Child process has died.`

**Comment by cloggy45** [comment]
Can I have a copy of your config.js

**Comment by haihosilver** [comment]
Standard, new installation no configs made. Only thing running was an import from GDAX.

**Comment by okonon** [comment]
same issue here my config

Name | Value
------|------
Market: | gdax
Currency/Asset: | USD/ETH
From: | 2017-12-01 21:34:00
To: | 2017-12-31 22:34:00
