### ISSUE TITLE
Child process has died when I  scan for Market Watcher Statistics ,How??

### ISSUE THREAD

**Issue by Jackzhangpan** [askmike/gekko#1592]
```
E:\Gekko\gekko\node_modules\bitcoin-co-id\index.js:65
    requestOptions[x] = options[x];
                   ^

ReferenceError: x is not defined
    at Bitcoincoid._request (E:\Gekko\gekko\node_modules\bitcoin-co-id\index.js:65:20)
    at Bitcoincoid._get (E:\Gekko\gekko\node_modules\bitcoin-co-id\index.js:20:8)
    at Bitcoincoid.getTrades (E:\Gekko\gekko\node_modules\bitcoin-co-id\index.js:119:8)
    at Trader.getTrades (E:\Gekko\gekko\exchanges\bitcoin-co-id.js:113:20)
    at Trader.bound [as getTrades] (E:\Gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher._fetch (E:\Gekko\gekko\core\budfox\marketFetcher.js:75:16)
    at Fetcher.bound [as _fetch] (E:\Gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher.fetch (E:\Gekko\gekko\core\budfox\marketFetcher.js:88:8)
    at Fetcher.bound (E:\Gekko\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.retrieve (E:\Gekko\gekko\core\budfox\marketDataProvider.js:31:15)
RECEIVED ERROR IN GEKKO 535418895635132
Child process has died.
```

**Comment by Jackzhangpan** [comment]
@cloggy45 can help me? thank you

**Comment by cloggy45** [comment]
I will look into it.

**Comment by cloggy45** [comment]
From what I can tell, it relates to this [node package issue](https://github.com/danKHUU/bitcoin-co-id/commit/7426836e0bd805ebe78f7808881e9e19eebc1fad).

**Comment by cloggy45** [comment]
@Jackzhangpan To solve the problem use ``npm install --only=production`` this will get all the updated dependencies.

**Comment by Jackzhangpan** [comment]
OK，thank you

**Comment by Hanna96** [comment]
@cloggy45 it doesn't work for me

**Comment by masbenx** [comment]
@cloggy45 doesn't work for me too
I still get error

> ReferenceError: x is not defined
    at Bitcoincoid._request (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\bitcoin-co-id\index.js:65:20)
    at Bitcoincoid._get (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\bitcoin-co-id\index.js:20:8)
    at Bitcoincoid.getTrades (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\bitcoin-co-id\index.js:119:8)
    at Trader.getTrades (C:\Users\Mindo-S\Documents\trade\gekko-stable\exchanges\bitcoin-co-id.js:113:20)
    at Trader.bound [as getTrades] (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher._fetch (C:\Users\Mindo-S\Documents\trade\gekko-stable\core\budfox\marketFetcher.js:75:16)
    at Fetcher.bound [as _fetch] (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher.fetch (C:\Users\Mindo-S\Documents\trade\gekko-stable\core\budfox\marketFetcher.js:88:8)
    at Fetcher.bound [as fetch] (C:\Users\Mindo-S\Documents\trade\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.retrieve (C:\Users\Mindo-S\Documents\trade\gekko-stable\core\budfox\marketDataProvider.js:31:15)
RECEIVED ERROR IN GEKKO 893362998379682
Child process has died.

**Comment by cloggy45** [comment]
@masbenx Is that still at the same point? `E:\Gekko\gekko\node_modules\bitcoin-co-id\index.js:65
    requestOptions[x] = options[x];`

**Comment by masbenx** [comment]
@cloggy45 yes you are right.
it's still at the same point.

**Comment by cloggy45** [comment]
I see, so it seems the original `bitcoin-co-id` npm package isn't updating the fix for this, at least for me. The temporary solution is to look inside `package.json`, and amend `"bitcoin-co-id": "0.0.1"` to look like` "bitcoin-co-id": "https://github.com/danKHUU/bitcoin-co-id.git",`. then run `npm install --only=production`

At least for me, this has resolved the issue.

**Comment by masbenx** [comment]
@cloggy45 thank you it's work now

**Comment by cloggy45** [comment]
@masbenx That's great, any further issues, let me know.

**Comment by chwijaya** [comment]
Hi @cloggy45 ,

I couldn't find the line containing `"bitcoin-co-id": "0.0.1"` in package.json.
Could you please help?

Thanks.

**Comment by masbenx** [comment]
@chwijaya 
you can found it at root folder
or gekko-stable/package.json in line 21

**Comment by chwijaya** [comment]
@masbenx 

Thanks a lot, it's working now.

**Comment by xtian7330** [comment]
Please help..

Error when trade bot bitcoin-co-id market

"This site says..."
GEKKO ERROR: Child process has died


E:\gekko-develop\node_modules\bitcoin-co-id\index.js:65
    requestOptions[x] = options[x];
                   ^

ReferenceError: x is not defined
    at Bitcoincoid._request (E:\gekko-develop\node_modules\bitcoin-co-id\index.js:65:20)
    at Bitcoincoid._get (E:\gekko-develop\node_modules\bitcoin-co-id\index.js:20:8)
    at Bitcoincoid.getTrades (E:\gekko-develop\node_modules\bitcoin-co-id\index.js:119:8)
    at Trader.getTrades (E:\gekko-develop\exchanges\bitcoin-co-id.js:113:20)
    at Trader.bound [as getTrades] (E:\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher._fetch (E:\gekko-develop\core\budfox\marketFetcher.js:75:23)
    at Fetcher.bound [as _fetch] (E:\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher.fetch (E:\gekko-develop\core\budfox\marketFetcher.js:88:8)
    at Fetcher.bound [as fetch] (E:\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.retrieve (E:\gekko-develop\core\budfox\marketDataProvider.js:31:15)
RECEIVED ERROR IN GEKKO 16753203962793
Child process has died.

**Comment by askmike** [comment]
@cloggy45 would love a PR for that fix!

**Comment by cloggy45** [comment]
https://github.com/askmike/gekko/pull/1945

**Comment by xtian7330** [comment]
@cloggy45 doesn't work for me 
I still get error

E:\gekko-develop>npm install --only=production
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xtambunan pc\AppData\Roaming\npm-cache\_logs\2018-02-21T13_32_56_922Z-debug.log
