### ISSUE TITLE
BTC-Markets Tradebot Authentication Failure

### ISSUE THREAD

**Issue by spockmanna** [askmike/gekko#1609]
I'm trying to use the live trade bot with btc-markets but received an error when my order was trying to be cancelled and re-sent.

I was able to submit a buy request and I saw that the buy was registered on the BTC markets under "my open orders".

```
2018-01-02 22:52:08 (INFO):     We have new trading advice!
2018-01-02 22:52:08 (INFO):              Position: long
2018-01-02 22:52:08 (INFO):              Market price: 0.0176441
2018-01-02 22:52:08 (INFO):              Based on market time: 2018-01-02 11:50:00
2018-01-02 22:52:08 (INFO):     Trader Received advice to go long. Buying  LTC
2018-01-02 22:52:08 (INFO):     Attempting to BUY 1.6085479115574957 LTC at BTC Markets price: 0.01764398
2018-01-02 22:52:28 (DEBUG):    Requested LTC/BTC trade data from BTC Markets ...
2018-01-02 22:52:28 (DEBUG):    No new trades.
```

The bot tried to cancel the order and re-send it but came up with an authentication error.
```
2018-01-02 22:53:08 (INFO):     BUY order was not (fully) filled, cancelling and creating new order
2018-01-02 22:53:08 (INFO):     Attempting to BUY 1.6085479115574957 LTC at BTC Markets price: 0.01764399
2018-01-02 22:53:08 (ERROR):    unable to buy { Authentication failed.: BTCMarkets.executeRequest() failed POST request
to url https://api.btcmarkets.net/order/create with message /order/create
1888888888888
{"currency":"BTC","instrument":"LTC","price":1764398.9999999998,"volume":160854791,"orderSide":"Bid","ordertype":"Limit"
,"clientRequestId":"0.5123457512345712"}. Error message: Authentication failed.
    at Request._callback (C:\gekko-stable\node_modules\btc-markets\index.js:138:21)
    at Request.self.callback (C:\gekko-stable\node_modules\btc-markets\node_modules\request
\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\gekko-stable\node_modules\btc-markets\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (C:\gekko-stable\node_modules\btc-markets\node_modules\r
equest\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  jse_shortmsg: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\1888888888888\n{"currency":"BTC","instrument":"LTC","price":1764398.9999999998,"volume":160854791,"o
rderSide":"Bid","ordertype":"Limit","clientRequestId":"x.xxxxxx"}. Error message: Authentication failed.',
  jse_summary: 'BTCMarkets.executeRequest() failed POST request to url 
```

Given the first BUY was accepted, is there an issue where not all the parameters are being reset when trying to send the next BUY request?

BTC-Markets Trading API is on GIT Hub but I couldn't work out how I could potentially fix it.
https://github.com/BTCMarkets/API/wiki/Trading-API

**Comment by zbdrm** [comment]
I'm in the same boat...
