### ISSUE TITLE
Util.retry options is undefined

### ISSUE THREAD

**Issue by knowlecules** [askmike/gekko#1616]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Configured email

* **Expected result** (what you hoped would happen)
Send an email

* **Actual result** (unexpected outcome)
    retryHelper(fn, options, callback);
                    ^

ReferenceError: options is not defined
    at Object.retry (/home/knowlecules/gekko/core/util.js:187:21)
    at Mailer.mail (/home/knowlecules/gekko/plugins/mailer.js:84:8)
    at Mailer.bound [as mail] (/home/knowlecules/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Mailer.setupMail (/home/knowlecules/gekko/plugins/mailer.js:42:12)
    at Mailer.setup (/home/knowlecules/gekko/plugins/mailer.js:79:15)
    at Mailer.bound (/home/knowlecules/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Mailer (/home/knowlecules/gekko/plugins/mailer.js:15:8)
    at load (/home/knowlecules/gekko/core/pluginUtil.js:95:22)
    at /home/knowlecules/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/knowlecules/gekko/node_modules/async/dist/async.js:1030:17)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ricadete** [comment]
At the file "/gekko/core/util.js"

change: retryHelper(fn, options, callback);
to: retryHelper(fn, operation, callback);

**Comment by mladenmilev** [comment]
I have same problem when trying to configure gmail server and the mailer is set to True upon startup. Please advice whan and how to troubleshoot. 

```
        Gekko v0.5.11
        I'm gonna make you rich, Bud Fox.


2018-01-12 16:25:10 (INFO):     Setting up Gekko in realtime mode
2018-01-12 16:25:10 (INFO):
2018-01-12 16:25:10 (INFO):     Setting up:
2018-01-12 16:25:10 (INFO):              Trading Advisor
2018-01-12 16:25:10 (INFO):              Calculate trading advice
2018-01-12 16:25:10 (INFO):              Using the strategy: CCI
2018-01-12 16:25:10 (WARN):     TALIB indicators could not be loaded, they will be unavailable.
2018-01-12 16:25:10 (WARN):     TULIP indicators could not be loaded, they will be unavailable.
2018-01-12 16:25:11 (INFO):             The trading method requests 10 minutes of historic data. Checking availablity..
2018-01-12 16:25:11 (INFO):

2018-01-12 16:25:11 (INFO):             No usable local data available, trying to get as much as possible from the exchange..
2018-01-12 16:25:11 (DEBUG):            Fetching exchange data since 10 minutes ago
2018-01-12 16:25:13 (DEBUG):            Available exchange data:
2018-01-12 16:25:13 (DEBUG):                    from: 10 minutes ago
2018-01-12 16:25:13 (DEBUG):                    to: 0 minutes ago
2018-01-12 16:25:13 (DEBUG):            Unable to stitch datasets.
2018-01-12 16:25:13 (INFO):             Not seeding locally available data to the trading method.
2018-01-12 16:25:13 (INFO):     Setting up:
2018-01-12 16:25:13 (INFO):              Mailer
2018-01-12 16:25:13 (INFO):              Sends you an email everytime Gekko has new advice.
/home/mladen/gekko/core/util.js:187
    retryHelper(fn, operation, callback);
                    ^

ReferenceError: operation is not defined
    at Object.retry (/home/mladen/gekko/core/util.js:187:21)
    at Mailer.mail (/home/mladen/gekko/plugins/mailer.js:84:8)
    at Mailer.bound [as mail] (/home/mladen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Mailer.setupMail (/home/mladen/gekko/plugins/mailer.js:42:12)
    at Mailer.setup (/home/mladen/gekko/plugins/mailer.js:79:15)
    at Mailer.bound (/home/mladen/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Mailer (/home/mladen/gekko/plugins/mailer.js:15:8)
    at load (/home/mladen/gekko/core/pluginUtil.js:95:22)
    at /home/mladen/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/mladen/gekko/node_modules/async/dist/async.js:1030:17)
```

**Comment by mladenmilev** [comment]
For me worked:

Changing line  /gekko/core/util.js:187 

from: `retryHelper(fn, operation, callback);`

to: `retryHelper(fn, options, callback);`

Also I needed to enable additional setting in my Google Account to allow access.
