### ISSUE TITLE
application token is invalid

### ISSUE THREAD

**Issue by luke-hub** [askmike/gekko#1635]
Getting this while running live trader on gdax:

/Users/***/code/bots/gekko/node_modules/pushover-notifications/lib/pushover.js:82
	    throw new Error(d.errors[0]);
	    ^

Error: application token is invalid
    at Pushover.errors (/Users/***/code/bots/gekko/node_modules/pushover-notifications/lib/pushover.js:82:12)
    at IncomingMessage.<anonymous> (/Users/***n/code/bots/gekko/node_modules/pushover-notifications/lib/pushover.js:148:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by billymcintosh** [comment]
You've enabled [pushover](https://pushover.net/) in your `config.js`.

Either put in the a `key` and `user` or disable it like so;

```js
config.pushover = {
  enabled: false,
  sendPushoverOnStart: false,
  muteSoft: true, // disable advice printout if it's soft
  tag: '[GEKKO]',
  key: '',
  user: ''
}
```

**Comment by luke-hub** [comment]
Ah, piece of cake, thank you.
