### ISSUE TITLE
[importer] bitfinex error since 0.5.12

### ISSUE THREAD

**Issue by stefano-neri** [askmike/gekko#1685]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started the gekko importer with my config.js (which worked with 0.5.11)
Excerpts:
```
config.watch = {

  // see https://gekko.wizb.it/docs/introduction/supported_exchanges.html
  exchange: 'bitfinex',
  currency: 'BTC',
  asset: 'XRP',

  // You can set your own tickrate (refresh rate).
  // If you don't set it, the defaults are 2 sec for
  // okcoin and 20 sec for all other exchanges.
  tickrate: 20
}
```
...
```
config.adapter = 'mongodb';
// Mongodb adapter, requires mongodb >= 3.3 (no version earlier tested)
config.mongodb = {
  path: 'plugins/mongodb',
  version: 0.1,
  connectionString: 'mongodb://localhost:27017/gekko', // connection to mongodb server
  dependencies: [{
    module: 'mongojs',
    version: '2.4.0'
  }]
}
```
...
```
config.importer = {
  daterange: {
    // NOTE: these dates are in UTC
    from: "2018-01-13 16:00:00",
	to: "2018-01-14 10:00:00"
  }
}
```
* **Expected result** (what you hoped would happen)
Import of trades within specified time range

* **Actual result** (unexpected outcome)
```
c:\temp\gekko-stable>node gekko --import --config config.js

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.5.12
        I'm gonna make you rich, Bud Fox.


2018-01-14 11:36:42 (INFO):     Setting up Gekko in importer mode
2018-01-14 11:36:42 (INFO):
2018-01-14 11:36:42 (INFO):     Setting up:
2018-01-14 11:36:42 (INFO):              Candle writer
2018-01-14 11:36:42 (INFO):              Store candles in a database
2018-01-14 11:36:43 (DEBUG):    Enabling adviceWriter.
2018-01-14 11:36:43 (DEBUG):    Enabling candleWriter.
2018-01-14 11:36:43 (INFO):

2018-01-14 11:36:43 (WARN):     The plugin Trading Advisor does not support the mode importer. It has been disabled.
2018-01-14 11:36:43 (WARN):     The plugin Advice logger does not support the mode importer. It has been disabled.
2018-01-14 11:36:43 (WARN):     The plugin Trader does not support the mode importer. It has been disabled.
2018-01-14 11:36:43 (WARN):     The plugin Performance Analyzer does not support the mode importer. It has been disabled.
2018-01-14 11:36:43 (WARN):     Candle writer wanted to listen to the tradingAdvisor, however the tradingAdvisor is disabled.
c:\temp\gekko-stable\importers\exchanges\bitfinex.js:79
    batch_end = moment(from).add(stride, 'h');
                                 ^

ReferenceError: stride is not defined
    at Object.fetch (c:\temp\gekko-stable\importers\exchanges\bitfinex.js:79:34)
    at Market.get (c:\temp\gekko-stable\core\markets\importer.js:95:16)
    at Market.bound [as get] (c:\temp\gekko-stable\node_modules\lodash\dist\lodash.js:729:21)
    at new Market (c:\temp\gekko-stable\core\markets\importer.js:80:8)
    at c:\temp\gekko-stable\core\pipeline.js:187:20
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:3853:9
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:484:16
    at replenish (c:\temp\gekko-stable\node_modules\async\dist\async.js:1025:25)
    at iterateeCallback (c:\temp\gekko-stable\node_modules\async\dist\async.js:1015:17)
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:988:16
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:3850:13
    at apply (c:\temp\gekko-stable\node_modules\async\dist\async.js:41:25)
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:76:12
    at prepareMarket (c:\temp\gekko-stable\core\pipeline.js:164:7)
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:3845:9
    at replenish (c:\temp\gekko-stable\node_modules\async\dist\async.js:1030:17)
    at iterateeCallback (c:\temp\gekko-stable\node_modules\async\dist\async.js:1015:17)
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:988:16
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:3850:13
    at apply (c:\temp\gekko-stable\node_modules\async\dist\async.js:41:25)
    at c:\temp\gekko-stable\node_modules\async\dist\async.js:76:12
    at subscribePlugins (c:\temp\gekko-stable\core\pipeline.js:156:5)
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by stefano-neri** [comment]
However: Running a trading bot works.

**Comment by Daewju** [comment]
I'm having the same issue with 0.5.12 when i try to import data from Bitfinex.

**Comment by askmike** [comment]
@cmroche there is a bug in the new importer:

https://github.com/askmike/gekko/blob/a6e697fbbdd09fcd7ea17afc758a066e9b6646bd/importers/exchanges/bitfinex.js#L93-L104

The variables `ITERATING_STRIDE`, `SCANNING_STRIDE` and `stride` are not defined anywhere.

**Comment by cmroche** [comment]
@askmike must have been a bad merge along the way, I’ll send a Pro with a fix in a few minutes. Fortunately I have the good version of the file. It appears that the defines were the only thing lost too.

**Comment by cmroche** [comment]
#1692 will fix this

**Comment by askmike** [comment]
@cmroche thanks a lot for the quick fix!

@stefano-neri @Daewju please try the latest develop branch that includes @cmroche's fix.
