### ISSUE TITLE
[importer] bitfinex error In develop

### ISSUE THREAD

**Issue by Paulovms** [askmike/gekko#1702]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I started the gekko importer with my config.js after upgraded bitfinex.js with issue #1685 fixed in develop branch.

* **Expected result** (what you hoped would happen)
Import of trades within specified time range.

* **Actual result** (unexpected outcome)
```
2018-01-16 09:37:41 (INFO):     Setting up Gekko in importer mode
2018-01-16 09:37:41 (INFO):     
2018-01-16 09:37:41 (INFO):     Setting up:
2018-01-16 09:37:41 (INFO):              Candle writer
2018-01-16 09:37:41 (INFO):              Store candles in a database
2018-01-16 09:37:41 (INFO):     

2018-01-16 09:37:41 (WARN):     The plugin Trading Advisor does not support the mode importer. It has been disabled.
2018-01-16 09:37:41 (WARN):     The plugin Pushover does not support the mode importer. It has been disabled.
2018-01-16 09:37:41 (WARN):     The plugin Advice logger does not support the mode importer. It has been disabled.
2018-01-16 09:37:41 (WARN):     The plugin Trader does not support the mode importer. It has been disabled.
2018-01-16 09:37:41 (WARN):     The plugin Performance Analyzer does not support the mode importer. It has been disabled.
/root/gekko/importers/exchanges/bitfinex.js:40
  let handler = cb => this.bitfinex.makePublicRequest(path, this.handleResponse('getTrades', cb));
                                                                 ^

TypeError: this.handleResponse is not a function
    at Trader.handler (/root/gekko/importers/exchanges/bitfinex.js:40:66)
    at bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at RetryOperation._fn (/root/gekko/core/util.js:23:5)
    at RetryOperation.attempt (/root/gekko/node_modules/retry/lib/retry_operation.js:97:8)
    at retryHelper (/root/gekko/core/util.js:22:13)
    at Object.retryCustom (/root/gekko/core/util.js:190:5)
    at Trader.Fetcher.getTrades (/root/gekko/importers/exchanges/bitfinex.js:41:8)
    at Trader.bound [as getTrades] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Object.fetch (/root/gekko/importers/exchanges/bitfinex.js:84:13)
    at Market.get (/root/gekko/core/markets/importer.js:95:16)
    at Market.bound [as get] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Market (/root/gekko/core/markets/importer.js:80:8)
    at /root/gekko/core/pipeline.js:187:20
    at /root/gekko/node_modules/async/dist/async.js:3853:9
    at /root/gekko/node_modules/async/dist/async.js:484:16
    at replenish (/root/gekko/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at prepareMarket (/root/gekko/core/pipeline.js:164:7)
```
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

@cmroche it’s seems the function handleResponse is not defined.

**Comment by cmroche** [comment]
Can you try this on the develop branch and confirm if it is still an issue there?  There might be a partial integration from dev to stable as this function was added recently when refactoring error and retry handling with Bitfinex.

**Comment by Paulovms** [comment]
@cmroche I’d tried this on the developer branch and I got the same issue.

**Comment by cmroche** [comment]
I'll check it out then

**Comment by cmroche** [comment]
@Paulovms I grab the latest developed and tested and it is working for me. I do see that the handleResponse function is defined in to bitfinex exchange file, so I suspect there may be something up with your local copy.

Can you please try a checkout of the develop branch to a fresh location on your filesystem and retry.

Thanks.

**Comment by Paulovms** [comment]
@cmroche Thank you! 
It was my fault. It seems I had got the fist version of bitfinex exchange file on #1550.
