### ISSUE TITLE
Crash when Gekko has full history on second day

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#172]
it appears we don't load the second day in correctly.

debug log:

    2014-01-21 20:29:00 (INFO): Setting up:
    2014-01-21 20:29:00 (INFO):    Profit Simulator
    2014-01-21 20:29:00 (INFO):    Paper trader that logs fake profits.

    2014-01-21 20:29:00 (INFO): Setting up:
    2014-01-21 20:29:00 (INFO):    Profit Simulator
    2014-01-21 20:29:00 (INFO):    Paper trader that logs fake profits.

    2014-01-21 20:29:00 (INFO): Starting to watch the market: BTC-e BTC/USD
    2014-01-21 20:29:01 (INFO): We don't have enough history yet to start giving advice, I'll need to gather more data first.
    2014-01-21 20:29:01 (INFO): I will start giving advice around 2014-01-22 21:03:00 (local time, that's in a day).
    2014-01-22 21:01:21 (INFO): We have all required history, going to calculate advice from this point.
    
    /root/gekko/core/candleManager.js:560
      this.days[mom.dayString].handle.find({
                                      ^
    TypeError: Object #<error> has no method 'find'
        at Manager.getCandles (/root/gekko/core/candleManager.js:560:35)
        at bound [as getCandles] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
        at iterator (/root/gekko/core/candleManager.js:516:10)
        at bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
        at /root/gekko/node_modules/async/lib/async.js:224:13
        at /root/gekko/node_modules/async/lib/async.js:108:13
        at Array.forEach (native)
        at _each (/root/gekko/node_modules/async/lib/async.js:32:24)
        at async.each (/root/gekko/node_modules/async/lib/async.js:107:9)
        at _asyncMap (/root/gekko/node_modules/async/lib/async.js:223:9)

**Comment by askmike** [comment]
fixed!
