### ISSUE TITLE
Gekko trader bot GDAX - QUERY_DELAY not defined

### ISSUE THREAD

**Issue by blastbeng** [askmike/gekko#1727]
Hello,
i think gdax trader has an undefined variable

i solved that by adding 

const QUERY_DELAY = 350;

at line 9

> gekko/exchanges/gdax.js:256
          }, QUERY_DELAY);
             ^

ReferenceError: QUERY_DELAY is not defined
    at Trader.process (/gekko/exchanges/gdax.js:256:14)
    at bound (/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /gekko/core/util.js:28:7
    at /gekko/exchanges/gdax.js:92:12
    at Request._callback (/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)

**Comment by cmroche** [comment]
@blast1987 Thanks, looks like a bad merge.. had another similar issue recently. I'll send a PR with a fix.
