### ISSUE TITLE
My first strategy

### ISSUE THREAD

**Issue by rEVOLV3r** [askmike/gekko#1778]
Hi,

It's the first time i do some js code and i have some trouble with my code.
I used the BB strategy and i modified it because i just want to sell at 2% after a buy (when the zone has reach the bottom).
I will adjust, increase and optimise the strategy after but i'm not able to do this simple task.
I mostly code VBA....but i'm a fast learner.
Where do i declare the Bought_price variable to keep the price at each method.check. So i'll be able to test if the candle.close price is above the bought_price.
(next step is put this %gain in parameters...haha)

Thank you for helping me !
Cheers.

```
/*
  BB_Stepgain strategy - rEVOLV3r 2018-01-23
 */
// helpers
var _ = require('lodash');
var log = require('../core/log.js');

var BB = require('./indicators/BB.js');

// let's create our own method
var method = {};
		
// prepare everything our method needs
method.init = function() {
  this.name = 'BB_Stepgain';
  this.nsamples = 0;
  this.trend = {
    zone: 'none',  // none, top, high, low, bottom
    duration: 0,
    persisted: false
  };
  this.requiredHistory = this.tradingAdvisor.historySize;

  // define the indicators we need
  this.addIndicator('bb', 'BB', this.settings.bbands);
  
  //define the variables we need - it's not working here, where then ?
	var Bought_Price =0;
	var Gain =0; 
}

// for debugging purposes log the last
// calculated parameters.
method.log = function(candle) {
  var digits = 8;
  var BB = this.indicators.bb;
  //BB.lower; BB.upper; BB.middle are your line values 

log.debug('______________________________________');
  log.debug('calculated BB properties for candle ',this.nsamples);

  if (BB.upper>candle.close)  log.debug('\t', 'Upper BB:', BB.upper.toFixed(digits));
  if (BB.middle>candle.close) log.debug('\t', 'Mid   BB:', BB.middle.toFixed(digits));
  if (BB.lower>=candle.close) log.debug('\t', 'Lower BB:', BB.lower.toFixed(digits));
  log.debug('\t', 'price:', candle.close.toFixed(digits));
  if (BB.upper<=candle.close)  log.debug('\t', 'Upper BB:', BB.upper.toFixed(digits));
  if (BB.middle<=candle.close) log.debug('\t', 'Mid   BB:', BB.middle.toFixed(digits));
  if (BB.lower<candle.close)   log.debug('\t', 'Lower BB:', BB.lower.toFixed(digits));
  log.debug('\t', 'Band gap: ', BB.upper.toFixed(digits) - BB.lower.toFixed(digits));
}

method.check = function(candle) {
	var BB = this.indicators.bb;
	var price = candle.close;
	this.nsamples++;

	// price Zone detection
	var zone = 'none';
	if (price >= BB.upper) zone = 'top';
	if ((price < BB.upper) && (price >= BB.middle)) zone = 'high';
	if ((price > BB.lower) && (price < BB.middle)) zone = 'low';
	if (price <= BB.lower) zone = 'bottom';
	log.debug('current zone:  ',zone);
 
	//Not already bought
	if (Bought_Price =0){
		// Ain't no zone change
		if (this.trend.zone == zone){ 
			log.debug('persisted');
			this.trend = {
				zone: zone,  // none, top, high, low, bottom
				duration: this.trend.duration+1,
				persisted: true
			}
			this.advice();
		}
		// There is a zone change
		else {
			log.debug('Leaving zone: ',this.trend.zone)
	
			//utility ? what happend if i don't send any advice ???
			if (this.trend.zone == 'top') this.advice();
			if (this.trend.zone == 'high') this.advice();
			if (this.trend.zone == 'low') this.advice();
			
			if (this.trend.zone == 'bottom') {
				this.advice('long');
				//Putting bought_price
				Bought_Price = price;
				log.debug('>>>>>  WE BOUGHT ! <<<<<<<<');
				log.debug('PRICE : ',price);
			}
			this.trend = {
			  zone: zone,  // none, top, high, low, bottom
			  duration: 0,
			  persisted: false
			}
	  }
	}
	//Time to sell
	else{
		log.debug('bought price :', Bought_Price);
		if (price >= Bought_Price*1.02){
			this.advice('short');
			gain = ((price/Bought_Price)-1)*100;
			log.debug('>>>>>  WE SELL ! <<<<<<<<');
			log.debug('Price : ',price);
			log.debug('Gain : ',Gain);
			Bought_Price = 0;
		}

	
	}

}

module.exports = method;
```

**Comment by rEVOLV3r** [comment]
Ok that works with : if (Bought_Price ==0) and not juste if (Bought_Price =0)...noob mistake.
And i had to declare the 2 internal variables in the beggining of the code.

But how to put this variables into parameters in the .toml ?
Thanks.

**Comment by hansixxxx** [comment]
can´t see a chart when backtracking this... whats the problem?

**Comment by mstfimi** [comment]
cant see the plot after I backtested it, do you know the reason?

**Comment by mstfimi** [comment]
Error: Cannot find module './indicators/BB.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\*****\Desktop\setup\strategies\BBStepgain.js:8:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  xxx POST /api/backtest 500 168ms -

**Comment by rEVOLV3r** [comment]
Hello,

I used the BB strategy that you find in the pll request section. You have to create the 3 files (bb.js for the strat, bb.js for the indicators, bb.toml for config). After that you can run it. By the way i completely modified the bb strategy to add multiple indicators. It s not finished yet.

**Comment by mstfimi** [comment]
How can I create those files and do we know the code inside them?

**Comment by rEVOLV3r** [comment]
Check the pull request section with bb strategy subject. You have the 3 codes written in the post. Just copy past your files, rename them with bb.js or bb.toml and put the code inside them.

**Comment by mstfimi** [comment]
Thanks for you help! I did what you say and run bactest. Allthogh I can run BB strategy without any error, I get this error while running BB_Stepgain:


TypeError: Cannot read property 'NbDevUp' of undefined
    at Indicator.update (C:\Users\fimi\Desktop\setup\strategies\indicators\BB.js:33:44)
    at Base.<anonymous> (C:\Users\fimi\Desktop\setup\plugins\tradingAdvisor\baseTradingMethod.js:143:9)
    at C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:901:23
    at forOwn (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.forEach (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:3303:9)
    at Base.tick (C:\Users\fimi\Desktop\setup\plugins\tradingAdvisor\baseTradingMethod.js:141:5)
    at Base.bound [as tick] (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:729:21)
    at Actor.processCustomCandle (C:\Users\fimi\Desktop\setup\plugins\tradingAdvisor\tradingAdvisor.js:79:15)
    at CandleBatcher.bound (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:729:21)
    at emitOne (events.js:116:13)
--> in Database#all('\n    SELECT * from candles_USDT_BTC\n    WHERE start <= 1508937239 AND start >= 1508934240\n    OR
DER BY start ASC\n  ', [Function])
    at Reader.get (C:\Users\fimi\Desktop\setup\plugins\sqlite\reader.js:98:11)
    at Reader.bound [as get] (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:729:21)
    at Market.get (C:\Users\fimi\Desktop\setup\core\markets\backtest.js:61:15)
    at Market.bound [as get] (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:729:21)
    at Market.processCandles (C:\Users\fimi\Desktop\setup\core\markets\backtest.js:105:10)
    at bound (C:\Users\fimi\Desktop\setup\node_modules\lodash\dist\lodash.js:729:21)
    at Statement.<anonymous> (C:\Users\fimi\Desktop\setup\plugins\sqlite\reader.js:108:5)
  xxx POST /api/backtest 500 310ms -

**Comment by mstfimi** [comment]
And this: ReferenceError: Bought_Price is not defined

**Comment by rEVOLV3r** [comment]
Define 
var Bought_Price =0; 	
var Gain =0; 

Before methode.init as explain in my second post. 

I had another rookie mistake with the ==0. And another one that i learned when programming, in js, var1 <> Var1 or VaR1. The upper case define another variable. So change all the uppercase in my variables and normaly that will work

**Comment by harveymomo** [comment]
i have problem

+var Indicator = function(BBSettings) {
  ^^^

SyntaxError: Unexpected token var
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
  xxx POST /api/backtest 500 785ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (D:\gekko-0.5.13\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

can you help me solve it

**Comment by radumiron** [comment]
@mstfimi I get the same error:
`TypeError: Cannot read property 'NbDevUp' of undefined`
Did you get to fix that? I guess I can always hardcode the value in the BB.js indicator file, but I think that's a configuration that has to be added somewhere...

**Comment by GO1984** [comment]
> TypeError: Cannot read property 'NbDevUp' of undefined

I have this problem too. Any hints for solving it?

**Comment by askmike** [comment]
Hey guys! May I request to move this to the discussion to the forum? Here it is: https://forum.gekko.wizb.it/forum-12.html

You can by all means keep discussing it in this thread but I'm closing it up so it doesn't clog the bug tracker here on github. Thanks!
