### ISSUE TITLE
Binance - Child process dies after around 24 hours

### ISSUE THREAD

**Issue by storshun** [askmike/gekko#1781]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Running a binance traderbot on ETH/NEO with MACD strat for approx. 24 hours.

* **Expected result** (what you hoped would happen)
Child process shouldn't die unexpectedly

* **Actual result** (unexpected outcome)
Error prompt with "Child process has died" language
console shows the following output:
```
2018-01-24 03:08:06 (DEBUG):    calculated MACD properties for candle:
2018-01-24 03:08:06 (DEBUG):             short: 0.00006983
2018-01-24 03:08:06 (DEBUG):             long: 0.00006987
2018-01-24 03:08:06 (DEBUG):             macd: -0.00000004
2018-01-24 03:08:06 (DEBUG):             signal: 0.00000003
2018-01-24 03:08:06 (DEBUG):             macdiff: -0.00000007
2018-01-24 03:08:06 (DEBUG):    In downtrend since 7 candle(s)
  --> POST /api/backtest 200 2,420ms 145.19kb
**[PATH REDACTED]**\gekko\node_modules\binance\lib\rest.js:78
                    if (response.statusCode === 400 && payload.code === -1021 &&
                                 ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (**[PATH REDACTED]**\gekko\node_modules\binance\lib\rest.js:78:34)
    at self.callback (**[PATH REDACTED]**\gekko\node_modules\request\request.js:186:22)
    at Request.emit (events.js:160:13)
    at ClientRequest.<anonymous> (**[PATH REDACTED]**\gekko\node_modules\request\request.js:816:16)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:255:19)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket.Socket._onTimeout (net.js:412:8)
RECEIVED ERROR IN GEKKO 477099192962004
Child process has died.
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
This is a bug with the binance library we are using, I have posted the issue here: https://github.com/aarongarvey/binance/issues/31

**Comment by askmike** [comment]
This bug was actually already fixed in the library. Please install the latest develop version of Gekko and run `npm install` again to fix!
