### ISSUE TITLE
Binance - this.binance.startTimeSync is not a function

### ISSUE THREAD

**Issue by sven76** [askmike/gekko#1802]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
- Cloned the last develop version
- Local Data -> Go to importer -> Start new import
- Exchange: Binance
- Currency: ETH
- Asset: WTC
- From: 2018-01-01 0:01
- To: 2018-01-28 21:38

* **Expected result** (what you hoped would happen)
Import historical data from binance.

* **Actual result** (unexpected outcome)
Import 467041127819075 started
  --> POST /api/import 200 49ms 148b
/var/lib/gekko/gekko_dev.bak/exchanges/binance.js:38
  this.binance.startTimeSync();
               ^

TypeError: this.binance.startTimeSync is not a function
    at new Trader (/var/lib/gekko/gekko_dev.bak/exchanges/binance.js:38:16)
    at Object.<anonymous> (/var/lib/gekko/gekko_dev.bak/importers/exchanges/binance.js:17:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/gekko/gekko_dev.bak/core/markets/importer.js:38:15)
RECEIVED ERROR IN IMPORT 467041127819075
Child process has died.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by HOllarves** [comment]
Try `npm uninstall binance && npm install binance@1.3.0` that solved the problem for me. Apparently it was fixed in https://github.com/askmike/gekko/pull/1737. Also make sure to be on the stable branch and in the current version of it.
