### ISSUE TITLE
Binance Exchange - RSI indicator - this.roundTrip.exit.date.diff is not a function - Child process has died.

### ISSUE THREAD

**Issue by joeljjablonski** [askmike/gekko#1862]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Trading using the RSI indicator on the Binance exchange and after a few hours running it stops with the following error. I've installed the latest version of gekko but the error is still occuring.

* **Expected result** (what you hoped would happen)

I expected that gekko would keep running.

* **Actual result** (unexpected outcome)

C:\Users\Joel\Downloads\gekko-develop\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:112
    duration: this.roundTrip.exit.date.diff(this.roundTrip.entry.date)
                                       ^

TypeError: this.roundTrip.exit.date.diff is not a function
    at PerformanceAnalyzer.handleRoundtrip (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:112:40)
    at PerformanceAnalyzer.bound [as handleRoundtrip] (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.logRoundtripPart (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:94:10)
    at PerformanceAnalyzer.bound [as logRoundtripPart] (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at PerformanceAnalyzer.processTrade (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\plugins\performanceAnalyzer\performanceAnalyzer.js:72:8)
    at Trader.bound (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at emitOne (events.js:121:20)
    at Trader.emit (events.js:211:7)
    at Trader.bound [as emit] (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.Trader.manager.on.trade (C:\Users\Joel\Downloads\gekko-develop\gekko-develop\plugins\trader\trader.js:24:10)
RECEIVED ERROR IN GEKKO 3874845880689617
Child process has died.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Ps. I really appreciate any help anyone may be able to give.

**Comment by askmike** [comment]
What version of Gekko did you download (specifically did you download the release or latest develop branch)?

**Comment by joeljjablonski** [comment]
I've downloaded the develop branch v0.5.13, I was having another issue with the stable release v0.5.10 where it was running into an "undefined" error on the Binance exchange which is why I tried this version. 
What I've done so far (I'm not a programmer) is simply commented out the line that I was having issues with (line 112 of performanceAnalyzer.js), and so far everything seems to be running okay. 
I'm not sure if there would be anything else that you may recommend me to do or if this should be sufficient for me in the time being?

**Comment by askmike** [comment]
Are you running the UI or the CLI version? If the latter please post the config (with API keys removed).

**Comment by joeljjablonski** [comment]
I'm just running the UI.

**Comment by askmike** [comment]
I am quite confident I've found the root cause (empty trade events being broadcasted, see [here](https://github.com/askmike/gekko/pull/1834#issuecomment-362970448) for details). Working on a fix.

What I found:

- paper trader not effected.
- if you use a real trader and the order is not filled the first time an empty event is broadcasted causing other plugins to mess up (like here). If the order is filled straight away this issue does not happen.

**Comment by askmike** [comment]
@joeljjablonski can we keep this open until it's fixed? Thanks!

**Comment by askmike** [comment]
It turned out to be something else, namely this commit: https://github.com/askmike/gekko/commit/2a07c609f3da1629c3e585f702e743f4488dd7ca

**Comment by Red-Maximus** [comment]
Experiencing the same issue. I didn't think to search closed bugs before I submit mine, should I close mine now? (#1872)

**Comment by askmike** [comment]
@Red-Maximus let's keep this one closed and pick up yours in #1872!
