### ISSUE TITLE
Child Process Died

### ISSUE THREAD

**Issue by avi123r** [askmike/gekko#1879]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)
2018-02-07 17:39:13 (INFO):	Setting up Gekko in backtest mode
2018-02-07 17:39:13 (INFO):	
2018-02-07 17:39:13 (INFO):	Setting up:
2018-02-07 17:39:13 (INFO):		 Trading Advisor
2018-02-07 17:39:13 (INFO):		 Calculate trading advice
2018-02-07 17:39:13 (INFO):		 Using the strategy: StochRSI_MACD
  xxx POST /api/backtest 500 185ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/avi/Documents/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
You have to tell us a bit more than this... (what dataset, what strategy, what settings)?

**Comment by cmroche** [comment]
Most of the time this means that your backtest params are not setup properly, tulind and talib sometimes just throw (or lead to exceptions) when you give it a bad config. To troubleshoot this your going to have to provide those details.

**Comment by WebfinityDesign** [comment]
Same error here using Ubuntu, UI, paper trader,  macd, 4 hour candles
