### ISSUE TITLE
BUY order Invalid order or insufficient balance with bitcoin-co-id

### ISSUE THREAD

**Issue by ferdysopian** [askmike/gekko#1895]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Bot was failed to buy order

* **Expected result** (what you hoped would happen)
buy with correct quantity

* **Actual result** (unexpected outcome)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

`2018-02-10 16:36:39 (INFO):	Attempting to BUY 4.2499405469678955 XRP at Bitcoin-co-id price: 0.00012767
2018-02-10 16:36:39 (ERROR):	unable to buy { VError: Bitcoincoid._request() API error: Insufficient balance.
    at Request._callback (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/index.js:85:23)
    at Request.self.callback (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  jse_shortmsg: 'Bitcoincoid._request() API error: Insufficient balance.',
  jse_info: {},
  message: 'Bitcoincoid._request() API error: Insufficient balance.' }
`

`2018-02-10 17:06:18 (INFO):	Trader Received advice to go long. Buying  XRP
2018-02-10 17:06:18 (ERROR):	unable to cancel order:  3403670 ( { VError: Bitcoincoid._request() API error: invalid order.
    at Request._callback (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/index.js:85:23)
    at Request.self.callback (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/chekerlamer/Documents/gekko/node_modules/bitcoin-co-id/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  jse_shortmsg: 'Bitcoincoid._request() API error: invalid order.',
  jse_info: {},
  message: 'Bitcoincoid._request() API error: invalid order.' } ), retrying...
`

**Comment by PhunkyBob** [comment]
Same problem here with Gekko 6.2.0 and Binance - ONT/USDT:
```
2018-07-10 13:36:21 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-07-10 13:36:22 (DEBUG):    Processing 38 new trades. From 2018-07-10 11:36:02 UTC to 2018-07-10 11:36:19 UTC. (a few seconds)
2018-07-10 13:36:42 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-07-10 13:36:43 (DEBUG):    Processing 37 new trades. From 2018-07-10 11:36:22 UTC to 2018-07-10 11:36:40 UTC. (a few seconds)
2018-07-10 13:37:02 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-07-10 13:37:02 (DEBUG):    Processing 39 new trades. From 2018-07-10 11:36:42 UTC to 2018-07-10 11:37:00 UTC. (a few seconds)
2018-07-10 13:37:02 (INFO):     Trader Received advice to go long. Buying  ONT
2018-07-10 13:37:07 (DEBUG):    [ORDER] statusChange: SUBMITTED
handleCreate [binance.js] Error -2010: Account has insufficient balance for requested action.

/home/gekko/gekko/exchange/orders/sticky.js:122
      throw err;
      ^
Error
    at Object.<anonymous> (/home/gekko/gekko/exchange/exchangeErrors.js:34:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/gekko/gekko/exchange/exchangeChecker.js:4:16)
    at Module._compile (module.js:652:30)
```

**Comment by askmike** [comment]
@ferdy42id unfortunately that exchange (recently renamed to indodax) is currently not working anymore.

@PhunkyBob Very strange, I did not encounter this before. Can you please download the latest develop branch that includes a few binance fixes. And if the issue persists please open a new issue.

**Comment by askmike** [comment]
Closing this since `Bitcoin-co-id` is currently not enabled.
