### ISSUE TITLE
No activity on traderbot - BTC-Markets

### ISSUE THREAD

**Issue by lowphatt** [askmike/gekko#1911]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed latest version of Gekko and launched UI. Launched Gekko UI in the command line with 'node gekko --ui'. 

I then did some backtesting on imported data and was happy with a simple strategy that I want to test on a live exchange to make sure the traderbot works. Happy with the testing, I copied & pasted my BTC-Markets API keys into the 'config' tab in the UI. 

* **Expected result** (what you hoped would happen)
After several attempts I let it run with the following simple RSI strategy:

interval = 2

[thresholds]
low = 35
high = 85
persistence = 1

1 minute candles with 10 minute history.

* **Actual result** (unexpected outcome)
After letting the bot run for 3.5 hours today, there were no trades made. I've read that there shouldn't be any other watchers & paperbots running however everytime I run the traderbot there is also a Market Watcher running, i'm guessing this is intended. I do receive buy & sell trades when I run backtesting on the same time period of data. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Is there anything else I need to configure to get the UI Traderbot working? I was under the impression that the using the UI means the config files do not need to be edited. Please let me know if anymore information is required,.

**Comment by lowphatt** [comment]
So I got the traderbot working, apparently it just wasn't updating the UI's 'Roundtrips' table. When I check the logfile I can see the bot running in action.

I have spotted something weird because the Traderbot has moved the decimal point on the price and volume that it is trying to purchase. It received a Buy signal to purchase 390.6026666814814 XRP @ $1.32 AUD, however several lines below that, the bot is trying to purchase 39060266668 XRP at $134000000.00000001

Does anyone have any advice on how to sort out this issue? Thanks

2018-02-12 19:21:21 (INFO):	Trader Received advice to go long. Buying  XRP
2018-02-12 19:21:21 (INFO):	Attempting to BUY 390.6026666814814 XRP at BTC Markets price: 1.34
2018-02-12 19:21:21 (ERROR):	unable to buy { Authentication failed.: BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1518423681481
{"currency":"AUD","instrument":"XRP","price":134000000.00000001,"volume":39060266668,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"0.41558520493604156"}. Error message: Authentication failed.
    at Request._callback (C:\Gekko2\node_modules\btc-markets\index.js:138:21)
    at Request.self.callback (C:\Gekko2\node_modules\btc-markets\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Gekko2\node_modules\btc-markets\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Gekko2\node_modules\btc-markets\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  jse_shortmsg: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1518423681481\n{"currency":"AUD","instrument":"XRP","price":134000000.00000001,"volume":39060266668,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"0.41558520493604156"}. Error message: Authentication failed.',
  jse_summary: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1518423681481\n{"currency":"AUD","instrument":"XRP","price":134000000.00000001,"volume":39060266668,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"0.41558520493604156"}. Error message: Authentication failed.',
  message: 'BTCMarkets.executeRequest() failed POST request to url https://api.btcmarkets.net/order/create with message /order/create\n1518423681481\n{"currency":"AUD","instrument":"XRP","price":134000000.00000001,"volume":39060266668,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"0.41558520493604156"}. Error message: Authentication failed.',
  name: 'Authentication failed.' }
