### ISSUE TITLE
Installed on google cloud, can access web UI ,but it disconnects every time I start trading... 

### ISSUE THREAD

**Issue by ooairbb** [askmike/gekko#1916]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Installed on google cloud, can access web UI ,but it disconnects every time I start paper trader,maarket watcher,or tradebot... 

* **Expected result** (what you hoped would happen)
connect api and start trade...

* **Actual result** (unexpected outcome)
It will shows disconnected .
The error log 👍 

TypeError: _.get is not a function
    at pipelineRunner (/home/server/gekko/web/routes/startGekko.js:86:10)
    at Object.message (/home/server/gekko/core/workers/pipeline/messageHandlers/r                                                                 ealtimeHandler.js:15:9)
    at ChildProcess.<anonymous> (/home/server/gekko/core/workers/pipeline/parent.                                                                 js:29:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
server@gekko:~/gekko$ disconnect

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Thanks

**Comment by ooairbb** [comment]
problem solved gekko-develop\web\routes\startGekko.js:86
needed to be changed to  if(event.log) line

**Comment by askmike** [comment]
Yea that is something that has been fixed, please download the latest version!
