### ISSUE TITLE
Quadriga async.series(getOrders, relay) in porfolioManager crashes

### ISSUE THREAD

**Issue by jchudon** [askmike/gekko#1923]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
async.series(getOrders, relay) in porfolioManager Manager.prototype.relayOrder = function(done) { } crashes right after first trade (buy or sell) on quadrigacx.

* **Expected result** (what you hoped would happen)

* **Actual result** (unexpected outcome)

**Comment by cmroche** [comment]
Callstack, error message or exception?

**Comment by jchudon** [comment]
I am deeply sorry as this is an awful way to report a bug. I will revert back my code and try to reproduce it in order to come with the stack trace.

**Comment by cmroche** [comment]
Lol no worries, when you can get the info I'll take a look :)

**Comment by jchudon** [comment]
There you go

2018-02-13 21:49:37 (INFO):	BUY was successfull
/home/jean-christophe/gekko/exchanges/quadriga.js:180
    if (err) return this.retry(this.getOrder, 'unable to get order', args, err);
                                                                     ^

ReferenceError: args is not defined
    at Trader.<anonymous> (/home/jean-christophe/gekko/exchanges/quadriga.js:180:70)
    at Quadrigacx.module.exports.Quadrigacx.api (/home/jean-christophe/gekko/node_modules/quadrigacx/lib/quadrigacx.js:113:14)
    at Trader.getOrder (/home/jean-christophe/gekko/exchanges/quadriga.js:189:17)
    at Trader.bound [as getOrder] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at next (/home/jean-christophe/gekko/plugins/trader/portfolioManager.js:368:36)
    at /home/jean-christophe/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/home/jean-christophe/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/jean-christophe/gekko/node_modules/async/dist/async.js:1034:9
    at eachOfLimit (/home/jean-christophe/gekko/node_modules/async/dist/async.js:1061:22)
    at /home/jean-christophe/gekko/node_modules/async/dist/async.js:1066:16

**Comment by cmroche** [comment]
Thanks, I'll have something for you to test shortly.

**Comment by jchudon** [comment]
2018-02-14 20:20:07 (DEBUG):	Unable to find "CAD" in portfolio provided by exchange, assuming 0.
2018-02-14 20:20:07 (DEBUG):	Unable to find "LTC" in portfolio provided by exchange, assuming 0.
2018-02-14 20:20:07 (INFO):	trading at quadriga ACTIVE

**Comment by jchudon** [comment]
Hey, after I've "fixed" the uppercase problem, I get  

2018-02-14 22:09:38 (INFO):	Attempting to BUY 0.011234782608695652 eth at quadriga price: 1145.05
/home/jean-christophe/gekko/exchanges/quadriga.js:140
  var market = this.getCapabilities().markets.find(function(market){ return market.pair[0] === this.currency && market.pair[1] === this.asset });
                    ^

TypeError: this.getCapabilities is not a function
    at Trader.roundAmount (/home/jean-christophe/gekko/exchanges/quadriga.js:140:21)
    at Trader.bound [as roundAmount] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.addOrder (/home/jean-christophe/gekko/exchanges/quadriga.js:154:17)
    at Trader.bound [as addOrder] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.buy (/home/jean-christophe/gekko/exchanges/quadriga.js:194:8)
    at Trader.bound [as buy] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.buy (/home/jean-christophe/gekko/plugins/trader/portfolioManager.js:219:17)
    at Manager.bound [as buy] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.act (/home/jean-christophe/gekko/plugins/trader/portfolioManager.js:165:16)
    at bound (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)


Does that ring a bell?

**Comment by cmroche** [comment]
Pushed an update, please give it a try

**Comment by jchudon** [comment]
I still get : 2018-02-16 06:48:20 (DEBUG):	Unable to find "CAD" in portfolio provided by exchange, assuming 0.
2018-02-16 06:48:20 (DEBUG):	Unable to find "ETH" in portfolio provided by exchange, assuming 0.

**Comment by larathydo** [comment]
I am also having this issue, I am on 0.5.13 and see the following when I start it up using CAD/LTC on QuadrigaCX:

2018-03-10 18:14:52 (DEBUG):    Unable to find "CAD" in portfolio provided by exchange, assuming 0.
2018-03-10 18:14:52 (DEBUG):    Unable to find "LTC" in portfolio provided by exchange, assuming 0.

**Comment by daflame76** [comment]
You'll need to check out this repo.  There is a fix for balance determination.
https://github.com/cmroche/gekko/tree/qcx

You'll have to cherry pick to stable though.  Event then I needed to apply another patch to fix Quadriga rounding issues.
