### ISSUE TITLE
Crashes when buying on quadriga

### ISSUE THREAD

**Issue by jchudon** [askmike/gekko#1935]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)

Set up a quadriga file with CAD and ETH

* **Expected result** (what you hoped would happen)

The robot buys when it meets the required config

* **Actual result** (unexpected outcome)

The robot crashed

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

2018-02-16 09:37:26 (INFO):	Trader Received advice to go long. Buying  eth
2018-02-16 09:37:26 (INFO):	Attempting to BUY 0.0026050146532074245 eth at quadriga price: 1157.00
/home/jean-christophe/gekko/exchanges/quadriga.js:142
  if(Number.isInteger(market.precision))
                             ^

TypeError: Cannot read property 'precision' of undefined
    at Trader.roundAmount (/home/jean-christophe/gekko/exchanges/quadriga.js:142:30)
    at Trader.bound [as roundAmount] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.addOrder (/home/jean-christophe/gekko/exchanges/quadriga.js:154:17)
    at Trader.bound [as addOrder] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.buy (/home/jean-christophe/gekko/exchanges/quadriga.js:194:8)
    at Trader.bound [as buy] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.buy (/home/jean-christophe/gekko/plugins/trader/portfolioManager.js:218:17)
    at Manager.bound [as buy] (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.act (/home/jean-christophe/gekko/plugins/trader/portfolioManager.js:164:16)
    at bound (/home/jean-christophe/gekko/node_modules/lodash/dist/lodash.js:729:21)

**Comment by jcoder76** [comment]
I have the same problem, has this never been fixed?

**Comment by jcoder76** [comment]
Based on how it is failing I would guess it could be related to the issue with the lowercase asset and currency names again.

**Comment by jcoder76** [comment]
It does a search for the matching market just before the precision check and I suspect isn't finding a matching market:

```javascript
  var market = Trader.getCapabilities().markets.find(function(market){ return market.pair[0] === this.currency && market.pair[1] === this.asset });
```

**Comment by jcoder76** [comment]
All the markets are 8 digit precision so I commented out the if statement and market lookup and left it at the default of 8 digits.  It is running trades just fine now.

**Comment by jcoder76** [comment]
The QuadrigaCX exchange is dead and all references should be removed.  https://www.quadrigacx.com/
