### ISSUE TITLE
[gdax.js] (getPortfolio) returned an irrecoverable error: request timestamp expired

### ISSUE THREAD

**Issue by ianwaldrop** [askmike/gekko#1967]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
* Tried to start a tradebot.

* **Expected result** (what you hoped would happen)
* Tradebot begins to trade.

* **Actual result** (unexpected outcome)
* Tradebot failed to start; alert dialog appears in page, issue title appears in log.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

1. Checked out develop (0d975707009456720f59b98c102c334c05e35585)
2. Started docker instance using included docker files
3. tradebot log
```
2018-02-24 02:26:25 (INFO):	Setting up Gekko in realtime mode
2018-02-24 02:26:25 (INFO):	
2018-02-24 02:26:25 (INFO):	Setting up:
2018-02-24 02:26:25 (INFO):		 Candle writer
2018-02-24 02:26:25 (INFO):		 Store candles in a database
2018-02-24 02:26:25 (INFO):	

2018-02-24 02:26:25 (INFO):	Setting up:
2018-02-24 02:26:25 (INFO):		 Trading Advisor
2018-02-24 02:26:25 (INFO):		 Calculate trading advice
2018-02-24 02:26:25 (INFO):		 Using the strategy: Wallyworld
2018-02-24 02:26:25 (INFO):	

2018-02-24 02:26:25 (INFO):	Setting up:
2018-02-24 02:26:25 (INFO):		 Trader
2018-02-24 02:26:25 (INFO):		 Follows the advice and create real orders.
2018-02-24 02:26:25 (DEBUG):	getting ticker, balance & fee from GDAX
2018-02-24 02:26:25 (INFO):	

2018-02-24 02:26:26 (ERROR):	[gdax.js] (getPortfolio) returned an irrecoverable error: request timestamp expired
```
4. gekko log
```
gekko_1  |   <-- GET /api/imports
gekko_1  |   --> GET /api/imports 200 6ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 1ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 1ms 2b
gekko_1  |   <-- GET /api/exchanges
gekko_1  |   <-- GET /api/apiKeys
gekko_1  |   --> GET /api/apiKeys 200 1ms 2b
gekko_1  |   --> GET /api/exchanges 200 736ms 91.58kb
gekko_1  |   <-- GET /api/imports
gekko_1  |   --> GET /api/imports 200 1ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 0ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 0ms 2b
gekko_1  |   <-- GET /api/apiKeys
gekko_1  |   --> GET /api/apiKeys 200 1ms 2b
gekko_1  |   <-- GET /api/exchanges
gekko_1  |   --> GET /api/exchanges 200 4ms 91.58kb
gekko_1  |   <-- GET /api/configPart/candleWriter
gekko_1  |   <-- GET /api/configPart/performanceAnalyzer
gekko_1  |   --> GET /api/configPart/candleWriter 200 3ms 47b
gekko_1  |   --> GET /api/configPart/performanceAnalyzer 200 3ms 144b
gekko_1  |   <-- GET /api/strategies
gekko_1  |   <-- GET /api/configPart/paperTrader
gekko_1  |   --> GET /api/configPart/paperTrader 200 1ms 132b
gekko_1  |   --> GET /api/strategies 200 30ms 2.2kb
gekko_1  |   <-- GET /api/imports
gekko_1  |   --> GET /api/imports 200 0ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 0ms 2b
gekko_1  |   <-- GET /api/gekkos
gekko_1  |   --> GET /api/gekkos 200 1ms 2b
gekko_1  |   <-- GET /api/apiKeys
gekko_1  |   --> GET /api/apiKeys 200 1ms 2b
gekko_1  |   <-- GET /api/exchanges
gekko_1  |   --> GET /api/exchanges 200 4ms 91.58kb
gekko_1  |   <-- POST /api/addApiKey
gekko_1  |   --> POST /api/addApiKey 200 4ms 15b
gekko_1  |   <-- GET /api/configPart/candleWriter
gekko_1  |   <-- GET /api/configPart/performanceAnalyzer
gekko_1  |   --> GET /api/configPart/candleWriter 200 4ms 47b
gekko_1  |   --> GET /api/configPart/performanceAnalyzer 200 4ms 144b
gekko_1  |   <-- GET /api/strategies
gekko_1  |   <-- GET /api/configPart/paperTrader
gekko_1  |   --> GET /api/configPart/paperTrader 200 1ms 132b
gekko_1  |   --> GET /api/strategies 200 48ms 2.2kb
gekko_1  |   <-- POST /api/startGekko
gekko_1  | Gekko 532994159319142 started
gekko_1  |   --> POST /api/startGekko 200 9ms 143b
gekko_1  |   <-- POST /api/startGekko
gekko_1  | Gekko 199890294241011 started
gekko_1  |   --> POST /api/startGekko 200 6ms 326b
gekko_1  | RECEIVED ERROR IN GEKKO 199890294241011
gekko_1  |
gekko_1  |
gekko_1  | Gekko encountered an error and can't continue
gekko_1  |
gekko_1  |
gekko_1  | Gekko encountered an error and can't continue
gekko_1  |
gekko_1  | Error:
gekko_1  |
gekko_1  | [gdax.js] request timestamp expired
gekko_1  |
gekko_1  | Meta debug info:
gekko_1  |
gekko_1  | Gekko version: v0.5.13
gekko_1  | Nodejs version: v8.9.4
```

**Comment by ianwaldrop** [comment]
For now I've gone as far as locating the `getPortfolio` function and will take a look later tonight.

**Comment by ianwaldrop** [comment]
Tried running from command line with same effect, but I got a hot tip about the npm log.

Gekko log
```
gekko_1  |    /      \ /        |/  |  /  |/  |  /  | /      \
gekko_1  |   /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
gekko_1  |   $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
gekko_1  |   $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
gekko_1  |   $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
gekko_1  |   $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
gekko_1  |   $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
gekko_1  |    $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/
gekko_1  |
gekko_1  | 	Gekko v0.5.13
gekko_1  | 	I'm gonna make you rich, Bud Fox.
gekko_1  |
gekko_1  |
gekko_1  | 2018-02-24 06:24:18 (INFO):	Setting up Gekko in realtime mode
gekko_1  | 2018-02-24 06:24:18 (INFO):
gekko_1  | 2018-02-24 06:24:18 (INFO):	Setting up:
gekko_1  | 2018-02-24 06:24:18 (INFO):		 Trading Advisor
gekko_1  | 2018-02-24 06:24:18 (INFO):		 Calculate trading advice
gekko_1  | 2018-02-24 06:24:18 (INFO):		 Using the strategy: Wallyworld
gekko_1  | 2018-02-24 06:24:18 (INFO):		The trading method requests 600 minutes of historic data. Checking availablity..
gekko_1  | 2018-02-24 06:24:18 (INFO):
gekko_1  |
gekko_1  | 2018-02-24 06:24:18 (DEBUG):		Available local data:
gekko_1  | 2018-02-24 06:24:18 (DEBUG):			from: 32 minutes ago
gekko_1  | 2018-02-24 06:24:18 (DEBUG):			to: 26 minutes ago
gekko_1  | 2018-02-24 06:24:18 (INFO):		Usable local data available, trying to match with exchange data..
gekko_1  | 2018-02-24 06:24:18 (DEBUG):		Fetching exchange data since 41 minutes ago
gekko_1  | 2018-02-24 06:24:18 (DEBUG):	Scanning back in the history needed...
gekko_1  | 2018-02-24 06:24:18 (DEBUG):	2018-02-24T05:43:00Z
gekko_1  | 2018-02-24 06:24:19 (DEBUG):	Scanning backwards...2018-02-24T06:24:00.87Z
gekko_1  | 2018-02-24 06:24:20 (DEBUG):	Scanning backwards...2018-02-24T06:21:13.005Z
gekko_1  | 2018-02-24 06:24:20 (DEBUG):	Scanning backwards...2018-02-24T06:12:58.947Z
gekko_1  | 2018-02-24 06:24:21 (DEBUG):	Scanning backwards...2018-02-24T06:00:08.625Z
gekko_1  | 2018-02-24 06:24:22 (DEBUG):	Scanning backwards...2018-02-24T05:46:57.397Z
gekko_1  | 2018-02-24 06:24:23 (DEBUG):	Backwards: 2018-02-24T05:21:54.846Z (37999627) to 2018-02-24T05:27:01.62Z (37999726)
gekko_1  | 2018-02-24 06:24:23 (DEBUG):	Backwards: 2018-02-24T05:27:08.353Z (37999727) to 2018-02-24T05:30:07.613Z (37999826)
gekko_1  | 2018-02-24 06:24:24 (DEBUG):	Backwards: 2018-02-24T05:30:07.613Z (37999827) to 2018-02-24T05:33:03.509Z (37999926)
gekko_1  | 2018-02-24 06:24:25 (DEBUG):	Backwards: 2018-02-24T05:33:03.509Z (37999927) to 2018-02-24T05:37:01.769Z (38000026)
gekko_1  | 2018-02-24 06:24:25 (DEBUG):	Backwards: 2018-02-24T05:37:01.769Z (38000027) to 2018-02-24T05:41:48.921Z (38000126)
gekko_1  | 2018-02-24 06:24:26 (DEBUG):	Backwards: 2018-02-24T05:41:48.921Z (38000127) to 2018-02-24T05:46:57.395Z (38000226)
gekko_1  | 2018-02-24 06:24:27 (DEBUG):	Backwards: 2018-02-24T05:46:57.397Z (38000227) to 2018-02-24T05:47:33.778Z (38000326)
gekko_1  | 2018-02-24 06:24:27 (DEBUG):	Backwards: 2018-02-24T05:47:33.778Z (38000327) to 2018-02-24T05:47:49.862Z (38000426)
gekko_1  | 2018-02-24 06:24:28 (DEBUG):	Backwards: 2018-02-24T05:47:49.862Z (38000427) to 2018-02-24T05:51:55.079Z (38000526)
gekko_1  | 2018-02-24 06:24:28 (DEBUG):	Backwards: 2018-02-24T05:51:55.079Z (38000527) to 2018-02-24T05:52:50.517Z (38000626)
gekko_1  | 2018-02-24 06:24:29 (DEBUG):	Backwards: 2018-02-24T05:52:58.85Z (38000627) to 2018-02-24T06:00:07.674Z (38000726)
gekko_1  | 2018-02-24 06:24:31 (DEBUG):	Backwards: 2018-02-24T06:00:08.625Z (38000727) to 2018-02-24T06:03:50.14Z (38000826)
gekko_1  | 2018-02-24 06:24:31 (DEBUG):	Backwards: 2018-02-24T06:03:52.073Z (38000827) to 2018-02-24T06:06:08.97Z (38000926)
gekko_1  | 2018-02-24 06:24:32 (DEBUG):	Backwards: 2018-02-24T06:06:08.97Z (38000927) to 2018-02-24T06:06:57.069Z (38001026)
gekko_1  | 2018-02-24 06:24:32 (DEBUG):	Backwards: 2018-02-24T06:06:58.292Z (38001027) to 2018-02-24T06:12:50.753Z (38001126)
gekko_1  | 2018-02-24 06:24:33 (DEBUG):	Backwards: 2018-02-24T06:12:58.947Z (38001127) to 2018-02-24T06:16:21.93Z (38001226)
gekko_1  | 2018-02-24 06:24:33 (DEBUG):	Backwards: 2018-02-24T06:16:21.93Z (38001227) to 2018-02-24T06:18:29.806Z (38001326)
gekko_1  | 2018-02-24 06:24:34 (DEBUG):	Backwards: 2018-02-24T06:18:29.806Z (38001327) to 2018-02-24T06:21:13.005Z (38001426)
gekko_1  | 2018-02-24 06:24:35 (DEBUG):	Backwards: 2018-02-24T06:21:13.005Z (38001427) to 2018-02-24T06:23:49.039Z (38001526)
gekko_1  | 2018-02-24 06:24:36 (DEBUG):	Backwards: 2018-02-24T06:23:49.039Z (38001527) to 2018-02-24T06:24:00.87Z (38001626)
gekko_1  | 2018-02-24 06:24:36 (DEBUG):	Backwards: 2018-02-24T06:24:00.87Z (38001627) to 2018-02-24T06:25:22.486Z (38001726)
gekko_1  | 2018-02-24 06:24:37 (DEBUG):	Backwards: 2018-02-24T06:24:00.87Z (38001630) to 2018-02-24T06:25:39.53Z (38001729)
gekko_1  | 2018-02-24 06:24:38 (DEBUG):	Backwards: 2018-02-24T06:24:00.87Z (38001630) to 2018-02-24T06:25:39.53Z (38001729)
gekko_1  | 2018-02-24 06:24:38 (DEBUG):	Scan finished: data found:2300
gekko_1  | 2018-02-24 06:24:38 (DEBUG):		Available exchange data:
gekko_1  | 2018-02-24 06:24:38 (DEBUG):			from: 62 minutes ago
gekko_1  | 2018-02-24 06:24:38 (DEBUG):			to: -1 minutes ago
gekko_1  | 2018-02-24 06:24:38 (DEBUG):		Exchange offered more data than locally available. Ignoring local data
gekko_1  | 2018-02-24 06:24:38 (DEBUG):		Unable to stitch datasets.
gekko_1  | 2018-02-24 06:24:38 (INFO):		Not seeding locally available data to the trading method.
gekko_1  | 2018-02-24 06:24:38 (INFO):		However the exchange returned enough data anyway!
gekko_1  | 2018-02-24 06:24:38 (INFO):	Setting up:
gekko_1  | 2018-02-24 06:24:38 (INFO):		 Trader
gekko_1  | 2018-02-24 06:24:38 (INFO):		 Follows the advice and create real orders.
gekko_1  | 2018-02-24 06:24:38 (DEBUG):	getting ticker, balance & fee from GDAX
gekko_1  | 2018-02-24 06:24:38 (INFO):
gekko_1  |
gekko_1  | 2018-02-24 06:24:39 (ERROR):	[gdax.js] (getPortfolio) returned an irrecoverable error: request timestamp expired
gekko_1  |
gekko_1  |
gekko_1  | Gekko encountered an error and can't continue
gekko_1  |
gekko_1  | Error:
gekko_1  |
gekko_1  | [gdax.js] request timestamp expired
gekko_1  |
gekko_1  |
gekko_1  |
gekko_1  | Meta debug info:
gekko_1  |
gekko_1  | Gekko version: v0.5.13
gekko_1  | Nodejs version: v8.9.4
gekko_1  |
gekko_1  | npm ERR! code ELIFECYCLE
gekko_1  | npm ERR! errno 1
gekko_1  | npm ERR! gekko@0.5.13 start: `node ./gekko --config config.js`
gekko_1  | npm ERR! Exit status 1
gekko_1  | npm ERR!
gekko_1  | npm ERR! Failed at the gekko@0.5.13 start script.
gekko_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
gekko_1  |
gekko_1  | npm ERR! A complete log of this run can be found in:
gekko_1  | npm ERR!     /root/.npm/_logs/2018-02-24T06_24_39_169Z-debug.log
```

npm log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gekko@0.5.13~prestart: gekko@0.5.13
6 info lifecycle gekko@0.5.13~start: gekko@0.5.13
7 verbose lifecycle gekko@0.5.13~start: unsafe-perm in lifecycle true
8 verbose lifecycle gekko@0.5.13~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle gekko@0.5.13~start: CWD: /usr/src/app
10 silly lifecycle gekko@0.5.13~start: Args: [ '-c', 'node ./gekko --config config.js' ]
11 silly lifecycle gekko@0.5.13~start: Returned: code: 1  signal: null
12 info lifecycle gekko@0.5.13~start: Failed to exec start script
13 verbose stack Error: gekko@0.5.13 start: `node ./gekko --config config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid gekko@0.5.13
15 verbose cwd /usr/src/app
16 verbose Linux 4.9.49-moby
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error gekko@0.5.13 start: `node ./gekko --config config.js`
22 error Exit status 1
23 error Failed at the gekko@0.5.13 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ianwaldrop** [comment]
I got it to work. Needed to do a few things.

1. dunno if it's necessary, but I did it, update gdax npm package to 0.6.0. Update gdax.js to conform to new api (3 methods, 5 places)...will edit this with detail more soon.
2. apply patch to skew local/gdax time from here [here](https://github.com/coinbase/gdax-node/issues/242) and [here](https://github.com/coinbase/gdax-node/pull/243/files)
