### ISSUE TITLE
Please Assist gekko setup on Ras Pi3 (Stretch)

### ISSUE THREAD

**Issue by CharlieJazzGuitar** [askmike/gekko#1974]
Hi,

I am getting these errors when attempting to run gekko (I can't even find this file??).  Any assistance would be most appreciated.:

Tku,

Charlie...

  <-- POST /api/startGekko
Gekko 865599915792683 started
  --> POST /api/startGekko 200 53ms 147b
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/home/pi/gekko/core/../history'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.<anonymous> (/home/pi/gekko/plugins/sqlite/handle.js:35:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/gekko/plugins/sqlite/writer.js:4:14)
RECEIVED ERROR IN GEKKO 865599915792683
Child process has died.

**Comment by askmike** [comment]
This is a permission problem, gekko doesn't have access to read/write inside the gekko dir. If you are unable to fix it still please ask around on the forum. This is a bug tracker :)
