### ISSUE TITLE
Gekko is trying to connect 192.168.1.1:443

### ISSUE THREAD

**Issue by clementcho** [askmike/gekko#1989]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
I am looking into the log file and I found that there is an attempt to connect 192.168.1.1:443

* **Expected result** (what you hoped would happen)
Not looking into connect my local address. 

* **Actual result** (unexpected outcome)
I am getting this message in my log file. 
2018-03-01 11:53:22 (ERROR):    Error getTrades() { success: false,
  message: 'URL request error',
  error:
   { Error: connect ECONNREFUSED 192.168.1.1:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1181:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '192.168.1.1',
     port: 443 },
  result: undefined }
2018-03-01 11:53:22 (DEBUG):    Bittrex returned an error, retrying. [ false, [Function: bound], false ]
2018-03-01 11:53:22 (ERROR):    Error getTrades() { success: false,
  message: 'URL request error',
  error:
   { Error: connect ECONNREFUSED 192.168.1.1:443
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1181:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '192.168.1.1',
     port: 443 },
  result: undefined }

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
What exchange were you running?

**Comment by clementcho** [comment]
I was running with Gdax, Poloniex, Kraken, Bittrex.
