### ISSUE TITLE
[wex.nz] getOrder Error: invalid nonce parameter

### ISSUE THREAD

**Issue by kifirkin** [askmike/gekko#2015]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Strategy send advice to go long.

* **Expected result** (what you hoped would happen)
No errors.

* **Actual result** (unexpected outcome)
Got Error.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
2018-03-08 22:43:40 (INFO): We have new trading advice!
2018-03-08 22:43:40 (INFO):      Position: long
2018-03-08 22:43:40 (INFO):      Market price: 1.93
2018-03-08 22:43:40 (INFO):      Based on market time: 2018-03-08 19:32:00

2018-03-08 22:43:40 (INFO): Trader Received advice to go long. Buying  NMC
2018-03-08 22:43:40 (INFO): Attempting to BUY 2.415745943877551 NMC at wex.nz price: 1.93
2018-03-08 22:44:42 (INFO): BUY was successfull
getOrder 216082038
2018-03-08 22:44:42 (ERROR):    error on getOrder Error: invalid nonce parameter; on key:1520538282, you sent:'1520538282', you should send:1520538283
    at Request._callback (C:\homework\money\gekko\node_modules\node-wex\wex.js:60:23)
    at Request.self.callback (C:\homework\money\gekko\node_modules\node-wex\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\homework\money\gekko\node_modules\node-wex\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\homework\money\gekko\node_modules\node-wex\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
getOrder 216082038
2018-03-08 22:44:52 (ERROR):    wex.nz did not provide the order
```

**Comment by krieghof** [comment]
This should be fixed now with the new node-wex v1.0.4.

**Comment by kifirkin** [comment]
@krieghof I guess it's gone! thanks!

**Comment by krieghof** [comment]
@alexmironof
Thanks for reporting the bug, glad I could help you
