### ISSUE TITLE
operation is not defined

### ISSUE THREAD

**Issue by rogerfar** [askmike/gekko#2038]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken**
Configure the mailer and try so have it send an email (and fail)

**Expected result** (what you hoped would happen)
Email gets sent

**Actual result** (unexpected outcome)
ReferenceError: operation is not defined
    at Object.retry (/root/gekko/core/util.js:187:21)
    at Mailer.mail (/root/gekko/plugins/mailer.js:84:8)
    at Mailer.bound [as mail] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Mailer.setupMail (/root/gekko/plugins/mailer.js:42:12)
    at Mailer.setup (/root/gekko/plugins/mailer.js:79:15)
    at Mailer.bound [as setup] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Mailer (/root/gekko/plugins/mailer.js:15:8)
    at load (/root/gekko/core/pluginUtil.js:95:22)
    at /root/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/root/gekko/node_modules/async/dist/async.js:1030:17)

Looks like there is an undefined object "operation" in util.js line 187. Replace it with "options" and that should be good.

**Comment by askmike** [comment]
Oops! Will fix asap
