### ISSUE TITLE
Gekko headless errror: Cannot read property 'enabled'

### ISSUE THREAD

**Issue by Kralg** [askmike/gekko#2041]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Followed the instructions of Gekko installation on raspberry. https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html#configuring-gekko-to-run-in-the-cloud

node gekko --config web/vue/UIconfig.js

**Expected result** (what you hoped would happen)
Running headless Gekko on raspberry

**Actual result** (unexpected outcome)
home/pi/gekko/gekko.js:50
  config.trader.enabled &&
                ^

TypeError: Cannot read property 'enabled' of undefined
    at Object.<anonymous> (/home/pi/gekko/gekko.js:50:17)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
If I run node gekko I am getting message that config file is not specified. Therefore I run node gekko --config web/vue/UIconfig.js

The UIconfig.js is

```
const CONFIG = {
  headless: true,
  api: {
    host: '127.0.0.1',
    port: 3000//,
    // timeout: 120000 // 2 minutes
  },
  ui: {
    ssl: false,
    host: '192.168.1.96', //'localhost',
    port: 3000,
    path: '/'
  },
  adapter: 'sqlite'
}

if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

```

**Comment by Kralg** [comment]
The problem was that gekko should be launched with node gekko --ui in this case.
