### ISSUE TITLE
TelegramBot-  Error: connect ETIMEDOUT 149.154.167.220:443

### ISSUE THREAD

**Issue by xFFFFF** [askmike/gekko#2045]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
nothing. 

**Expected result** (what you hoped would happen)
advice notification via telegram bot

**Actual result** (unexpected outcome)
```
[Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
    at new RequestError (/home/f/!skrypty/gekko/binance-trade/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/f/!skrypty/gekko/binance-trade/node_modules/node-telegram-bot-api/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/f/!skrypty/gekko/binance-trade/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/f/!skrypty/gekko/binance-trade/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)]
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
```
[ping 149.154.167.220
PING 149.154.167.220 (149.154.167.220) 56(84) bytes of data.
64 bytes from 149.154.167.220: icmp_seq=1 ttl=50 time=83.1 ms
64 bytes from 149.154.167.220: icmp_seq=2 ttl=50 time=67.0 ms
64 bytes from 149.154.167.220: icmp_seq=3 ttl=50 time=60.7 ms
```

```
curl 149.154.167.220:443
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor=whit">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.12.2</center>
</body>
</html>`
```

Notification was work some days, and stop work 2 days ago.

**Comment by xFFFFF** [comment]
Another error on gekko start:
```
2018-03-23 18:57:54 (INFO):              Telegram module lets you communicate with Gekko on Telegram.
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:649:30
```

**Comment by maxbaluev** [comment]
I have same error with sendPhoto

**Comment by xFFFFF** [comment]
Russian ban some ips ranges. You must use proxy.

**Comment by maxbaluev** [comment]
I have same error with VPN

**Comment by xFFFFF** [comment]
Try with VPN from Russia:)
https://www.siliconrepublic.com/enterprise/russia-telegram-google-gmail
https://www.theverge.com/2018/4/17/17246150/telegram-russia-ban
