### ISSUE TITLE
Gdax Trade Class Error

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2106]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a Gekko CLI crash error...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Rn Gekko bot on GDax exchange after pulling latest update including the Trade class PR, when the bot attempts to trade on advice it crashes.

**Expected result** (what you hoped would happen)
It would trade

**Actual result** (unexpected outcome)
It crashes

**Other information** (e.g. Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

CLI error code below...

/root/gekko/plugins/trader/trade.js:312
      return minimum = this.minimalOrder.amount;
                     ^

ReferenceError: minimum is not defined
    at Trade.getMinimum (/root/gekko/plugins/trader/trade.js:312:22)
    at Trade.sell (/root/gekko/plugins/trader/trade.js:185:22)
    at act (/root/gekko/plugins/trader/trade.js:89:18)
    at /root/gekko/node_modules/async/dist/async.js:3853:9
    at /root/gekko/node_modules/async/dist/async.js:484:16
    at replenish (/root/gekko/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at set (/root/gekko/plugins/trader/portfolio.js:89:9)
    at Trader.getFee (/root/gekko/exchanges/gdax.js:140:3)
    at Trader.bound [as getFee] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Portfolio.setFee (/root/gekko/plugins/trader/portfolio.js:91:19)
    at /root/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/root/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at set (/root/gekko/plugins/trader/portfolio.js:74:9)
    at Trader.result (/root/gekko/exchanges/gdax.js:115:5)
    at bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /root/gekko/core/util.js:28:7
    at /root/gekko/exchanges/gdax.js:101:12
    at Request._callback (/root/gekko/node_modules/gdax/lib/clients/public.js:45:7)

Help as i cannot use the bot at this point in time,

**Comment by H256** [comment]
Have a look here for a temporary fix: https://github.com/askmike/gekko/issues/2083

**Comment by Kris191** [comment]
Perfect will make the adjustment
