### ISSUE TITLE
Problem with starting the GA

### ISSUE THREAD

**Issue by 123qweas** [askmike/gekko#2117]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I started a API server with this comand `node –max-old-space-size=8192 server.js`. Workes fine.
I followed the steps form [this](http://gekkowarez.com/gekko-genetic-algorithm/) page how to start the GA. After I used his comand `node run -c config/your-new.js`. 

**Expected result** (what you hoped would happen)
I expected that the GA would run.

**Actual result** (unexpected outcome)
I got this error message:

C:\Users\threi\Downloads\hanstutorial\gekko-stable\gekkoga>node run -c config/your-new.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'flat'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\threi\Downloads\hanstutorial\gekko-stable\gekkoga\index.js:7:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\threi\Downloads\hanstutorial\gekko-stable\gekkoga\run.js:1:74)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Befor I got this Error I got this Error:

C:\Users\threi\Downloads\hanstutorial\gekko-stable\gekkoga>node run -c config/your-new.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'nodemailer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\threi\Downloads\hanstutorial\gekko-stable\gekkoga\index.js:2:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

But I fixed it with installing the module.
Unluckily I didnt founf a flat module to install.

**Comment by H256** [comment]
Try installing the flat module via `npm install flat` - this should do.

**Comment by 123qweas** [comment]
It worked. Thanks!
