### ISSUE TITLE
GA: Error: socket hang up

### ISSUE THREAD

**Issue by 123qweas** [askmike/gekko#2119]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report 
[ ] question about the decisions made in the repository

**Action taken** (what you did)
started the GA with `node run -c config/your-new-macd-XPR.js` while my API server was running

**Expected result** (what you hoped would happen)
That the GA does its thing.

**Actual result** (unexpected outcome)
Does everything nomal but after a time I got this error and I can't find a solution.

{ RequestError: Error: socket hang up
    at new RequestError (C:\Users\threi\Downloads\hanstutorial\gekko-stable\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\threi\Downloads\hanstutorial\gekko-stable\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\threi\Downloads\hanstutorial\gekko-stable\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\threi\Downloads\hanstutorial\gekko-stable\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\threi\Downloads\hanstutorial\gekko-stable\node_modules\request\request.js:878:8)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: socket hang up',
  cause: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' },
  error: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' },
  options:
   { url: 'http://localhost:3000/api/backtest',
     json: true,
     body: { gekkoConfig: [Object], data: [Object] },
     headers: { 'Content-Type': 'application/json' },
     timeout: 1200000,
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

btw: the API server didnt got interrupted by this error.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by xFFFFF** [comment]
I see you increased the timeout in `UIconfig.js`. Try to increase it even more. If this does not help, check if the japonicus has similar problems.
