### ISSUE TITLE
Error when starting a genetic simulation on actual config (macos)

### ISSUE THREAD

**Issue by BobTheTool** [askmike/gekko#2128]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Start my config.js on gekkoga genetic plugin (mac osx 10.13

**Expected result** (what you hoped would happen)

launch backtest for my strategy and help me to improve it.

**Actual result** (unexpected outcome)

gekkoga josephmichel$ node run -c config/config.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module './web/isWindows.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/josephineboutron/gekko/gekkoga/config/config.js:282:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/josephineboutron/gekko/gekkoga/run.js:16:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

isWindows.js is actually here in the gekko/web folder

**Comment by roller-project** [comment]
error because u move config file to sub folder.
u can fix 
cp config/config.js config/config-2.js
node run -c config-2.js
