### ISSUE TITLE
Cannot BACKTEST with varPPO strategy

### ISSUE THREAD

**Issue by shmutalov** [askmike/gekko#2138]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a bug**
[ ] bug report

**Action taken** (what you did)
Loaded BTC-XLM data from Binance (2018-02-01 - 2018-04-27)
Ran backtest with `varPPO` strategy:
![image](https://user-images.githubusercontent.com/8098898/39391802-e5ab1cce-4ac2-11e8-8c93-85085bf49452.png)

**Expected result** (what you hoped would happen)
Successful execution

**Actual result** (unexpected outcome)
```js
2018-04-28 08:59:00 (INFO):     Setting up Gekko in backtest mode
2018-04-28 08:59:00 (INFO):
2018-04-28 08:59:00 (INFO):     Setting up:
2018-04-28 08:59:00 (INFO):              Trading Advisor
2018-04-28 08:59:00 (INFO):              Calculate trading advice
2018-04-28 08:59:00 (INFO):              Using the strategy: varPPO
2018-04-28 08:59:00 (WARN):     TALIB indicators could not be loaded, they will be unavailable.
D:\Dev\git\gekko\strategies\indicators\PPO.js:9
  this.short = new EMA(config.short);
                             ^

TypeError: Cannot read property 'short' of undefined
    at new Indicator (D:\Dev\git\gekko\strategies\indicators\PPO.js:9:30)
    at Base.addIndicator (D:\Dev\git\gekko\plugins\tradingAdvisor\baseTradingMethod.js:308:34)
    at Base.bound [as addIndicator] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Base.method.init (D:\Dev\git\gekko\strategies\varPPO.js:27:8)
    at Base.bound [as init] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at new Base (D:\Dev\git\gekko\plugins\tradingAdvisor\baseTradingMethod.js:87:8)
    at Actor.setupTradingMethod (D:\Dev\git\gekko\plugins\tradingAdvisor\tradingAdvisor.js:62:17)
    at Actor.bound [as setupTradingMethod] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at new Actor (D:\Dev\git\gekko\plugins\tradingAdvisor\tradingAdvisor.js:23:8)
    at load (D:\Dev\git\gekko\core\pluginUtil.js:95:22)
  xxx POST /api/backtest 500 2,223ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (D:\Dev\git\gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
IDK

**Comment by 151henry151** [comment]
I was able to reproduce this with a fresh clean install, I don't know what is causing it but I get the same error when trying to do the same thing. Sorry I can't be more helpful!

**Comment by spec-r** [comment]
cd ~/gekko
npm install talib

**Comment by xFFFFF** [comment]
It's written: `TypeError: Cannot read property 'short' of undefined` Add `short=100000000` to configuration

**Comment by TheHalcyonSavant** [comment]
Check #2157 for fix

**Comment by askmike** [comment]
Apologies for the delay, can you try adding `short` in the parameters section in the UI like:

    short = 10

And see if that resolves it? If so we need to update the default TOML file.

**Comment by shmutalov** [comment]
@askmike just got the latest development version and tested with your suggestion. It doesn't work.

![image](https://user-images.githubusercontent.com/8098898/39991740-ed080f1c-5789-11e8-8e18-c621ffd6fe44.png)

```
  <-- POST /api/backtest
2018-05-14 15:15:12 (INFO):     Setting up Gekko in backtest mode
2018-05-14 15:15:12 (INFO):
2018-05-14 15:15:12 (INFO):     Setting up:
2018-05-14 15:15:12 (INFO):              Trading Advisor
2018-05-14 15:15:12 (INFO):              Calculate trading advice
2018-05-14 15:15:12 (INFO):              Using the strategy: varPPO
2018-05-14 15:15:12 (WARN):     TALIB indicators could not be loaded, they will be unavailable.
D:\Dev\git\gekko\strategies\indicators\PPO.js:9
  this.short = new EMA(config.short);
                             ^

TypeError: Cannot read property 'short' of undefined
    at new Indicator (D:\Dev\git\gekko\strategies\indicators\PPO.js:9:30)
    at Base.addIndicator (D:\Dev\git\gekko\plugins\tradingAdvisor\baseTradingMethod.js:308:34)
    at Base.bound [as addIndicator] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Base.method.init (D:\Dev\git\gekko\strategies\varPPO.js:27:8)
    at Base.bound [as init] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at new Base (D:\Dev\git\gekko\plugins\tradingAdvisor\baseTradingMethod.js:87:8)
    at Actor.setupTradingMethod (D:\Dev\git\gekko\plugins\tradingAdvisor\tradingAdvisor.js:62:17)
    at Actor.bound [as setupTradingMethod] (D:\Dev\git\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at new Actor (D:\Dev\git\gekko\plugins\tradingAdvisor\tradingAdvisor.js:23:8)
    at load (D:\Dev\git\gekko\core\pluginUtil.js:95:22)
  xxx POST /api/backtest 500 2,661ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (D:\Dev\git\gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nick-dolan** [comment]
The same issue, it's work's fine when running in terminal mode, and not ok when running in UI mode. I'm using dev branch at 0e1458df262529abc3998cb9ca3711cd1cc85286 commit.

**Comment by Speculor** [comment]
Same issue here with latest release. I tried defining "short" to no avail as well.
