### ISSUE TITLE
gekko/node_modules/promisify-node/utils/args.js:9

### ISSUE THREAD

**Issue by mtinfo** [askmike/gekko#2143]
hello,

On Ubuntu 16.04, and trying to install gekko, by following installing_gekko.html web page, doing many time from scratch to find the good way to install sqlite3 before dependencies, it stay unable to run.

Find the solution for this problem : gekko/core/error.js:3 on the forum, but stay block with this one.

without logfile in gekko, here it is what I have on screen

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/ 
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

	Gekko v0.5.14
	I'm gonna make you rich, Bud Fox. 

/home/XXXXXX/gekko/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (/home/XXXXXX/gekko/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/home/XXXXXX/gekko/node_modules/promisify-node/index.js:61:29)
    at module.exports (/home/XXXXXX/gekko/node_modules/promisify-node/index.js:164:10)
    at Object.<anonymous> (/home/XXXXXX/gekko/web/routes/scanDateRange.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/XXXXXX/gekko/web/server.js:56:26)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)

If someone have the solution or an idea ?
Thanks

**Comment by mtinfo** [comment]
After full re-install of nodejs and gekko, it work fine.

problem come from nodejs and npm not compatible in ubuntu 16.04.

if it could help some

**Comment by hilkoc** [comment]
I had the same problem: #2150
