### ISSUE TITLE
child process has died

### ISSUE THREAD

**Issue by Shahid7001** [askmike/gekko#2149]
i get this erron when paper trading using this strategy i.e saichovsky.js it is modified version of buyatsell at  

Error: Cannot find module '../helper.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Gekko\gekko-develop\strategies\saichovsky.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
RECEIVED ERROR IN GEKKO 322275099741874
Child process has died.

**Comment by H256** [comment]
Try the helper.js from here https://github.com/cloggy45/Gekko-Bot-Resources/tree/ddd19df4e2e6ee7009ee303607ae0e18bba4e021/gekko maybe this works ;)

**Comment by askmike** [comment]
This is a problem with another strategy, since I am not familiar with it I won't be able to help you out.
