### ISSUE TITLE
Installation: "TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by lincolnaleixo** [askmike/gekko#2199]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
- Created another server from scratch

**Expected result** (what you hoped would happen)
- First time running gekko, I believe it should execute this command correctly (node gekko --ui)

**Actual result** (unexpected outcome)
/home/lincolnmorais/gekko/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (/home/lincolnmorais/gekko/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/home/lincolnmorais/gekko/node_modules/promisify-node/index.js:61:29)
    at module.exports (/home/lincolnmorais/gekko/node_modules/promisify-node/index.js:164:10)
    at Object.<anonymous> (/home/lincolnmorais/gekko/web/routes/scanDateRange.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/lincolnmorais/gekko/web/server.js:56:26)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Ubuntu 16.04
Nodejs version 10.1.0

**Comment by askmike** [comment]
Weird, can you completely remove all dependencies and install them again like so:

    rm -rf node_modules
    npm i

**Comment by pitxels** [comment]
I have the same error, I also tried, removing all dependecies and installing again, but same exact thing.

**Comment by Tronab** [comment]
same problem for me

**Comment by lincolnaleixo** [comment]
Someone on discord helped me, fixed using this solution:
https://github.com/askmike/gekko/issues/2150

**Comment by intrepidsolutions** [comment]
Can confirm the discord fix works:

Ad the question mark (?) after the s and your good to go:

vim /home/lincolnmorais/gekko/node_modules/promisify-node/utils/args.js
var args = func.toString().match(/function\s?.?(([^)]))/)[1];

**Comment by askmike** [comment]
I am assuming this is fixed in 0.6, if it isn't please comment here.

**Comment by dkadmin** [comment]
npm install -g udemy-dl
