### ISSUE TITLE
ok tried making my own custom strategy

### ISSUE THREAD

**Issue by DrBlackross** [askmike/gekko#2207]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
changed the custom area to match the one on the GUI backtest page for CLI usage

// custom settings:
config.Dave = {
short:2,
long:10,

  thresholds: {
	down:0.01,
	up:0.01,
	getout:0.03,
	persistence:1,
	maxExposureLength:30
      }
}

**Expected result** (what you hoped would happen)

well, expected to work just like it did on/in the web interface

**Actual result** (unexpected outcome)

2018-05-25 17:42:58 (INFO):	Setting up Gekko in backtest mode
2018-05-25 17:42:58 (INFO):	
2018-05-25 17:42:58 (INFO):	Setting up:
2018-05-25 17:42:58 (INFO):		 Trading Advisor
2018-05-25 17:42:58 (INFO):		 Calculate trading advice
2018-05-25 17:42:58 (INFO):		 Using the strategy: Dave
2018-05-25 17:42:58 (WARN):	TALIB indicators could not be loaded, they will be unavailable.
2018-05-25 17:42:58 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
2018-05-25 17:42:58 (INFO):	

2018-05-25 17:42:58 (INFO):	Setting up:
2018-05-25 17:42:58 (INFO):		 Paper Trader
2018-05-25 17:42:58 (INFO):		 Paper trader that simulates fake trades.
./Desktop/gekko/plugins/paperTrader/paperTrader.js:13
  this.fee = 1 - (calcConfig['fee' + calcConfig.feeUsing.charAt(0).toUpperCase() + calcConfig.feeUsing.slice(1)] + calcConfig.slippage) / 100;
                                                         ^

TypeError: Cannot read property 'charAt' of undefined
    at new PaperTrader (./Desktop/gekko/plugins/paperTrader/paperTrader.js:13:58)
    at load (./Desktop/gekko/core/pluginUtil.js:100:22)
    at ./Desktop/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (./Desktop/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (./Desktop/gekko/node_modules/async/dist/async.js:1015:17)
    at ./Desktop/gekko/node_modules/async/dist/async.js:988:16
    at ./Desktop/gekko/node_modules/async/dist/async.js:1158:13
    at load (./Desktop/gekko/core/pluginUtil.js:68:14)
    at ./Desktop/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (./Desktop/gekko/node_modules/async/dist/async.js:1030:17)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Dave is pulled from https://raw.githubusercontent.com/digidigo/gekko/stable/strategies/Dave.js works in the web gui but not manually added to the config and ran via CLI

From command line without "Dave" in the config it works fine. Dave.js in in the /gekko/strategies folder, Dave.toml is in the gekko/config/strategies folder

**Comment by askmike** [comment]
It's complaining about another part of your config, your config does not seem to include an up to date paper trader config, see here: https://github.com/askmike/gekko/blob/develop/sample-config.js#L186-L202

If you still have problems, please see this link: https://gekko.wizb.it/docs/introduction/getting_help.html

As this is the issue tracker to discuss bugs and such :)

**Comment by DrBlackross** [comment]
ZEN! thanks mike
