### ISSUE TITLE
Trading live getting date issue

### ISSUE THREAD

**Issue by whoodat** [askmike/gekko#2221]
Mike when I am trading live on GDAX I am running into this error:

0|Live     | Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
0|Live     | Arguments: 
0|Live     | [0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: false, _f: undefined, _strict: undefined, _locale: [object Object]
0|Live     | Error
0|Live     |     at Function.createFromInputFallback (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:320:98)
0|Live     |     at configFromInput (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:2606:19)
0|Live     |     at prepareConfig (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:2577:13)
0|Live     |     at createFromConfig (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:2544:44)
0|Live     |     at createLocalOrUTC (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:2631:16)
0|Live     |     at Function.createUTC [as utc] (/home/whoodat/Gekko/gekko/node_modules/moment/moment.js:88:16)
0|Live     |     at Trader.getTrades (/home/whoodat/Gekko/gekko/exchanges/gdax.js:339:24)
0|Live     |     at Trader.bound [as getTrades] (/home/whoodat/Gekko/gekko/node_modules/lodash/dist/lodash.js:729:21)
0|Live     |     at Fetcher._fetch (/home/whoodat/Gekko/gekko/core/budfox/marketFetcher.js:75:23)
0|Live     |     at Fetcher.bound [as _fetch] (/home/whoodat/Gekko/gekko/node_modules/lodash/dist/lodash.js:729:21)

**Comment by whoodat** [comment]
Updated moment.js I believe this fixed my issue thanks.
