### ISSUE TITLE
TypeError: Object false has no method 'find'

### ISSUE THREAD

**Issue by NeoBelerophon** [askmike/gekko#224]
/~/gekko/core/candleManager.js:560
Today gekko quits with this message:

  this.days[mom.dayString].handle.find({
                                  ^
TypeError: Object false has no method 'find'
    at Manager.getCandles (/~/gekko/core/candleManager.js:560:35)
    at bound [as getCandles] (/~/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at iterator (/~/gekko/core/candleManager.js:516:10)
    at bound (/~/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /~/gekko/node_modules/async/lib/async.js:227:13
    at /~/gekko/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/~/gekko/node_modules/async/lib/async.js:32:24)
    at async.each (/~/gekko/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/~/gekko/node_modules/async/lib/async.js:226:9)

**Comment by askmike** [comment]
this is fixed in 0.2.
