### ISSUE TITLE
Gemini - unable to buy Error: Invalid quantity for symbol ETHUSD (command line)

### ISSUE THREAD

**Issue by crypto49er** [askmike/gekko#2246]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I setup Gekko to live trade ETH/USD on Gemini via command line. 

**Expected result** (what you hoped would happen)
Gekko sending buy and sell advice to Gemini API server.

**Actual result** (unexpected outcome)
I'm getting the follow error message. I can replicate this issue consistently. 

2018-06-17 15:10:31 (ERROR):	unable to buy Error: Invalid quantity for symbol ETHUSD: 2.00618643
    at Request._callback (/home/jack/gekko/node_modules/gemini-exchange-coffee-api/lib/gemini.js:64:19)
    at Request.self.callback (/home/jack/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:123:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/jack/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:893:14)
    at Request.emit (events.js:165:20)
    at IncomingMessage.<anonymous> (/home/jack/gekko/node_modules/gemini-exchange-coffee-api/node_modules/request/request.js:844:12)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19) undefined

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I have tried git pull to pull down the latest version of Gekko on my computer but that didn't fix the issue.

I will provide more info as I document steps I'm taking to troubleshoot this issue. Right now I only have the key and secret field populated in the config.trader section in the config file, I will try adding a username to see if that helps. I will also test BTC/USD trade pair just to see if this is an issue specific to the ETH/USD trade pair or if it affects all trade pairs.

**Comment by askmike** [comment]
It's very hard for me to test Gemini integration as they only accept US residents. I just released a big upgrade (0.6) of Gekko that unfortunately does not come with Gemini support. I'll try to figure out a way to properly test Gemini integration asap.

**Comment by crypto49er** [comment]
Thanks Mike. It's an issue but there's no need for testing asap unless others are reporting this issue. Gemini has increased their trade fees 3x since I last used them so it's really hard to make profits on their platform.

**Comment by askmike** [comment]
gemini is not supported right now unfortunately :(
