### ISSUE TITLE
v0.6.0: ReferenceError: log is not defined

### ISSUE THREAD

**Issue by shimanotaka** [askmike/gekko#2268]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Updated to v.0.6.0.
No changes to strategy.

**Expected result** (what you hoped would happen)
Gekko would run

**Actual result** (unexpected outcome)
Gekko crashes.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
Windows 10. Tried to add the line below to the strategy but it didn't make any difference.
`var log = require('../core/log.js');`

Getting the following output:

`C:\Users\Shima\gekko\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

ReferenceError: log is not defined
    at Trader.getTrades (C:\Users\Shima\gekko\exchange\wrappers\gdax.js:377:7)
    at Stitcher.checkExchangeTrades (C:\Users\Shima\gekko\core\tools\dataStitcher.js:199:11)
    at Stitcher.<anonymous> (C:\Users\Shima\gekko\core\tools\dataStitcher.js:108:10)
    at Statement.<anonymous> (C:\Users\Shima\gekko\plugins\sqlite\reader.js:64:14)
--> in Database#all('\n    SELECT start from candles_EUR_BTC\n    WHERE start <= 1530761100 AND start >= 1530573900\n    ORDER BY start DESC\n  ', [Function])
    at Reader.mostRecentWindow (C:\Users\Shima\gekko\plugins\sqlite\reader.js:23:11)
    at Reader.bound [as mostRecentWindow] (C:\Users\Shima\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Stitcher.prepareHistoricalData (C:\Users\Shima\gekko\core\tools\dataStitcher.js:63:15)
    at new Actor (C:\Users\Shima\gekko\plugins\tradingAdvisor\tradingAdvisor.js:34:14)
    at load (C:\Users\Shima\gekko\core\pluginUtil.js:98:22)
    at C:\Users\Shima\gekko\node_modules\async\dist\async.js:1156:9
    at replenish (C:\Users\Shima\gekko\node_modules\async\dist\async.js:1030:17)
    at iterateeCallback (C:\Users\Shima\gekko\node_modules\async\dist\async.js:1015:17)
    at C:\Users\Shima\gekko\node_modules\async\dist\async.js:988:16`

**Comment by askmike** [comment]
Thanks for the report, this has been fixed in 0.6.1 :)
