### ISSUE TITLE
Intermittent failure to fetch Bitstamp data

### ISSUE THREAD

**Issue by realart** [askmike/gekko#227]
Often (but not always) when I start Gekko I get this error:
```
C:\gekko>node gekko
2014-03-09 14:22:03 (INFO):     Gekko v0.1.2 started
2014-03-09 14:22:03 (INFO):     I'm gonna make you rich, Bud Fox.


2014-03-09 14:22:03 (INFO):     Setting up Gekko in realtime mode

2014-03-09 14:22:03 (INFO):     Setting up:
2014-03-09 14:22:03 (INFO):              Trading Advisor
2014-03-09 14:22:03 (INFO):              Calculate trading advice
2014-03-09 14:22:03 (INFO):              Using trading method: DEMA

2014-03-09 14:22:03 (INFO):     Setting up:
2014-03-09 14:22:03 (INFO):              IRC bot
2014-03-09 14:22:03 (INFO):              IRC module lets you communicate with Ge
kko on IRC.

2014-03-09 14:22:03 (INFO):     Setting up:
2014-03-09 14:22:03 (INFO):              Trader
2014-03-09 14:22:03 (INFO):              Trader will follow the advice and creat
e real orders.
2014-03-09 14:22:03 (DEBUG):    Getting balance & fee from Bitstamp

2014-03-09 14:22:09 (INFO):     Trading at Bitstamp ACTIVE
2014-03-09 14:22:09 (INFO):     Bitstamp trading fee will be: NaN%
2014-03-09 14:22:09 (INFO):     Bitstamp portfolio:
2014-03-09 14:22:09 (INFO):              BTC: 1.1525913
2014-03-09 14:22:09 (INFO):              USD: 0.05

C:\gekko\exchanges\bitstamp.js:67
    callback(false, data.fee / 100);
                        ^
TypeError: Cannot read property 'fee' of undefined
    at set (C:\gekko\exchanges\bitstamp.js:67:25)
    at bound (C:\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at ClientRequest.<anonymous> (C:\gekko\node_modules\bitstamp\bitstamp.js:58:
5)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketCloseListener (http.js:1522:9)
    at CleartextStream.EventEmitter.emit (events.js:117:20)
    at tls.js:696:10
    at process._tickCallback (node.js:415:13)
```

**Comment by askmike** [comment]
I assume this is fixed, as I haven't seen this for long. If this is still a bug, please comment here.
