### ISSUE TITLE
v.0.6.1: TypeError: util.retry is not a function

### ISSUE THREAD

**Issue by shimanotaka** [askmike/gekko#2275]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Updated to v.0.6.1

**Expected result** (what you hoped would happen)
Gekko would run as before

**Actual result** (unexpected outcome)
Gekko crashed with the below error when mailer is enabled. Gekko starts when mailer is disabled.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
OS: Windows 10

Gives the following error:
```
C:\Users\Shima\gekko\plugins\mailer.js:84
  util.retry(function(cb) {
       ^

TypeError: util.retry is not a function
    at Mailer.mail (C:\Users\Shima\gekko\plugins\mailer.js:84:8)
    at Mailer.bound [as mail] (C:\Users\Shima\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Mailer.setupMail (C:\Users\Shima\gekko\plugins\mailer.js:42:12)
    at Mailer.setup (C:\Users\Shima\gekko\plugins\mailer.js:79:15)
    at Mailer.bound [as setup] (C:\Users\Shima\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at new Mailer (C:\Users\Shima\gekko\plugins\mailer.js:15:8)
    at load (C:\Users\Shima\gekko\core\pluginUtil.js:98:22)
    at C:\Users\Shima\gekko\node_modules\async\dist\async.js:1156:9
    at replenish (C:\Users\Shima\gekko\node_modules\async\dist\async.js:1030:17)
    at iterateeCallback (C:\Users\Shima\gekko\node_modules\async\dist\async.js:1015:17)
```

**Comment by askmike** [comment]
Thanks for reporting! Fixed for now in the latest develop branch.
