### ISSUE TITLE
v0.6.1: Deprecation warning: value provided is not in a recognized RFC2822 or ISO format.

### ISSUE THREAD

**Issue by shimanotaka** [askmike/gekko#2276]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Started gekko (without mailer enabled)

**Expected result** (what you hoped would happen)
Gekko running error free.

**Actual result** (unexpected outcome)
Throws the below error a while after startup. I don't know if it affects Gekko's function. At least Gekko still processes trades after the error is thrown.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
OS: Windows 10

Error:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: false, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:320:98)
    at configFromInput (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:2606:19)
    at prepareConfig (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:2577:13)
    at createFromConfig (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:2544:44)
    at createLocalOrUTC (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:2631:16)
    at Function.createUTC [as utc] (C:\Users\Shima\gekko\exchange\node_modules\moment\moment.js:88:16)
    at Trader.getTrades (C:\Users\Shima\gekko\exchange\wrappers\gdax.js:378:26)
    at Fetcher._fetch (C:\Users\Shima\gekko\core\budfox\marketFetcher.js:76:23)
    at Fetcher.bound [as _fetch] (C:\Users\Shima\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Fetcher.fetch (C:\Users\Shima\gekko\core\budfox\marketFetcher.js:89:8)

```

**Comment by askmike** [comment]
Very strange, a deprecation warning should not make Gekko crash. I removed the line in question, can you see if the latest develop makes a differnce? Thanks!

**Comment by shimanotaka** [comment]
I updated and left Gekko running through the night. Have not seen the error again.

**Comment by askmike** [comment]
Awesome, closing this under the assumption that it is fixed, if it pops up again please reopen :)
