### ISSUE TITLE
[v0.6.1] Error during installation

### ISSUE THREAD

**Issue by alexandershalin** [askmike/gekko#2282]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
git clone git://github.com/askmike/gekko.git -b stable
cd gekko
npm install --only=production
**Expected result** (what you hoped would happen)
Gekko should be installed without errors.

**Actual result** (unexpected outcome)
See logs.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
root@BishopsVM:~/gekko# npm install --only=production

> websocket@1.0.24 install /home/bishop/gekko/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> sqlite3@3.1.13 install /home/bishop/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.6.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.6.0 (node-v64 ABI) (falling back to source compile with node-gyp)
gypgyp  ERR! ERR!configure error
 gypconfigure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/bishop/gekko/node_modules/sqlite3/build'
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/bishop/gekko/node_modules/sqlite3/build'
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR!  System Linux 4.13.0-45-generic
gypERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gyp ERR! command  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gypERR! cwd  /home/bishop/gekko/node_modules/sqlite3
gypERR! cwd  /home/bishop/gekko/node_modules/sqlite3
gypERR!  node -vERR! node -v v10.6.0
gyp ERR! v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
 node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bishop/gekko/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.13.0-45-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/bishop/gekko/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/bishop/gekko/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/bishop/gekko/node_modules/sqlite3/lib/binding/node-v64-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bishop/.npm/_logs/2018-07-06T13_53_24_066Z-debug.log
root@BishopsVM:~/gekko#
```

**Comment by askmike** [comment]
Please run the LTS version of nodejs, that way your system does not need to compile sqlite.

> EACCES: permission denied

Compiling failed because of permission issues, strange but let's focus on getting pre compiled binaries.

If that doesn't work please comment here and I will reopen!

**Comment by askmike** [comment]
> git clone git://github.com/askmike/gekko.git -b stable

Also: 0.6 was huge and unfortunately came with a few minor issues I have been cleaning up. As of now please pull the develop branch to make sure you have all latest fixes.

**Comment by deadheadtn** [comment]
`sudo ln -s "$(which nodejs)" /usr/bin/node`
`npm install sqlite --unsafe-perm`
