### ISSUE TITLE
[Binance] Error /home/gekko/gekko/exchange/exchangeErrors.js:34:24

### ISSUE THREAD

**Issue by bobychain** [askmike/gekko#2297]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken**
Trading Live on Binance 

**Expected result**
Automatic Sell & Buy on Binance following my strategy

**Actual result**
The Short stopped in the middle of the amount and no more orders after

**Other information**
I use the latest version (0.6.2) and everything was working fine since a while (on 0.5 & 0.6.1).

I got this error:

```
Error
    at Object.<anonymous> (/home/gekko/gekko/exchange/exchangeErrors.js:34:24)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/gekko/gekko/exchange/exchangeChecker.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```
and this in the logs:

```
2018-07-10 09:21:47 (INFO):     Trader Received advice to go short. Selling  STEEM
{"status":1,"request":"ac0c40aa-ca73-401c-aa6b-1c22ca019d39"}
2018-07-10 09:21:52 (DEBUG):    [ORDER] statusChange: SUBMITTED
2018-07-10 09:21:53 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:21:57 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:21:58 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:22:59 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:23:00 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:24:02 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:24:02 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:25:05 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:25:05 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:26:05 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:26:06 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:27:08 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:27:08 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:28:35 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:28:35 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:29:36 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:29:37 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 09:30:40 (DEBUG):    [ORDER] statusChange: MOVING
2018-07-10 09:30:41 (DEBUG):    [ORDER] statusChange: OPEN
2018-07-10 10:36:07 (INFO):     Received advice to buy however Gekko is already in the process to sell
2018-07-10 10:36:07 (INFO):     Canceling sell order first
{"status":1,"request":"b9f1218e-61bf-4621-86a7-2d0a07a4e42a"}
2018-07-10 10:36:08 (DEBUG):    syncing portfolio
2018-07-10 10:36:14 (INFO):     ignoring advice: already cancelling previous sell order
2018-07-10 11:32:27 (INFO):     ignoring advice: already in the process to sell
{"status":1,"request":"72cd19a4-2b5c-4846-b69d-922012d7ca62"}
2018-07-10 12:39:47 (INFO):     ignoring advice: already cancelling previous sell order
{"status":1,"request":"32530de1-d655-490f-bb36-cd78a1f127c1"}
```

Let me know if you need more info!

**Comment by askmike** [comment]
I just pushed a bunch of changes related to this code (see #2302) to the develop branch. Could you try running the develop branch? I am not sure if it will fix this issue but at least there will be better logging of the binance error.

**Comment by bobychain** [comment]
Thanks, I'm running now the develop branch and I will post here any logs if the error happens again!

**Comment by askmike** [comment]
I am assuming this issue was the same as #2308 (but Gekko did not log all binance errors at the time, so no way to be sure). But since #2308 is fixed I am assuming this is also fixed :)

If you run into any other binance problem it's probably better to create a new issue since we can focus on the actual error from the start!
