### ISSUE TITLE
Failure by running gekko on raspberry 3

### ISSUE THREAD

**Issue by nimasTT** [askmike/gekko#2320]
**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

I get this Message after trying to run gekko 0.6.2 on raspberry 3:
```
Gekko v0.6.2
       I'm gonna make you rich, Bud Fox.
vents.js:165
     throw er; // Unhandled 'error' event
     ^

rror: listen EADDRINUSE 127.0.0.1:3000
   at Server.setupListenHandle [as _listen2] (net.js:1346:14)
   at listenInCluster (net.js:1387:12)
   at doListen (net.js:1502:7)
   at process._tickCallback (internal/process/next_tick.js:178:19)
   at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
   at startup (internal/bootstrap/node.js:201:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
mitted 'error' event at:
   at Server.WebSocketServer._onServerError (/home/pi/gekko/node_modules/ws/lib/WebSocketServer.js:82:50)
   at Server.emit (events.js:180:13)
   at emitErrorNT (net.js:1366:8)
   at process._tickCallback (internal/process/next_tick.js:178:19)
   [... lines matching original stack trace ...]
   at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

```
The documentation on the website seems to be not uptodate.
There is no UIConfig file in web/vue/

**Comment by askmike** [comment]
That doc was indeed outdated, I fixed it for now. See 941b3de for the exact changes.

Note that the error you posted has to do with another process already listening to port 3000 (required for Gekko). You most likely still have another Gekko process running, you need to stop that first.
