### ISSUE TITLE
can't import backtest data because of error on poloniex.js module

### ISSUE THREAD

**Issue by Kelevra79** [askmike/gekko#2325]
Hi, 
I've just installed gekko on raspbian stretch on a raspberry pi 3..
I've struggled for long with an issue with mysqlite3 module, but now I think that problem is solved..
I'm trying to check the cli import tool and I had setup a config.js file for import backtest data from poloniex..
I've used this command for begin the import process:
node gekko.js  --config config --import

but i get the following error, probably related to an exchange module:

Error: Cannot find module 'poloniex.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/apps/gekko/exchange/wrappers/poloniex.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Other than this, when I try the GUI import tool, I see no Market combo list in the importer windows, so I can't select any exchange, and couldn't make any import from GUI also..

I don't know if these two behaviours are related..

Thanks for your support

**Comment by mark-sch** [comment]
cd exchange
npm install

Did you perform this already? Gekko broker needs separate install...

**Comment by Kelevra79** [comment]
That's it! 
 Now everything works fine
thanks for your help
