### ISSUE TITLE
Crash while getting getting amount from bitstamp

### ISSUE THREAD

**Issue by xXLupoXx** [askmike/gekko#233]
Hi,

my gekko crashed while getting the amount of something from bitstamp.
Happened after a new advise came in and this is the error:

2014-04-01 06:09:32 (INFO):     We have new trading advice!
2014-04-01 06:09:32 (INFO):              Position to take: long
2014-04-01 06:09:32 (INFO):              Market price: 462.69
2014-04-01 06:09:32 (INFO):              Based on market time: 2014-04-01 06:09:11

2014-04-01 06:09:32 (DEBUG):    Processed trades, sleeping for a minute...

/root/gekko/core/portfolioManager.js:107
  return this.getFund(fund).amount;
                           ^
TypeError: Cannot read property 'amount' of undefined
    at Manager.getBalance (/root/gekko/core/portfolioManager.js:107:28)
    at bound [as getBalance] (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at act (/root/gekko/core/portfolioManager.js:135:23)
    at bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /root/gekko/node_modules/async/lib/async.js:232:13
    at /root/gekko/node_modules/async/lib/async.js:142:25
    at /root/gekko/node_modules/async/lib/async.js:229:17
    at /root/gekko/node_modules/async/lib/async.js:556:34
    at set (/root/gekko/core/portfolioManager.js:77:7)
    at bound (/root/gekko/node_modules/lodash/dist/lodash.js:729:21)

These are the gekko and node versions:
Gekko version: v0.1.2
Nodejs version: v0.10.26

It worked pretty well for a time, no idea what caused this

**Comment by askmike** [comment]
this is now fixed!
