### ISSUE TITLE
Can't enable trading on BTCe

### ISSUE THREAD

**Issue by ciseugene** [askmike/gekko#236]
When i changed

config.trader = {
  enabled: false,
  key: '',
  secret: '',
  username: '' // your username, only fill in when using bitstamp or cexio
}

to

config.trader = {
  enabled: true,
  key: 'LO7XSD01-TMV48J5W-VIM0IRVE-FQ1BLIZJ-VJSUMAAC',
  secret: '029d7dbe96f3f295ce4c8d0702950f79aaac085e4deadf363df4b3aabef5e6b5',
  username: '' // your username, only fill in when using bitstamp or cexio
}

Result:

C:\Users\Administrator\Desktop\gekko-master>node gekko

Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.10.26

Error:

Do you understand what Gekko will do with your money? Read this first:

https://github.com/askmike/gekko/issues/201

node.js:729
        throw errnoException(process._errno, 'kill');
              ^
Error: kill ESRCH
    at errnoException (node.js:540:13)
    at process.kill (node.js:729:15)
    at Object.util.die (C:\Users\Administrator\Desktop\gekko-master\core\util.js
:140:13)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\gekko-master\gekko.js:
68:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

C:\Users\Administrator\Desktop\gekko-master>

**Comment by nonkreon** [comment]
why u post your api key and secret publicly on the internet?
