### ISSUE TITLE
 TypeError: Cannot read property 'c' of undefined / TypeError: Cannot call method 'toFixed' of undefined

### ISSUE THREAD

**Issue by cryptocxeq** [askmike/gekko#238]
what should I put my candleSize and historySize at for DEMA if I want to emulate the 2hr EMAs, but don't want to wait forever to get data (esp. since I'm crashing all the time...)

I keep getting this error on btce

TypeError: Cannot read property 'c' of undefined
    at Base.tick (C:\Users\Zack\Desktop\gekko-candle-rewrite\core\baseTradingMethod.js:74:21)
    at bound [as tick] (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at Actor.processCandle (C:\Users\Zack\Desktop\gekko-candle-rewrite\plugins\tradingAdvisor.js:39:15)
    at bound (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at EventEmitter.emit (events.js:95:17)
    at bound [as emit] (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.relayCandle (C:\Users\Zack\Desktop\gekko-candle-rewrite\core\marketManager.js:60:8)
    at bound (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at EventEmitter.emit (events.js:117:20)
    at bound [as emit] (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)

and this one on bitstamp

C:\Users\Zack\Desktop\gekko-candle-rewrite\methods\DEMA.js:44
  var message = '@ ' + price.toFixed(8) + ' (' + diff.toFixed(5) + ')';
                             ^
TypeError: Cannot call method 'toFixed' of undefined
    at method.check (C:\Users\Zack\Desktop\gekko-candle-rewrite\methods\DEMA.js:44:30)
    at bound (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at Base.tick (C:\Users\Zack\Desktop\gekko-candle-rewrite\core\baseTradingMethod.js:86:10)
    at bound [as tick] (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at Actor.processCandle (C:\Users\Zack\Desktop\gekko-candle-rewrite\plugins\tradingAdvisor.js:39:15)
    at bound (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at EventEmitter.emit (events.js:95:17)
    at bound [as emit] (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)
    at Manager.relayCandle (C:\Users\Zack\Desktop\gekko-candle-rewrite\core\marketManager.js:60:8)
    at bound (C:\Users\Zack\Desktop\gekko-candle-rewrite\node_modules\lodash\dist\lodash.js:729:21)

my settings are basically unchanged:

  enabled: true,
  exchange: 'BTCe', // 'MtGox', 'BTCe', 'Bitstamp', 'cexio' or 'kraken'
  currency: 'USD',
  asset: 'BTC'
  method: 'DEMA',
  candleSize: 60,
  historySize: 50

Mailer on.

**Comment by askmike** [comment]
Thanks for reporting, I am pretty sure this will be fixed by the [new version](https://github.com/askmike/gekko/tree/candle-rewrite#important-note).

**Comment by askmike** [comment]
new version is out!
