### ISSUE TITLE
Crash on insufficent funds trigger

### ISSUE THREAD

**Issue by Kris191** [askmike/gekko#2381]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Bot was running, short trigger followed by long trigger occurred

**Expected result** (what you hoped would happen)
CLI log bot to continue to be live and operational

**Actual result** (unexpected outcome)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Below is the console output, please note the strat runs on a 4hr candle

`2018-07-26 16:42:24 (INFO):	Trader Received advice to go short. Selling  XLM
2018-07-26 16:42:59 (INFO):	[ORDER] summary: { price: 0.00003949,
  amount: 43,
  date: moment("2018-07-26T16:42:58.494"),
  side: 'sell',
  orders: 1,
  fees: { BTC: 0.0000017 },
  feePercent: 0.09999999999999999 }
2018-07-26 16:43:04 (INFO):	(PROFIT REPORT) original balance:	 0.00183541 BTC
2018-07-26 16:43:04 (INFO):	(PROFIT REPORT) current balance:	 0.00190348 BTC
2018-07-26 16:43:04 (INFO):	(PROFIT REPORT) profit:		 0.00006808 BTC (3.70907358%)
2018-07-26 16:43:04 (INFO):	(ROUNDTRIP) entry date (UTC)  	exit date (UTC)  	exposed duration	P&L 	profit
2018-07-26 16:43:04 (INFO):	(ROUNDTRIP) 2018-07-25 18:42	2018-07-26 14:42	20 hours        	0.00	2.13
2018-07-26 16:43:04 (INFO):	Sending Trade Data to your Google Sheet
2018-07-26 20:42:08 (INFO):	We are in an UP trend: Price = 0.00004003
2018-07-26 20:42:08 (INFO):	Were going long
2018-07-26 20:42:08 (INFO):	Trader Received advice to go long. Buying  XLM
handleCreate Error -2010: Account has insufficient balance for requested action.
/root/gekko/exchange/orders/sticky.js:132
      throw err;
      ^

Error: Error -2010: Account has insufficient balance for requested action.
    at /root/gekko/exchange/wrappers/binance.js:72:15
    at Request.request [as _callback] (/root/gekko/exchange/node_modules/binance/lib/rest.js:90:25)
    at Request.self.callback (/root/gekko/exchange/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/gekko/exchange/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/gekko/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
`

**Comment by askmike** [comment]
This has been fixed 11 days ago in #2330. Which has been released in both 0.6.3 and 0.6.4. Please update your gekko as per instructions here: https://gekko.wizb.it/docs/installation/updating_gekko.html :)

I'm moving fast whilst trying not to break things (but when I do I try to fix them as soon as possible).
