### ISSUE TITLE
Installation fails with "ERR! UNCAUGHT EXCEPTION" on linux when Installing Gekko's dependencies

### ISSUE THREAD

**Issue by WilbertNL** [askmike/gekko#2411]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Followed the installation steps up to, and including, `npm install --only=production`

I tried cloning git with both `-b stable` and without. I'm running Linux Mint 18.3 with all available updates (4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017).

**Expected result** (what you hoped would happen)
`npm install --only=production` executes without errors and the ability to continue the installation/configuration steps

**Actual result** (unexpected outcome)
npm throws error messages at the `> node-pre-gyp install --fallback-to-build` part, unable to continue installation of dependencies.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
gekkotrader@gekkotrader01 ~/gekko $ npm install --only=production
loadDep:tar → resolveWith ▌ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> sqlite3@4.0.2 install /home/gekkotrader/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/gekkotrader/gekko/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/gekkotrader/gekko/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! System Linux 4.10.0-38-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/gekkotrader/gekko/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/gekkotrader/gekko/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--only=production"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gekkotrader/gekko/npm-debug.log
```

I found [this](https://github.com/mapbox/node-pre-gyp/issues/406) with regards to a similar issue:

> I resolved the issue by forcing tar to version 4.4.0. node-pre-gyp should consider locking the tar version to prevent mistakes like this in the future. I made an issue in the node-tar github. (BHare1985)

Edit: display output as code

**Comment by WilbertNL** [comment]
Ow... I got it fixed, apparently the proper version of node.js was not installed. I now installed version 8.x using the debian package manager:

`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

result:
```
gekkotrader@gekkotrader01 ~/gekko $ npm install --only=production

> sqlite3@4.0.2 install /home/gekkotrader/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/gekkotrader/gekko/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote
added 55 packages and updated 1 package in 11.052s
```

..continuing the installation..

**Comment by askmike** [comment]
good stuff :)
