### ISSUE TITLE
TypeError: _.floor is not a function

### ISSUE THREAD

**Issue by r-schipper** [askmike/gekko#2418]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Bot tried to go long.

**Expected result** (what you hoped would happen)
Placing a buy order.

**Actual result** (unexpected outcome)
/var/www/gekko/exchange/wrappers/poloniex.js:268
  return _.floor(amount, 8);
           ^

TypeError: _.floor is not a function
    at Trader.roundAmount (/var/www/gekko/exchange/wrappers/poloniex.js:268:12)
    at Trader.wrapper [as roundAmount] (/var/www/gekko/node_modules/lodash/index.js:3181:19)
    at StickyOrder.create (/var/www/gekko/exchange/orders/sticky.js:45:24)
    at syncPrivateData (/var/www/gekko/exchange/gekkoBroker.js:150:13)
    at /var/www/gekko/node_modules/async/dist/async.js:3853:9
    at /var/www/gekko/node_modules/async/dist/async.js:484:16
    at replenish (/var/www/gekko/node_modules/async/dist/async.js:1025:25)
    at iterateeCallback (/var/www/gekko/node_modules/async/dist/async.js:1015:17)
    at /var/www/gekko/node_modules/async/dist/async.js:988:16
    at Timeout.<anonymous> (/var/www/gekko/node_modules/async/dist/async.js:3850:13)

**Comment by askmike** [comment]
There is something wrong with the dependencies for Gekko Broker, either you haven't installed them or they something went wrong when you tried to install them last time.

Please delete `exchange/node_modules` and reinstall Gekko Broker deps!
