### ISSUE TITLE
TypeError: Cannot read property 'available' of undefined

### ISSUE THREAD

**Issue by Wowie7450** [askmike/gekko#243]
C:\Users\AW\Downloads\gekko-master\gekko-master\exchanges\cexio.js:125
    assets = parseFloat(data.GHS.available);
                                ^
TypeError: Cannot read property 'available' of undefined
    at calculate (C:\Users\AW\Downloads\gekko-master\gekko-master\exchanges\cexi
o.js:125:33)
    at bound (C:\Users\AW\Downloads\gekko-master\gekko-master\node_modules\lodas
h\dist\lodash.js:729:21)
    at IncomingMessage.<anonymous> (C:\Users\AW\Downloads\gekko-master\gekko-mas
ter\node_modules\cexio\cexio.js:65:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

is the error i get. Any suggestions?

**Comment by askmike** [comment]
Thanks for reporting, I am pretty sure this will be fixed by the [new version](https://github.com/askmike/gekko/tree/candle-rewrite#important-note).

**Comment by askmike** [comment]
0.2 is out!
