### ISSUE TITLE
Binance Gekko crash TypeError: Cannot read property 'feePercent'

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2439]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Dev branch after last LOT SIZE fix.
Live-Trading on Binance using commandline

**Expected result** (what you hoped would happen)
Trading for a lot days

**Actual result** (unexpected outcome)
2018-08-13 06:19:14 (DEBUG):    Requested ONT/BNB trade data from Binance ...
2018-08-13 06:19:15 (DEBUG):    Processing 1 new trades. From 2018-08-13 06:19:10 UTC to 2018-08-13 06:19:10 UTC. (a few seconds)
2018-08-13 06:19:15 (DEBUG):    Sell - Predicted variation:  -0.32437864712342335
/home/username/gekko/plugins/trader/trader.js:269
        if(_.isNumber(summary.feePercent)) {
                              ^

TypeError: Cannot read property 'feePercent' of undefined
    at sync (/home/username/gekko/plugins/trader/trader.js:269:31)
    at broker.syncPrivateData (/home/username/gekko/plugins/trader/trader.js:71:7)
    at /home/username/gekko/exchange/node_modules/async/dist/async.js:3874:9
    at /home/username/gekko/exchange/node_modules/async/dist/async.js:473:16
    at replenish (/home/username/gekko/exchange/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/home/username/gekko/exchange/node_modules/async/dist/async.js:983:17)
    at /home/username/gekko/exchange/node_modules/async/dist/async.js:958:16
    at Timeout._onTimeout (/home/username/gekko/exchange/node_modules/async/dist/async.js:3871:13)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
Thanks for the report. I'm running the same code without issues, but because you keep reporting your issues I am able to make things more stable for everyone :)

Your error means GB was unable to create a summary for whatever reason. I've pushed a fix that checks this and logs (and emits) whatever error there is. Gekko won't crash anymore but if it happens again you'll see something like:

    Error while creating summary: [ error ]

In which case, please let me know the error!

**Comment by xbromy** [comment]
Thanks!
