### ISSUE TITLE
Error thrown: internal/modules/cjs/loader.js:573

### ISSUE THREAD

**Issue by storshun** [askmike/gekko#2446]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Installed gekko on an AWS instance, left it unsecure intentionally just to see if it would run, tried to run a command-line trade bot after setting it up in a custom config.js file. 

I've succesfully set this up on another separate instance of an AWS ec2 server, and it runs daily without issues. I'm open to the idea I've missed something obvious, but am a bit lost as to this specific error.

**Expected result** (what you hoped would happen)
Not get errors and have the trade bot run properly

**Actual result** (unexpected outcome)
Errors as follows after the "Bud Fox" line:

internal/modules/cjs/loader.js:573
   throw err;
   ^

Error: Cannot find module './web/isWindows.js'
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
   at Function.Module._load (internal/modules/cjs/loader.js:497:25)
   at Module.require (internal/modules/cjs/loader.js:626:17)
   at require (internal/modules/cjs/helpers.js:20:18)
   at Object.<anonymous> (/home/bitnami/gekko/drastrat/strat1.js:292:16)
   at Module._compile (internal/modules/cjs/loader.js:678:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
   at Module.load (internal/modules/cjs/loader.js:589:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
   at Function.Module._load (internal/modules/cjs/loader.js:520:3)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by storshun** [comment]
Apparently this is caused by trying to run a commandline strat from a sub-directory of gekko. Moving the strat to the `/gekko` directory resolved the issue.

**Comment by askmike** [comment]
:+1:
