### ISSUE TITLE
Cannot read property 'feePercent' of undefined

### ISSUE THREAD

**Issue by PhunkyBob** [askmike/gekko#2452]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
My strategy created a "long" order on Binance USDT/ONT market.

**Expected result** (what you hoped would happen)
Order is placed.

**Actual result** (unexpected outcome)
Gekko crashes.

```
2018-08-16 19:39:47 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:40:05 (DEBUG):    Processing 100 new trades. From 2018-08-16 17:39:28 UTC to 2018-08-16 17:40:04 UTC. (a few seconds)
2018-08-16 19:40:05 (INFO):     Trader Received advice to go long. Buying  ONT
2018-08-16 19:40:05 (DEBUG):    Creating order to buy 54.68422692318925 ONT
2018-08-16 19:40:07 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:40:11 (DEBUG):    Processing 11 new trades. From 2018-08-16 17:40:05 UTC to 2018-08-16 17:40:06 UTC. (a few seconds)
2018-08-16 19:40:27 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:40:28 (DEBUG):    Processing 21 new trades. From 2018-08-16 17:40:08 UTC to 2018-08-16 17:40:24 UTC. (a few seconds)
2018-08-16 19:40:47 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:40:48 (DEBUG):    Processing 15 new trades. From 2018-08-16 17:40:32 UTC to 2018-08-16 17:40:47 UTC. (a few seconds)
2018-08-16 19:41:07 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:41:08 (DEBUG):    [ORDER] statusChange: SUBMITTED
2018-08-16 19:41:09 (DEBUG):    [ORDER] statusChange: OPEN
2018-08-16 19:41:26 (DEBUG):    Processing 47 new trades. From 2018-08-16 17:40:48 UTC to 2018-08-16 17:41:25 UTC. (a few seconds)
2018-08-16 19:41:27 (DEBUG):    Requested ONT/USDT trade data from Binance ...
2018-08-16 19:41:28 (DEBUG):    [ORDER] statusChange: MOVING
2018-08-16 19:41:28 (DEBUG):    Processing 4 new trades. From 2018-08-16 17:41:26 UTC to 2018-08-16 17:41:27 UTC. (a few seconds)
2018-08-16 19:41:45 (DEBUG):    [ORDER] statusChange: FILLED
2018-08-16 19:41:45 (INFO):     [ORDER] summary: undefined
2018-08-16 19:41:45 (DEBUG):    syncing private data
2018-08-16 19:41:47 (DEBUG):    Requested ONT/USDT trade data from Binance ...
/home/gekko/gekko/plugins/trader/trader.js:269
        if(_.isNumber(summary.feePercent)) {
                              ^

TypeError: Cannot read property 'feePercent' of undefined
    at sync (/home/gekko/gekko/plugins/trader/trader.js:269:31)
    at broker.syncPrivateData (/home/gekko/gekko/plugins/trader/trader.js:71:7)
    at /home/gekko/gekko/exchange/node_modules/async/dist/async.js:3874:9
    at /home/gekko/gekko/exchange/node_modules/async/dist/async.js:473:16
    at replenish (/home/gekko/gekko/exchange/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/home/gekko/gekko/exchange/node_modules/async/dist/async.js:983:17)
    at /home/gekko/gekko/exchange/node_modules/async/dist/async.js:958:16
    at Timeout._onTimeout (/home/gekko/gekko/exchange/node_modules/async/dist/async.js:3871:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)

```

However, I made a LONG then a SHORT order on the same market few hours before, and it worked fine.

**Comment by askmike** [comment]
This has been fixed in the latest develop branch, would you mind running that and report back?

See https://github.com/askmike/gekko/issues/2439#issuecomment-412439210 for details (please also comment there).
