### ISSUE TITLE
Error while creating summary: Error: Trades not found

### ISSUE THREAD

**Issue by cstegmann** [askmike/gekko#2471]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Running Gekko in pm2 with newest commit (e12eea0279b2c16b2d3e308c09d77e7b24b2d95e)

**Expected result** (what you hoped would happen)
Summary to be posted. Right now it just returned a tradeErrored event.

**Actual result** (unexpected outcome)
Summary failed due to 'trades not found' .  At least order was filled.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Debug log:
```
Current market: bull
Percent change predicted: 0.5231228061487263
Current price: 9.809
Last buy price: 0
Current position: none
2018-08-22 17:59:10 (INFO):     Trader Received advice to go long. Buying  BNB
2018-08-22 17:59:10 (DEBUG):    Creating order to buy <censored amount> BNB
2018-08-22 17:59:16 (DEBUG):    [ORDER] statusChange: SUBMITTED
2018-08-22 17:59:16 (DEBUG):    [ORDER] statusChange: OPEN
2018-08-22 17:59:18 (INFO):     [ORDER] partial buy fill, total filled: 183.46
2018-08-22 17:59:18 (DEBUG):    [ORDER] statusChange: FILLED


2018-08-22 18:00:09 (DEBUG):                                    [EVENT tradeErrored]
 { id: 'trade-1',
  adviceId: 'advice-1',
  date: moment("2018-08-22T17:59:20.764"),
  reason: 'Trades not found' }
```

pm2 Error log:
```
  2018-08-22 17:59:20 (ERROR):    Error while creating summary: Error: Trades not found
      at get (/home/chris/gekko-neural-USDTpair/exchange/wrappers/binance.js:364:23)
      at checkFn (/home/chris/gekko-neural-USDTpair/exchange/exchangeUtils.js:23:16)
      at /home/chris/gekko-neural-USDTpair/exchange/wrappers/binance.js:129:12
      at Request.request [as _callback] (/home/chris/gekko-neural-USDTpair/exchange/node_modules/binance/lib/rest.js:100:21)
      at Request.self.callback (/home/chris/gekko-neural-USDTpair/exchange/node_modules/request/request.js:185:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (/home/chris/gekko-neural-USDTpair/exchange/node_modules/request/request.js:1157:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (/home/chris/gekko-neural-USDTpair/exchange/node_modules/request/request.js:1079:12)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:111:20)
      at IncomingMessage.emit (events.js:208:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by askmike** [comment]
This is actually the same issue as #2465 so closing this as a dup. Replying there as well.
