### ISSUE TITLE
TypeError: Cannot read property 'fee' of undefined

### ISSUE THREAD

**Issue by perey2002** [askmike/gekko#250]
Hi askmike!
I've got an error, could you help me please?
Installing gekko for trading at bitstamp and getting this error about fee:

2014-09-02 18:20:05 (INFO):     Gekko v0.1.2 started
2014-09-02 18:20:05 (INFO):     I'm gonna make you rich, Bud Fox.

2014-09-02 18:20:05 (INFO):     Setting up Gekko in realtime mode

2014-09-02 18:20:05 (INFO):     Setting up:
2014-09-02 18:20:05 (INFO):              Trading Advisor
2014-09-02 18:20:05 (INFO):              Calculate trading advice
2014-09-02 18:20:05 (INFO):              Using trading method: DEMA

2014-09-02 18:20:05 (INFO):     Setting up:
2014-09-02 18:20:05 (INFO):              Trader
2014-09-02 18:20:05 (INFO):              Trader will follow the advice and create real orders.
2014-09-02 18:20:05 (DEBUG):    Getting balance & fee from Bitstamp

2014-09-02 18:20:15 (INFO):     Trading at Bitstamp ACTIVE
2014-09-02 18:20:15 (INFO):     Bitstamp trading fee will be: NaN%
2014-09-02 18:20:15 (INFO):     Bitstamp portfolio:

/var/www/vhost/XXX/gekko/exchanges/bitstamp.js:67
    callback(false, data.fee / 100);
                        ^
TypeError: Cannot read property 'fee' of undefined
    at set (/var/www/vhost/XXX/gekko/exchanges/bitstamp.js:67:25)
    at bound (/var/www/vhost/XXX/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at ClientRequest.<anonymous> (/var/www/vhost/XXX/gekko/node_modules/bitstamp/bitstamp.js:58:5)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketCloseListener (http.js:1522:9)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:693:10
    at process._tickCallback (node.js:419:13)

Thank you very much in advance!!

**Comment by ph3onix** [comment]
bump me as well

**Comment by kuzetsa** [comment]
This is nearly identical to the way I was noticing some cex.io API-related errors I had to spend some time debugging several months ago.

This particular type of error when is caused when the exchange API doesn't populate an expected object in their JSON reply. The only way to fix it would be a JSON sanitizer which checks to make sure the object isn't malformed or missing expected bits.

**Comment by perey2002** [comment]
Wow! Too much for me! Thanks for your reply. So... No kraken support in the app. Thats all! ;-)

-- 
P No imprimir si no es necesario. Protejamos el Medio Ambiente // Please consider the environment - do you really need to print this email?
Enviado desde dispositivo móvil.

**Comment by askmike** [comment]
this is fixed in 0.2.
