### ISSUE TITLE
Module not found (0.6.6 + neuralnet)

### ISSUE THREAD

**Issue by xbromy** [askmike/gekko#2515]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Updated to lastest dev branch

**Expected result** (what you hoped would happen)
Running gekko

**Actual result** (unexpected outcome)

When I use neuralnet strat I get this, I did everything like ever. Any idea what I shall check? What is module is missing? 

2018-09-09 11:49 Gekko 2018-09-09-11-49-tradebot-073749867402127 started.
  --> POST /api/startGekko 200 4ms 1.81kb
uncaughtException { Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/username/gekko/exchange/dependencyCheck.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
RECEIVED ERROR IN GEKKO INSTANCE 2018-09-09-11-49-tradebot-073749867402127
{ code: 'MODULE_NOT_FOUND' }

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by xbromy** [comment]
Okay, I fixed it by remove and reinstall all.
