### ISSUE TITLE
Kraken: unknown minimum amount on XBT/XDG

### ISSUE THREAD

**Issue by H256** [askmike/gekko#2535]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Started a live gekko on kraken XBT/XDG

**Expected result** (what you hoped would happen)
It trades.

**Actual result** (unexpected outcome)
Whenever gekko tries to buy/sell, it throws an error:

2018-09-16T17:21:57.092Z '[sticky order] FATAL ERROR' 'Order:Invalid price:Invalid price argument.'
2018-09-16T17:21:57.093Z Error: Order:Invalid price:Invalid price argument.
    at rawRequest (/home/pi/gekko/exchange/node_modules/kraken-api/kraken.js:54:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

Is there any way to get this to work?

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I'm running the latest version from the development branch.

**Comment by askmike** [comment]
> I'm running the latest version from the development branch.

~Could you specify this some more? I pushed some fixes here: 7d548fb these also include more logging. So if you were already running that please post more logs.~

Scratch the above: it's a different error. So the error comes from Gekko not knowing the minimum amount to of XDG you can trade on kraken, since it's not listed on their help page: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

Most exchanges provide this data but Kraken does not, as such I can only fix this once anyone tells me what the minimum amount is for that market:

<img width="1094" alt="screen shot 2018-09-17 at 13 59 07" src="https://user-images.githubusercontent.com/969743/45607876-e1676f80-ba81-11e8-8c0f-463b22c618f2.png">

**Comment by H256** [comment]
@askmike Ok, so I pulled the latest commit. The error is gone now. However, gekko's trades get rejected (?). The log looks like it tried to buy enough XDG but at a price of 0 XBT.

Kraken seems to be pretty ****** in ways of trading over API... 😢 

The minimum order size for Dogecoin (DOGE / XDG) is **3000** on kraken. This is mentioned here:
https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

```
018-09-17 04:18:17 (INFO):	Trader Received advice to go long. Buying  XDG
2018-09-17 04:18:17 (DEBUG):	Creating order to buy 6641.0396 XDG
2018-09-17 04:18:29 (DEBUG):	[ORDER] statusChange: SUBMITTED
2018-09-17 04:18:30 (DEBUG):	[ORDER] statusChange: OPEN
2018-09-17 04:18:38 (DEBUG):	[ORDER] statusChange: REJECTED
2018-09-17 04:18:38 (INFO):	[ORDER] summary: { price: 0,
  amount: 0,
  date: moment("1970-01-01T01:00:00.000"),
  side: 'buy',
  orders: 1 }
2018-09-17 04:18:38 (DEBUG):	syncing private data
2018-09-17 04:18:49 (WARN):	WARNING: exchange did not provide fee information, assuming no fees..
2018-09-17 04:26:32 (DEBUG):	syncing private data
2018-09-17 04:36:32 (DEBUG):	syncing private data
2018-09-17 04:46:32 (DEBUG):	syncing private data
2018-09-17 04:48:39 (INFO):	(PROFIT REPORT) original balance:		 0.00699057 XBT
2018-09-17 04:48:39 (INFO):	(PROFIT REPORT) current balance:		 0.00699057 XBT
2018-09-17 04:48:39 (INFO):	(PROFIT REPORT) profit:				 0.00000000 XBT (0.00000000%)
2018-09-17 04:56:32 (DEBUG):	syncing private data
```

**Comment by askmike** [comment]
Ah I replied to quickly, check my edit! So it might work, but not if the amount is less than the minimum. And we don't know what that is, I just pinged them about it: https://twitter.com/mikevanrossum/status/1041568645321678850

**Comment by askmike** [comment]
@H256 please try latest develop, I am still not 100% convinced since your error complains about price and what I fixed is about amount. Now I fixed the amount it should not really change the price calculations, but I'm not 100% sure about Kraken's error reporting here. Please open a new issue if the problem persists. (Since this one contains a lot of other things now).
