### ISSUE TITLE
Tulip/Talib indicators could not be loaded (but they are installed)

### ISSUE THREAD

**Issue by armyanov** [askmike/gekko#2555]
Hi!

I am having trouble running both tulip and talib indicators simultaneously. 

When I am trying to backtest a strategy that uses a tulip indicator, I get this: 

2018-09-23 00:05:45 (INFO):	Setting up Gekko in backtest mode
2018-09-23 00:05:45 (INFO):	
2018-09-23 00:05:45 (INFO):	Setting up:
2018-09-23 00:05:45 (INFO):		 Trading Advisor
2018-09-23 00:05:45 (INFO):		 Calculate trading advice
2018-09-23 00:05:45 (INFO):		 Using the strategy: NEO
2018-09-23 00:05:45 (WARN):	TULIP indicators could not be loaded, they will be unavailable.
2018-09-23 00:05:45 (ERROR):	Failed to load indicator Alligator
2018-09-23 00:05:45 (ERROR):	Failed to load indicator HEIKEN
2018-09-23 00:05:45 (ERROR):	Failed to load indicator NN
2018-09-23 00:05:45 (ERROR):	Failed to load indicator RSI-beta
2018-09-23 00:05:45 (ERROR):	Failed to load indicator STC-1525204573
2018-09-23 00:05:45 (ERROR):	Failed to load indicator STC
2018-09-23 00:05:45 (ERROR):	Failed to load indicator Stoch
  xxx POST /api/backtest 500 171ms -

  Error: non-error thrown: Child process has died.

When I run `npm install tulind --no-save` I can backtest the strategy, but then when I try to backtest a strategy that uses Talib indicators I get the same error only it says "TaLIB indicators could not be loaded" Then again if I run `npm install talib --no-save` I can backtest it but Tulip indicators are not working again.

What am I doing wrong?

**Comment by askmike** [comment]
NPM can be tricky sometimes, it's a lot more stable if you omit the `--no-save` part, but that means NPM will start writing to package.json and package-lock.json (not a problem, but can be confusing down the line when updating Gekko and we have also updated these files).

I never have problems when I run the command like this:

    npm install talib tulind --no-save

Closing this issue now, but let me know if that doesn't work for you!

**Comment by antal0** [comment]
Hi,
I read that you closed this topic however I have been following your video tut on CLI installing Gekko - and the same err comes up to me also. May I ask your advice? 

Having installed "npm install talib tulind --no-save" but 

node gekko --backtest --config config.js - gives this err:

fs.js:660
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: EACCES: permission denied, open '/home/lant/gekko/config.js'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:664:20)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.getConfig (/home/lant/gekko/core/util.js:31:15)
    at Object.<anonymous> (/home/lant/gekko/core/log.js:13:19)

Thanks
Tony

**Comment by antal0** [comment]
Sorry -  I copied an earlier err

here is the actual I get
   Gekko v0.6.7
        I'm gonna make you rich, Bud Fox.


2018-11-05 08:22:34 (INFO):     Setting up Gekko in backtest mode
2018-11-05 08:22:34 (INFO):
2018-11-05 08:22:34 (WARN):     The plugin Candle writer does not support the mode backtest. It has been disabled.
2018-11-05 08:22:34 (INFO):     Setting up:
2018-11-05 08:22:34 (INFO):              Trading Advisor
2018-11-05 08:22:34 (INFO):              Calculate trading advice
2018-11-05 08:22:34 (INFO):              Using the strategy: moon
/home/lant/gekko/core/tulind.js:36
            throw new Error(tulindError + methodName + ' requires ' + paramName + '.');
            ^

Error: Gekko was unable to configure Tulip Indicators:
        macd requires optInFastPeriod.
    at _.each.paramName (/home/lant/gekko/core/tulind.js:36:19)
    at Function.forEach (/home/lant/gekko/node_modules/lodash/dist/lodash.js:3298:15)
    at verifyParams (/home/lant/gekko/core/tulind.js:34:7)
    at Object.create (/home/lant/gekko/core/tulind.js:472:9)
    at AsyncIndicatorRunner.addTulipIndicator (/home/lant/gekko/plugins/tradingAdvisor/asyncIndicatorRunner.js:145:23)
    at Base.addTulipIndicator (/home/lant/gekko/plugins/tradingAdvisor/baseTradingMethod.js:226:29)
    at Base.bound [as addTulipIndicator] (/home/lant/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.strat.init (/home/lant/gekko/strategies/moon.js:6:8)
    at Base.bound [as init] (/home/lant/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/lant/gekko/plugins/tradingAdvisor/baseTradingMethod.js:69:8)
