### ISSUE TITLE
Market Orders

### ISSUE THREAD

**Issue by Borrismorris** [askmike/gekko#2569]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Tried to change the binance wrapper to issue market orders rather than sticky limits.

  let reqData = {
    symbol: this.pair,
    side: tradeType.toUpperCase(),
    type: 'MARKET',
    timeInForce: 'GTC', // Good to cancel (I think, not really covered in docs, but is default)
    quantity: amount,
    price: price,
    timestamp: new Date().getTime()
  };

  let handler = (cb) => this.binance.newOrder(reqData, this.handleResponse('addOrder', cb));
  util.retryCustom(retryCritical, _.bind(handler, this), _.bind(setOrder, this));

**Expected result** (what you hoped would happen)
The bot would trade in market orders rather than limits

**Actual result** (unexpected outcome)
Recieved an error code

2018-09-28T19:27:33.078Z '[sticky order] FATAL ERROR' 'Error -1106: Parameter \'timeInForce\' sent when not required.'
2018-09-28T19:27:33.079Z Error: Error -1106: Parameter 'timeInForce' sent when not required.
    at C:\gekko2\exchange\wrappers\binance.js:98:15
    at Request.request [as _callback] (C:\gekko2\exchange\node_modules\binance\lib\rest.js:90:25)
    at Request.self.callback (C:\gekko2\exchange\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\gekko2\exchange\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\gekko2\exchange\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by Borrismorris** [comment]
apologies this is for Binance by the way

**Comment by askmike** [comment]
That's an error from Binance. Gekko sends the parameter `timeInForce` because it's designed to do limit orders. However Binance complains if you pass this as a market order (which you hacked Gekko into doing). So you need to remove that parameter.

Market orders are very dangerous, especially on illiquid markets. As such Gekko does not support them. They are very usable if you know what you are doing, but if your gekko trades ~10 times a day with market orders on an illiquid market you will lose all your money in less than a week. I go into that in this video: https://youtu.be/r0yc1sonYvo?t=8m20s
