### ISSUE TITLE
Gekko GUI stopped showing pull down menus (Exchanges, fiat currencies, etc)

### ISSUE THREAD

**Issue by dannunz1** [askmike/gekko#2583]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Hi,
I followed the installation tutorial and installed the dependencies and everything as explained. I opened the UI and the bot was working. After i tried to install the telegram bot (i had to install Npm install moment, Npm install lodash,Npm install node-telegram-bot-api) and changed my token key on config.js

After that i restarted the server and the following error message appeared:

Serving Gekko UI on http://localhost:3000/

  <-- GET /api/imports
  --> GET /api/imports 200 9ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 3ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 2b
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 3ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/home/danunz/Desktop/GEKKO/gekko/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/home/danunz/Desktop/GEKKO/gekko/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/home/danunz/Desktop/GEKKO/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/home/danunz/Desktop/GEKKO/gekko/node_modules/co/index.js:65:19)
      at <anonymous>

  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 2ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/home/danunz/Desktop/GEKKO/gekko/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/home/danunz/Desktop/GEKKO/gekko/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/home/danunz/Desktop/GEKKO/gekko/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/home/danunz/Desktop/GEKKO/gekko/node_modules/co/index.js:65:19)
      at <anonymous>

  <-- GET /api/imports
  --> GET /api/imports 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b

![screenshot from 2018-10-08 00-05-32](https://user-images.githubusercontent.com/43939854/46588069-ef5f4d80-ca8d-11e8-9258-34ba20037d7f.png)
![screenshot from 2018-10-08 00-05-32](https://user-images.githubusercontent.com/43939854/46588075-f9814c00-ca8d-11e8-82bb-8000992f3cba.png)

I already removed the gekko folder, removed the npm installation and tried to reinstall.. Nothing differs..
The effect on the GUI is that it does not show any exchange, nor fiat currency or other. All the dropdown menus stopped showing basically..

Thank you in advance!

**Comment by askmike** [comment]
You haven't correctly installed Gekko **Broker** dependencies. See the docs. If you see an error while running that command post it here.

**Comment by dannunz1** [comment]
I solved it by just git clone it into another folder. I did install the broker dependencies ..

Thank you
