### ISSUE TITLE
Poloniex returned an error while fetching trades: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by YuriyTigiev** [askmike/gekko#2588]
**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
trade bitcoin/xrp

**Expected result** (what you hoped would happen)
sell xrp

**Actual result** (unexpected outcome)
2018-10-10 04:07:49 (INFO):		 Performance Analyzer
2018-10-10 04:07:49 (INFO):		 Analyzes performances of trades
2018-10-10 04:07:49 (INFO):	

2018-10-10 04:07:49 (INFO):	Starting to watch the market: Poloniex XRP/BTC
2018-10-10 13:01:53 (WARN):	Poloniex returned an error while fetching trades: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/ytigiev/gekko/exchange/node_modules/gekko-broker-poloniex/poloniex.js:106:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2018-10-10 15:32:41 (WARN):	Poloniex returned an error while fetching trades: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/ytigiev/gekko/exchange/node_modules/gekko-broker-poloniex/poloniex.js:106:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

The bot worked correctly with  USDT/BTC pair on this computer.

**Comment by askmike** [comment]
Most likely the same as #2587, can you try out that suggested debugging method? Thanks
