### ISSUE TITLE
Gekko tries to sell but cannot sell as holding is below minimal order quantity

### ISSUE THREAD

**Issue by g1tt** [askmike/gekko#2592]
**I'm submitting a ...**
[ ] bug report

**Action taken** (what you did)
I am trading EOS on Kraken. Due to some web timeout circumstances I have this portfolio:
15.7768 EUR
0.97625316 EOS
So I am exposed as follows -
yes (21.86%)

**Expected result** (what you hoped would happen)
I expect gekko to sell first as it is exposed

**Actual result** (unexpected outcome)
Because the EOS holding is below the minimal order qty (3.0) gekko cannot sell.
Additionally gekko never tries to buy because it considers it is already exposed.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I thought I could fix this.

I found the setting where gekko makes the decision that we are exposed because our holding is > 10%.
I could just amend that to a higher value but it seems the better way is to check whether our holding is > minimal order qty and if not then set exposed to no (or better still existing value && our new check).

I tried adding this code to the Trader.prototype.setBalance  function within trader.js -

  // if more than 10% of balance is in asset we are exposed
  this.exposed = this.exposure > 0.1;
  // check out holding is > minimalOrder.amount
  this.exposed = this.exposed && (this.portfolio.asset>this.brokerConfig.asset.minimalOrder.amount);

but this throws an exception. I hunted around in the code for where I receive the "order qty was too small" error and found a different reference so tried this -

this.exposed = this.exposed && (this.portfolio.asset>market.minimalOrder.amount);  

but this also crashes gekko. I guess I am not accessing the var correctly or the var is not accessible within trader.js.

How can I access the minimalOrder.amount var within the context of the trader? Is this even possible?

Thanks! :)

**Comment by g1tt** [comment]
Here are the errors from the console if they help!

2018-10-13 15:58 Gekko 2018-10-13-15-58-tradebot-499089764964893 started.
  --> POST /api/startGekko 200 590ms 1.7kb
uncaughtException TypeError: Cannot read property 'amount' of undefined
    at Trader.setBalance (/usr/local/git/gekko_3011/plugins/trader/trader.js:115:93)
    at Trader.bound [as setBalance] (/usr/local/git/gekko_3011/node_modules/lodash/dist/lodash.js:729:21)
    at broker.syncPrivateData (/usr/local/git/gekko_3011/plugins/trader/trader.js:68:10)
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:3888:9
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:995:17)
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:969:16
    at Timeout._onTimeout (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:3885:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
RECEIVED ERROR IN GEKKO INSTANCE 2018-10-13-15-58-tradebot-499089764964893


2018-10-13 16:14 Gekko 2018-10-13-16-14-tradebot-7058478457411477 started.
  --> POST /api/startGekko 200 481ms 1.7kb
uncaughtException ReferenceError: market is not defined
    at Trader.setBalance (/usr/local/git/gekko_3011/plugins/trader/trader.js:116:56)
    at Trader.bound [as setBalance] (/usr/local/git/gekko_3011/node_modules/lodash/dist/lodash.js:729:21)
    at broker.syncPrivateData (/usr/local/git/gekko_3011/plugins/trader/trader.js:68:10)
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:3888:9
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:995:17)
    at /usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:969:16
    at Timeout._onTimeout (/usr/local/git/gekko_3011/exchange/node_modules/async/dist/async.js:3885:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
RECEIVED ERROR IN GEKKO INSTANCE 2018-10-13-16-14-tradebot-7058478457411477

For now I have set this -
  // if more than 10% of balance is in asset we are exposed
  this.exposed = this.exposure > 0.9;

And now gekko has started with no problems and registered itself as not exposed, therefore it should now buy more EOS (if I have the funds for that!!) and then will be able to sell it all.

But my first fix would be better! :)

**Comment by askmike** [comment]
The boolean `this.exposed` is either true or false right now. It's used for a few different things so changing that can have strange consequences. We should NOT be using this boolean to decide when to sell/buy, we should always sell when there is more quantity available than the minimum.

**Comment by g1tt** [comment]
Hi Mike,

I am new to Node so maybe my logic is wrong. I wasn't trying to set this.exposed to something other than yes or no... What I am trying to do is...

// if more than 10% of balance is in asset we are exposed
this.exposed = this.exposure > 0.1;

- at this stage exposed=yes because this.exposure > 0.1

BUT - 0.97625316 EOS is below the minimum order qty of 3, so I cannot sell it.
Yet as 'exposed==true' gekko will try and sell rather than buy (which is what it needs to do in this scenario!)

So I was trying to add a second check...

this.portfolio.asset>this.brokerConfig.asset.minimalOrder.amount

and if that is true AND the results of the earlier operation (this.exposure > 0.1) was true then set exposed=true, otherwise exposed=false, hence...

this.exposed = this.exposed && (this.portfolio.asset>market.minimalOrder.amount);

Maybe a better way of writing it would be...

if (this.exposure > 0.9 && this.portfolio.asset > this.brokerConfig.asset.minimalOrder.amount) {
    this.exposed=true
} else {
    this.exposed=false
}

That's what I was going for.

Does that make more sense?

Or did you get what I meant anyway? :)

I did set this to get around the problem -

this.exposed = this.exposure > 0.9;

and that worked fine, but I'm sure like this I'd have the same problem in reverse, ie I wouldn't be able you buy as I don't enough funds to buy the minimum!

So I looked at the buy routine, and this is my problem -

if(direction === 'buy') {
    if(this.exposed) {
      log.info('NOT buying, already exposed');
      return this.deferredEmit('tradeAborted', {
        id,
        adviceId: advice.id,
        action: direction,
        portfolio: this.portfolio,
        balance: this.balance,
        reason: "Portfolio already in position."
      });
    }

The strategy tells gekko to buy, but because this.exposed==true it doesn't buy. So it tries to sell instead. But it can't sell because we don't have enough qty to sell. And we end up stuck in a loop and I have to restart the strategy (with this.exposed = this.exposure > 0.9;'' to get around the problem!)

direction is set here -

  if(advice.recommendation === 'long') {
    direction = 'buy';
  } else if(advice.recommendation === 'short') {
    direction = 'sell';
  } else {
    log.error('ignoring advice in unknown direction');
    return;
  }

and advice.recommendation comes from the strategy so do you mean I should be checking that we are above the minimum order qty in my strategy?

I will keep hunting but if any of this makes sense to you and you could point me in the vague general direction that would be awesome! :)

Thanks!

**Comment by g1tt** [comment]
Okay let's try explaining it a bit better, from the top! :)

Here's a tradebot log (with lots of lines removed to just show what happens each time advice switches between buy and sell) that follows a partial buy leaving us with less than the minimum order qty -

2018-10-18 18:20:37 (INFO):	[ORDER] partial buy fill, total filled: 0.01631881
2018-10-18 18:20:56 (DEBUG):	Sell - Predicted variation:  -0.0837502372900265
2018-10-18 18:20:56 (INFO):	Received advice to sell however Gekko is already in the process to buy
2018-10-18 18:20:56 (INFO):	Canceling buy order first
2018-10-18 18:20:56 (DEBUG):	Sell - Predicted variation:  -0.06440877572327124
2018-10-18 18:21:01 (INFO):	NOT selling, already no exposure
2018-10-18 18:27:16 (DEBUG):	Buy - Predicted variation:  0.09239415201120758
2018-10-18 18:27:16 (INFO):	Trader Received advice to go long. Buying  BCH
2018-10-18 18:27:16 (WARN):	NOT creating order! Reason: Amount is too small
2018-10-18 19:18:58 (DEBUG):	Sell - Predicted variation:  -0.1337296712578553
2018-10-18 19:18:58 (INFO):	NOT selling, already no exposure
2018-10-18 19:44:39 (DEBUG):	Buy - Predicted variation:  0.1535563495526938
2018-10-18 19:44:39 (INFO):	Trader Received advice to go long. Buying  BCH
2018-10-18 19:44:39 (WARN):	NOT creating order! Reason: Amount is too small

This is still going on now - three days later!

So looking at the two issues - it tries to buy but it can't as there's not enough funds in the account to make the trade (I am working with small amounts until all my bots run continuously without issues!) -

2018-10-18 18:27:16 (INFO):	Trader Received advice to go long. Buying  BCH
2018-10-18 18:27:16 (WARN):	NOT creating order! Reason: Amount is too small

So the logical thing to do is to sell. But when the sell instruction comes along we get this -

2018-10-18 19:18:58 (DEBUG):	Sell - Predicted variation:  -0.1337296712578553
2018-10-18 19:18:58 (INFO):	NOT selling, already no exposure

and that happens because this.exposed is false within trader.js -

    if(!this.exposed) {
      log.info('NOT selling, already no exposure');
      return this.deferredEmit('tradeAborted', {
        id,
        adviceId: advice.id,
        action: direction,
        portfolio: this.portfolio,
        balance: this.balance,
        reason: "Portfolio already in position."
      });
    }

So as I see it... as well as checking for the minimum order quantity when we set this.exposed (as per my original post)... we should also re-check this.exposed after every trade!

But that's just looking at a small section of the code and I'm new here so I fully understand that I could well be looking in the wrong place!

What would you suggest? :)

**Comment by g1tt** [comment]
Okay... back to what you said -

We should NOT be using this boolean to decide when to sell/buy, we should always sell when there is more quantity available than the minimum.

So I have amended the buy/sell routines within trader.js to use check.valid rather than this.exposed to determine whether the action is valid.

I will report back!

**Comment by g1tt** [comment]
Early days but the signs are that it does seem to have fixed it!

Here are the condensed logs again...

2018-10-21 19:45:37 (DEBUG):	Buy - Predicted variation:  0.15073636929596734
2018-10-21 19:45:37 (WARN):	NOT buying! Reason: Amount is too small
2018-10-21 19:48:57 (DEBUG):	Sell - Predicted variation:  -0.12049191904414319
2018-10-21 19:48:57 (INFO):	Trader Received advice to go short. Selling  ETC
2018-10-21 19:48:57 (DEBUG):	Creating order to sell 0.98534968 ETC
2018-10-21 19:49:02 (DEBUG):	[ORDER] statusChange: SUBMITTED
2018-10-21 19:49:02 (DEBUG):	[ORDER] statusChange: OPEN
2018-10-21 20:03:40 (DEBUG):	[ORDER] statusChange: MOVING
2018-10-21 20:03:40 (DEBUG):	[ORDER] statusChange: OPEN
2018-10-21 20:10:57 (DEBUG):	Buy - Predicted variation:  0.025210949746647473
2018-10-21 20:10:57 (INFO):	Received advice to buy however Gekko is already in the process to sell
2018-10-21 20:10:57 (INFO):	Canceling sell order first
2018-10-21 20:11:02 (WARN):	NOT buying! Reason: Amount is too small
2018-10-21 20:49:19 (DEBUG):	Sell - Predicted variation:  -0.06680763980373534
2018-10-21 20:49:19 (INFO):	Trader Received advice to go short. Selling  ETC
2018-10-21 20:49:19 (DEBUG):	Creating order to sell 0.98534968 ETC
2018-10-21 20:49:24 (DEBUG):	[ORDER] statusChange: SUBMITTED
2018-10-21 20:49:24 (DEBUG):	[ORDER] statusChange: OPEN
2018-10-21 21:10:39 (DEBUG):	Buy - Predicted variation:  0.026500172403494268
2018-10-21 21:10:39 (INFO):	Received advice to buy however Gekko is already in the process to sell
2018-10-21 21:10:39 (INFO):	Canceling sell order first
2018-10-21 21:10:44 (WARN):	NOT buying! Reason: Amount is too small

So even though it's not actually selling (advice is changing before sale completes) it IS switching between trying to buy and sell and at least placing the orders where it wasn't doing that before.

Amended code is here if you want a look - https://github.com/askmike/gekko/compare/develop...g1tt:fix-min-order-qty-issue

I will monitor and report back! :)
