### ISSUE TITLE
[GB] gekko crashes on coinfalcon 524 error

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#2613]
2018-10-25T11:14:29.083Z '[cf] big error!' '524' [Function]
    2018-10-25T11:14:29.084Z '[sticky order] FATAL ERROR' '524'
    2018-10-25T11:14:29.084Z Error: 524
        at IncomingMessage.<anonymous> (/root/gb/node_modules/coinfalcon/dist/libs/https.js:918:22)
        at IncomingMessage.emit (events.js:187:15)
        at endReadableNT (_stream_readable.js:1090:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)

524 is a timeout from cloudflare, which means we don't know if it's safe to retry the API call (in case it was an order creation). In order to fix we need to update the retry logic to use the exchangeUtils.retry method.

**Comment by askmike** [comment]
Also happens with 530:

    Error: 530
        at IncomingMessage.<anonymous> (/home/ubuntu/eur-arb/node_modules/coinfalcon/dist/libs/https.js:918:22)
        at IncomingMessage.emit (events.js:185:15)
        at endReadableNT (_stream_readable.js:1101:12)
        at process._tickCallback (internal/process/next_tick.js:114:19) Promise {
      <rejected> Error: 530
        at IncomingMessage.<anonymous> (/home/ubuntu/eur-arb/node_modules/coinfalcon/dist/libs/https.js:918:22)
        at IncomingMessage.emit (events.js:185:15)
        at endReadableNT (_stream_readable.js:1101:12)
        at process._tickCallback (internal/process/next_tick.js:114:19) }
