### ISSUE TITLE
TypeError: Cannot read property 'learning_rate' of undefined

### ISSUE THREAD

**Issue by dzimu** [askmike/gekko#2619]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[*] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I tried to run backtest but this error came up

**Expected result** (what you hoped would happen)

**Actual result** (unexpected outcome)
2018-10-31 06:06:12 (INFO):	Setting up Gekko in backtest mode
2018-10-31 06:06:12 (INFO):	
2018-10-31 06:06:12 (WARN):	The plugin Candle writer does not support the mode backtest. It has been disabled.
2018-10-31 06:06:12 (INFO):	Setting up:
2018-10-31 06:06:12 (INFO):		 Trading Advisor
2018-10-31 06:06:12 (INFO):		 Calculate trading advice
2018-10-31 06:06:12 (INFO):		 Using the strategy: neuralnet
/home/serbona/gekko/strategies/neuralnet.js:54
      learning_rate: this.settings.learning_rate,
                                   ^

TypeError: Cannot read property 'learning_rate' of undefined
    at Base.init (/home/serbona/gekko/strategies/neuralnet.js:54:36)
    at Base.bound [as init] (/home/serbona/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/serbona/gekko/plugins/tradingAdvisor/baseTradingMethod.js:69:8)
    at Actor.setupStrategy (/home/serbona/gekko/plugins/tradingAdvisor/tradingAdvisor.js:61:19)
    at Actor.bound [as setupStrategy] (/home/serbona/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/home/serbona/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/home/serbona/gekko/core/pluginUtil.js:98:22)
    at /home/serbona/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/serbona/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/home/serbona/gekko/node_modules/async/dist/async.js:1015:17)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by ghost** [comment]
It seems you haven't read this link:
https://gekko.wizb.it/docs/strategies/creating_a_strategy.html

TypeError: Cannot read property 'learning_rate' of undefined
 This means you are accessing a variable that is not previously defined, for now add this to your config.js file and check the result

config.neuralnet = {
  threshold_buy : 1.0,
  threshold_sell : -1.0,
  price_buffer_len : 100,
  learning_rate : 0.01,
  momentum : 0.9,
  decay : 0.001,
  min_predictions : 1000,
  stoploss_enabled : true, 
  stoploss_threshold : 0.9,
}

**Comment by dzimu** [comment]
Oh thank you man i am blind hahah

**Comment by dzimu** [comment]
Now backtest is running good, the only downside is that it shows me -9% loss on this strategy :) thank you again @AJ-gohan every help mean a lot to me because I am very new to coding.

**Comment by askmike** [comment]
Your initial problem is a problem with a third party strategy! As such it's not applicable to this issue tracker (for the general Gekko project).

> Now backtest is running good, the only downside is that it shows me -9% loss on this strategy :)

Good thing it's not real money!
