### ISSUE TITLE
Unexpected token 'u' while using Bitfinex

### ISSUE THREAD

**Issue by vongdarakia** [askmike/gekko#262]
Hi, I'm new to using Gekko, and trying to use it for Bitfinex. I've changed the exchanged variable in config.watcher to 'Bitfinex', then tried to run node gekko.js but I'm getting this unexpected token error. Running the program from bitstamp works fine, but not for Bitfinex. Just wondering if anybody else got this error and know how to fix it.

Here is the debug info:

2015-01-15 22:56:37 (INFO):	Gekko v0.1.2 started
2015-01-15 22:56:37 (INFO):	I'm gonna make you rich, Bud Fox. 

2015-01-15 22:56:37 (INFO):	Using config file: /Users/username/Desktop/gekko/config.js
2015-01-15 22:56:37 (INFO):	Setting up Gekko in realtime mode

2015-01-15 22:56:37 (INFO):	Setting up:
2015-01-15 22:56:37 (INFO):		 Trading Advisor
2015-01-15 22:56:37 (INFO):		 Calculate trading advice
2015-01-15 22:56:37 (INFO):		 Using trading method: DEMA

2015-01-15 22:56:37 (INFO):	Setting up:
2015-01-15 22:56:37 (INFO):		 Profit Simulator
2015-01-15 22:56:37 (INFO):		 Paper trader that logs fake profits.

2015-01-15 22:56:37 (INFO):	Starting to watch the market: Bitfinex BTC/USD
2015-01-15 22:56:37 (DEBUG):	~market start
2015-01-15 22:56:37 (DEBUG):	checking history
2015-01-15 22:56:37 (DEBUG):	~watch market
2015-01-15 22:56:37 (DEBUG):	Requested BTC/USD trade data from Bitfinex ...

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /Users/username/Desktop/gekko/exchanges/bitfinex.js:127:23
    at Request._callback (/Users/username/Desktop/gekko/node_modules/bitfinex/bitfinex.js:105:14)
    at Request.self.callback (/Users/username/Desktop/gekko/node_modules/bitfinex/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/username/Desktop/gekko/node_modules/bitfinex/node_modules/request/request.js:893:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/username/Desktop/gekko/node_modules/bitfinex/node_modules/request/request.js:844:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

**Comment by askmike** [comment]
Seems like bitfinex did not return proper JSON data. Will look into this, thanks for reporting!

**Comment by michaelryancaputo** [comment]
@askmike same thing here. On line 127, body is returning undefined.

**Comment by michaelryancaputo** [comment]
I see the issue here, the Bitfinex API is wrong in the bitfinex package, as per the bitfinex site, the api should be https://api.bitfinex.com/v1

**Comment by michaelryancaputo** [comment]
After taking a look (and not knowing very much about this app, as I just found it), it seems like to get it running, changing ```    var result = JSON.parse(body);``` to ```var result = data``` gets past the error, if this actually fixes it, i'm not sure.

**Comment by 1c3Candy** [comment]
I got a lots of error, too bad im not a programmer. Any help that you can
suggest?

**Comment by askmike** [comment]
After some testing the solution provided by @michaelryancaputo appears to fix it. 

I haven't touched this code in a while but this might be related to a change in [the bitfinex module](https://github.com/naddison36/bitfinex) Gekko uses to fetch data from Bitfinex

 Let me know if you run into more problems!
