### ISSUE TITLE
TypeError: Object false has no method 'find'

### ISSUE THREAD

**Issue by FireWalkerX** [askmike/gekko#263]
Gekko crashes when ready to give advice with the following:

2015-01-22 11:00:53 (INFO):	We have all required history, going to calculate advice from this point.
/home/pi/gekko/core/candleManager.js:560
TypeError: Object false has no method 'find'
    at Manager.getCandles (/home/pi/gekko/core/candleManager.js:560:35)
    at bound [as getCandles] (/home/pi/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at iterator (/home/pi/gekko/core/candleManager.js:516:10)
    at bound (/home/pi/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/pi/gekko/node_modules/async/lib/async.js:227:13
    at /home/pi/gekko/node_modules/async/lib/async.js:111:13
    at _each (/home/pi/gekko/node_modules/async/lib/async.js:32:24)
    at async.each (/home/pi/gekko/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/home/pi/gekko/node_modules/async/lib/async.js:226:9)

Program node gekko exited with code 8
Starting child process with 'node gekko'

then when restarted it will state it need data for another 15 hours

**Comment by askmike** [comment]
Thanks for reporting, I am pretty sure this will be fixed by the [new version](https://github.com/askmike/gekko/tree/candle-rewrite#important-note).

**Comment by michaelryancaputo** [comment]
@askmike is v2 stable enough to start using?

**Comment by Gargamil** [comment]
I have the same problem...

**Comment by askmike** [comment]
This is fixed in the new version.
