### ISSUE TITLE
Unable to Backtest on Ubuntu

### ISSUE THREAD

**Issue by sahni619** [askmike/gekko#2646]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (Tried Backtesting a Dataset)

**Expected result** (Would have shown the backtest results)

**Actual result** (TypeError: Cannot read property 'to' of undefined)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Error** : 
   
`   from: r.to,
                        ^

TypeError: Cannot read property 'to' of undefined
    at _.map.r (/root/gekko/core/tools/dateRangeScanner.js:117:25)
    at Function.map (/root/gekko/node_modules/lodash/dist/lodash.js:3509:27)
    at async.whilst (/root/gekko/core/tools/dateRangeScanner.js:115:15)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at Object.whilst (/root/gekko/node_modules/async/dist/async.js:5092:25)
    at async.parallel (/root/gekko/core/tools/dateRangeScanner.js:68:13)
    at /root/gekko/node_modules/async/dist/async.js:3853:9
    at /root/gekko/node_modules/async/dist/async.js:484:16
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1013:24)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at Statement.<anonymous> (/root/gekko/plugins/sqlite/reader.js:135:5) `

Tried on Gekko UI. Haven't tried command-line.

**Comment by sahni619** [comment]
**More Findings** I retried backtesting and it worked once and then again when I tried it gave out below error 
`  Error: non-error thrown: Child process has died.
      at Object.onerror (/root/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)`

Plz note am using default RSI strategy to backtest with only modifications in the TOML file.

**Comment by sahni619** [comment]
I restarted my bot and after 2 days it crashed again with the same error. It happens all the time.
<img width="1106" alt="screen shot 2018-11-11 at 4 40 54 pm" src="https://user-images.githubusercontent.com/17097887/48312169-c53f0500-e5d0-11e8-8538-f4b4c43ec67f.png">

**Comment by itsdarkerinnit** [comment]
I'm having the same issue running on a Raspberry Pi 3 npm v6.4.1 and nodejs 8.12.0, fresh install, using Gekko v0.6.7 and Gekko UI v0.2.3.
Heres the error: 
````
<-- POST /api/scansets
/home/qwe/gekko/core/tools/dateRangeScanner.js:117
                from: r.to,
                        ^

TypeError: Cannot read property 'to' of undefined
    at _.map.r (/home/qwe/gekko/core/tools/dateRangeScanner.js:117:25)
    at Function.map (/home/qwe/gekko/node_modules/lodash/dist/lodash.js:3509:27)
    at async.whilst (/home/qwe/gekko/core/tools/dateRangeScanner.js:115:15)
    at /home/qwe/gekko/node_modules/async/dist/async.js:988:16
    at Object.whilst (/home/qwe/gekko/node_modules/async/dist/async.js:5092:25)
    at async.parallel (/home/qwe/gekko/core/tools/dateRangeScanner.js:68:13)
    at /home/qwe/gekko/node_modules/async/dist/async.js:3853:9
    at /home/qwe/gekko/node_modules/async/dist/async.js:484:16
    at iterateeCallback (/home/qwe/gekko/node_modules/async/dist/async.js:1013:24)
    at /home/qwe/gekko/node_modules/async/dist/async.js:988:16
    at /home/qwe/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/home/qwe/gekko/node_modules/async/dist/async.js:41:25)
    at /home/qwe/gekko/node_modules/async/dist/async.js:76:12
    at Statement.<anonymous> (/home/qwe/gekko/plugins/sqlite/reader.js:135:5)
  --> POST /api/scansets 200 6,668ms 254b
```
`
This happens as soon as I try to scan datasets on local data and backtest.

**Comment by devsigner-xyz** [comment]
Hi! I am having the same issue running Gekko in my setup:

Windows 10 64bit
Node 8.11.4
Gekko v0.6.7 
Gekko UI v0.2.3

I also noticed about broken HTML when I try to use some indicators I don't if this could be related.

C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\core\tools\dateRangeScanner.js:117
from: r.to,
^

TypeError: Cannot read property 'to' of undefined
at _.map.r (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\core\tools\dateRangeScanner.js:117:25)
at Function.map (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\lodash\dist\lodash.js:3509:27)
at async.whilst (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\core\tools\dateRangeScanner.js:115:15)
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:988:16
at Object.whilst (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:5092:25)
at async.parallel (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\core\tools\dateRangeScanner.js:68:13)
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:3853:9
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:484:16
at iterateeCallback (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:1013:24)
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:988:16
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:3850:13
at apply (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:41:25)
at C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\node_modules\async\dist\async.js:76:12
at Statement.<anonymous> (C:\Users\pcarballeda\Desktop\gekko-custom-configuration\gekko\plugins\sqlite\reader.js:135:5)

I was able to avoid the error by adjusting the date range manually. It seems that at some point the date variable `to` is not taken and when it is changed manually it is reassigned in some way. I have no idea.

**Comment by thecccut** [comment]
Me to :(
