### ISSUE TITLE
uncaughtException TypeError: Cannot read property 'exchange' of undefined

### ISSUE THREAD

**Issue by arbourp** [askmike/gekko#2651]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
While attempting to run a backtest through the API, using the example code provided in the documentation from the API I get this error along with a stack trace taht shows <anonymous> objects throughout.

**Expected result** (what you hoped would happen)
I expect that the APi would trigger a backtest.

**Actual result** (unexpected outcome)
Error generated, from the backtest API, with a 500 server error

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

I've pulled out the stack trace. I also tried to print what was in the actual message from within the backtest wrapper and it seems to be empty.

uncaughtException TypeError: Cannot read property 'exchange' of undefined
    at Object.<anonymous> (/root/gekko/plugins/sqlite/handle.js:29:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/gekko/plugins/sqlite/reader.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/gekko/core/tools/dateRangeScanner.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/gekko/core/prepareDateRange.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at prepareMarket (/root/gekko/core/pipeline.js:176:7)
    at /root/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/root/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)
    at /root/gekko/node_modules/async/dist/async.js:988:16
    at /root/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/root/gekko/node_modules/async/dist/async.js:41:25)
    at /root/gekko/node_modules/async/dist/async.js:76:12
    at subscribePlugins (/root/gekko/core/pipeline.js:171:5)
    at /root/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/root/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/root/gekko/node_modules/async/dist/async.js:1015:17)

This is the API call I was trying(tried a bunch of others, same result):

{
    "watch": {
        "exchange": "poloniex",
        "currency": "USDT",
        "asset": "ETH"
    },
    "paperTrader": {
        "feeMaker": 0.25,
        "feeTaker": 0.25,
        "feeUsing": "maker",
        "slippage": 0.05,
        "simulationBalance": {
            "asset": 1,
            "currency": 100
        },
        "reportRoundtrips": true,
        "enabled": true
    },
    "tradingAdvisor": {
        "enabled": true,
        "method": "MACD",
        "candleSize": 60,
        "historySize": 10
    },
    "MACD": {
        "short": 10,
        "long": 21,
        "signal": 9,
        "thresholds": {
            "down": -0.025,
            "up": 0.025,
            "persistence": 1
        }
    },
    "backtest": {
        "daterange": {
            "from": "2016-06-01T11:57:00Z",
            "to": "2016-11-13T14:57:00Z"
        }
    },
    "backtestResultExporter": {
        "enabled": true,
        "writeToDisk": false,
        "data": {
            "stratUpdates": false,
            "roundtrips": true,
            "stratCandles": true,
            "stratCandleProps": [
                "open"
            ],
            "trades": true
        }
    },
    "performanceAnalyzer": {
        "riskFreeReturn": 2,
        "enabled": true
    }
}

**Comment by askmike** [comment]
How did you post that data? Can you share dummy code?
