### ISSUE TITLE
import error: sqlite missing

### ISSUE THREAD

**Issue by benjiqq** [askmike/gekko#2686]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report

**Action taken** (what you did)
running import, binance

**Expected result** (what you hoped would happen)
import the data

**Actual result** (unexpected outcome)
error message

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

```
RECEIVED ERROR IN IMPORT 704061826151627

 ERROR: Error: dlopen(/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 318342
	/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 318342

uncaughtException Error: dlopen(/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 318342
	/Users/ben/archonx/gekko/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 318342
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ben/archonx/gekko/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)


```

**Comment by askmike** [comment]
Your sqlite3 isn't installed correctly. Easiest is to manually delete the `gekko/node_modules` folder and run the dependency installation commends again.
