### ISSUE TITLE
DOUBLE UNIQUE INSERT

### ISSUE THREAD

**Issue by iebb** [askmike/gekko#271]
this problem happens almost once a day

2015-03-05 17:44:03 (DEBUG):    Starting to watch the market: Cryptsy DRK/BTC
2015-03-05 17:44:03 (DEBUG):    ~market start
2015-03-05 17:44:03 (DEBUG):    checking history
2015-03-05 17:44:03 (DEBUG):    ~watch market
2015-03-05 17:44:03 (DEBUG):    Requested DRK/BTC trade data from Cryptsy ...
2015-03-05 17:44:05 (DEBUG):    Fetched 1000 new trades, from 2015-03-05 18:52:59 UTC to 2015-03-06 00:43:09 UTC
2015-03-05 17:44:05 (DEBUG):    shifting past midnight
2015-03-05 17:44:05 (INFO):     We don't have enough history yet to start giving advice, I'll need to gather more data first.
2015-03-05 17:44:05 (INFO):     I will start giving advice around 2015-03-06 12:17:00 (local time, that's in 19 hours).
2015-03-05 17:44:05 (DEBUG):    minimum trade treshold: 2015-03-06 00:00:00 UTC
2015-03-05 17:44:05 (DEBUG):    processing 50 trade(s)
2015-03-05 17:44:05 (DEBUG):    from 2015-03-06T00:00:03+00:00 to 2015-03-06T00:43:09+00:00
2015-03-05 17:44:05 (DEBUG):    Skipping creation of already existing database 2015-03-06
2015-03-05 17:44:05 (WARN):     DOUBLE UNIQUE INSERT, this should never happen. Please post details  here: https://github.com/askmike/gekko/issues/90 2015-03-06 0 { message: 'Can\'t insert key 0, it violates the unique constraint',
  key: 0,
  errorType: 'uniqueViolated' }

Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.10.25

Error:

{ message: 'Can\'t insert key 0, it violates the unique constraint',
  key: 0,
  errorType: 'uniqueViolated' } '\n\n'
Terminated

**Comment by Nargren** [comment]
I just encountered the same problem while watching Bitstamp. I'm posting here as this seems a relevant thread plus the linked one is over a year old.


2016-01-01 04:03:59 (INFO):	We have all required history, going to calculate advice from this point.

/home/ubuntu/gekko/node_modules/nedb/lib/datastore.js:60
    if (err) { throw err; }
                     ^
[object Object]
2016-01-01 02:01:20 (WARN):	DOUBLE UNIQUE INSERT, this should never happen. Please post details  here: https://github.com/askmike/gekko/issues/90 2016-01-01 0 { message: 'Can\'t insert key 0, it violates the unique constraint',
  key: 0,
  errorType: 'uniqueViolated' }


Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.12.5

Error:

{ message: 'Can\'t insert key 0, it violates the unique constraint',
  key: 0,
  errorType: 'uniqueViolated' } '\n\n'
node.js:609
        throw new TypeError('invalid pid');
              ^
TypeError: invalid pid
    at process.kill (node.js:609:15)
    at Object.util.die (/home/ubuntu/gekko/core/util.js:141:13)
    at null.<anonymous> (/home/ubuntu/gekko/core/candleManager.js:898:12)
    at bound (/home/ubuntu/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at callback (/home/ubuntu/gekko/node_modules/nedb/lib/executor.js:25:17)
    at Datastore._insert (/home/ubuntu/gekko/node_modules/nedb/lib/datastore.js:280:12)
    at /home/ubuntu/gekko/node_modules/nedb/lib/executor.js:36:13
    at Object.q.process (/home/ubuntu/gekko/node_modules/nedb/node_modules/async/lib/async.js:728:21)
    at next (/home/ubuntu/gekko/node_modules/nedb/node_modules/async/lib/async.js:725:27)
    at /home/ubuntu/gekko/node_modules/nedb/node_modules/async/lib/async.js:24:16

**Comment by Emzy** [comment]
2016-06-01 00:01:52 (DEBUG):    Requested XMR/BTC trade data from Poloniex ...
2016-06-01 00:01:53 (DEBUG):    Fetched 200 new trades, from 2016-05-31 22:56:45 UTC to 2016-06-01 00:01:25 UTC
2016-06-01 00:01:53 (DEBUG):    minimum trade treshold: 2016-05-31 23:59:00 UTC
2016-06-01 00:01:53 (DEBUG):    processing 1 trade(s)
2016-06-01 00:01:53 (DEBUG):    from 2016-06-01T00:01:25+00:00 to 2016-06-01T00:01:25+00:00
2016-06-01 00:01:53 (DEBUG):    fetch spans midnight
2016-06-01 00:01:53 (DEBUG):    Skipping creation of already loaded database 2016-05-31
2016-06-01 00:01:53 (WARN):     DOUBLE UNIQUE INSERT, this should never happen. Please post details  here: https://github.com/askmike/gekko/issues/90 2016-05-31 1 { message: 'Can\'t insert key 1, it violates the unique constraint',
  key: 1,
  errorType: 'uniqueViolated' }


Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.10.29

Error:

{ message: 'Can\'t insert key 1, it violates the unique constraint',
  key: 1,
  errorType: 'uniqueViolated' } '\n\n'

**Comment by askmike** [comment]
this is fixed in the new version!
