### ISSUE TITLE
can not start using confi

### ISSUE THREAD

**Issue by zndtoshi** [askmike/gekko#2728]
Starting the config file I get this error: (I set kraken and currency EUR and coin XBT)

/home/kubuntu/Gekko-DCA/config-live.js:35
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
at new Script (vm.js:85:7)
at createScript (vm.js:266:10)
at Object.runInThisContext (vm.js:314:10)
at Module._compile (internal/modules/cjs/loader.js:698:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
at Module.load (internal/modules/cjs/loader.js:630:32)
at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
at Function.Module._load (internal/modules/cjs/loader.js:562:3)
at Module.require (internal/modules/cjs/loader.js:667:17)
at require (internal/modules/cjs/helpers.js:20:18)
Starting the config file I get this error (edited by your description)

/home/kubuntu/Gekko-DCA/config-live.js:35
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
at new Script (vm.js:85:7)
at createScript (vm.js:266:10)
at Object.runInThisContext (vm.js:314:10)
at Module._compile (internal/modules/cjs/loader.js:698:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
at Module.load (internal/modules/cjs/loader.js:630:32)
at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
at Function.Module._load (internal/modules/cjs/loader.js:562:3)
at Module.require (internal/modules/cjs/loader.js:667:17)
at require (internal/modules/cjs/helpers.js:20:18)
Starting the config file I get this error (edited by your description)

/home/kubuntu/Gekko-DCA/config-live.js:35
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
at new Script (vm.js:85:7)
at createScript (vm.js:266:10)
at Object.runInThisContext (vm.js:314:10)
at Module._compile (internal/modules/cjs/loader.js:698:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
at Module.load (internal/modules/cjs/loader.js:630:32)
at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
at Function.Module._load (internal/modules/cjs/loader.js:562:3)
at Module.require (internal/modules/cjs/loader.js:667:17)
at require (internal/modules/cjs/helpers.js:20:18)

**Comment by bonaragung** [comment]
SyntaxError: Unexpected token {
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

**Comment by sheerlox** [comment]
@zndtoshi this is a git merge conflict separator: `<<<<<<< HEAD`.
So it means you have to complete the merge in your `config-live.js` file at line 35 before continuing further.

**Comment by sheerlox** [comment]
@bonaragung your error isn't related to this issue.
Please open a new one if you still need help, and provide more context to your error.

@askmike I think this issue can be closed.
