### ISSUE TITLE
Binance live Canceling order cause gekko crash

### ISSUE THREAD

**Issue by malikhodaei** [askmike/gekko#2733]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ *] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
after runnig my strategy in binance when gekko decide to cancel the order gekko suddenly crash.
I recently try to read as much as issues that i can find and also try gekko stable ,develop and binance ver , but still no success.please help me to solve this situation. 

**Expected result** (what you hoped would happen)
normally buy and sell an strategy followed by gekko

**Actual result** (unexpected outcome)
It crash every time....

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Here is my ERRORS:
2019-03-06 03:04:07 (DEBUG):	Sell at:  0.035272
2019-03-06 03:04:07 (INFO):	Trader Received advice to go long. Buying  ETH
2019-03-06 03:04:07 (DEBUG):	Creating order to buy 0.22013244216375596 ETH
2019-03-06 03:04:07 (INFO):	Received advice to sell however Gekko is already in the process to undefined
2019-03-06 03:04:07 (INFO):	Canceling undefined order first
2019-03-05T23:34:08.599Z 'Error -1105: Parameter \'orderId\' was empty.'
/home/ali/alibot/exchange/wrappers/binance.js:474
      if(err.message.contains(''))
                     ^

TypeError: err.message.contains is not a function
    at cancel (/home/ali/alibot/exchange/wrappers/binance.js:474:22)
    at checkFn (/home/ali/alibot/exchange/exchangeUtils.js:45:7)
    at /home/ali/alibot/exchange/wrappers/binance.js:126:14
    at Request.request [as _callback] (/home/ali/alibot/exchange/node_modules/binance/lib/rest.js:90:25)
    at Request.self.callback (/home/ali/alibot/exchange/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ali/alibot/exchange/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ali/alibot/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Borrismorris** [comment]
Hey guys got the same problem here, using Binance to trade, just tried updating the dependencies will leave to test till tomorrow morning. Hopefully this fixes it

**Comment by malikhodaei** [comment]
Hi @Borrismorris thanks for your reply .
I am appreciate and waiting for your solution.
