### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Shrike998** [askmike/gekko#2734]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Ran gekko CLI using a historySize of 42750

**Expected result** (what you hoped would happen)
gekko would run normaly

**Actual result** (unexpected outcome)

RangeError: Maximum call stack size exceeded
    at Actor.emit (events.js:140:44)
    at Actor.bound [as emit] (C:\Users\Shrike\Desktop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at Actor.GekkoEventEmitter.broadcastDeferredEmit (C:\Users\Shrike\Desktop\gekko-develop\core\emitter.js:30:8)
    at Actor.bound [as broadcastDeferredEmit] (C:\Users\Shrike\Desktop\gekko-develop\node_modules\lodash\dist\lodash.js:729:21)
    at _.find.producer (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:82:26)
    at Function.find (C:\Users\Shrike\Desktop\gekko-develop\node_modules\lodash\dist\lodash.js:3217:15)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:80:25)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)
    at Gekko.flushDefferedEvents (C:\Users\Shrike\Desktop\gekko-develop\core\gekkoStream.js:89:10)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by medozero** [comment]
UP
