### ISSUE TITLE
Live Gekko Binance - Error -1022: Signature for this request is not valid

### ISSUE THREAD

**Issue by mseewooth** [askmike/gekko#2736]
Hello , 

I'm unable to Gekko tradebot with my binance account . Below are the errors : 

>>>>>
uncaughtException { Error
    at Object.<anonymous> (/home/manjeet/gekko/exchange/exchangeErrors.js:9:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/manjeet/gekko/exchange/exchangeChecker.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
  name: 'ExchangeError',
  message:
   Error: Error -1022: Signature for this request is not valid.
       at /home/manjeet/gekko/exchange/wrappers/binance.js:101:15
       at Request.request [as _callback] (/home/manjeet/gekko/exchange/node_modules/binance/lib/rest.js:90:25)
       at Request.self.callback (/home/manjeet/gekko/exchange/node_modules/request/request.js:185:22)
       at Request.emit (events.js:189:13)
       at Request.<anonymous> (/home/manjeet/gekko/exchange/node_modules/request/request.js:1157:10)
       at Request.emit (events.js:189:13)
       at IncomingMessage.<anonymous> (/home/manjeet/gekko/exchange/node_modules/request/request.js:1079:12)
       at Object.onceWrapper (events.js:277:13)
       at IncomingMessage.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1125:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) }
RECEIVED ERROR IN GEKKO INSTANCE 2019-03-09-15-18-tradebot-280491685238438
<<<<<
After some researches, all i did is  : 
npm install 
Please help ? 
![Screen Shot 2019-03-09 at 6 30 30 PM](https://user-images.githubusercontent.com/36693402/54072826-79a81980-4299-11e9-8f9c-2538e7d73d38.png)

**Comment by Borrismorris** [comment]
Also having this error, may be due to the binance update? Any fixes?

**Comment by mseewooth** [comment]
Hello, 

i deleted my actual binance api and then created a new one . i reconfigured gekko with the newly created AP? and it works :) 
i think i might wrongly added the api at start.
