### ISSUE TITLE
KRAKEN : [ORDER] Gekko received error from GB: Order:Insufficient funds

### ISSUE THREAD

**Issue by mseewooth** [askmike/gekko#2741]
Hello Team, 

Gekko failed to make and order which i'm not understanding why. 

Below are the logs :  

>>>>
2019-03-16 13:29:01 (INFO):     Setting up:
2019-03-16 13:29:01 (INFO):              Trader
2019-03-16 13:29:01 (INFO):              Follows the advice and create real orders.
2019-03-16 13:29:03 (DEBUG):    syncing private data
2019-03-16 13:29:03 (INFO):     
2019-03-16 13:29:14 (INFO):              Portfolio:
2019-03-16 13:29:14 (INFO):                      135.104 USD
2019-03-16 13:29:14 (INFO):                      0 BCH
2019-03-16 13:29:14 (INFO):              Balance:
2019-03-16 13:29:14 (INFO):                      135.104 USD
2019-03-16 13:29:14 (INFO):              Exposed:
2019-03-16 13:29:14 (INFO):                      no (0.00%)
2019-03-16 13:29:14 (INFO):     Setting up:
2019-03-16 13:29:14 (INFO):              Performance Analyzer
2019-03-16 13:29:14 (INFO):              Analyzes performances of trades
2019-03-16 13:29:15 (INFO):     
2019-03-16 13:29:15 (INFO):     Setting up:
2019-03-16 13:29:15 (INFO):              Child to parent
2019-03-16 13:29:15 (INFO):              Relays events from the child to the parent process
2019-03-16 13:29:15 (INFO):     

2019-03-16 13:39:03 (DEBUG):    syncing private data
2019-03-16 13:39:55 (INFO):     Trader Received advice to go long. Buying  BCH
2019-03-16 13:39:55 (DEBUG):    Creating order to buy 0.838333115610712 BCH
2019-03-16 13:40:05 (DEBUG):    [ORDER] statusChange: SUBMITTED
2019-03-16 13:40:06 (DEBUG):    [ORDER] statusChange: OPEN
2019-03-16 13:40:10 (DEBUG):    [ORDER] statusChange: MOVING
2019-03-16 13:40:11 (DEBUG):    [ORDER] statusChange: ERROR
**2019-03-16 13:40:11 (ERROR):    [ORDER] Gekko received error from GB: Order:Insufficient funds**
**2019-03-16 13:40:11 (DEBUG):    Error: Order:Insufficient funds**
    at rawRequest (/home/manjeet/gekko/exchange/node_modules/kraken-api/kraken.js:54:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
<<<<

When i calculated, 0.838 BCH was around $122. GEkko could still buy it.

When i checked on kraken > my orders, i found that gekko bought 0.8004 BCH.  

All i did, was git pull to have all up to date.

Did anyone had this issue ? How does gekko decides how much to buy ? Can it be lowered ? 

Is it my fund is too low ?

Your help will be really appreciated. Thank you very much :) 

Regards, 
Manjeet

**Comment by medozero** [comment]
sometimes it happens due to fast moving price . check market order or use greenGeeko it has other feature to help fixing this
