### ISSUE TITLE
Gekko UI live trading missing trade entry (Binance)

### ISSUE THREAD

**Issue by claytonchew** [askmike/gekko#2745]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[/ ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Only 1 live trading (+ market watch) instance with Gekko UI.

**Expected result** (what you hoped would happen)
Would logs all trades to Gekko UI.

**Actual result** (unexpected outcome)
One trade is missing. (Gekko has initiated 3 trade orders, all which are successful. Gekko UI only showing 2 trades)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Screenshot of Gekko UI:

![screenshot-gekko-ui](https://i.imgur.com/kSGjvzY.png)

Screenshot of Trade Order (Binance):

![screenshot-tradeorder-binance](https://i.imgur.com/l4kS4c0.png)
My timezone is UTC+8.

Gekko tradelogs:

```
2019-03-24 08:22:32 (INFO):     Setting up:
2019-03-24 08:22:32 (INFO):              Trader
2019-03-24 08:22:32 (INFO):              Follows the advice and create real orders.
2019-03-24 08:22:34 (DEBUG):    syncing private data
2019-03-24 08:22:34 (INFO):
2019-03-24 08:22:40 (INFO):              Portfolio:
2019-03-24 08:22:40 (INFO):                      0.32721451 USDT
2019-03-24 08:22:40 (INFO):                      10.1 ETH
2019-03-24 08:22:40 (INFO):              Balance:
2019-03-24 08:22:40 (INFO):                      1376.1492145099999 USDT
2019-03-24 08:22:40 (INFO):              Exposed:
2019-03-24 08:22:40 (INFO):                      yes (99.98%)
2019-03-24 08:22:40 (INFO):     Setting up:
2019-03-24 08:22:40 (INFO):              Performance Analyzer
2019-03-24 08:22:40 (INFO):              Analyzes performances of trades
2019-03-24 08:22:40 (INFO):
2019-03-24 08:22:40 (INFO):     Setting up:
2019-03-24 08:22:40 (INFO):              Child to parent
2019-03-24 08:22:40 (INFO):              Relays events from the child to the parent process
2019-03-24 08:22:40 (INFO):

      <truncated>

2019-03-24 09:37:24 (INFO):     Trader Received advice to go short. Selling  ETH
2019-03-24 09:37:24 (DEBUG):    Creating order to sell 10.1 ETH
2019-03-24 09:37:29 (DEBUG):    [ORDER] statusChange: SUBMITTED
2019-03-24 09:37:29 (DEBUG):    [ORDER] statusChange: OPEN
2019-03-24 09:37:31 (INFO):     [ORDER] partial sell fill, total filled: 10.09929
2019-03-24 09:37:34 (DEBUG):    [ORDER] statusChange: MOVING
2019-03-24 09:37:35 (DEBUG):    [ORDER] statusChange: ERROR
2019-03-24 09:37:35 (ERROR):    [ORDER] Gekko received error from GB: Error -2011: Unknown order sent.
2019-03-24 09:37:35 (DEBUG):    Error: Error -2011: Unknown order sent.
    at /home/chew1992/gekko/exchange/wrappers/binance.js:101:15
    at Request.request [as _callback] (/home/chew1992/gekko/exchange/node_modules/binance/lib/rest.js:90:25)
    at Request.self.callback (/home/chew1992/gekko/exchange/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/home/chew1992/gekko/exchange/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/home/chew1992/gekko/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:285:20)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

      <truncated>

2019-03-24 11:22:29 (INFO):     Trader Received advice to go long. Buying  ETH
2019-03-24 11:22:29 (DEBUG):    Creating order to buy 9.616928844717975 ETH
2019-03-24 11:22:34 (DEBUG):    [ORDER] statusChange: SUBMITTED
2019-03-24 11:22:34 (DEBUG):    [ORDER] statusChange: OPEN
2019-03-24 11:22:35 (DEBUG):    syncing private data
2019-03-24 11:22:38 (INFO):     [ORDER] partial buy fill, total filled: 9.61692
2019-03-24 11:22:38 (DEBUG):    [ORDER] statusChange: FILLED
2019-03-24 11:22:39 (INFO):     [ORDER] summary: { price: 136.63,
  amount: 9.61692,
  date:
   Moment {
     _isAMomentObject: true,
     _i: 1553426556433,
     _isUTC: false,
     _pf:
      { empty: false,
        unusedTokens: [],
        unusedInput: [],
        overflow: -2,
        charsLeftOver: 0,
        nullInput: false,
        invalidMonth: null,
        invalidFormat: false,
        userInvalidated: false,
        iso: false,
        parsedDateParts: [],
        meridiem: null,
        rfc2822: false,
        weekdayMismatch: false },
     _locale:
      Locale {
        _calendar: [Object],
        _longDateFormat: [Object],
        _invalidDate: 'Invalid date',
        ordinal: [Function: ordinal],
        _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
        _relativeTime: [Object],
        _months: [Array],
        _monthsShort: [Array],
        _week: [Object],
        _weekdays: [Array],
        _weekdaysMin: [Array],
        _weekdaysShort: [Array],
        _meridiemParse: /[ap]\.?m?\.?/i,
        _abbr: 'en',
        _config: [Object],
        _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/ },
     _d: 2019-03-24T11:22:36.433Z,
     _isValid: true },
  side: 'buy',
  orders: 1,
  fees: { BNB: 0.05771097 },
  feePercent: 0.00075 }
2019-03-24 11:22:39 (DEBUG):    syncing private data
2019-03-24 11:23:09 (INFO):     (PROFIT REPORT) original balance:                1374.63421451 USDT
2019-03-24 11:23:09 (INFO):     (PROFIT REPORT) current balance:                 1384.30122971 USDT
2019-03-24 11:23:09 (INFO):     (PROFIT REPORT) profit:                          9.66701520 USDT (0.70324273%)

     <truncated>

2019-03-24 22:07:20 (INFO):     Trader Received advice to go short. Selling  ETH
2019-03-24 22:07:20 (DEBUG):    Creating order to sell 9.61692 ETH
2019-03-24 22:07:26 (DEBUG):    [ORDER] statusChange: SUBMITTED
2019-03-24 22:07:26 (DEBUG):    [ORDER] statusChange: OPEN
2019-03-24 22:07:29 (INFO):     [ORDER] partial sell fill, total filled: 0.08511
2019-03-24 22:07:37 (INFO):     [ORDER] partial sell fill, total filled: 9.61692
2019-03-24 22:07:37 (DEBUG):    [ORDER] statusChange: FILLED
2019-03-24 22:07:39 (INFO):     [ORDER] summary: { price: 135.91,
  amount: 9.61692,
  date:
   Moment {
     _isAMomentObject: true,
     _i: 1553465256060,
     _isUTC: false,
     _pf:
      { empty: false,
        unusedTokens: [],
        unusedInput: [],
        overflow: -2,
        charsLeftOver: 0,
        nullInput: false,
        invalidMonth: null,
        invalidFormat: false,
        userInvalidated: false,
        iso: false,
        parsedDateParts: [],
        meridiem: null,
        rfc2822: false,
        weekdayMismatch: false },
     _locale:
      Locale {
        _calendar: [Object],
        _longDateFormat: [Object],
        _invalidDate: 'Invalid date',
        ordinal: [Function: ordinal],
        _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
        _relativeTime: [Object],
        _months: [Array],
        _monthsShort: [Array],
        _week: [Object],
        _weekdays: [Array],
        _weekdaysMin: [Array],
        _weekdaysShort: [Array],
        _meridiemParse: /[ap]\.?m?\.?/i,
        _abbr: 'en',
        _config: [Object],
        _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/ },
     _d: 2019-03-24T22:07:36.060Z,
     _isValid: true },
  side: 'sell',
  orders: 1,
  fees: { BNB: 0.05722519 },
  feePercent: 0.00075 }
2019-03-24 22:07:39 (DEBUG):    syncing private data
2019-03-24 22:08:20 (INFO):     (ROUNDTRIP) entry date (UTC)    exit date (UTC)         exposed duration        P&L
        profit
2019-03-24 22:08:20 (INFO):     (ROUNDTRIP) 2019-03-24 11:22    2019-03-24 22:07        11 hours                -6.
92      -0.50
2019-03-24 22:08:21 (INFO):     (PROFIT REPORT) original balance:                1374.63421451 USDT
2019-03-24 22:08:21 (INFO):     (PROFIT REPORT) current balance:                 1376.80003211 USDT
2019-03-24 22:08:21 (INFO):     (PROFIT REPORT) profit:                          2.16581760 USDT (0.15755592%)
```

**Comment by Subway4711** [comment]
same here with Binance. Some Trades he counts, most not. 
Papertrader is running without any issue. 

![1](https://user-images.githubusercontent.com/48947547/55137125-6ff33280-5130-11e9-9f4e-5cc69e2483a6.PNG)
![2](https://user-images.githubusercontent.com/48947547/55137126-6ff33280-5130-11e9-8d3d-9d11571664ce.PNG)

**Comment by sejamaior** [comment]
Same issue runing on Docker

**Comment by harmitonkana** [comment]
Encountered the same problem. The last trade would not show up on the UI and this is what I found in the log.

![gekko_unknown](https://user-images.githubusercontent.com/3531682/56154072-5bcc8380-5fc0-11e9-8fb3-7fdf25f89f77.PNG)

Trading on Binance.

**Comment by claytonchew** [comment]
I did a further investigation into this case, seems to be a specific issue with Binance.

It happens when the order get filled in full before it could be cancelled, meaning it was not cancelled, hence the Error -2011: Unknown order sent was logged (or 'CANCEL_REJECTED' according to Binance API doc).

There's a patch that has already been included in Gekko to handle this situation in #2328. However, I'm not sure why the trade did not register itself in Gekko UI. Hopefully someone would be able to help figure it out?

**Comment by ghost** [comment]
Hey I get this issue too.

The error seems to occur on Binance. For orders that do not get filled quickly.
In the log output below describes my issue. I am getting it often.
I do not know if the error effects trades AFTER the error but the application still appears to run despite the error. However I have forced it to restart after every time this has happened (which is around 6 times so far in a week).

2019-05-22 18:40:58 (INFO):     Trader Received advice to go long. Buying  POA
2019-05-22 18:40:58 (DEBUG):    Creating order to buy 10815.903222685185 POA
2019-05-22 18:40:58 (DEBUG):    Buy - Predicted variation:  0.8528561945502295
2019-05-22 18:40:58 (DEBUG):    Buy - Predicted variation:  0.7799634016436916
2019-05-22 18:40:58 (DEBUG):    Buy - Predicted variation:  0.6876504127364681
2019-05-22 18:40:58 (DEBUG):    Buy - Predicted variation:  0.5819534880460339
2019-05-22 18:41:05 (DEBUG):    [ORDER] statusChange: SUBMITTED
2019-05-22 18:41:05 (DEBUG):    [ORDER] statusChange: OPEN
2019-05-22 18:41:07 (DEBUG):    [ORDER] statusChange: CHECKING
2019-05-22 18:41:07 (DEBUG):    [ORDER] statusChange: CHECKED
2019-05-22 18:41:09 (DEBUG):    [ORDER] statusChange: CHECKING
#checking for several minutes....
2019-05-22 18:48:25 (DEBUG):    [ORDER] statusChange: CHECKING
2019-05-22 18:48:26 (DEBUG):    [ORDER] statusChange: CHECKED
2019-05-22 18:48:27 (DEBUG):    [ORDER] statusChange: MOVING
2019-05-22 18:48:28 (DEBUG):    [ORDER] statusChange: ERROR
2019-05-22 18:48:28 (ERROR):    [ORDER] Gekko received error from GB: Error -2011: Unknown order sent.
2019-05-22 18:48:28 (DEBUG):    Error: Error -2011: Unknown order sent.
    at /home/mack/gekko/exchange/wrappers/binance.js:101:15
    at Request.request [as _callback] (/home/mack/gekko/exchange/node_modules/binance/lib/rest.js:90:25)
    at Request.self.callback (/home/mack/gekko/exchange/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/mack/gekko/exchange/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/mack/gekko/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by ghost** [comment]
Guys - a fix has been found, and shared in this thread from all3kcis: https://github.com/askmike/gekko/issues/2762
File tweaks must be made to exchange/wrappers/binance.js - see modifications here https://github.com/askmike/gekko/pull/2792/files

**Comment by harmitonkana** [comment]
Thanks for the heads up! This seems to have resolved the issue for me.
