### ISSUE TITLE
Generic Algoritm install on W10 Error -koa lib- (Gekkoga)

### ISSUE THREAD

**Issue by federicorojas11** [askmike/gekko#2767]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** installed gekkoga and run it on windows 10. It opens ok. It connects to server (terminal 1) and opens localhost:3000. Made a default config:
 stratName: 'MACD',
  gekkoConfig: {
    watch: {
      exchange: 'poloniex',
      currency: 'USDT',
      asset: 'BTC'
    },
(already downloaded the localdata)

**Expected result** 

Start running the GA backtesting.

**Actual result** 

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*Transcription of terminal 1 below:
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
$ node run -c config/my-config.js
No previous run data, starting from scratch!
Starting GA with epoch populations of 20, running 5 units at a time!

st-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\user\Desktop\gekko\node_modu
les\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\user\Desktop\gekko\node_modules\request\r
equest.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\request\req
uest.js:1157:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\req
uest\request.js:1079:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',
  options:
   { url: 'http://localhost:3000/api/backtest',
     json: true,
     body:
*(... all the body content here. I omited this part on this transcription.)
*
*
(...)    toJSON: [Function: responseToJSON],
        caseless: Caseless { dict: [Object] },
         body: 'Internal Server Error' } }
 

Error on C:\Users\user\Desktop\gekko\node_modules\koa\lib\  (i gess...)
  

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*Full transcription of terminal 2 below (where the Error appears):
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

node server.js –max-old-space-size=8192
Serving Gekko UI on http://localhost:3000/

  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 5ms 2b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 6,453ms 95.02kb
  <-- POST /api/backtest
  <-- POST /api/backtest
  <-- POST /api/backtest
  <-- POST /api/backtest
  <-- POST /api/backtest
  xxx POST /api/backtest 500 4,819ms -

  Error: non-error thrown:
   ERROR: TypeError: Cannot read property 'prototype' of undefined

      at Object.onerror (C:\Users\user\Desktop\gekko\node_modules\koa\lib\contex
t.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  xxx POST /api/backtest 500 4,959ms -

  Error: non-error thrown:
   ERROR: TypeError: Cannot read property 'prototype' of undefined

      at Object.onerror (C:\Users\user\Desktop\gekko\node_modules\koa\lib\contex
t.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  xxx POST /api/backtest 500 4,934ms -

  Error: non-error thrown:
   ERROR: TypeError: Cannot read property 'prototype' of undefined

      at Object.onerror (C:\Users\user\Desktop\gekko\node_modules\koa\lib\contex
t.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  xxx POST /api/backtest 500 4,920ms -

  Error: non-error thrown:
   ERROR: TypeError: Cannot read property 'prototype' of undefined

      at Object.onerror (C:\Users\user\Desktop\gekko\node_modules\koa\lib\contex
t.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

uncaughtException TypeError: Cannot read property 'prototype' of undefined
    at inherits (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\sqlite3.js
:27:16)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\
sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\plugins\sqlite\handle.js:
21:33)
uncaughtException TypeError: Cannot read property 'prototype' of undefined
    at inherits (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\sqlite3.js
:27:16)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\
sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\plugins\sqlite\handle.js:
21:33)
uncaughtException TypeError: Cannot read property 'prototype' of undefined
    at inherits (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\sqlite3.js
:27:16)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\
sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\plugins\sqlite\handle.js:
21:33)
uncaughtException TypeError: Cannot read property 'prototype' of undefined
    at inherits (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\sqlite3.js
:27:16)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\
sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\plugins\sqlite\handle.js:
21:33)
  xxx POST /api/backtest 500 4,957ms -

  Error: non-error thrown:
   ERROR: TypeError: Cannot read property 'prototype' of undefined

      at Object.onerror (C:\Users\user\Desktop\gekko\node_modules\koa\lib\contex
t.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

uncaughtException TypeError: Cannot read property 'prototype' of undefined
    at inherits (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\sqlite3.js
:27:16)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\node_modules\sqlite3\lib\
sqlite3.js:66:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko\plugins\sqlite\handle.js:
21:33)

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

I tried instaling talib lib, reinstalling netFrameworks, reinstalling windows-tools-buils, and some other things... This is my first issue. Can you help me solving this?

**Comment by federicorojas11** [comment]
Solved reinstalling gekko. Closing this issue.
