### ISSUE TITLE
TypeError: msecs must be a number

### ISSUE THREAD

**Issue by Darksoulsong** [askmike/gekko#277]
Node version: 0.12.2
NPM version: 2.7.4
Gekko version: 0.1.2

I'm getting this error everytime I try to initialize the bot. I have enabled the mailer plugin. 

timers.js:156
    throw new TypeError('msecs must be a number');
          ^
TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:156:11)
    at TLSSocket.Socket.setTimeout (net.js:337:12)
    at new SMTPResponse (c:\SandBox\gekko\node_modules\emailjs\smtp\response.js:67:11)
    at Object.exports.monitor (c:\SandBox\gekko\node_modules\emailjs\smtp\response.js:72:9)
    at Object.SMTP.connect (c:\SandBox\gekko\node_modules\emailjs\smtp\smtp.js:173:35)
    at Object.Client._connect (c:\SandBox\gekko\node_modules\emailjs\smtp\client.js:68:17)
    at Object.Client._poll (c:\SandBox\gekko\node_modules\emailjs\smtp\client.js:28:18)
    at c:\SandBox\gekko\node_modules\emailjs\smtp\client.js:102:21
    at Object.Message.valid (c:\SandBox\gekko\node_modules\emailjs\smtp\message.js:140:10)
    at Object.Client.send (c:\SandBox\gekko\node_modules\emailjs\smtp\client.js:83:14)

Process finished with exit code 1

**Comment by Darksoulsong** [comment]
After some debugging I was able to find the problem:
In "../smtp/response.js", the function being returned is not passing all the arguments.

I had to change it to:

    exports.monitor = function(/* stream */)
    {
    	return new SMTPResponse(arguments[0], arguments[1], arguments[2]);
    };

Everything is fine now.
