### ISSUE TITLE
Issue with install tulind

### ISSUE THREAD

**Issue by YuriyTigiev** [askmike/gekko#2800]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)

Install tulind
```
ytigiev@ytigiev-VirtualBox:~/gekko$ sudo npm install tulind --no-save
```

**Expected result** (what you hoped would happen)
Failed installation

**Actual result** (unexpected outcome)

```
ytigiev@ytigiev-VirtualBox:~/gekko$ sudo npm install tulind --no-save

> tulind@0.8.15 install /home/ytigiev/gekko/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for tulind@0.8.15 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/ytigiev/gekko/node_modules/tulind/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ytigiev/gekko/node_modules/tulind/build'
gyp ERR! System Linux 5.0.0-17-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64/tulind.node" "--module_name=tulind" "--module_path=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/ytigiev/gekko/node_modules/tulind
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64/tulind.node --module_name=tulind --module_path=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ytigiev/gekko/node_modules/tulind/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.0.0-17-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ytigiev/gekko/node_modules/tulind/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ytigiev/gekko/node_modules/tulind
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64/tulind.node --module_name=tulind --module_path=/home/ytigiev/gekko/node_modules/tulind/lib/binding/Release/node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.15 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tulind@0.8.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ytigiev/.npm/_logs/2019-06-23T19_19_29_898Z-debug.log
ytigiev@ytigiev-VirtualBox:~/gekko$ sudo node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@12.4.0 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: gekko package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:216:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/local/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:774:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:641:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
node-pre-gyp ERR! System Linux 5.0.0-17-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ytigiev/gekko
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
gekko package.json is not node-pre-gyp ready:
package.json must declare these properties: 
main
binary.module_name
binary.module_path
binary.host
ytigiev@ytigiev-VirtualBox:~/gekko$ 

```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by IAMtheIAM** [comment]
Hello @YuriyTigiev  It appears you are attempting to install the latest version which is 0.8.15. I suggest you try installing the tested version of tulind@0.8.7

Run this command:
`npm i tulind@0.8.7 --production`

And see if it works.
