### ISSUE TITLE
not showing market exchanges ,currency ,assest none of at all.

### ISSUE THREAD

**Issue by Ksdbdex1998** [askmike/gekko#2809]
not showing market exchanges ,currency ,assest none of at all. in web broswer changed all the broswers in chrome iE
![Uploading Capture.PNG…]()

**Comment by mastermyx** [comment]
xxx GET /api/exchanges 500 1ms -

  TypeError: _.last(...).join is not a function
      at exchangesDir.filter.f (/Users/arthur/Desktop/gekko-develop/web/routes/exchanges.js:17:31)
      at Array.filter (<anonymous>)
      at Object.module.exports (/Users/arthur/Desktop/gekko-develop/web/routes/exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (/Users/arthur/Desktop/gekko-develop/node_modules/koa-router/lib/router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (/Users/arthur/Desktop/gekko-develop/node_modules/co/index.js:65:19)

**Comment by Ksdbdex1998** [comment]
how to fix this error i am non-technical one

**Comment by Ksdbdex1998** [comment]
is 

> xxx GET /api/exchanges 500 1ms -
> 
> TypeError: _.last(...).join is not a function
> at exchangesDir.filter.f (/Users/arthur/Desktop/gekko-develop/web/routes/exchanges.js:17:31)
> at Array.filter ()
> at Object.module.exports (/Users/arthur/Desktop/gekko-develop/web/routes/exchanges.js:17:6)
> at module.exports.next ()
> at Object.dispatch (/Users/arthur/Desktop/gekko-develop/node_modules/koa-router/lib/router.js:334:5)
> at dispatch.next ()
> at onFulfilled (/Users/arthur/Desktop/gekko-develop/node_modules/co/index.js:65:19)

is it this in techinical language the error

**Comment by mastermyx** [comment]
Hello, i have the same error. This is the log from terminal if someone can help us

**Comment by IAMtheIAM** [comment]
I suggest you guys try running `npm install --only=production from the root of the project. It looks like your `node_modules` are messed up or missing.

**Comment by Ksdbdex1998** [comment]
> I suggest you guys try running `npm install --only=production from the root of the project. It looks like your `node_modules` are messed up or missing.

Done that brother still its showing up that error

**Comment by IAMtheIAM** [comment]
Can you try node v8.16.0 and tell me the results?

**Comment by ChrisRyuGS** [comment]
@IAMtheIAM  After downgrade to 8.12.0 (8.16.0 is not registered in brew) still has same problem.

**Comment by IAMtheIAM** [comment]
Did you clear the node_modules folder completely in the project root and in /exchanges? and then attempt to run the npm install again? 

Your node_modules are messed up.

**Comment by Ksdbdex1998** [comment]
Issue solved first downgrade to 8.16 node js you can find in previous versions of node js .org website then install git and add path to the cmd option tick while trying to install git.
while installing gekko install npm install --only=production in gekko folder and also install in exchange folder navigate to exchange folder : command cd exchange
then again run npm install --only=production .hola problem solved  worked for me try it

**Comment by ChrisRyuGS** [comment]
@Ksdbdex1998 @IAMtheIAM  After downgrade to node 8.16.0, deleting node_modules folder and npm install only=production, the problem is gone.
I think my problem is caused by upgrading node version but geeko using lodash 2.x is not compatible with node 10.

**Comment by IAMtheIAM** [comment]
@Ksdbdex1998 and @ChrisRyuGS  I'm glad you guys got it running and that I could help. This issue can be closed now.
