### ISSUE TITLE
Unhandled rejection Error: Command failed 

### ISSUE THREAD

**Issue by nathanp83** [askmike/gekko#2821]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[x] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
Following the install procedure:
cd exchange
npm install --only=production

**Expected result** (what you hoped would happen)
No errors

**Actual result** (unexpected outcome)
```
npm install --only=production
Unhandled rejection Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/askmike/npm-kraken-api.git /home/blah/.npm/_cacache/tmp/git-clone-2ad68429
/home/blah/.npm/_cacache/tmp/git-clone-2ad68429/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)
When attempting to start live trading:
```
2019-07-09 10:52 Gekko 2019-07-09-10-52-tradebot-85466106566401 started.
  --> POST /api/startGekko 200 80ms 1.85kb

The following Gekko Broker dependencies are not installed: [ kraken-api ].

You need to install them first, read here how: https://gekko.wizb.it/docs/installation/installing_gekko.html#Installing-Gekko-39-s-dependencies

RECEIVED ERROR IN GEKKO INSTANCE 2019-07-09-10-52-tradebot-85466106566401
Child process has died.
```

**Comment by nathanp83** [comment]
I resolved that error by manually doing it.

cd exchange
sudo git clone git://github.com/askmike/npm-kraken-api.git

then
sudo npm install npm-kraken-api
+ kraken-api@1.0.0
updated 1 package and audited 10831 packages in 3.995s
found 0 vulnerabilities
