### ISSUE TITLE
 Unexpected token u

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#284]
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (C:\Users\Pascal\Desktop\gekko-github\node_modules\cryp
tsy-api\cryptsy.js:53:27)
    at self.callback (C:\Users\Pascal\Desktop\gekko-github\node_modules\cryptsy-
api\node_modules\request\request.js:198:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (C:\Users\Pascal\Desktop\gekko-github\node_modules
\cryptsy-api\node_modules\request\request.js:861:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1455:17)
    at Socket.emit (events.js:117:20)

**Comment by askmike** [comment]
cryptsy is kaput!
