### ISSUE TITLE
Sell orders are failing, looks like no (status === 'rejected') on coinbase pro anymore

### ISSUE THREAD

**Issue by vqalex** [askmike/gekko#2849]
2019-09-16T10:12:11.173Z 'HTTP 400 Error: Post only mode'
{ sellParams: 
   { price: '573.1',
     size: '3.337',
     product_id: 'ETH-USD',
     post_only: true,
     side: 'sell' } } 'HTTP 400 Error: Post only mode'
2019-09-16T12:12:14.678Z '[sticky order] FATAL ERROR' 'HTTP 400 Error: Post only mode'
2019-09-16T12:12:14.678Z { Error: HTTP 400 Error: Post only mode
    at Request._callback (/media/veracrypt1/gekko/exchange/node_modules/gdax/lib/clients/public.js:68:15)
    at Request.self.callback (/media/veracrypt1/gekko/exchange/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/media/veracrypt1/gekko/exchange/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/media/veracrypt1/gekko/exchange/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by vqalex** [comment]
I'm trying to adjust a few things to see if it will help to recognize that "HTTP 400 Error: Post only mode" error. & retry.
