### ISSUE TITLE
Gekko does not support the exchange btc-e

### ISSUE THREAD

**Issue by ciseugene** [askmike/gekko#285]
C:\Users\Administrator\Desktop\gekko-master>node gekko
2015-07-30 08:21:03 (INFO):     Gekko v0.1.2 started
2015-07-30 08:21:03 (INFO):     I'm gonna make you rich, Bud Fox.

2015-07-30 08:21:03 (INFO):     Using config file: C:\Users\Administrator\Deskto
p\gekko-master\config.js

Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.12.7

Error:

Gekko does not support the exchange btc-e

node.js:609
        throw new TypeError('invalid pid');
              ^
TypeError: invalid pid
    at process.kill (node.js:609:15)
    at Object.util.die (C:\Users\Administrator\Desktop\gekko-master\core\util.js
:141:13)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\gekko-master\gekko.js:
88:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\Users\Administrator\Desktop\gekko-master>

**Comment by zerogods** [comment]
Please use 
>> exchange: 'btce'

**Comment by ciseugene** [comment]
it's work! Thank you so much!
