### ISSUE TITLE
Program Crash when attempting to create an order

### ISSUE THREAD

**Issue by hashpower** [askmike/gekko#286]
Hi,
I have been trying to run this program and allow it to create trades. i think that everytime it tries to create it crashes with the following:

C:\Bitbot\core\portfolioManager.js:108
  return this.getFund(fund).amount;
                           ^
TypeError: Cannot read property 'amount' of undefined
    at Manager.getBalance (C:\Bitbot\core\portfolioManager.js:108:28)
    at bound [as getBalance] (C:\Bitbot\node_modules\lodash\dist\lodash.js:729:21)
    at act (C:\Bitbot\core\portfolioManager.js:130:26)
    at bound (C:\Bitbot\node_modules\lodash\dist\lodash.js:729:21)
    at C:\Bitbot\node_modules\async\lib\async.js:232:13
    at C:\Bitbot\node_modules\async\lib\async.js:142:25
    at C:\Bitbot\node_modules\async\lib\async.js:229:17
    at C:\Bitbot\node_modules\async\lib\async.js:556:34
    at set (C:\Bitbot\core\portfolioManager.js:78:7)
    at bound (C:\Bitbot\node_modules\lodash\dist\lodash.js:729:21)
21 Aug 02:01:22 - [nodemon] app crashed - waiting for file changes before starting...
21 Aug 08:17:04 - [nodemon] restarting due to changes...
21 Aug 08:17:04 - [nodemon] starting `node gekko.js`
2015-08-21 08:17:05 (INFO):     Gekko v0.1.2 started
2015-08-21 08:17:05 (INFO):     I'm gonna make you rich, Bud Fox.

when do i need to set the amount?
thanks

**Comment by hashpower** [comment]
anyone

**Comment by horsecoin** [comment]
My Cexio bot had this same issue. The thing was once I fixed one error, it would throw another, and another.   Eventually I decided I better make a fork to keep all my edits together, link below, check out the changes I made below to get it to work.
https://github.com/horsecoin/gekko/commit/dd70d024fdaf63868a732142707c09e78dbd99ef

**Comment by askmike** [comment]
what exchange is this? Regardless it should be fixed in gekko 0.2.
