### ISSUE TITLE
Instantly crashing when using data set. (TypeError: done is not a function)

### ISSUE THREAD

**Issue by hesa2020** [askmike/gekko#2877]
Hello i tried making a new Exchange/Importer for Alpaca ( Not a crypto exchange but i think it should work just fine ).

However after importer data and trying to use it i get this crash:

/Users/sylvainmartens/Desktop/gekko/core/workers/datasetScan/parent.js:50
        done(err, resp);
        ^

TypeError: done is not a function
    at async.eachLimit.err (/Users/sylvainmartens/Desktop/gekko/core/workers/datasetScan/parent.js:50:9)
    at /Users/sylvainmartens/Desktop/gekko/node_modules/async/dist/async.js:484:16
    at iterateeCallback (/Users/sylvainmartens/Desktop/gekko/node_modules/async/dist/async.js:1013:24)
    at /Users/sylvainmartens/Desktop/gekko/node_modules/async/dist/async.js:988:16
    at dateRangeScan (/Users/sylvainmartens/Desktop/gekko/core/workers/datasetScan/parent.js:34:9)
    at ForkTask.task.once.ranges (/Users/sylvainmartens/Desktop/gekko/core/workers/dateRangeScan/parent.js:15:12)
    at ForkTask.listener (/Users/sylvainmartens/Desktop/gekko/node_modules/eventemitter2/lib/eventemitter2.js:264:10)
    at ForkTask.EventEmitter.emit (/Users/sylvainmartens/Desktop/gekko/node_modules/eventemitter2/lib/eventemitter2.js:328:19)
    at ForkTask.IPCEE.onmessage (/Users/sylvainmartens/Desktop/gekko/node_modules/ipcee/index.js:84:15)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
disconnect

Im linking my Exchange script and my Importer script right here.
If anyone can point to me what im doing wrong of what i need to do to fix that issue would be really appreciated.

https://hastebin.com/sumoyayetu.js

https://hastebin.com/liwuciwora.js

**Comment by hesa2020** [comment]
My bad idk why i got an old version i downloaded lates stable.
