### ISSUE TITLE
Error: non-error thrown: ERROR: Talib is not enabled

### ISSUE THREAD

**Issue by masspar** [askmike/gekko#2890]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[X ] bug report
[ ] question about the decisions made in the repository

**Action taken** (what you did)
I tried to install Talib with this command "npm install tulind --no-save" but I get an error. I followed these "TAlib not enabled error # 2777" instructions but it didn't work for me. When I try to execute a strategy that contains the Talib indicator, gekko returns the following error:

**Expected result** (what you hoped would happen)
The strategy to execute

**Actual result** (unexpected outcome)
I get the error:

Error: non-error thrown:
   ERROR: Talib is not enabled

      at Object.onerror (/home/max/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
uncaughtException TypeError: Cannot read property 'ema' of null
    at AsyncIndicatorRunner.addTalibIndicator (/home/max/gekko/plugins/tradingAdvisor/asyncIndicatorRunner.js:126:15)
    at Base.addTalibIndicator (/home/max/gekko/plugins/tradingAdvisor/baseTradingMethod.js:222:29)
    at Base.bound [as addTalibIndicator] (/home/max/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.method.init (/home/max/gekko/strategies/EMACrossover.js:30:8)
    at Base.bound [as init] (/home/max/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/max/gekko/plugins/tradingAdvisor/baseTradingMethod.js:69:8)
    at Actor.setupStrategy (/home/max/gekko/plugins/tradingAdvisor/tradingAdvisor.js:61:19)
    at Actor.bound [as setupStrategy] (/home/max/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/home/max/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/home/max/gekko/core/pluginUtil.js:98:22)

Gekko version: v0.6.8
Nodejs version: v8.17.0

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm making the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm marking the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
