### ISSUE TITLE
Unable to see the functionality of any page  

### ISSUE THREAD

**Issue by Vardaan100** [askmike/gekko#2891]
![Screenshot (2)](https://user-images.githubusercontent.com/59680064/74402159-72926f80-4e49-11ea-95b8-9ce47bdfdda2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/59680064/74402260-b5544780-4e49-11ea-9c16-bed39d7707c2.png)

**Comment by Vardaan100** [comment]
C:\Projects\Watch-Me-Build-a-Trading-Bot>node gekko --ui

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.6.8
        I'm gonna make you rich, Bud Fox.


Serving Gekko UI on http://localhost:3000/

  <-- GET /favicon.ico
  --> GET /favicon.ico 404 4ms -
  <-- GET /api/imports
  --> GET /api/imports 200 2ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 24ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\exchanges.js:17:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  xxx GET /api/strategies 500 5ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 19ms 152b
  --> GET /api/configPart/paperTrader 200 14ms 148b
  <-- POST /api/scansets
  --> POST /api/scansets 200 2,275ms 27b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  --> GET /api/configPart/performanceAnalyzer 200 2ms 152b
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 1ms 148b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 13ms 152b
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 2ms 148b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  xxx GET /api/strategies 500 3ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 8ms 152b
  --> GET /api/configPart/paperTrader 200 5ms 148b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 9ms 152b
  --> GET /api/configPart/paperTrader 200 9ms 148b
  <-- POST /api/scansets
  --> POST /api/scansets 200 4ms 27b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 6ms 152b
  --> GET /api/configPart/paperTrader 200 5ms 148b
  <-- GET /api/configPart/candleWriter
  --> GET /api/configPart/candleWriter 200 3ms 49b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/performanceAnalyzer 200 4ms 152b
  xxx GET /api/strategies 500 4ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/paperTrader 200 5ms 148b
  <-- GET /api/strategies
  xxx GET /api/strategies 500 3ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  <-- GET /api/configPart/paperTrader
  xxx GET /api/strategies 500 2ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  --> GET /api/configPart/performanceAnalyzer 200 5ms 152b
  --> GET /api/configPart/paperTrader 200 3ms 148b
  <-- GET /api/configPart/performanceAnalyzer
  <-- GET /api/strategies
  --> GET /api/configPart/performanceAnalyzer 200 4ms 152b
  xxx GET /api/strategies 500 4ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\strategies.js:9:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

  <-- GET /api/configPart/paperTrader
  --> GET /api/configPart/paperTrader 200 2ms 148b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 1ms 24b
  <-- GET /api/imports
  --> GET /api/imports 200 1ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 1ms 2b
  <-- GET /api/exchanges
  xxx GET /api/exchanges 500 0ms -

  TypeError: _.last(...).join is not a function
      at C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\exchanges.js:17:31
      at Array.filter (<anonymous>)
      at Object.module.exports (C:\Projects\Watch-Me-Build-a-Trading-Bot\web\routes\exchanges.js:17:6)
      at module.exports.next (<anonymous>)
      at Object.dispatch (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\koa-router\lib\router.js:334:5)
      at dispatch.next (<anonymous>)
      at onFulfilled (C:\Projects\Watch-Me-Build-a-Trading-Bot\node_modules\co\index.js:65:19)

**Comment by askmike** [comment]
I am unfortunately not maintaining this project anymore. I'm making the whole repo as read only.

Read more here: https://medium.com/@gekkoplus/archiving-open-source-gekko-dba02e6efc7
