### ISSUE TITLE
 Gekko crashes when processing cex.io trades

### ISSUE THREAD

**Issue by zxpectre** [askmike/gekko#290]
Gekko recently crashed after processing trade history, when it's about to calculate advice. It happened with cex.io exchange. 
I'm using:
*    Lubuntu 64bits
*    node v0.10.25,
*    Gekko v0.1.2,
*    config.js has no custom values other than api keys and exchange setup.

**EDIT: Also happened with other exchanges recently, so it's an exchange independent error and seems also nothing to do with loss of internet conection**

The first caught errors at 2015-11-19 02:03:34 were due a network conectivity loss, but the last critical errors managed to finally crash gekko.

> 2015-11-19 02:03:03 (DEBUG):	Requested GHS/BTC trade data from CEX.io ...
2015-11-19 02:03:34 (DEBUG):	cex.io returned an error, retrying.. { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } waiting for 10000 ms
2015-11-19 02:04:04 (DEBUG):	cex.io returned an error, retrying.. { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' } waiting for 10000 ms
2015-11-19 02:04:51 (DEBUG):	cex.io returned an error, retrying.. { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } waiting for 10000 ms
2015-11-19 02:05:21 (DEBUG):	cex.io returned an error, retrying.. { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' } waiting for 10000 ms
2015-11-19 02:05:51 (DEBUG):	cex.io returned an error, retrying.. { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' } waiting for 10000 ms
2015-11-19 02:06:29 (DEBUG):	cex.io returned an error, retrying.. { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } waiting for 10000 ms
2015-11-19 02:06:59 (DEBUG):	cex.io returned an error, retrying.. { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' } waiting for 10000 ms
2015-11-19 02:07:29 (DEBUG):	cex.io returned an error, retrying.. { [Error: getaddrinfo EADDRINFO] code: 'EADDRINFO', errno: 'EADDRINFO', syscall: 'getaddrinfo' } waiting for 10000 ms
2015-11-19 02:08:14 (DEBUG):	cex.io returned an error, retrying.. { [Error: socket hang up] code: 'ECONNRESET' } waiting for 10000 ms
2015-11-19 02:08:29 (DEBUG):	Fetched 1000 new trades, from 2015-11-17 13:35:41 UTC to 2015-11-19 02:01:36 UTC
2015-11-19 02:08:29 (DEBUG):	minimum trade treshold: 2015-11-19 02:01:36 UTC
2015-11-19 02:08:29 (DEBUG):	done with this batch (1)
2015-11-19 02:08:29 (DEBUG):	Processed trades, sleeping for a minute...
2015-11-19 02:09:17 (DEBUG):	Requested GHS/BTC trade data from CEX.io ...
2015-11-19 02:09:21 (DEBUG):	Fetched 1000 new trades, from 2015-11-17 13:35:41 UTC to 2015-11-19 02:01:36 UTC
2015-11-19 02:09:21 (DEBUG):	minimum trade treshold: 2015-11-19 02:01:36 UTC
2015-11-19 02:09:21 (DEBUG):	done with this batch (1)
2015-11-19 02:09:21 (DEBUG):	Processed trades, sleeping for a minute...
2015-11-19 02:10:09 (DEBUG):	Requested GHS/BTC trade data from CEX.io ...
2015-11-19 02:10:12 (DEBUG):	Fetched 1000 new trades, from 2015-11-17 13:35:55 UTC to 2015-11-19 02:09:29 UTC
2015-11-19 02:10:12 (DEBUG):	minimum trade treshold: 2015-11-19 02:01:36 UTC
2015-11-19 02:10:12 (DEBUG):	processing 1 trade(s)
2015-11-19 02:10:12 (DEBUG):	from 2015-11-19T02:09:29+00:00 to 2015-11-19T02:09:29+00:00
2015-11-19 02:10:12 (DEBUG):	Skipping creation of already loaded database 2015-11-19
2015-11-19 02:10:12 (DEBUG):	inserting candle 121 (2015-11-19 02:01:00 UTC) volume: 68.98050563
2015-11-19 02:10:12 (DEBUG):	inserting candle 122 (2015-11-19 02:02:00 UTC) volume: 0
2015-11-19 02:10:12 (DEBUG):	inserting candle 123 (2015-11-19 02:03:00 UTC) volume: 0
2015-11-19 02:10:12 (DEBUG):	inserting candle 124 (2015-11-19 02:04:00 UTC) volume: 0
2015-11-19 02:10:12 (DEBUG):	inserting candle 125 (2015-11-19 02:05:00 UTC) volume: 0
2015-11-19 02:10:12 (INFO):	We have all required history, going to calculate advice from this point.
> 
> /home/lubuntu/Documents/gekko/gekko/core/candleManager.js:560
  this.days[mom.dayString].handle.find({
>                                   ^
> TypeError: Object false has no method 'find'
    at Manager.getCandles (/home/lubuntu/Documents/gekko/gekko/core/candleManager.js:560:35)
    at bound [as getCandles] (/home/lubuntu/Documents/gekko/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at iterator (/home/lubuntu/Documents/gekko/gekko/core/candleManager.js:516:10)
    at bound (/home/lubuntu/Documents/gekko/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/lubuntu/Documents/gekko/gekko/node_modules/async/lib/async.js:227:13
    at /home/lubuntu/Documents/gekko/gekko/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/home/lubuntu/Documents/gekko/gekko/node_modules/async/lib/async.js:32:24)
    at async.each (/home/lubuntu/Documents/gekko/gekko/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/home/lubuntu/Documents/gekko/gekko/node_modules/async/lib/async.js:226:9)

**Comment by askmike** [comment]
this is fixed in 0.2
