### ISSUE TITLE
Gekko crash when Trader enable

### ISSUE THREAD

**Issue by victor95pc** [askmike/gekko#293]
exchange: 'bitfinex'

Gekko encountered an error and can't continue

Meta debug info:

Gekko version: v0.1.2
Nodejs version: v0.12.7

Error:

Do you understand what Gekko will do with your money? Read this first:

https://github.com/askmike/gekko/issues/201

node.js:609
        throw new TypeError('invalid pid');
              ^
TypeError: invalid pid
    at process.kill (node.js:609:15)
    at Object.util.die (/home/pi/gekko/core/util.js:141:13)
    at Object.<anonymous> (/home/pi/gekko/gekko.js:68:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by askmike** [comment]
With what exchange did you experience this? The whole API communication flow has been rewritten so this has most likely been fixed. Please comment here if it's not.
