### ISSUE TITLE
Cannot find module './lib/datastore'

### ISSUE THREAD

**Issue by hhansx** [askmike/gekko#295]
> 2016-03-03 12:53:59 (INFO): Setting up:
2016-03-03 12:53:59 (INFO):   Profit Simulator
2016-03-03 12:53:59 (INFO):   Paper trader that logs fake profits.

>module.js:341
    throw err;
    ^

>Error: Cannot find module './lib/datastore'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/gekko/node_modules/nedb/index.js:1:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

freshly installed Raspberry Pi 2B running raspian

**Comment by hhansx** [comment]
reinstalled gekko solved it
