### ISSUE TITLE
another crashing thread ( btce )

### ISSUE THREAD

**Issue by topher2880** [askmike/gekko#300]
Alot of threads about Gekko crashing. Mine will crash every single day, multiple times, and always on a trade. Occasionally it will buy or sell and continue on, but mostly it crashes as soon as its send the signal.

This is my latest error, not sure of previous ones as I havent copied them.
*ive also had to set my "trade percent" to zero to get it to do anything.. not sure if this is why its crashing but it always crashed on 1 as well..

Any ideas would be greatly appreciated.

2016-05-26 13:19:43 (INFO):	Attempting too BUY 0.33645477517113603 BTC at BTC-E
2016-05-26 13:20:18 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
/home/pi/gekko/node_modules/btc-e/btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                 ^

TypeError: Cannot assign to read only property 'nonce' of 1085583055
    at BTCE.makeRequest (/home/pi/gekko/node_modules/btc-e/btc-e.js:46:18)
    at BTCE.orderList (/home/pi/gekko/node_modules/btc-e/btc-e.js:126:8)
    at Trader.cancelOrder (/home/pi/gekko/exchanges/btce.js:143:13)
    at bound [as cancelOrder] (/home/pi/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at finish (/home/pi/gekko/core/portfolioManager.js:293:21)
    at bound (/home/pi/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at check (/home/pi/gekko/exchanges/btce.js:134:7)
    at bound (/home/pi/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Request._callback (/home/pi/gekko/node_modules/btc-e/btc-e.js:82:5)
    at Request.self.callback (/home/pi/gekko/node_modules/btc-e/node_modules/request/request.js:121:22)

**Comment by askmike** [comment]
This has finally been fixed, please download a new version of Gekko.
