### ISSUE TITLE
TypeError: Cannot read property 'sqlite' of undefined

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#329]
Hi,

I have gekko running in an ARM device and all went well till  a few days ago from when I started to get the error stated in the title.
Here is a CP of the response:

`/media/xx/16G/gekko/plugins/sqlite/handle.js:8

var adapter = config.adapters.sqlite;
                                               ^
TypeError: Cannot read property 'sqlite' of undefined
    at Object.<anonymous> (/media/xx/16G/gekko/plugins/sqlite/handle.js:8:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/media/xx/16G/gekko/plugins/sqlite/reader.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
`
Can't get the code to paste correctly, but the error is is on .sqlite in the config.adapter variable.

Can anyone help me on that?

For info: I had to build sqlite3 as the version in packages manager were too old. Nevertheless it was working till a few days ago.

Thx for the help it appreciated!

**Comment by askmike** [comment]
I've updated the config structure, so the reason you are getting this is because you are running an up-to-date gekko but the config you are using is out of date (I haven't figured out a clean way to overcome this yet).

Please recreate your config based on the new `sample-config.js`. If you run into anything else, let me know!

**Comment by ghost** [comment]
Up and running smoothly again! Thx for your help!
