### ISSUE TITLE
Creating ne indicator from talib

### ISSUE THREAD

**Issue by hoddy** [askmike/gekko#365]
I've been trying to add another indicator from the talib library, ive gotten a bit stuck maybe you could help?

I added this to my config.js:

```
config['talib-adx']` = {
  // Time Period
  parameters: 10,
  thresholds: {
    down: -0.025,
    up: 0.025,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 1
  }
```

and then I basicly copyed the talibMACD and added talib-adx.js file to /methods:

```
var config = require('../core/util.js').getConfig();
var settings = config['talib-adx'];

// Let's create our own method
var method = {};

// Prepare everything our method needs
method.init = function() {
  this.name = 'talib-adx'
  // keep state about the current trend
  // here, on every new candle we use this
  // state object to check if we need to
  // report it.
  this.trend = {
    direction: 'none',
    duration: 0,
    persisted: false,
    adviced: false
  };

  // how many candles do we need as a base
  // before we can start giving advice?
  this.requiredHistory = config.tradingAdvisor.historySize;

  var customADXSettings = settings.parameters;

  // define the indicators we need
  this.addTalibIndicator('adx', 'adx', customADXSettings);
}

// What happens on every new candle?
method.update = function(candle) {
  // nothing!
}


method.log = function() {

}

// Based on the newly calculated
// information, check if we should
// update or not.
method.check = function() {
  var price = this.lastPrice;
  var result = this.talibIndicators.adx.result;
  var adxdiff = result['outReal'];

  if(settings.thresholds.down > adxdiff && this.currentTrend !== 'short') {
    this.currentTrend = 'short';
    this.advice('short');

  } else if(settings.thresholds.up < adxdiff && this.currentTrend !== 'long'){
    this.currentTrend = 'long';
    this.advice('long');

  }
}

module.exports = method;

```

I found the "outReal" output in the ta_ADX.c file so I'm assuming thats right. When I run Gekko I get the following output: 

```
2016-07-03 15:40:33 (INFO):      
2016-07-03 15:40:33 (INFO): Setting up:
2016-07-03 15:40:33 (INFO):      Profit Simulator
2016-07-03 15:40:33 (INFO):      Paper trader that logs fake profits.
2016-07-03 15:40:33 (INFO): 

2016-07-03 15:40:33 (INFO): Starting to watch the market: BTC-e /
/home/dave/gekko/core/baseTradingMethod.js:174
      args.unshift(closePrices);
           ^

TypeError: args.unshift is not a function
    at Object.talibIndicators.(anonymous function)._fn (/home/dave/gekko/core/baseTradingMethod.js:174:12)
    at null.<anonymous> (/home/dave/gekko/core/baseTradingMethod.js:142:9)
    at /home/dave/gekko/node_modules/lodash/dist/lodash.js:901:23
    at forOwn (/home/dave/gekko/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/home/dave/gekko/node_modules/lodash/dist/lodash.js:3303:9)
    at Base.tick (/home/dave/gekko/core/baseTradingMethod.js:141:7)
    at bound [as tick] (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/dave/gekko/plugins/tradingAdvisor.js:173:15)
    at bound (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:77:13)
```

I know that the talib-ADX needs high, low and close price to run, am i right in thinking that the error is because I'm not passing the close price to talib correctly?

**Comment by wupeng1211** [comment]
this.asyncTick = false;

```
this.openPrices = [];
this.highPrices = [];
this.lowPrices = [];
this.closePrices = [];
this.volume = [];
this.vwprice = [];
```

.....

Base.prototype.tick = function(candle) {
  this.age++;
  this.candle = candle;

```
this.openPrices.push(candle.open);
this.highPrices.push(candle.high);
this.lowPrices.push(candle.low);
this.closePrices.push(candle.close);
this.volume.push(candle.volume);
this.vwprice.push(candle.vwprice);

if (this.age > 1000) {
    this.openPrices.shift();
    this.highPrices.shift();
    this.lowPrices.shift();
    this.closePrices.shift();
    this.volume.shift();
    this.vwprice.shift();
}
```

.
.
. _.each(this.talibIndicators, function(i) {
            i._fn(this.openPrices, this.highPrices, this.lowPrices, this.closePrices, this.volume, this.vwprice, next);
        }, this);
.
...
 // TODO: cleanup..
  this.talibIndicators[name] = {
    _params: parameters,
    _fn: function(openPrices, highPrices, lowPrices, closePrices, volume, vwprice, done) {

```
        var args = []
        for (x in parameters) {
            if (parameters[x] === 'OPEN' || parameters[x] === 'O') {
                args.push(openPrices);
            } else if (parameters[x] === 'HIGH' || parameters[x] === 'H') {
                args.push(highPrices);
            } else if (parameters[x] === 'LOW' || parameters[x] === 'L') {
                args.push(lowPrices);
            } else if (parameters[x] === 'CLOSE' || parameters[x] === 'C') {
                args.push(closePrices);
            } else if (parameters[x] === 'VOLUME' || parameters[x] === 'V') {
                args.push(volume);
            } else if (parameters[x] === 'VWPRICE' || parameters[x] === 'VP') {
                args.push(vwprice);
            } else {
                args.push(parameters[x]);
            }
        }

  talib[type].apply(this, args)(function(err, result) {
    if(err)
      util.die('TALIB ERROR:', err);

    this.result = _.mapValues(result, function(a) { return  _.last(a) ; });
    done();
  }.bind(this));
},
result: NaN
```

  }

**Comment by wupeng1211** [comment]
```
this.result = _.mapValues(result, function(a) { return  a ; });
```

另外我建议这里不要只返回最后一个值

**Comment by hoddy** [comment]
Thank you i will try and work this out ,all the pieces are here i just need to put them together thanks.

**Comment by hoddy** [comment]
Thanks Wupeng1211, I've updated baseTradingMethod.js as follows:

```
var _ = require('lodash');
var util = require('../core/util.js');
var config = util.getConfig();
var dirs = util.dirs();
var log = require('../core/log.js');

if(config.tradingAdvisor.talib.enabled) {
  // verify talib is installed properly
  var pluginHelper = require(dirs.core + 'pluginUtil');
  var pluginMock = {
    slug: 'tradingAdvisor',
    dependencies: [{
      module: 'talib',
      version: config.tradingAdvisor.talib.version
    }]
  };

  var cannotLoad = pluginHelper.cannotLoad(pluginMock);
  if(cannotLoad)
    util.die(cannotLoad);

  var talib = require(dirs.core + 'talib');
}

var indicatorsPath = '../methods/indicators/';

var Indicators = {
  MACD: {
    factory: require(indicatorsPath + 'MACD'),
    input: 'price'
  },
  EMA: {
    factory: require(indicatorsPath + 'EMA'),
    input: 'price'
  },
  DEMA: {
    factory: require(indicatorsPath + 'DEMA'),
    input: 'price'
  },
  PPO: {
    factory: require(indicatorsPath + 'PPO'),
    input: 'price'
  },
  LRC: {
    factory: require(indicatorsPath + 'LRC'),
    input: 'price'
  },
  SMA: {
    factory: require(indicatorsPath + 'SMA'),
    input: 'price'
  },

  RSI: {
    factory: require(indicatorsPath + 'RSI'),
    input: 'candle'
  },
  CCI: {
    factory: require(indicatorsPath + 'CCI'),
    input: 'candle'
  }
};

var allowedIndicators = _.keys(Indicators);
var allowedTalibIndicators = _.keys(talib);

var Base = function() {
  _.bindAll(this);

  // properties
  this.age = 0;
  this.setup = false;

  // defaults
  this.requiredHistory = 0;
  this.priceValue = 'close';
  this.indicators = {};
  this.talibIndicators = {};
  this.asyncTick = false;
  this.openPrices = [];
  this.highPrices = [];
  this.lowPrices = [];
  this.closePrices = [];
  this.volume = [];
  this.vwprice = [];

  // make sure we have all methods
  _.each(['init', 'check'], function(fn) {
    if(!this[fn])
      util.die('No ' + fn + ' function in this trading method found.')
  }, this);

  if(!this.update)
    this.update = function() {};

  // let's run the implemented starting point
  this.init();

  // should be set up now, check some things
  // to make sure everything is implemented
  // correctly.
  if(!this.name)
    log.warn('Warning, trading method has no name');

  if(!config.debug || !this.log)
    this.log = function() {};

  this.setup = true;

  if(_.size(this.talibIndicators))
    this.asyncTick = true;
}

// teach our base trading method events
var Util = require('util');
var EventEmitter = require('events').EventEmitter;
Util.inherits(Base, EventEmitter);

Base.prototype.tick = function(candle) {
  this.age++;
  this.candle = candle;

  this.openPrices.push(candle.open);
  this.highPrices.push(candle.high);
  this.lowPrices.push(candle.low);
  this.closePrices.push(candle.close);
  this.volume.push(candle.volume);
  this.vwprice.push(candle.vwprice);

  if (this.age > 1000) {
      this.openPrices.shift();
      this.highPrices.shift();
      this.lowPrices.shift();
      this.closePrices.shift();
      this.volume.shift();
      this.vwprice.shift();
   }
   // remove this??
  //this.closePrices.push(candle.close);
  //if(this.age > 1000) {
  //  this.closePrices.shift();
 // }

  // update all indicators
  var price = candle[this.priceValue];
  _.each(this.indicators, function(i) {
    if(i.input === 'price')
      i.update(price);
    if(i.input === 'candle')
      i.update(candle);
  });

  if(!this.asyncTick || this.requiredHistory > this.age) {
    this.propogateTick();
  } else {
    var next = _.after(
      _.size(this.talibIndicators),
      function() {
        this.propogateTick();
      }.bind(this)
    );

    _.each(this.talibIndicators, function(i) {
    i._fn(this.openPrices, this.highPrices, this.lowPrices, this.closePrices, this.volume, this.vwprice, next);
   }, this);
  }

  // update previous price
  this.lastPrice = price;
}

Base.prototype.propogateTick = function() {
  this.update(this.candle);
  if(this.requiredHistory <= this.age) {
    this.log();
    this.check();
  }
}

Base.prototype.addTalibIndicator = function(name, type, parameters) {
  if(!talib)
    util.die('Talib is not enabled');

  if(!_.contains(allowedTalibIndicators, type))
    util.die('I do not know the talib indicator ' + type);

  if(this.setup)
    util.die('Can only add talib indicators in the init method!');

  // TODO: cleanup..
 this.talibIndicators[name] = {
_params: parameters,
_fn: function(openPrices, highPrices, lowPrices, closePrices, volume, vwprice, done) {

        var args = []
        for (x in parameters) {
            if (parameters[x] === 'OPEN' || parameters[x] === 'O') {
                args.push(openPrices);
            } else if (parameters[x] === 'HIGH' || parameters[x] === 'H') {
                args.push(highPrices);
            } else if (parameters[x] === 'LOW' || parameters[x] === 'L') {
                args.push(lowPrices);
            } else if (parameters[x] === 'CLOSE' || parameters[x] === 'C') {
                args.push(closePrices);
            } else if (parameters[x] === 'VOLUME' || parameters[x] === 'V') {
                args.push(volume);
            } else if (parameters[x] === 'VWPRICE' || parameters[x] === 'VP') {
                args.push(vwprice);
            } else {
                args.push(parameters[x]);
            }
        }

  talib[type].apply(this, args)(function(err, result) {
    if(err)
      util.die('TALIB ERROR:', err);

    this.result = _.mapValues(result, function(a) { return  a ; });
    done();
  }.bind(this));
},
result: NaN

}
}

Base.prototype.addIndicator = function(name, type, parameters) {
  if(!_.contains(allowedIndicators, type))
    util.die('I do not know the indicator ' + type);

  if(this.setup)
    util.die('Can only add indicators in the init method!');

  this.indicators[name] = new Indicators[type].factory(parameters);

  // some indicators need a price stream, others need full candles
  this.indicators[name].input = Indicators[type].input;
}

Base.prototype.advice = function(newPosition) {
  // Possible values are long and short. Long will trigger a buy method
  // while short will trigger a sell method
  var advice = 'soft';
  if(newPosition) {
    advice = newPosition;
  }

  this.emit('advice', {
    recommandation: advice,
    portfolio: 1,
    moment: this.candle.start
  });
}

module.exports = Base;
```

However I now get:

```
2016-07-04 19:02:05 (INFO): Starting to watch the market: BTC-e /
/home/dave/gekko/core/talib.js:71
        endIdx: high.length - 1,
                    ^

TypeError: Cannot read property 'length' of undefined
    at Object.__dirname.adx (/home/dave/gekko/core/talib.js:71:21)
    at Object.talibIndicators.(anonymous function)._fn (/home/dave/gekko/core/baseTradingMethod.js:213:15)
    at null.<anonymous> (/home/dave/gekko/core/baseTradingMethod.js:163:7)
    at /home/dave/gekko/node_modules/lodash/dist/lodash.js:901:23
    at forOwn (/home/dave/gekko/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/home/dave/gekko/node_modules/lodash/dist/lodash.js:3303:9)
    at Base.tick (/home/dave/gekko/core/baseTradingMethod.js:162:7)
    at bound [as tick] (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/dave/gekko/plugins/tradingAdvisor.js:173:15)
    at bound (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
```

I'm really lost on this one, Im assuming that the high in tablib.js has yet to be set to anything but im not really sure where i would set that?

Thanks in advance

**Comment by wupeng1211** [comment]
var _ = require('lodash');
var util = require('../core/util.js');
var config = util.getConfig();
var dirs = util.dirs();
var log = require('../core/log.js');

if(config.tradingAdvisor.talib.enabled) {
  // verify talib is installed properly
  var pluginHelper = require(dirs.core + 'pluginUtil');
  var pluginMock = {
    slug: 'tradingAdvisor',
    dependencies: [{
      module: 'talib',
      version: config.tradingAdvisor.talib.version
    }]
  };

  var cannotLoad = pluginHelper.cannotLoad(pluginMock);
  if(cannotLoad)
    util.die(cannotLoad);

  var talib = require(dirs.core + 'talib');
}

var indicatorsPath = '../methods/indicators/';

var Indicators = {
  MACD: {
    factory: require(indicatorsPath + 'MACD'),
    input: 'price'
  },
  EMA: {
    factory: require(indicatorsPath + 'EMA'),
    input: 'price'
  },
  DEMA: {
    factory: require(indicatorsPath + 'DEMA'),
    input: 'price'
  },
  PPO: {
    factory: require(indicatorsPath + 'PPO'),
    input: 'price'
  },
  LRC: {
    factory: require(indicatorsPath + 'LRC'),
    input: 'price'
  },
  SMA: {
    factory: require(indicatorsPath + 'SMA'),
    input: 'price'
  },

  RSI: {
    factory: require(indicatorsPath + 'RSI'),
    input: 'candle'
  },
  CCI: {
    factory: require(indicatorsPath + 'CCI'),
    input: 'candle'
  }
};

var allowedIndicators = _.keys(Indicators);
var allowedTalibIndicators = _.keys(talib);

var Base = function() {
  _.bindAll(this);

  // properties
  this.age = 0;
  this.setup = false;

  // defaults
  this.requiredHistory = 0;
  this.priceValue = 'close';
  this.indicators = {};
  this.talibIndicators = {};
  this.asyncTick = false;

```
this.openPrices = [];
this.highPrices = [];
this.lowPrices = [];
this.closePrices = [];
this.volume = [];
this.vwprice = [];
```

  // make sure we have all methods
  _.each(['init', 'check'], function(fn) {
    if(!this[fn])
      util.die('No ' + fn + ' function in this trading method found.')
  }, this);

  if(!this.update)
    this.update = function() {};

  // let's run the implemented starting point
  this.init();

  // should be set up now, check some things
  // to make sure everything is implemented
  // correctly.
  if(!this.name)
    log.warn('Warning, trading method has no name');

  if(!config.debug || !this.log)
    this.log = function() {};

  this.setup = true;

  if(_.size(this.talibIndicators))
    this.asyncTick = true;
}

// teach our base trading method events
var Util = require('util');
var EventEmitter = require('events').EventEmitter;
Util.inherits(Base, EventEmitter);

Base.prototype.tick = function(candle) {
  this.age++;
  this.candle = candle;

```
this.openPrices.push(candle.open);
this.highPrices.push(candle.high);
this.lowPrices.push(candle.low);
this.closePrices.push(candle.close);
this.volume.push(candle.volume);
this.vwprice.push(candle.vwprice);

if (this.age > 1000) {
    this.openPrices.shift();
    this.highPrices.shift();
    this.lowPrices.shift();
    this.closePrices.shift();
    this.volume.shift();
    this.vwprice.shift();
}
```

  // update all indicators
  var price = candle[this.priceValue];
  _.each(this.indicators, function(i) {
    if(i.input === 'price')
      i.update(price);
    if(i.input === 'candle')
      i.update(candle);
  });

  if(!this.asyncTick || this.requiredHistory > this.age) {
    this.propogateTick();
  } else {
    var next = _.after(
      _.size(this.talibIndicators),
      function() {
        this.propogateTick();
      }.bind(this)
    );

```
    _.each(this.talibIndicators, function(i) {
        i._fn(this.openPrices, this.highPrices, this.lowPrices, this.closePrices, this.volume, this.vwprice, next);
    }, this);
```

  }

  // update previous price
  this.lastPrice = price;
}

Base.prototype.propogateTick = function() {
  this.update(this.candle);
  if(this.requiredHistory <= this.age) {
    this.log();
    this.check();
  }
}

Base.prototype.addTalibIndicator = function(name, type, parameters) {
  if(!talib)
    util.die('Talib is not enabled');

  if(!_.contains(allowedTalibIndicators, type))
    util.die('I do not know the talib indicator ' + type);

  if(this.setup)
    util.die('Can only add talib indicators in the init method!');

  // TODO: cleanup..
  this.talibIndicators[name] = {
    _params: parameters,
    _fn: function(openPrices, highPrices, lowPrices, closePrices, volume, vwprice, done) {

```
        var args = []
        for (x in parameters) {
            if (parameters[x] === 'OPEN' || parameters[x] === 'O') {
                args.push(openPrices);
            } else if (parameters[x] === 'HIGH' || parameters[x] === 'H') {
                args.push(highPrices);
            } else if (parameters[x] === 'LOW' || parameters[x] === 'L') {
                args.push(lowPrices);
            } else if (parameters[x] === 'CLOSE' || parameters[x] === 'C') {
                args.push(closePrices);
            } else if (parameters[x] === 'VOLUME' || parameters[x] === 'V') {
                args.push(volume);
            } else if (parameters[x] === 'VWPRICE' || parameters[x] === 'VP') {
                args.push(vwprice);
            } else {
                args.push(parameters[x]);
            }
        }

  talib[type].apply(this, args)(function(err, result) {
    if(err)
      util.die('TALIB ERROR:', err);

    this.result = _.mapValues(result, function(a) { return  _.last(a) ; });
    done();
  }.bind(this));
},
result: NaN
```

  }
}

Base.prototype.addIndicator = function(name, type, parameters) {
  if(!_.contains(allowedIndicators, type))
    util.die('I do not know the indicator ' + type);

  if(this.setup)
    util.die('Can only add indicators in the init method!');

  this.indicators[name] = new Indicators[type].factory(parameters);

  // some indicators need a price stream, others need full candles
  this.indicators[name].input = Indicators[type].input;
}

Base.prototype.advice = function(newPosition) {
  // Possible values are long and short. Long will trigger a buy method
  // while short will trigger a sell method
  var advice = 'soft';
  if(newPosition) {
    advice = newPosition;
  }

  this.emit('advice', {
    recommandation: advice,
    portfolio: 1,
    moment: this.candle.start
  });
}

## module.exports = Base;

## my baseTradingMethod.js code, and in methods code is 

```
// define the indicators we need
this.addTalibIndicator('atr', 'atr', ['H', 'L', 'C', this.p]);

this.addTalibIndicator('highestH', 'max', ['H', this.p]);
this.addTalibIndicator('lowestL', 'min', ['L', this.p]);
```

**Comment by askmike** [comment]
@wupeng1211 thanks for looking into this, I just pushed a commit to the develop branch based on your proposal (a bit different to make it easies for people writing methods):

[this commit should fix it](5e3bfb764d815b38e51fc54dab4bf8c4ec6ba7e4).

in your method.init:

```
 // define the indicators we need
 this.addTalibIndicator('adx', 'adx', customADXSettings);
```

in your method.check:

```
var result = this.talibIndicators.adx.result.outReal;
console.log(result);
```

example output:

```
60.23383391429159
59.71615389684439
59.699659793515096
(....)
```

@hoddy could you please pull the develop branch and test if it is working correctly?

**Comment by hoddy** [comment]
Thanks for this i havent had a chance tonight to test it but i will tomorrow and let you know

**Comment by wupeng1211** [comment]
Now, I have some questions, I need highest of high，I can not get，only get  highest  of close.

## in max function ,this data is close or high or low ,

this.max = function(data, period) {
    return talibWrapper({
        name: "MAX",
        inReal: **data.close,**
        startIdx: 0,
        endIdx: data.close.length - 1,
        optInTimePeriod: period
    });
};

**Comment by askmike** [comment]
You can change that to data.high. I'll fix that soon (or you can submit a
PR).

**Comment by hoddy** [comment]
I did a fresh install of the development branch on Ubuntu 14.04:

Small warnings while npm install:

```

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

I copied over my config.js and talib-adx.js and run Gekko:

```
2016-07-06 19:05:26 (INFO):      Paper trader that logs fake profits.
2016-07-06 19:05:26 (INFO): 

2016-07-06 19:05:26 (INFO): Starting to watch the market: BTC-e /
/home/dave/gekko/core/baseTradingMethod.js:193
      args.unshift(basectx.candleProps);
           ^

TypeError: args.unshift is not a function
    at Object.talibIndicators.(anonymous function)._fn (/home/dave/gekko/core/baseTradingMethod.js:193:12)
    at .<anonymous> (/home/dave/gekko/core/baseTradingMethod.js:160:9)
    at /home/dave/gekko/node_modules/lodash/dist/lodash.js:901:23
    at forOwn (/home/dave/gekko/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/home/dave/gekko/node_modules/lodash/dist/lodash.js:3303:9)
    at Base.tick (/home/dave/gekko/core/baseTradingMethod.js:159:7)
    at bound [as tick] (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.processCustomCandle (/home/dave/gekko/plugins/tradingAdvisor.js:207:15)
    at bound (/home/dave/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:96:13)
```

**Comment by hoddy** [comment]
Just checked, Gekko works perfectly with the original trading strategy’s e.g DEMA but hangs at:

```
2016-07-06 19:17:03 (INFO): 

2016-07-06 19:17:03 (INFO): Starting to watch the market: BTC-e /
```

if I run in talib-macd mode.

**Comment by askmike** [comment]
Strange, for me it is working fine. Could you double check that `debug` is on (maybe you just haven't seen any advice yet?)

If you quickly want to test whether things are working I suggest running [a backtest](https://github.com/askmike/gekko/blob/stable/docs/Backtesting.md) using your method.

**Comment by hoddy** [comment]
Oh yeah! Duh! Sorry my mistake, so the `args.unshift(basectx.candleProps);` fault is possibly to do with my talib-adx.js, I will work on it and see if I can get any joy.

**Comment by askmike** [comment]
@hoddy [here you go](https://gist.github.com/askmike/14eb128720d124ea4a0be6c538ee1861)!

**Comment by hoddy** [comment]
Epic =D, thank you!
