### ISSUE TITLE
Error trying to --import

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#377]
With Poloniex in config.js settings the importer bombs out.  Error below.
`config.watch = {
  exchange: 'Poloniex',
  currency: 'USDT',
  asset: 'BTC'
}`

`2016-07-09 03:59:56 (DEBUG):    No end date specified for importing, setting to 2016-07-09 03:59:56
module.js:442
    throw err;
    ^

Error: Cannot find module '/usr/src/gekko/core/../importers/exchanges/Poloniex'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/gekko/core/markets/importer.js:31:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
`

**Comment by hoddy** [comment]
Hmm, i belive you have to name your exchange in lower case e.g:
config.watch = { exchange: 'poloniex', currency: 'USDT', asset: 'BTC' }

**Comment by askmike** [comment]
yep that should fix it!

**Comment by BarnumD** [comment]
Yes that helped.

**Comment by askmike** [comment]
I will force the exchange name to lowercase asap.
