### ISSUE TITLE
Importing from poloniex - Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by BarnumD** [askmike/gekko#379]
`2016-07-09 17:02:05 (WARN):     The plugin Trading Advisor does not support the mode importer. It has been disabled.
2016-07-09 17:02:05 (WARN):     The plugin Advice logger does not support the mode importer. It has been disabled.
2016-07-09 17:02:05 (WARN):     The plugin Profit Simulator does not support the mode importer. It has been disabled.
2016-07-09 17:02:05 (WARN):     The plugin Redis beacon does not support the mode importer. It has been disabled.
2016-07-09 17:02:05 (DEBUG):    No end date specified for importing, setting to 2016-07-09 17:02:05
2016-07-09 17:02:06 (DEBUG):    Processing 2 new trades. From 2015-09-09 13:42:32 UTC to 2015-09-09 13:42:32 UTC. (a few seconds)
2016-07-09 17:02:07 (DEBUG):    Processing 2 new trades. From 2015-09-09 14:38:37 UTC to 2015-09-09 14:42:12 UTC. (4 minutes)
2016-07-09 17:02:08 (DEBUG):    Processing 1 new trades. From 2015-09-09 17:25:11 UTC to 2015-09-09 17:25:11 UTC. (a few seconds)
2016-07-09 17:02:09 (DEBUG):    Processing 9 new trades. From 2015-09-09 18:39:53 UTC to 2015-09-09 18:39:54 UTC. (a few seconds)
2016-07-09 17:02:10 (DEBUG):    Processing 1 new trades. From 2015-09-09 20:19:22 UTC to 2015-09-09 20:19:22 UTC. (a few seconds)
2016-07-09 17:02:12 (DEBUG):    Processing 2 new trades. From 2015-09-09 22:21:41 UTC to 2015-09-09 22:21:42 UTC. (a few seconds)
/usr/src/gekko/importers/exchanges/poloniex.js:68
  var last = moment.unix(_.last(trades).date);
                                       ^

TypeError: Cannot read property 'date' of undefined
    at trades (/usr/src/gekko/importers/exchanges/poloniex.js:68:40)
    at .<anonymous> (/usr/src/gekko/importers/exchanges/poloniex.js:42:5)
    at Request._callback (/usr/src/gekko/node_modules/poloniex.js/lib/poloniex.js:86:17)
    at Request.self.callback (/usr/src/gekko/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/src/gekko/node_modules/poloniex.js/node_modules/request/request.js:888:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/src/gekko/node_modules/poloniex.js/node_modules/request/request.js:839:12)
`

**Comment by BarnumD** [comment]
Starting from blank (no) database.  running node gekko --import. Current stable version.
config.watch = {
  exchange: 'poloniex', // see gekko/docs/supported_exchanges.md
  currency: 'USDT',
  asset: 'BTC'
}

**Comment by askmike** [comment]
I actually only added USDT recently, but didn't get around testing a full import. Nice catch!
