### ISSUE TITLE
TypeError: "msecs" argument must be a number

### ISSUE THREAD

**Issue by Darksoulsong** [askmike/gekko#385]
I just downloaded Gekko, ran npm install and node gekko. I enabled tradingAdvisor, profitSimulator and mailer, with an empty password. Gekko prompted me with a password and right after I typed it, the following error showed up:

```
C:\sandbox\twlgekko\gekko>node gekko
2016-07-17 11:23:30 (INFO):     Gekko v0.3.2 started
2016-07-17 11:23:30 (INFO):     I'm gonna make you rich, Bud Fox.


2016-07-17 11:23:30 (INFO):     Setting up Gekko in realtime mode
2016-07-17 11:23:30 (INFO):
2016-07-17 11:23:30 (INFO):     Setting up:
2016-07-17 11:23:30 (INFO):              Candle writer
2016-07-17 11:23:30 (INFO):              Store candles in a database
2016-07-17 11:23:30 (INFO):

2016-07-17 11:23:30 (INFO):     Setting up:
2016-07-17 11:23:30 (INFO):              Trading Advisor
2016-07-17 11:23:30 (INFO):              Calculate trading advice
2016-07-17 11:23:30 (DEBUG):    The trading method requests 90000 seconds of historic data. Checking availablity..
2016-07-17 11:23:30 (INFO):

2016-07-17 11:23:34 (DEBUG):    Exchange has data spanning 20717 seconds, we need at least 90000 seconds.
2016-07-17 11:23:34 (INFO):              Unable to seed the trading method with locally stored historical candles (Gekko needs more time before it can give advice).
2016-07-17 11:23:34 (INFO):              Using the trading method: MACD
2016-07-17 11:23:34 (WARN):     Warning, trading method has no name
2016-07-17 11:23:34 (INFO):     Setting up:
2016-07-17 11:23:34 (INFO):              Mailer
2016-07-17 11:23:34 (INFO):              Sends you an email everytime Gekko has new advice.
2016-07-17 11:23:34 (WARN):

        You configured Gekko to mail you advice, Gekko needs your email
        password to send emails (to you). Gekko is an opensource project
        [ http://github.com/askmike/gekko ], you can take my word but always
        check the code yourself.


        WARNING: If you have not downloaded Gekko from the github page above we
        CANNOT guarantuee that your email address & password are safe!

prompt: password:  2016-07-17 11:23:34 (INFO):


Got it.
readline.js:953
            throw err;
            ^

TypeError: "msecs" argument must be a number
    at Object.exports.enroll (timers.js:285:11)
    at TLSSocket.Socket.setTimeout (net.js:321:12)
    at new SMTPResponse (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\response.js:66:11)
    at Object.exports.monitor (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\response.js:71:9)
    at Object.SMTP.connect (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\smtp.js:173:35)
    at Object.Client._connect (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\client.js:68:17)
    at Object.Client._poll (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\client.js:28:18)
    at C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\client.js:102:21
    at Object.Message.valid (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\message.js:140:10)
    at Object.Client.send (C:\sandbox\twlgekko\gekko\node_modules\emailjs\smtp\client.js:83:14)
```

My node version is 6.3.0 and npm is 3.10.3, and it happens only if I enable mailer. 
My mailer config:

```
config.mailer = {
  enabled: true,       // Send Emails if true, false to turn off
  sendMailOnStart: true,    // Send 'Gekko starting' message if true, not if false

  email: 'myemail@gmail.com',    // Your Gmail address

  // You don't have to set your password here, if you leave it blank we will ask it
  // when Gekko's starts.
  //
  // NOTE: Gekko is an open source project < https://github.com/askmike/gekko >,
  // make sure you looked at the code or trust the maintainer of this bot when you
  // fill in your email and password.
  //
  // WARNING: If you have NOT downloaded Gekko from the github page above we CANNOT
  // guarantuee that your email address & password are safe!

  password: '',       // Your Gmail Password - if not supplied Gekko will prompt on startup.

  tag: '[GEKKO] ',    // Prefix all email subject lines with this

            //       ADVANCED MAIL SETTINGS
            // you can leave those as is if you 
            // just want to use Gmail

  server: 'smtp.gmail.com',   // The name of YOUR outbound (SMTP) mail server.
  smtpauth: true,     // Does SMTP server require authentication (true for Gmail)
          // The following 3 values default to the Email (above) if left blank
  user: '',       // Your Email server user name - usually your full Email address 'me@mydomain.com'
  from: '',       // 'me@mydomain.com'
  to: '',       // 'me@somedomain.com, me@someotherdomain.com'
  ssl: true,        // Use SSL (true for Gmail)
  port: '',       // Set if you don't want to use the default port
  tls: false        // Use TLS if true
}
```

**Comment by askmike** [comment]
looking into it!

**Comment by askmike** [comment]
sorry for delayed response, could you update (run `git pull && npm install` and try again)?
