### ISSUE TITLE
Error 503 : unable to sell

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#423]
2016-08-17 11:03:21 (INFO):     Trader Received advice to go short Selling  ETH

2016-08-17 11:03:21 (INFO):     We have new trading advice!
2016-08-17 11:03:21 (INFO):              Position: short
2016-08-17 11:03:21 (INFO):              Market price: 11.026
2016-08-17 11:03:21 (INFO):              Based on market time: 2016-08-17 08:46:
00

2016-08-17 11:04:02 (INFO):     attempting to SELL 2.63345409 ETH at BTC-E
2016-08-17 11:04:03 (ERROR):    unable to sell:

 Error: 503
    at Request._callback (\gekko\node_modules\btc-e\btc-e.js:68:23)
    at Request.self.callback (\gekko\node_modules\btc-e\node_modules\request\request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (\gekko\node_modules\btc-e\node_modules\request\request.js:978:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous (\gekko\node_modules\btce\node_modules\request\request.js:929:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by askmike** [comment]
This looks like an error from BTC-e, but Gekko should handle that properly. Looking into that ASAP.

**Comment by greenbigfrog** [comment]
@askmike this can be closed. no complaining in over a year

**Comment by askmike** [comment]
@greenbigfrog btc-e exchange doesn't exist anymore actually, haha. So yes let's close!

**Comment by greenbigfrog** [comment]
:rofl:
