### ISSUE TITLE
#419 again TypeError: Cannot create property 'nonce' on number '

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#428]
#419 again

2016-08-22 03:40:31 (INFO):     BUY order was not (fully) filled, cancelling and creating new order
\gekko\node_modules\btc-e\btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                           ^

TypeError: Cannot create property 'nonce' on number '1203764527'
    at BTCE.makeRequest (\gekko\node_modules\btc-e\btc-e.js:46:18)
    at BTCE.orderList (\gekko\node_modules\btc-e\btc-e.js:126:8)
    at bound [as orderList] \gekko\node_modules\lodash\dist\lodash.js:729:21)
    at Trader.cancelOrder (\gekko\exchanges\btce.js:146:13)
    at bound [as cancelOrder](gekkonode_moduleslodashdistlodash.js:729:21)
    at finish (\gekko\core\portfolioManager.js:282:21)
    at bound (\gekko\node_modules\lodash\dist\lodash.js:729:21)
    at check (\gekko\exchanges\btce.js:137:7)
    at bound (\node_modules\lodash\dist\lodash.js:729:21)
    at Request._callback \gekko\node_modules\btc-e\btc-e

**Comment by Pascal66** [comment]
Again : 
2016-08-24 05:00:36 (INFO):     attempting to BUY 4.350781412632024 ETH at BTC-E

2016-08-24 05:01:38 (INFO):     BUY order was not (fully) filled, cancelling and
 creating new order
C:\Users\Cabanou\Trading\gekko\node_modules\btc-e\btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                 ^

TypeError: Cannot create property 'nonce' on number '1207364211'


But : 
24.08.16 06:05	Your order #1207364211 (buy 3.60029421 ETH @ 11.07946) filled completely:
