### ISSUE TITLE
TypeError: Cannot create property 'nonce' on number everytime

### ISSUE THREAD

**Issue by Pascal66** [askmike/gekko#430]
#428 #419

Each time the order is filled and cant be canceled
Look : 
\gekko\node_modules\btc-e\btc-e.js:46
params.nonce = Math.round((new Date()).getTime() / 1000);
                       ^

TypeError: Cannot create property 'nonce' on number '**1207364211**'

But : 
24.08.16 06:05 Your order **#1207364211** (buy 3.60029421 ETH @ 11.07946) filled completely:

**Comment by Pascal66** [comment]
again, with more clues : 
2016-08-24 22:26:29 (INFO):     attempting to SELL 4.35078142 ETH at BTC-E
2016-08-24 22:27:31 (INFO):     SELL order was not (fully) filled, cancelling and creating new order
\gekko\node_modules\btc-e\btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                 ^
TypeError: Cannot create property 'nonce' on number '1208695533'

24.08.16 23:33  Your order #1208695533 (sell 3.25262141 ETH @ 11.00209) filled completely.

But it take time to fill it : 
ETH/USD sell    0.628746 ETH    11.0021 USD 6.91752636 USD  24.08.16 23:33
ETH/USD sell    1 ETH   11.0021 USD 11.0021 USD 24.08.16 23:32
ETH/USD sell    1.4 ETH 11.0021 USD 15.40294 USD    24.08.16 23:30
ETH/USD sell    0.106525 ETH    11.0021 USD 1.1719987 USD   24.08.16 23:26
ETH/USD sell    0.11735 ETH 11.0021 USD 1.29109643 USD  24.08.16 23:26
ETH/USD sell    0.98224 ETH 11.0021 USD 10.8067027 USD  24.08.16 23:26
ETH/USD sell    0.11592 ETH 11.0021 USD 1.27536343 USD  24.08.16 23:26

I'm investigate for why the nonce use the order number

**Comment by Pascal66** [comment]
first : still using V2 of btceAPI (it's V3 since more than a year)
this.publicApiUrl = 'https://btc-e.com/api/2/'

second : I think the problem come from The portfolio manager, in : 
Manager.prototype.noteOrder = function(err, order) {
Manager.prototype.checkOrder = function() {

**Comment by Pascal66** [comment]
Up

BUY order was not (fully) filled, cancelling and creating new order
\gekkoClipse\node_modules\btc-e\btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                 ^

TypeError: Cannot create property 'nonce' on number '1242577658'
    at BTCE.makeRequest (\gekkoClipse\node_modules\btc-e\btc-e.js:46:18)
    at BTCE.orderList (\gekkoClipse\node_modules\btc-e\btc-e.js:126:8)
    at bound [as orderList](gekkoClipsenode_moduleslodashdistlodash.js:729:21)
    at Trader.cancelOrder (\gekkoClipse\exchanges\btce.js:146:13)
    at bound [as cancelOrder](gekkoClipsenode_moduleslodashdistlodash.js:729:21)
    at finish (\gekkoClipse\core\portfolioManager.js:284:21)
    at bound (\gekkoClipse\node_modules\lodash\dist\lodash.js:729:21)
    at check (\gekkoClipse\exchanges\btce.js:137:7)
    at bound (\gekkoClipse\node_modules\lodash\dist\lodash.js:729:21)
    at Request._callback (\gekkoClipse\node_modules\btc-e\btc-e.js:82:5)

**Comment by Pascal66** [comment]
I've removed : 
this.exchange.cancelOrder(this.order);
and : 
setTimeout(function() { self.trade(self.action); }, 500);

One : it doesnt take care of action price after the cancel-> new trade
Second :  In low volume, there can be a long time between partially filled orders

So remove those lines can accept partially filled order, AND doesnt take care of bad nonce certainly due to usage of BTCE api V2

**Comment by greenbigfrog** [comment]
@askmike can be closed... BTC-E issue
