### ISSUE TITLE
Bitstamp cannot read property error

### ISSUE THREAD

**Issue by lyn168** [askmike/gekko#434]
Anyone came across this error for bitstamp?

/bitstamp/gekko/exchanges/bitstamp.js:48
    if(!_.isEmpty(data.error))
                      ^

TypeError: Cannot read property 'error' of undefined
    at .<anonymous> (/bitstamp/gekko/exchanges/bitstamp.js:48:23)
    at IncomingMessage.<anonymous> (/bitstamp/gekko/node_modules/bitstamp/bitstamp.js:48:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by lyn168** [comment]
Problem solved
need user ID

**Comment by joelbrennan0** [comment]
Or activate your API key via email in my case :P
