### ISSUE TITLE
Pushbullet issue. 'Cannot read property 'active' of undefined.'

### ISSUE THREAD

**Issue by yguy08** [askmike/gekko#463]
Wyatts-MacBook-Air:gekko Wyatt$ node gekko
2016-09-24 15:34:42 (INFO): Gekko v0.3.2 started
2016-09-24 15:34:42 (INFO): I'm gonna make you rich, Bud Fox. 

2016-09-24 15:34:42 (INFO): Setting up Gekko in realtime mode
2016-09-24 15:34:42 (INFO): 
2016-09-24 15:34:42 (INFO): Setting up:
2016-09-24 15:34:42 (INFO):      Candle writer
2016-09-24 15:34:42 (INFO):      Store candles in a database
2016-09-24 15:34:42 (INFO): 

2016-09-24 15:34:42 (INFO): Setting up:
2016-09-24 15:34:42 (INFO):      Trading Advisor
2016-09-24 15:34:42 (INFO):      Calculate trading advice
2016-09-24 15:34:42 (DEBUG):    The trading method requests 90000 seconds of historic data. Checking availablity..
2016-09-24 15:34:42 (INFO): 

2016-09-24 15:34:44 (DEBUG):    Exchange has data spanning 86216 seconds, we need at least 90000 seconds.
2016-09-24 15:34:44 (INFO):      Unable to seed the trading method with locally stored historical candles (Gekko needs more time before it can give advice).
2016-09-24 15:34:44 (INFO):      Using the trading method: MACD
2016-09-24 15:34:44 (WARN): Warning, trading method has no name
2016-09-24 15:34:44 (INFO): Setting up:
2016-09-24 15:34:44 (INFO):      Advice logger
2016-09-24 15:34:44 (INFO):  
2016-09-24 15:34:44 (INFO): Setting up:
2016-09-24 15:34:44 (INFO):      Profit Simulator
2016-09-24 15:34:44 (INFO):      Paper trader that logs fake profits.
2016-09-24 15:34:44 (INFO): 

2016-09-24 15:34:44 (INFO): Setting up:
2016-09-24 15:34:44 (INFO):      Pushbullet
2016-09-24 15:34:44 (INFO):      Sends advice to pushbullet.
2016-09-24 15:34:44 (INFO): 

2016-09-24 15:34:44 (INFO): Starting to watch the market: Bitstamp /
2016-09-24 15:34:44 (DEBUG):    scheduling ticks
2016-09-24 15:34:44 (DEBUG):    Requested / trade data from Bitstamp ...
/Users/Wyatt/Desktop/gekko-dev/gekko/plugins/pushbullet.js:71
        if (response.active){
                    ^

TypeError: Cannot read property 'active' of undefined
    at /Users/Wyatt/Desktop/gekko-dev/gekko/plugins/pushbullet.js:71:21
    at PushBullet.handleError (/Users/Wyatt/Desktop/gekko-dev/gekko/node_modules/pushbullet/lib/pushbullet.js:576:5)
    at PushBullet.handleResponse (/Users/Wyatt/Desktop/gekko-dev/gekko/node_modules/pushbullet/lib/pushbullet.js:556:8)
    at Request._callback (/Users/Wyatt/Desktop/gekko-dev/gekko/node_modules/pushbullet/lib/pushbullet.js:240:8)
    at Request.self.callback (/Users/Wyatt/Desktop/gekko-dev/gekko/node_modules/pushbullet/node_modules/request/request.js:237:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Wyatt/Desktop/gekko-dev/gekko/node_modules/pushbullet/node_modules/request/request.js:1146:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)

**Comment by yguy08** [comment]
User Error. Disabled pushbullet in config and working as expected.
