### ISSUE TITLE
PLUGIN: pusbullet is broken

### ISSUE THREAD

**Issue by appop** [askmike/gekko#467]
2016-10-03 10:16:28 (INFO): Setting up:
2016-10-03 10:16:28 (INFO):      Pushbullet
2016-10-03 10:16:28 (INFO):      Sends advice to pushbullet.
2016-10-03 10:16:28 (INFO):

2016-10-03 10:16:28 (INFO): Starting to watch the market: BTCC /
2016-10-03 10:16:28 (DEBUG):    scheduling ticks
2016-10-03 10:16:28 (DEBUG):    Requested / trade data from BTCC ...
/home/neal/gekko/plugins/pushbullet.js:71
        if (response.active){
                    ^

TypeError: Cannot read property 'active' of undefined
    at /home/neal/gekko/plugins/pushbullet.js:71:21
    at PushBullet.handleError (/home/neal/gekko/node_modules/pushbullet/lib/pushbullet.js:576:5)
    at PushBullet.handleResponse (/home/neal/gekko/node_modules/pushbullet/lib/pushbullet.js:556:8)
    at Request._callback (/home/neal/gekko/node_modules/pushbullet/lib/pushbullet.js:240:8)
    at Request.self.callback (/home/neal/gekko/node_modules/pushbullet/node_modules/request/request.js:237:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/neal/gekko/node_modules/pushbullet/node_modules/request/request.js:1146:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)

**Comment by appop** [comment]
hi I soved this.

I didn't setting the pushbullet.
