### ISSUE TITLE
Crash after buy at Poloniex

### ISSUE THREAD

**Issue by Stoner19** [askmike/gekko#476]
I get this crash error after a buy is filled:

```
2016-10-10 16:30:34 (INFO):     Attempting to BUY 1.0498241020596488 ETH at Poloniex
/home/user/gekko/plugins/trader/portfolioManager.js:275
  setTimeout(this.checkOrder, util.minToMs(1));
                                   ^

TypeError: util.minToMs is not a function
    at Manager.noteOrder (/home/user/gekko/plugins/trader/portfolioManager.js:275:36)
    at bound (/home/user/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.<anonymous> (/home/user/gekko/exchanges/poloniex.js:104:5)
    at Request._callback (/home/user/gekko/node_modules/poloniex.js/lib/poloniex.js:86:17)
    at Request.self.callback (/home/user/gekko/node_modules/poloniex.js/node_modules/request/request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/user/gekko/node_modules/poloniex.js/node_modules/request/request.js:888:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
```

There are no other instances running and nothing significant changed in the config.

**Comment by rajeshdalsaniya** [comment]
hi stoner i am also using gekko with poloniex but no success. can you post your config file (remove ur api keys, creditnals). So we can discuss further

**Comment by askmike** [comment]
Damn I broke this yesterday, sorry guys!

**Comment by Stoner19** [comment]
Thanks @askmike!

**Comment by askmike** [comment]
@rajeshdalsaniya if you have problems running Gekko, could you make a new issue?

**Comment by Stoner19** [comment]
@rajeshdalsaniya feel free to find me on Freenode IRC and I'd be happy to discuss things. Keep in mind that I'm still very new to this wonderful bot that @askmike created.

@askmike would be cool if you had an IRC channel for users to chat about the bot and trading. ##gekko is currently available on Freenode IRC (#gekko is not). I'll hang out in ##gekko if anyone else is interested in joining up.

**Comment by askmike** [comment]
@Stoner19 I was quite active in early 2014 on gekko and we had the channel #gekko on freenode. Not quite sure what happened after that.. I'll be in the channel tomorrow (~11 hours from). Very interested in ideas for new features etc for Gekko that people might have.

**Comment by Stoner19** [comment]
I'll be there as well. #gekko currently looks like freenode-staff took ahold of it, but it might be worth joining the #freenode channel to discuss gaining access to that one again. See you tomorrow on IRC :)

**Comment by rajeshdalsaniya** [comment]
#gekko is private IRC (invite only channel)  - cant able to join
##gekko is open channel
