### ISSUE TITLE
CEXIO: TypeError: Cannot read property 'amount' of undefined

### ISSUE THREAD

**Issue by martin5256** [askmike/gekko#483]
me/martin/CEX.io/plugins/trader/portfolioManager.js:110
  return this.getFund(fund).amount;
                           ^

TypeError: Cannot read property 'amount' of undefined
    at Manager.getBalance (/home/martin/CEX.io/plugins/trader/portfolioManager.js:110:28)
    at Manager.bound [as getBalance](/home/martin/CEX.io/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.act (/home/martin/CEX.io/plugins/trader/portfolioManager.js:138:23)
    at bound (/home/martin/CEX.io/node_modules/lodash/dist/lodash.js:729:21)
    at /home/martin/CEX.io/node_modules/async/lib/async.js:232:13
    at /home/martin/CEX.io/node_modules/async/lib/async.js:142:25
    at /home/martin/CEX.io/node_modules/async/lib/async.js:229:17
    at /home/martin/CEX.io/node_modules/async/lib/async.js:556:34
    at Manager.<anonymous> (/home/martin/CEX.io/plugins/trader/portfolioManager.js:76:7)
    at Trader.calculate (/home/martin/CEX.io/exchanges/cexio.js:135:5)

**Comment by martin5256** [comment]
Sory miss clicked wanted to write more

**Comment by martin5256** [comment]
Hapnend on cex io

**Comment by askmike** [comment]
Thanks! will look into asap. Most probably related to #481.

**Comment by martin5256** [comment]
Thanks a lot :D as a student i see a lot of potential in this bot with my 12 euros. Invested years ago :) anybody good setings for cex ?

My config for cex 

```
// MACD settings:
config.MACD = {
  // EMA weight (  )
  // the higher the weight, the more smooth (and delayed) the line
  short: 12,                                                                 long: 26,
  signal: 9,
  // the difference between the EMAs (to act as triggers)
  thresholds: {
    down: -0.0000025,
    up: 0.0000025,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 1
```

**Comment by askmike** [comment]
Could you update and try again?

**Comment by askmike** [comment]
> Thanks a lot :D as a student i see a lot of potential in this bot with my 12 euros. Invested years ago :) anybody good setings for cex ?

If I were you I would start by backtesting and or paper trading until you find a strategy that is profitable. **The default settings are not recommended to be ran with real money.**
