### ISSUE TITLE
The gekko need get Requested trade data from BTCC again after I do restart 

### ISSUE THREAD

**Issue by appop** [askmike/gekko#498]
2016-11-14 10:00:58 (DEBUG):            Available local data:
2016-11-14 10:00:58 (DEBUG):                    from: 1500 minutes ago
2016-11-14 10:00:58 (DEBUG):                    to: 1 minutes ago
2016-11-14 10:00:58 (INFO):             Usable local data available, trying to match with exchange data..
2016-11-14 10:00:58 (DEBUG):            Fetching exchange data since 16 minutes ago
2016-11-14 10:01:01 (DEBUG):            Available exchange data:
2016-11-14 10:01:01 (DEBUG):                    from: 0 minutes ago
2016-11-14 10:01:01 (DEBUG):                    to: 0 minutes ago
2016-11-14 10:01:01 (DEBUG):            Unable to stitch datasets.
2016-11-14 10:01:01 (INFO):             Not seeding locally available data to the trading method.
2016-11-14 10:01:01 (INFO):             The exchange does not return enough data. 0 minutes are still missing.
2016-11-14 10:01:01 (INFO):     Setting up:
2016-11-14 10:01:01 (INFO):              Trader
2016-11-14 10:01:01 (INFO):              Follows the advice and create real orders.
2016-11-14 10:01:01 (DEBUG):    getting balance & fee from BTCC
2016-11-14 10:01:01 (INFO):

**Comment by askmike** [comment]
strange, could you post the output of:

```
node gekko --version
```

**Comment by askmike** [comment]
If this is also a problem for anyone else, please reopen.

**Comment by tkh23** [comment]
Jul 26 12:29:16 tk44 gekko-node[8224]: 2017-07-26 12:29:16 (INFO):                The trading method requests 600 minutes of historic data. Checking availablity..
Jul 26 12:29:16 tk44 gekko-node[8224]: 2017-07-26 12:29:16 (INFO):
Jul 26 12:29:16 tk44 gekko-node[8224]: 2017-07-26 12:29:16 (INFO):                No usable local data available, trying to get as much as possible from the exchange..
Jul 26 12:29:16 tk44 gekko-node[8224]: 2017-07-26 12:29:16 (INFO):                Preventing Gekko from requesting 600 minutes of history.
Jul 26 12:29:16 tk44 gekko-node[8224]: 2017-07-26 12:29:16 (DEBUG):                Fetching exchange data since 240 minutes ago
Jul 26 12:29:17 tk44 gekko-node[8224]: 2017-07-26 12:29:17 (DEBUG):                Available exchange data:
Jul 26 12:29:17 tk44 gekko-node[8224]: 2017-07-26 12:29:17 (DEBUG):                        from: 239 minutes ago
Jul 26 12:29:17 tk44 gekko-node[8224]: 2017-07-26 12:29:17 (DEBUG):                        to: 2 minutes ago
Jul 26 12:29:17 tk44 gekko-node[8224]: 2017-07-26 12:29:17 (DEBUG):                Unable to stitch datasets.
Jul 26 12:29:17 tk44 gekko-node[8224]: 2017-07-26 12:29:17 (INFO):                Not seeding locally available data to the trading method.


Performed import prior to, also gekko was running for at least ten hours before I restarted it. Data should be available. Using devel version. 
Gekko version: v0.5.0
Nodejs version: v8.2.1

**Comment by askmike** [comment]
>  No usable local data available, 

At the time you ran this (2017-07-26 12:29:16) what data did you have locally available?

**Comment by tkh23** [comment]
As mentioned, I had done an import for past 15 days and I also previously ran the node for over ten hours, I just made a change to the config.js so I restarted and now I have to wait again for it to collect history...

**Comment by askmike** [comment]
> As mentioned, I had done an import for past 15 days and I also previously ran the node for over ten hours

For some reason Gekko was unable to detect this. What happens if you scan for data (backtest CLI with range scan or using the UI)?

**Comment by tkh23** [comment]
I'm sorry if this is a dumb question, but can I start a second node from the same folder without disturbing the first one? (It has almost collected its 600 minutes and I don't want to wait another 10h).
Or should I copy the folder and try in a second folder?

**Comment by askmike** [comment]
> but can I start a second node from the same folder without disturbing the first one?

Should be fine yes! Would be safer to only enable the candleWriter on one.

**Comment by tkh23** [comment]
I did cp -r and ran CLI-backtest:
[...]
2017-07-26 22:28:57 (DEBUG):	calculated Ultimate Oscillator properties for candle:
2017-07-26 22:28:57 (DEBUG):		 tsi: -41.02409359
2017-07-26 22:28:57 (DEBUG):		 price: 182.40000001
2017-07-26 22:28:57 (DEBUG):	In low since 22 candle(s)
/home/tkh/gekko2/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'currency' of undefined
    at PerformanceAnalyzer.calculateReportStatistics (/home/tkh/gekko2/plugins/performanceAnalyzer/performanceAnalyzer.js:133:29)
    at PerformanceAnalyzer.bound [as calculateReportStatistics] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.finalize (/home/tkh/gekko2/plugins/performanceAnalyzer/performanceAnalyzer.js:170:23)
    at PerformanceAnalyzer.bound [as finalize] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at /home/tkh/gekko2/core/gekkoStream.js:44:9
    at Function.forEach (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:3298:15)
    at Gekko.shutdown (/home/tkh/gekko2/core/gekkoStream.js:42:5)
    at Base.finish (/home/tkh/gekko2/plugins/tradingAdvisor/baseTradingMethod.js:322:12)
    at Base.bound [as finish] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.finish (/home/tkh/gekko2/plugins/tradingAdvisor/tradingAdvisor.js:80:15)
--> in Database#all('\n    SELECT * from candles_USDT_ZEC\n    WHERE start <= 1501004460 AND start >= 1501006560\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/tkh/gekko2/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/tkh/gekko2/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/tkh/gekko2/core/markets/backtest.js:105:10)
    at bound (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/tkh/gekko2/plugins/sqlite/reader.js:108:5)
[tkh@tk44 gekko2]$

**Comment by tkh23** [comment]
Running in live-mode from second folder fails again:
2017-07-26 22:33:20 (INFO):		No usable local data available, trying to get as much as possible from the exchange..
2017-07-26 22:33:20 (INFO):		Preventing Gekko from requesting 600 minutes of history.
2017-07-26 22:33:20 (DEBUG):		Fetching exchange data since 240 minutes ago
2017-07-26 22:33:21 (DEBUG):		Available exchange data:
2017-07-26 22:33:21 (DEBUG):			from: 239 minutes ago
2017-07-26 22:33:21 (DEBUG):			to: 1 minutes ago
2017-07-26 22:33:21 (DEBUG):		Unable to stitch datasets.
2017-07-26 22:33:21 (INFO):		Not seeding locally available data to the trading method.
2017-07-26 22:33:21 (INFO):	Setting up:
2017-07-26 22:33:21 (INFO):		 Trader
2017-07-26 22:33:21 (INFO):		 Follows the advice and create real orders.
2017-07-26 22:33:21 (DEBUG):	getting ticker, balance & fee from Poloniex
2017-07-26 22:33:21 (INFO):	

Running import for past ~20h:
2017-07-26 22:35:24 (WARN):	The plugin Performance Analyzer does not support the mode importer. It has been disabled.
2017-07-26 22:35:24 (DEBUG):	No end date specified for importing, setting to 2017-07-26 19:35:24
2017-07-26 22:35:24 (INFO):	USDT ZEC Requesting data from 2017-07-26 00:00:00, to 2017-07-26 02:00:00
[...]
2017-07-26 22:35:49 (DEBUG):	Processing 224 new trades. From 2017-07-26 18:30:02 UTC to 2017-07-26 19:33:25 UTC. (an hour)
2017-07-26 22:35:50 (INFO):	USDT ZEC Requesting data from 2017-07-26 20:10:00, to 2017-07-26 22:10:00
2017-07-26 22:35:51 (DEBUG):	Trade fetch came back empty.
2017-07-26 22:35:52 (INFO):	USDT ZEC Requesting data from 2017-07-26 22:00:00, to 2017-07-27 00:00:00
2017-07-26 22:35:52 (DEBUG):	Trade fetch came back empty.
[ctrl+c because trying to fetch future trades]

Rerunning node, error persists: 
2017-07-26 22:37:21 (INFO):		The trading method requests 600 minutes of historic data. Checking availablity..
2017-07-26 22:37:21 (INFO):	

2017-07-26 22:37:21 (INFO):		No usable local data available, trying to get as much as possible from the exchange..
2017-07-26 22:37:21 (INFO):		Preventing Gekko from requesting 600 minutes of history.
2017-07-26 22:37:21 (DEBUG):		Fetching exchange data since 240 minutes ago
2017-07-26 22:37:22 (DEBUG):		Available exchange data:
2017-07-26 22:37:22 (DEBUG):			from: 240 minutes ago
2017-07-26 22:37:22 (DEBUG):			to: 3 minutes ago
2017-07-26 22:37:22 (DEBUG):		Unable to stitch datasets.
2017-07-26 22:37:22 (INFO):		Not seeding locally available data to the trading method.
2017-07-26 22:37:22 (INFO):	Setting up:
2017-07-26 22:37:22 (INFO):		 Trader
2017-07-26 22:37:22 (INFO):		 Follows the advice and create real orders.
2017-07-26 22:37:22 (DEBUG):	getting ticker, balance & fee from Poloniex
2017-07-26 22:37:22 (INFO):

**Comment by askmike** [comment]
See #866. Are both these errors (live gekko + backtester) running based on the same database?

**Comment by tkh23** [comment]
Yes they are. I checked 866, indeed candlewriter was set to false. I enabled, this will probably fix the issue in the future. My mistake for overlooking, thanks!

**Comment by askmike** [comment]
> indeed candlewriter was set to false

With the config it's a bit hard to use Gekko. Therefor I would advice to use the UI where everything is configured properly. The UI also supports live trading now (since yesterday).

**Comment by tkh23** [comment]
Does it also support ZEC now?

**Comment by askmike** [comment]
Yes: USDT/ZEC, ETH/ZEC and XMR/ZEC
