### ISSUE TITLE
Cannot find module '/home/fox/gekko-stable/core/../importers/exchanges/Poloniex'

### ISSUE THREAD

**Issue by foxhitch** [askmike/gekko#511]
whenever i try to run the Importing  i am getting this error

    throw err;
    ^

Error: Cannot find module '/home/fox/gekko-stable/core/../importers/exchanges/Poloniex'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fox/gekko-stable/core/markets/importer.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by askmike** [comment]
Could you set the exchange in your config as "poloniex" (so with a small P instead)? I will update the checks for this.

**Comment by foxhitch** [comment]
yes It's Working Now Thank You very much
