### ISSUE TITLE
btc-e TypeError: Cannot read property 'btc_ltc' of undefined

### ISSUE THREAD

**Issue by groverz** [askmike/gekko#526]
`
📵  gekko [stable] node gekko
2016-12-22 13:27:20 (INFO):	Gekko v0.3.4 started
2016-12-22 13:27:20 (INFO):	I'm gonna make you rich, Bud Fox. 

2016-12-22 13:27:20 (INFO):	Setting up Gekko in realtime mode
2016-12-22 13:27:20 (INFO):	
2016-12-22 13:27:20 (INFO):	Setting up:
2016-12-22 13:27:20 (INFO):		 Candle writer
2016-12-22 13:27:20 (INFO):		 Store candles in a database
2016-12-22 13:27:20 (INFO):	

2016-12-22 13:27:21 (INFO):	Setting up:
2016-12-22 13:27:21 (INFO):		 Trading Advisor
2016-12-22 13:27:21 (INFO):		 Calculate trading advice
2016-12-22 13:27:21 (INFO):		 Using the trading method: MACD
2016-12-22 13:27:21 (WARN):	Warning, trading method has no name
2016-12-22 13:27:21 (INFO):		The trading method requests 1500 minutes of historic data. Checking availablity..
2016-12-22 13:27:21 (INFO):	

2016-12-22 13:27:21 (INFO):		No usable local data available, trying to get as much as possible from the exchange..
2016-12-22 13:27:21 (INFO):		Preventing Gekko from requesting 1500 minutes of history.
2016-12-22 13:27:21 (DEBUG):		Fetching exchange data since 240 minutes ago
/app/gekko/exchanges/btce.js:174
    var trades = _.map(data[this.pair], function(t) {
                           ^

TypeError: Cannot read property 'btc_ltc' of undefined
    at Trader.<anonymous> (/app/gekko/exchanges/btce.js:174:28)
    at Request._callback (/app/gekko/node_modules/btc-e/btc-e.js:106:14)
    at Request.self.callback (/app/gekko/node_modules/btc-e/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/gekko/node_modules/btc-e/node_modules/request/request.js:978:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/gekko/node_modules/btc-e/node_modules/request/request.js:929:12)
    at emitNone (events.js:91:20)
`

**Comment by askmike** [comment]
will look into asap.

**Comment by groverz** [comment]
Working in the Docker (barnumd/gekko) :). Used Docker.

**Comment by slavach** [comment]
The same problem. Gekko v0.3.5.
