### ISSUE TITLE
module.js:471 throw error

### ISSUE THREAD

**Issue by Litvakas** [askmike/gekko#533]
Hi,

I have just recently installed gekko, but seems that i am receiving an error when trying to open it. Error is received when trying opening with UI option or it. Any advice? a bit lost here. 

`MacBookAir:gekko Tomas$ node geko --ui
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/Tomas/gekko/geko'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
MacBookAir:gekko Tomas$ `

Thank you

**Comment by Litvakas** [comment]
Re-installed it and now works :)

By the way awesome job done!
