### ISSUE TITLE
unable to buy

### ISSUE THREAD

**Issue by brunoartc** [askmike/gekko#554]
previous:
   { Error: bad response on command 'Qm9yYm9sZXRh'
       at module.exports (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\error.js:3:13)
       at response (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\smtp.js:203:31)
       at caller (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\smtp.js:49:14)
       at TLSSocket.response (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\smtp.js:182:11)
       at TLSSocket.g (events.js:291:16)
       at emitTwo (events.js:106:13)
       at TLSSocket.emit (events.js:191:7)
       at notify (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\response.js:19:14)
       at TLSSocket.watch (C:\Users\bruno\Desktop\gekko-stable\node_modules\emailjs\smtp\response.js:44:7)
       at emitOne (events.js:96:13)
     code: 2,
     smtp: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials q88sm1451929qkq.21 - gsmtp\r\n' },
  smtp: undefined }
2017-01-18 20:55:57 (ERROR):    unable to buy: There was an error while placing your order: Invalid amount
2017-01-18 20:56:15 (DEBUG):    Requested / trade data from CEX.io ...

**Comment by brunoartc** [comment]
I got it, have an low balance, and can't not buy the minimum 0.01 BTC :)
