### ISSUE TITLE
Problem in --import

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#582]
```
2017-02-06 18:34:07 (INFO):     Gekko v0.3.4 started
2017-02-06 18:34:07 (INFO):     I'm gonna make you rich, Bud Fox.


2017-02-06 18:34:07 (INFO):     Setting up Gekko in importer mode
2017-02-06 18:34:07 (INFO):
2017-02-06 18:34:07 (INFO):     Setting up:
2017-02-06 18:34:07 (INFO):              Candle writer
2017-02-06 18:34:07 (INFO):              Store candles in a database
2017-02-06 18:34:07 (INFO):

2017-02-06 18:34:07 (WARN):     The plugin Trading Advisor does not support the mode importer. It has been disabled.
2017-02-06 18:34:07 (WARN):     The plugin Advice logger does not support the mode importer. It has been disabled.
2017-02-06 18:34:07 (WARN):     The plugin Profit Simulator does not support the mode importer. It has been disabled.
2017-02-06 18:34:07 (DEBUG):    No end date specified for importing, setting to 2017-02-06 23:34:07
module.js:472
    throw err;
    ^

Error: Cannot find module '/root/gekko/core/../importers/exchanges/Poloniex'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/gekko/core/markets/importer.js:31:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
root@vps116171:~/gekko#
```

How to fix that?

**Comment by Momohime** [comment]
Replace 'Poloniex' with 'poloniex'

**Comment by ghost** [comment]
Thanks a lot man.... i will do some backtest's now... i just started today any suggestion for a newbie?
