### ISSUE TITLE
error in IRC plugin

### ISSUE THREAD

**Issue by voidzero** [askmike/gekko#596]
I'm getting the following error when trying to enable the IRC plugin (node v7.5.0, npm 4.1.2, Linux x86_64)

<pre>TypeError: The super constructor to "inherits" must not be null or undefined
   at Object.exports.inherits (util.js:962:11)
   at Object.<anonymous> (/user/gitrepos/gekko/node_modules/irc/lib/irc.js:545:17)
   at Module._compile (module.js:571:32)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:488:32)
   at tryModuleLoad (module.js:447:12)
   at Function.Module._load (module.js:439:3)
   at Module.require (module.js:498:17)
   at require (internal/module.js:20:19)
   at /user/gitrepos/gekko/core/pluginUtil.js:28:19 '\n\n'
</pre>

**Comment by askmike** [comment]
that looks like a bug in the dependency, I'll check if there is a new version out asap!

**Comment by voidzero** [comment]
Great, thank you!

**Comment by greenbigfrog** [comment]
@askmike can most likely be closed

**Comment by askmike** [comment]
Follow up should happen on the forum! :)
