### ISSUE TITLE
GDAX configuration

### ISSUE THREAD

**Issue by albertolive** [askmike/gekko#605]
Hi,

Finally I see that we can use GDAX to this great project. I have added my trader keys to config and tried to run it to heroku but I have this error:

```javascript
/app/node_modules/sqlite3/lib/trace.js:28
                    throw err;
                    ^
Error: Cannot find module '/app/core/../exchanges/gdax'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Stitcher.checkExchangeTrades (/app/core/dataStitcher.js:163:22)
    at Stitcher.<anonymous> (/app/core/dataStitcher.js:83:10)
    at Statement.<anonymous> (/app/plugins/sqlite/reader.js:34:14)
--> in Database#all('\n    SELECT start from candles_EUR_BTC\n    WHERE start <= 1488623520 AND start >= 1488533520\n    ORDER BY start DESC\n  ', [Function])
    at Reader.mostRecentWindow (/app/plugins/sqlite/reader.js:22:11)
    at Reader.bound [as mostRecentWindow] (/app/node_modules/lodash/dist/lodash.js:729:21)
    at Stitcher.prepareHistoricalData (/app/core/dataStitcher.js:43:15)
    at new Actor (/app/plugins/tradingAdvisor.js:26:14)
    at load (/app/core/pluginUtil.js:102:22)
    at /app/node_modules/async/lib/async.js:227:13
    at iterate (/app/node_modules/async/lib/async.js:134:13)
    at /app/node_modules/async/lib/async.js:145:25
    at /app/node_modules/async/lib/async.js:229:17
```

My trader config looks like this:

```javascript
config.trader = {
  enabled: true,
  key: '',
  secret: '',
  passphrase: '',
  sandbox: false, //defaults to false
  post_only: true, //defaults to false, if true all trades will be POST Only which means all orders will be maker trades or will be rejected by the system
  username: '' // your username, only required for specific exchanges.
}
```

My watch looks like this:

```javascript
config.watch = {

  // see https://github.com/askmike/gekko#supported-exchanges
  exchange: 'GDAX',
  currency: 'EUR',
  asset: 'BTC'
}
```

I see that GDAX is missing in exchanges. Do I have to add it?

Thank you

**Comment by albertolive** [comment]
Nevermind, now I see that the [PR](https://github.com/askmike/gekko/pull/564) never went to develop....

**Comment by askmike** [comment]
What do you mean? It did! Can you try lowercasing that exchange name?

**Comment by albertolive** [comment]
That your PR with your changes is not in branch develop.

Now it's working on Heroku but I had to take your commit changes and added it manually to my branch.

![screen shot 2017-03-04 at 12 18 28](https://cloud.githubusercontent.com/assets/1182864/23578334/b50c841a-00d4-11e7-82b6-3990bf58a5e8.png)

**Comment by albertolive** [comment]
Or maybe I took branch instead develop. Let me check...

**Comment by albertolive** [comment]
Yes I did that. My bad. Thx anyway.

**Comment by askmike** [comment]
No problem, I haven't had a lot of time to properly review and test the gdax within gekko. If you run into anything feel free to post an issue :)
