### ISSUE TITLE
GDAX Importing data error

### ISSUE THREAD

**Issue by albertolive** [askmike/gekko#606]
Hi,

I'm running `node gekko --import` and I'm getting this error:

```javascript
 2017-03-04 11:52:27 (DEBUG):	Skipping data, they are before from date 2016-07-01T07:50:55+00:00
 2017-03-04 11:52:27 (DEBUG):	Backwards: 2016-07-01T07:51:47.43651Z (715493) to 2016-07-01T08:45:11.028345Z (715592)
 2017-03-04 11:52:27 (DEBUG):	Skipping data, they are before from date 2016-07-01T08:45:11+00:00
 2017-03-04 11:52:28 (DEBUG):	Backwards: 2016-07-01T08:45:11.449921Z (715593) to 2016-07-01T09:20:25.626376Z (715692)
 2017-03-04 11:52:28 (DEBUG):	Skipping data, they are before from date 2016-07-01T09:20:25+00:00
 2017-03-04 11:52:28 (DEBUG):	Backwards: 2016-07-01T09:20:25.627121Z (715693) to 2016-07-01T10:30:19.696206Z (715792)
 2017-03-04 11:52:28 (DEBUG):	Skipping data, they are before from date 2016-07-01T10:30:19+00:00
 /app/exchanges/gdax.js:199
                 log.debug('Backwards: ' + last.time + ' (' + last.trade_id + ') to ' + first.time + ' (' + first.trade_id + ')');
                                               ^

 TypeError: Cannot read property 'time' of undefined
     at Trader.<anonymous> (/app/exchanges/gdax.js:199:47)
     at Request._callback (/app/node_modules/gdax/lib/clients/public.js:45:7)
     at Request.self.callback (/app/node_modules/gdax/node_modules/request/request.js:187:22)
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:194:7)
     at Request.<anonymous> (/app/node_modules/gdax/node_modules/request/request.js:1044:10)
     at emitOne (events.js:96:13)
     at Request.emit (events.js:191:7)
     at IncomingMessage.<anonymous> (/app/node_modules/gdax/node_modules/request/request.js:965:12)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:188:7)
```

```javascript
config.importer = {
  daterange: {
    // NOTE: these dates are in UTC
    from: "2016-07-01 12:00:00"
  }
}
```

Another question I have is, do I need to import data before trading? Or do I need to backtest? What is the prefer way? If the second, do I need to set up to heroku a sqlite db?

Thank you

**Comment by askmike** [comment]
> do I need to import data before trading? Or do I need to backtest?

You can trade right away, you don't need any historical data. The idea is that if you have a strategy that requires some history Gekko will keep running until this history is gathered. But I am seeing this is not the behaviour at gdax..

-----

Gekko supports running against a live market and backtesting. You never have to do the last one, but it is recommended that you you test a strategy first before using it with your real money.. Another option is to run against a live market but not use the real trader (but instead use the tradingSimulator, which will act as a paper trader).

----

> do I need to set up to heroku a sqlite db?

Gekko only needs a sqlite database if you want to persist the data. Reasons why you might want to do this:

- to backtest
- to always have history available you can feed into your strat: if you have a strat that requires a day of history you can stop gekko, change your strat, start gekko again and gekko can pick up a day of data from the database.

But as said before, it appears gdax integration behaves differently from other exchange integrations..

**Comment by askmike** [comment]
ping @smurfy

**Comment by smurfy** [comment]
What unit/asset combo is used, this would be helpful. I will try to reproduce / fix this.
Based on the "low" amount of trades i'm guessing ETH/BTC

I had something like this, while developing but it did not occured after a second try.
My guess at that time was there could be a problem if the time frame is to small (lots of trades at the same time).
But based on the dates shown this is not the case here.

**Comment by imkane** [comment]
I'm seeing this same bug with gdax importing ...

BTC / LTC

daterange: {
    // NOTE: these dates are in UTC
    from: "2017-01-01 00:00:00",
	to: "2017-06-26 00:00:00"
  }

**Comment by imkane** [comment]
It looks like GDAX may be having server issues, the site isn't even loading for me ...

**Comment by discosultan** [comment]
Same issue (v0.5.6):

```js
config.watch = {
  exchange: 'gdax',
  currency: 'EUR',
  asset: 'ETH',
}

config.importer = {
  daterange: {
    from: "2017-01-01 00:00:00"
  }
}
```

**Comment by CptanPanic** [comment]
I am having the same issue here with latest stable.  

```
2017-09-27 10:48:50 (DEBUG):    Processing 100 new trades. From 2016-07-21 23:17:15 UTC to 2016-07-22 00:21:09 UTC. (an hour)
2017-09-27 10:48:52 (DEBUG):    Backwards: 2016-07-22T00:21:21.085704Z (71379) to 2016-07-22T01:44:09.928163Z (71478)
2017-09-27 10:48:52 (DEBUG):    Processing 100 new trades. From 2016-07-22 00:21:21 UTC to 2016-07-22 01:44:09 UTC. (an hour)
2017-09-27 10:48:54 (DEBUG):    Backwards: 2016-07-22T01:44:10.141753Z (71479) to 2016-07-22T02:49:19.334655Z (71578)
2017-09-27 10:48:54 (DEBUG):    Processing 100 new trades. From 2016-07-22 01:44:10 UTC to 2016-07-22 02:49:19 UTC. (an hour)
/mnt/aux/linux/home/brian/gekko/exchanges/gdax.js:262
                log.debug('Backwards: ' + last.time + ' (' + last.trade_id + ') to ' + first.time + ' (' + first.trade_id + ')');
                                              ^

TypeError: Cannot read property 'time' of undefined
    at Trader.<anonymous> (/mnt/aux/linux/home/brian/gekko/exchanges/gdax.js:262:47)
    at Request._callback (/mnt/aux/linux/home/brian/gekko/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/mnt/aux/linux/home/brian/gekko/node_modules/gdax/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/mnt/aux/linux/home/brian/gekko/node_modules/gdax/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/mnt/aux/linux/home/brian/gekko/node_modules/gdax/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by askmike** [comment]
This has since been fixed!
