### ISSUE TITLE
Issue in Dev Branch CCI Strategy

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#626]
hey, testing the cci Strategy in dev branch, i get the following error.

2017-03-15 20:19:33 (INFO):		 Using the strategy: CCI
/Users/decoye/Desktop/gekko/strategies/CCI.js:27
  this.uplevel = settings.thresholds.up;
                         ^

TypeError: Cannot read property 'thresholds' of undefined
    at Base.method.init (/Users/decoye/Desktop/gekko/strategies/CCI.js:27:26)
    at Base.bound [as init] (/Users/decoye/Desktop/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/Users/decoye/Desktop/gekko/plugins/tradingAdvisor/baseTradingMethod.js:112:8)
    at Actor.setupTradingMethod (/Users/decoye/Desktop/gekko/plugins/tradingAdvisor/tradingAdvisor.js:58:17)
    at Actor.bound [as setupTradingMethod] (/Users/decoye/Desktop/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Actor (/Users/decoye/Desktop/gekko/plugins/tradingAdvisor/tradingAdvisor.js:23:8)
    at load (/Users/decoye/Desktop/gekko/core/pluginUtil.js:95:22)
    at /Users/decoye/Desktop/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/Users/decoye/Desktop/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/Users/decoye/Desktop/gekko/node_modules/async/dist/async.js:1015:17)

**Comment by askmike** [comment]
Can you post the CCI portion of your config? That error has to do with Gekko failing to parse your CCI settings.

**Comment by thegamecat** [comment]
If using the CLI - then make sure the config.cfg has a CCI entry:

> // CCI Settings
> config.CCI = {
>     constant: 0.015, // constant multiplier. 0.015 gets to around 70% fit
>     history: 90, // history size, make same or smaller than history
>     thresholds: {
>         up: 100, // fixed values for overbuy upward trajectory
>         down: -100, // fixed value for downward trajectory
>         persistence: 0 // filter spikes by adding extra filters candles
>     }
> };

If you're using the dev branch UI then make sure there is a .toml file for cci and it has the relevant settings:

> constant = 0.015
> 
> history = 90
> 
> [thresholds]
> up = 100
> down = -100
> persistence = 0

**Comment by askmike** [comment]
@thegamecat can you format this (or post a link to a gist or pastebin instead)?

**Comment by thegamecat** [comment]
I don't really understand how. The "code" link is rubbish.

**Comment by askmike** [comment]
Is this the CLI or UI? If the CLI, what is the gekko command you are running?

EDIT: ahhh @thegamecat that is a solution to the problem, didn't understand it haha.

**Comment by decoye** [comment]
I am using cli.

It's the standart dev branch that ive downloaded no modifications to any file made.
It's just out of the box.

**Comment by askmike** [comment]
@decoye can you post the CCI part of the config you selected?

**Comment by decoye** [comment]
Hey Mike,

Im not able to post it cuz the configure that comes with the dev branch does not hold the ccI strategy.
So when I try to copy the strategy into the config I get an error. 

So i currently have no idea how to run gekko from the cli using ccI. Which is unfortunate. Because I cant do tests with real money outside of cli.

**Comment by askmike** [comment]
Ah, I moved the config for each strat back into the sample-config. Could you use those CCI settings and try agian?
