### ISSUE TITLE
Error module.js:471

### ISSUE THREAD

**Issue by KimHono** [askmike/gekko#658]
My Gekko installation was running perfectly.
Then I saw that you published a new realease (Gekko v0.4.5) and decided to update mine.
Everything seemed OK.
But, while running "node gekko" I saw :
`module.js:471
    throw err;
    ^

Error: Cannot find module './tasks'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/gekko/node_modules/relieve/src/index.js:2:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`
Of course the message is about a module tasks, so I tried "npm install tasks".
But the problem is still there...

I'm using Node.js v6.10.1.
Thanks

**Comment by askmike** [comment]
This seems to be caused by an outdated dependency. Could you try running `npm install`?

**Comment by askmike** [comment]
I am pretty sure that should fix your issue, if it doesn't please reopen.

**Comment by KimHono** [comment]
Thanks askmike, Gekko works now !
