### ISSUE TITLE
cex.io API crashes gekko when the connection times out or errors repeatedly

### ISSUE THREAD

**Issue by kuzetsa** [askmike/gekko#69]
The cex.io exchange has been having some lag issues the past few days, and whenever it gets laggy and the API times out there's about a 50% chance for a gekko crash like this one to happen:

    2013-12-07 09:30:19 (DEBUG):    fetching new trades for new bucket at cex.io
    2013-12-07 09:30:22 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:30:23 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:30:36 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:30:36 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:30:50 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:30:50 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:31:04 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:31:04 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:31:17 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:31:18 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:31:31 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:31:31 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:31:45 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:31:45 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:31:59 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:31:59 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:32:12 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:32:13 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:32:27 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:32:27 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:32:40 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:32:40 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:32:54 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:32:54 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:33:08 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:33:08 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:33:22 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:33:22 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:33:35 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:33:35 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:33:49 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:33:49 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:34:03 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:34:03 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:34:16 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:34:16 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:34:30 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:34:30 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:34:44 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:34:44 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:34:58 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:34:58 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:35:12 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:35:12 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:35:26 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:35:27 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:35:40 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:35:41 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:35:54 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:35:55 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:36:08 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:36:09 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:36:22 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:36:22 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:36:36 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:36:37 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:36:50 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:36:51 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:04 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:05 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:19 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:19 (DEBUG):    fetching new trades for new bucket at cex.io
    2013-12-07 09:37:23 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:23 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:23 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:37 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:40 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:40 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:40 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:54 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:57 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:37:58 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:37:58 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:11 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:15 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:15 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:15 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:28 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:32 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:32 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:33 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:46 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:50 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:38:50 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:38:50 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:39:04 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:39:07 (DEBUG):    cex.io fetching from tid 642944
    2013-12-07 09:39:08 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:39:08 (DEBUG):    cex.io returned an error, retrying..
    2013-12-07 09:39:08 (DEBUG):    cex.io returned an error, retrying..

    c:\gekko\exchanges\cexio.js:157
        function() { method.apply(self, args) },
                        ^
    TypeError: Cannot call method 'apply' of undefined
        at null._onTimeout (c:\gekko\exchanges\cexio.js:157:25)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by askmike** [comment]
fixed.
