### ISSUE TITLE
API Key on Poloniex not working

### ISSUE THREAD

**Issue by hoerbi1000** [askmike/gekko#694]
since Thursday im not able to login to poloniex with my api , im always getting 

`Unhandled rejection Error: 401 {"ok":false,"error_code":401,"description":"Unauthorized"}
    at /home/hoerbi/gekko/node_modules/node-telegram-bot-api/lib/telegramPolling.js:133:17
    at tryCatcher (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/hoerbi/gekko/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
`

somebody else got this problem? 
i have checkey my API , but this config was running some days.

I have also tried to generate a new API

**Comment by askmike** [comment]
The error you posted comes from `node-telegram-bot-api/lib/telegramPolling.js`. Did you change anything to your telegram configuration?

**Comment by hoerbi1000** [comment]
i feel  so stuipd now, i have change my telegram bot to a new one :(

sorry for the bad question.

**Comment by askmike** [comment]
No worries, glad you were able to solve it. The error message was also not very descriptive so..
