### ISSUE TITLE
Unable to find datasets in the following markets

### ISSUE THREAD

**Issue by nozyqubis** [askmike/gekko#701]
I am getting this error : Unable to find datasets in the following markets:
- poloniex:

TypeError: Cannot read property 'close' of undefined
    at scan (/home/alpha/gekko/core/workers/dateRangeScan/child.js:20:13)
    at async.parallel (/home/alpha/gekko/core/tools/dateRangeScanner.js:46:16)
    at /home/alpha/gekko/node_modules/async/dist/async.js:3853:9
    at /home/alpha/gekko/node_modules/async/dist/async.js:484:16
    at iterateeCallback (/home/alpha/gekko/node_modules/async/dist/async.js:1013:24)
    at /home/alpha/gekko/node_modules/async/dist/async.js:988:16
    at /home/alpha/gekko/node_modules/async/dist/async.js:3850:13
    at apply (/home/alpha/gekko/node_modules/async/dist/async.js:41:25)
    at /home/alpha/gekko/node_modules/async/dist/async.js:76:12
    at Statement.<anonymous> (/home/alpha/gekko/plugins/sqlite/reader.js:135:5)

**Comment by askmike** [comment]
what database are you using?

**Comment by askmike** [comment]
Ah nevermind got it! Sorry about that, should really better test before pushing to stable..
