### ISSUE TITLE
Error while importing ETH data from GDAX Exchange

### ISSUE THREAD

**Issue by lucarosellini** [askmike/gekko#730]
While trying to download historical ETH data from GDAX exchange to sqlite3, I consistently get the following error at around "2017-01-08 13:40:00 UTC" :
```
/home/lujo/gekko/core/budfox/candleCreator.js:76
  this.threshold = candles.pop().start;
                                ^

TypeError: Cannot read property 'start' of undefined
    at CandleCreator.write (/home/lujo/gekko/core/budfox/candleCreator.js:76:33)
    at CandleCreator.bound (/home/lujo/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.processTrades (/home/lujo/gekko/core/budfox/candleManager.js:32:22)
    at TradeBatcher.bound (/home/lujo/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at emitOne (events.js:96:13)
    at TradeBatcher.emit (events.js:188:7)
    at TradeBatcher.bound [as emit] (/home/lujo/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at TradeBatcher.write (/home/lujo/gekko/core/budfox/tradeBatcher.js:78:8)
    at TradeBatcher.bound (/home/lujo/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processTrades (/home/lujo/gekko/core/markets/importer.js:99:21)
```

In order to not get stuck I applied the following quick and dirty fix, but I am sure there's a much more elegant way to solve this:

```
diff --git a/core/budfox/candleCreator.js b/core/budfox/candleCreator.js
index e2ae35d..46d934d 100644
--- a/core/budfox/candleCreator.js
+++ b/core/budfox/candleCreator.js
@@ -73,8 +73,11 @@ CandleCreator.prototype.write = function(batch) {
   candles = this.addEmptyCandles(candles);

   // the last candle is not complete
-  this.threshold = candles.pop().start;
+  var popped = candles.pop();

+  if (typeof(popped) != 'undefined'){
+    this.threshold = popped.start;
+  }
   this.emit('candles', candles);
 }
```

Best,
Luca

**Comment by askmike** [comment]
Interesting, thanks for the report! Will have a look at this asap.

**Comment by askmike** [comment]
It is definitely an edge case. I did something similar as your fix to solve this.
