### ISSUE TITLE
Needing some advice on this startegy i've set

### ISSUE THREAD

**Issue by Pedro942** [askmike/gekko#735]
Hi Guys so i finally written a strategy based on 3 indicators but it doesn't work and says : 

2017-05-04 11:57:42 (INFO):     Setting up Gekko in backtest mode
2017-05-04 11:57:42 (INFO):
2017-05-04 11:57:42 (INFO):     Setting up:
2017-05-04 11:57:42 (INFO):              Trading Advisor
2017-05-04 11:57:42 (INFO):              Calculate trading advice
2017-05-04 11:57:42 (INFO):              Using the strategy: strat
C:\Users\Scorp\Desktop\BOTS\gekko-stable\strategies\strat.js:11
up = 0.005,persistence = 1};
^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Actor.setupTradingMethod (C:\Users\Scorp\Desktop\BOTS\gekko-stable\plugins\tradingAdvisor\tradingAdvisor.js:48:16)

**Comment by Pedro942** [comment]
Here is my strategy : 

// Let's create our own strategy
var strat = {};

// Prepare everything our strat needs
strat.init = function() {
  // start of with no investment
  this.currentTrend = 'short';
  // your code!
  // add a native MACD
var parameters = {short: 12, long: 26, signal: 9,down = -0.0001
up = 0.005,persistence = 1};
this.addIndicator('mynativemacd', 'MACD', parameters);
 //add native RSI
 var parameters1 = {interval = 14,low = 30, high = 70, persistence = 2};
this.addIndicator('mynativeRSI', 'RSI', parameters1);
//add native CCI
var parameters2 = {constant = 0.015,history = 90,up = 100,down = -100,persistence = 0};
this.addIndicator('mynativeCCI','CCI',parameters2);

}

// What happens on every new candle?
strat.update = function(candle) {
  // your code!
}

// For debugging purposes.
strat.log = function() {
  // your code!

}

// Based on the newly calculated
// information, check if we should
// update or not.
strat.check = function() {
  // your code!
    //setting vars for MACD results
  var MACD = this.indicators.macd.macd;
  var MACDsaysBUY = down < -0.0001;
  var MACDsaysSELL = up > 0.005;
  // setting vars for RSI results
  var RSI = this.indicators.rsi.rsi;
  var RSIsaysBUY = RSI > RSIhigh;
  var RSIsaysSELL = RSI < RSIlow;
  // setting vars for CCI results
  var CCI = this.indicators.cci.cci;
  var CCIsaysBUY = down < -100;
  var CCIsaysSELL = up > 100;
   /// Setting conditions
   
  if(this.currentTrend === 'long') {

    // maybe we need to advice short now?

    // only if BOTH MACD and RSI and CCI say so:
    if(MACDsaysSELL && RSIsaysSELL && CCIsaysSELL ) {
      this.currentTrend = 'short';
      this.advice('short')
    }

  } else if(this.currentTrend === 'short') {

    // maybe we need to advice long now?

    // only if BOTH MACD and RSI and CCI say so:
    if(MACDsaysBUY && RSIsaysBUY && CCIsaysBUY) {
      this.currentTrend = 'long';
      this.advice('long')
    }

}

module.exports = strat;

**Comment by askmike** [comment]
You are missing a comma here:

     var parameters = {short: 12, long: 26, signal: 9,down = -0.0001
     up = 0.005,persistence = 1};

change it into:

     var parameters = {short: 12, long: 26, signal: 9,down = -0.0001,
     up = 0.005,persistence = 1};

**Comment by Pedro942** [comment]
even though i set the comma, this is what i get after running 
gekko-stable>node gekko --config config.js --backtest

2017-05-04 12:32:45 (INFO):     Setting up Gekko in backtest mode
2017-05-04 12:32:45 (INFO):
2017-05-04 12:32:45 (INFO):     Setting up:
2017-05-04 12:32:45 (INFO):              Trading Advisor
2017-05-04 12:32:45 (INFO):              Calculate trading advice
2017-05-04 12:32:45 (INFO):              Using the strategy: strat
C:\Users\Scorp\Desktop\BOTS\gekko-stable\strategies\strat.js:10
var parameters = {short: 12, long: 26, signal: 9,down = -0.0001,
                                                 ^^^^^^^^^^^^^^
SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Actor.setupTradingMethod (C:\Users\Scorp\Desktop\BOTS\gekko-stable\plugins\tradingAdvisor\tradingAdvisor.js:48:16)

**Comment by askmike** [comment]
Can you please create a gist on github (gist.github.com) and send the link here? That's a lot easier to debug.

**Comment by Pedro942** [comment]
here it is thanks for fast replying askmike :D
https://gist.github.com/Pedro942/b05d4340d44ecd7c02ecbe2bcfeab1ae

**Comment by askmike** [comment]
there were a number of bugs and typos in there.

This works: https://gist.github.com/askmike/a50c1438095bc56a09723c90bfefacdf

------

Gekko allows you to create your own strategies, but you do have to program them in valid javascript. The problems you were having had to do with bugs in your javascript code. Gekko was trying to execute your strat but couldn't because it had syntax errors.

**Comment by Pedro942** [comment]
Well for sure it does work but it doesn't trade even if I changed the values nothing happens on the backtest

**Comment by askmike** [comment]
There is logic that advices on certain conditions, if these conditions are never met I suggest you start logging values to see what is happening.
