### ISSUE TITLE
What is this error ?

### ISSUE THREAD

**Issue by fasetto** [askmike/gekko#738]
I tried to run gekko like this: `node gekko --ui`
And i have an error.
I searched but i didn't find any packages like that.
```
module.js:472
    throw err;
    ^

Error: Cannot find module './tasks'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/gekko/node_modules/relieve/src/index.js:2:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by askmike** [comment]
Strange, it indicates an error with a dependency. Can you delete the `node_modules` folder and rerun `npm install`?

**Comment by fasetto** [comment]
It worked. 
Thank you.
