### ISSUE TITLE
Backtest CLI Date Range

### ISSUE THREAD

**Issue by decoye** [askmike/gekko#741]
Hey Mike,

can you tell me if i am able to define a timeframe for my backtest on the command line?

**Comment by decoye** [comment]
this:
In your config set the backtest.daterange to scan. This will force Gekko to scan the local database to figure out what dataranges are available. If you already know exactly what daterange you would like to backtest against, you can set the backtest.daterange directly (set backtest.daterange as an object with the keys from and to and the values as a data parsable by moment).

is unfortunately not clear to me.

**Comment by askmike** [comment]
Hey!

set it from this:

    config.backtest = {
      daterange: 'scan',
      batchSize: 50
    }

to this:

    config.backtest = {
      daterange: {
        from: "2017-02-01 00:00:00",
        to: "2017-03-01 00:00:00"
      },
      batchSize: 50
    }

Note that these dates will be in UTC, not your local timezone.

**Comment by jamesalbert** [comment]
@askmike I made the same change you just did, but when I change it back to 'scan', it gives this error:
```sh
...
2018-01-22 00:00:05 (INFO):	Setting up:
2018-01-22 00:00:05 (INFO):		 Performance Analyzer
2018-01-22 00:00:05 (INFO):		 Analyzes performances of trades
2018-01-22 00:00:05 (INFO):

/usr/src/app/core/markets/backtest.js:12
var to = moment.utc(daterange.to);
                              ^

TypeError: Cannot read property 'to' of undefined
    at Object.<anonymous> (/usr/src/app/core/markets/backtest.js:12:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /usr/src/app/core/pipeline.js:185:20
    at /usr/src/app/node_modules/async/dist/async.js:3853:9
```

edit: as soon as I post on github, I figured it out. Fat fingered datarange instead of daterange
