### ISSUE TITLE
Importing error in CLI

### ISSUE THREAD

**Issue by KimHono** [askmike/gekko#755]
While Gekko is running perfectly, when I try to import historical datas, I get this error : 

	Gekko v0.4.10
	I'm gonna make you rich, Bud Fox. 

2017-05-25 07:52:15 (INFO):	Setting up Gekko in importer mode
2017-05-25 07:52:15 (INFO):	
2017-05-25 07:52:15 (INFO):	Setting up:
2017-05-25 07:52:15 (INFO):		 Candle writer
2017-05-25 07:52:15 (INFO):		 Store candles in a database
2017-05-25 07:52:15 (INFO):	

2017-05-25 07:52:15 (WARN):	The plugin Trading Advisor does not support the mode importer. It has been disabled.
2017-05-25 07:52:15 (WARN):	The plugin Paper Trader does not support the mode importer. It has been disabled.
2017-05-25 07:52:15 (DEBUG):	No end date specified for importing, setting to 2017-05-25 07:52:15
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/KimHono/gekko/core/../importers/exchanges/Poloniex'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/KimHono/gekko/core/markets/importer.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by askmike** [comment]
When using the CLI you need to specify the exchange using small caps. So replace `Poloniex` with `poloniex`.

**Comment by KimHono** [comment]
Well done, thanks askmike !
This advice may be written in "sample-config.js" ?
