### ISSUE TITLE
Backtesting on large sets via CommandLine and MongoDB errors (sometimes)

### ISSUE THREAD

**Issue by f0o** [askmike/gekko#774]
With datasets larger than a year stored in MongoDB (on the same server) it seems that gekko takes too long time to fetch/process the data mid-test.
Eventually gekko errors.

I will do some more debugging and append to this issue.

```
Gekko encountered an error and can't continue

Error:

{ MongoError: Cursor not found, cursor id: 18478283947
    at Function.MongoError.create (/home/f0o/gekko/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/f0o/gekko/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/home/f0o/gekko/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/home/f0o/gekko/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/home/f0o/gekko/node_modules/mongodb-core/lib/connection/connection.js:331:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
  name: 'MongoError',
  message: 'Cursor not found, cursor id: 18478283947',
  ok: 0,
  errmsg: 'Cursor not found, cursor id: 18478283947',
  code: 43,
  codeName: 'CursorNotFound' } '\n\n'

Meta debug info:

Gekko version: v0.4.10
Nodejs version: v8.0.0
```

MongoDB log:
```
2017-06-07T13:58:38.780+0000 I COMMAND  [conn928] command gekko.poloniex_candles command: getMore { getMore: 18478283947, collection: "poloniex_candles", batchSize: 1000 } originatingCommand: { find: "poloniex_candles", filter: { pair: "USDT_BTC" } } planSummary: COLLSCAN cursorid:18478283947 keysExamined:0 docsExamined:235475 numYields:1843 nreturned:1000 reslen:1700111 locks:{ Global: { acquireCount: { r: 3688 } }, Database: { acquireCount: { r: 1844 } }, Collection: { acquireCount: { r: 1844 } } } protocol:op_query 542ms
```

From mongodb's jira (https://jira.mongodb.org/browse/NODE-844):
```
you might want to set the no cursor timeout flag in this case but be aware that this could cause the cursors to live for ever if they are not explicitly killed.
```

I tried adding `{ timeout: false }` to the options of every `find()` call in `plugins/mongodb/*` but it didnt solve the issue

**Comment by askmike** [comment]
The mongo adapter is very outdated, I'll do some testing myself soon (I am surprised it still backtests with latest stable). Never seen this issue before, will keep this open until for now!

**Comment by f0o** [comment]
So far I could only mitigate it by setting the timeout on the mongodb server to the largest possible value. However gekko seems to degrade in performance the longer the backtester works (even with sufficient resources idling around) which eventually make it hit that timeout again.

**Comment by joernroeder** [comment]
> The mongo adapter is very outdated, …

@askmike just stumbled over this issue. which storage do you suggest for large datasets? thx

**Comment by joernroeder** [comment]
@f0o i had the same issue and updated the `Reader.prototype.get` method to use the [mongodb aggregation pipeline](https://docs.mongodb.com/manual/aggregation/#aggregation-pipeline) – and therefore the collection indexes. I didn't make any benchmarks but i don't see a lot of long running queries in the logs right now and an initial scan of the available datasets is much quicker now.

```js
Reader.prototype.get = function get (from, to, what, next) { // returns all fields in general
  // Find some documents
  this.collection.aggregate([
    { $match: { pair: this.pair, start: { $gte: from, $lte: to } } },
    { $sort: { start: 1 } }
  ], (err, docs) => {
    if (err) {
      return util.die('DB error at `get`');
    }
    return next(null, docs);
  });
}
```
