### ISSUE TITLE
BTC-e.com live - unable to buy: Error...

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#776]
Error you incorrectly entered one of the fields.

Any idea what's causing this?

**Comment by askmike** [comment]
I will pick this up when going over BTCe as part of #737.

**Comment by netcoding** [comment]
The same problem at me ;-(

`2017-07-07 10:53:28 (INFO):     Attempting to BUY 0.020058609401120624 BTC at BTC-E
2017-07-07 10:53:30 (ERROR):    unable to buy: Error: You incorrectly entered one of fields.
    at Request._callback (/opt/gekko.GIT/node_modules/btc-e/btc-e.js:79:23)
    at Request.self.callback (/opt/gekko.GIT/node_modules/btc-e/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/gekko.GIT/node_modules/btc-e/node_modules/request/request.js:978:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/gekko.GIT/node_modules/btc-e/node_modules/request/request.js:929:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`
