### ISSUE TITLE
BTCe.com nonce issues when order not filled.

### ISSUE THREAD

**Issue by thegamecat** [askmike/gekko#780]
2017-06-08 21:48:03 (INFO):	Attempting to BUY 3.1398476313056083 ETH at BTC-E
2017-06-08 21:49:05 (INFO):	BUY order was not (fully) filled, cancelling and creating new order
/Users/freefall/gekkoinstalls/gekko/node_modules/btc-e/btc-e.js:46
    params.nonce = Math.round((new Date()).getTime() / 1000);
                 ^

TypeError: Cannot create property 'nonce' on number '1832535087'
    at BTCE.makeRequest (/Users/freefall/gekkoinstalls/gekko/node_modules/btc-e/btc-e.js:46:18)
    at BTCE.orderList (/Users/freefall/gekkoinstalls/gekko/node_modules/btc-e/btc-e.js:126:8)
    at BTCE.bound [as orderList] (/Users/freefall/gekkoinstalls/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.cancelOrder (/Users/freefall/gekkoinstalls/gekko/exchanges/btce.js:146:13)
    at Trader.bound [as cancelOrder] (/Users/freefall/gekkoinstalls/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Manager.finish (/Users/freefall/gekkoinstalls/gekko/plugins/trader/portfolioManager.js:291:21)
    at bound (/Users/freefall/gekkoinstalls/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Trader.check (/Users/freefall/gekkoinstalls/gekko/exchanges/btce.js:137:7)
    at bound (/Users/freefall/gekkoinstalls/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Request._callback (/Users/freefall/gekkoinstalls/gekko/node_modules/btc-e/btc-e.js:82:5)

**Comment by askmike** [comment]
Thanks! Will look at it asap :)

**Comment by askmike** [comment]
This does happen 100% of the time?

**Comment by thegamecat** [comment]
Yes.

**Comment by askmike** [comment]
I will pick this up when going over BTCe as part of #737.

**Comment by askmike** [comment]
This was not fixed in f775c1d yet:

> /Users/pear/projects/gekko/node_modules/btc-e/btc-e.js:78
>     params.nonce = Math.round((new Date()).getTime() / 1000);
>                  ^
> 
> TypeError: Cannot create property 'nonce' on number '1885514729'
>     at BTCE.makeRequest (/Users/pear/projects/gekko/node_modules/btc-e/btc-e.js:78:18)
>     at BTCE.orderList (/Users/pear/projects/gekko/node_modules/btc-e/btc-e.js:127:8)
>     at BTCE.bound [as orderList] (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
>     at Trader.cancelOrder (/Users/pear/projects/gekko/exchanges/btce.js:198:13)
>     at Trader.bound [as cancelOrder] (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
>     at Manager.cancelLastOrder (/Users/pear/projects/gekko/plugins/trader/portfolioManager.js:271:17)
>     at Manager.bound [as cancelLastOrder] (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
>     at Manager.trade (/Users/pear/projects/gekko/plugins/trader/portfolioManager.js:147:17)
>     at Manager.bound [as trade] (/Users/pear/projects/gekko/node_modules/lodash/dist/lodash.js:729:21)
>     at Trader.processAdvice (/Users/pear/projects/gekko/plugins/trader/trader.js:51:18)
> RECEIVED ERROR IN GEKKO 224116916502668
> Child process has died.
