### ISSUE TITLE
start problem (headless)

### ISSUE THREAD

**Issue by pimbolilu** [askmike/gekko#819]
Hi, can someone help me with this problem:

TAlib is disabled
/home/ubuntu/gekko/web/server.js:74
server.listen(config.api.port, config.api.host, '::', () => {
                        ^

TypeError: Cannot read property 'port' of undefined
    at Object.<anonymous> (/home/ubuntu/gekko/web/server.js:74:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/gekko/gekko.js:43:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

**Comment by askmike** [comment]
Gekko was unable to (properly) parse your UIconfig. Can you post it here so we can troubleshoot?

**Comment by pimbolilu** [comment]
Hi,

I used the example from the webpage:


```
const CONFIG = {
    headless: true,
    api: {
        host: '0.0.0.0',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: '192.168.2.2', // Set this to the IP of the machine that will run Gekko
        port: 3000,
        path: '/'
    }
}
```

**Comment by askmike** [comment]
Does it also contains [these lines](https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L21-L24) at the end? Those are necessary as well. If that was the problem I'll update the example.

**Comment by pimbolilu** [comment]
ah thank for your help. now it works, I removed them (copy - paste..)

**Comment by askmike** [comment]
great! I'll update the docs soon.
