### ISSUE TITLE
ReferenceError: candle is not defined

### ISSUE THREAD

**Issue by wesgarrison** [askmike/gekko#821]
Fresh install, just trying to get it going.  Installed from git, stable branch, b87c4d6 .

Was able to:
* Set up an import through the UI
* Set up a watcher through the UI

However, starting a paper trader through the UI failed.
All of the basic strategies fail with the default configurations.

Error on the console:

```
  <-- POST /api/backtest
/Users/wg/code/ethereum/gekko/plugins/tradingAdvisor/baseTradingMethod.js:280
      candle
      ^

ReferenceError: candle is not defined
    at Base.<anonymous> (path/gekko/plugins/tradingAdvisor/baseTradingMethod.js:280:7)
    at Timeout._onTimeout (path/gekko/node_modules/lodash/dist/lodash.js:5496:43)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
  xxx POST /api/backtest 500 332ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (path/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

### version

```
node gekko --version
Gekko version: v0.4.10
Nodejs version: v8.1.3
```

Happy to provide more information for diagnosis.

**Comment by ljm625** [comment]
same issue here

**Comment by askmike** [comment]
Apologies! I pushed a hotfix (for #817) and it appears I didn't test properly. Pushed a bugfix for this now.

**Comment by wesgarrison** [comment]
Confirming this fix worked for me.  Thanks for the amazing support @askmike !
