### ISSUE TITLE
Error with Developing for the Gekko UI frontend

### ISSUE THREAD

**Issue by imkane** [askmike/gekko#832]
re: https://gekko.wizb.it/docs/internals/gekko_ui.html

On **feature/ui-trader** branch.

```
# path to webserver
cd gekko/web
# launch the server - we use this API
node server
```

Got to this step and received:

```
[user@vps2 web]$ node server
TAlib is enabled
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3002
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```
Any ideas?

**Comment by sanitariu** [comment]
There is already running gekko or something else which works on port 3002.
Try to find it.

**Comment by imkane** [comment]
Oh duh - that one should have been obvious lol. Thanks!
