### ISSUE TITLE
Errors when run simultaneous backtests

### ISSUE THREAD

**Issue by AntiLopa** [askmike/gekko#839]
I run some backtests simultaneously trough different terminals and sometimes I get errors.

`Error: near line 1: near ",": syntax error` - I'm sorry I don't have more info as to which file, I know it's impossible to know where it come from. It's just for documentation.

```
/Users/macbook/Documents/gekko/gekko.js:50
  config.trader.enabled &&
               ^

TypeError: Cannot read property 'enabled' of undefined
    at Object.<anonymous> (/Users/macbook/Documents/gekko/gekko.js:50:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

This happened once or twice but I'm sure I'll get more of this as I only now started to run tests simultaneously.

**Comment by AntiLopa** [comment]
I was using the same config file for both threads...
