### ISSUE TITLE
ui trader feature error

### ISSUE THREAD

**Issue by ghost** [askmike/gekko#842]
______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

        Gekko v0.4.11
        I'm gonna make you rich, Bud Fox.

TAlib is disabled
module.js:471
    throw err;
    ^

Error: Cannot find module '../api-keys.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\Desktop\gekko-feature-ui-trader\web\apiKeyManager.js:19:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

can run stable branch fine without errors why feature ui trader throws this error.

**Comment by ghost** [comment]
anyone know how to fix this?

**Comment by askmike** [comment]
yes, create the missing file.

This branch is in development and not stable, therefor I cannot offer any support at the moment.
