### ISSUE TITLE
Gekko appears to wait to execute positions?

### ISSUE THREAD

**Issue by mcowger** [askmike/gekko#845]
I've been having trouble with a custom strategy I'm building....it seems that Gekko is waiting extra periods to execute trades (at least in back testing) compared to when they are requested.   To find this, I added log statements to log exactly the price and candle ID on which i issue the `this.advice('long')` vs. when gekko seems to execute the trade.

See below:

```
2017-07-13 18:14:29 (DEBUG):    We dont have any assets, lets see if we should buy something @ CID 14009
2017-07-13 18:14:29 (DEBUG):    We dont have any assets, lets see if we should buy something @ CID 14014
2017-07-13 18:14:29 (DEBUG):    Issuing BUY guidance @ 201.53 @ CID 14014
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14019
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14024
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14029
2017-07-13 18:14:29 (INFO):     2017-07-10 20:53:00: Paper trader simulated a BUY       0.00000000 USD  => 0.50864751 ETH
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14035
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14040
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 14045

```
As you can see, there are at least 3 run thoughs of the `update` function between when the long is issues and when Paper Trader executes it....any idea why?

sometimes this results in crossed up orders when the buy and sell are close together:

```
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15207
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15212
2017-07-13 18:14:29 (DEBUG):    Issuing SELL guidance @ 193.87 @ CID 15212
2017-07-13 18:14:29 (DEBUG):    We dont have any assets, lets see if we should buy something @ CID 15217
2017-07-13 18:14:29 (DEBUG):    We dont have any assets, lets see if we should buy something @ CID 15222
2017-07-13 18:14:29 (DEBUG):    We dont have any assets, lets see if we should buy something @ CID 15227
2017-07-13 18:14:29 (DEBUG):    Issuing BUY guidance @ 193.63 @ CID 15227
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15232
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15237
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15242
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15247
2017-07-13 18:14:29 (INFO):     2017-07-11 16:53:00: Paper trader simulated a SELL      102.71625541 USD <= 0.00000000 ETH
2017-07-13 18:14:29 (INFO):     2017-07-11 16:53:00: Paper trader simulated a BUY       0.00000000 USD  => 0.53698341 ETH
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15252
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15257
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15262
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15267
2017-07-13 18:14:29 (DEBUG):    We have assets, lets see if we should sell something @ CID 15272

```

**Comment by askmike** [comment]
Hey! A few questions:

- Does your custom strategy use talib indicators?
- What gekko version are you running (what git branch)?

**Comment by mcowger** [comment]
Mike -

No - only the built in MACD (plus other custom values caulcated in the update function)

Running on stable branch.  

M

**Comment by askmike** [comment]
Would you mind testing the same in the development branch? It might still
be non sequential, but the numbers might be different and correct.

https://github.com/askmike/gekko/tree/develop

**Comment by mcowger** [comment]
The develop branch seems to like me less :(

```
pi@raspberrypi:~/gekko-dev $ node gekko --config config.js --backtest

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

module.js:471
    throw err;
    ^

Error: Cannot find module 'retry'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/gekko-dev/core/util.js:7:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by askmike** [comment]
@mcowger every time you switch branches you need to rerun `npm install` since the dependencies might have changed!

**Comment by koendc** [comment]
FWIW: I saw similar issues where the paper trader was executing trading advice at the wrong time. After pulling the stable branch again, the problems disappeared. Most likely this commit https://github.com/askmike/gekko/commit/a3cc7d47efa4ea85277ee7da328c6697cd3056d0 solved it.

**Comment by askmike** [comment]
I assume so too, if it isn't @mcowger please let me know :)
