### ISSUE TITLE
[performanceAnalyzer] TypeError: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by askmike** [askmike/gekko#886]
Found by @tkh23 ([here](https://github.com/askmike/gekko/issues/498#issuecomment-318157719)):

    TypeError: Cannot read property 'currency' of undefined
        at PerformanceAnalyzer.calculateReportStatistics (/home/tkh/gekko2/plugins/performanceAnalyzer/performanceAnalyzer.js:133:29)
        at PerformanceAnalyzer.bound [as calculateReportStatistics] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at PerformanceAnalyzer.finalize (/home/tkh/gekko2/plugins/performanceAnalyzer/performanceAnalyzer.js:170:23)
        at PerformanceAnalyzer.bound [as finalize] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at /home/tkh/gekko2/core/gekkoStream.js:44:9
        at Function.forEach (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:3298:15)
        at Gekko.shutdown (/home/tkh/gekko2/core/gekkoStream.js:42:5)
        at Base.finish (/home/tkh/gekko2/plugins/tradingAdvisor/baseTradingMethod.js:322:12)
        at Base.bound [as finish] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at Actor.finish (/home/tkh/gekko2/plugins/tradingAdvisor/tradingAdvisor.js:80:15)
    --> in Database#all('\n    SELECT * from candles_USDT_ZEC\n    WHERE start <= 1501004460 AND start >= 1501006560\n    ORDER BY start ASC\n  ', [Function])
        at Reader.get (/home/tkh/gekko2/plugins/sqlite/reader.js:98:11)
        at Reader.bound [as get] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at Market.get (/home/tkh/gekko2/core/markets/backtest.js:61:15)
        at Market.bound [as get] (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at Market.processCandles (/home/tkh/gekko2/core/markets/backtest.js:105:10)
        at bound (/home/tkh/gekko2/node_modules/lodash/dist/lodash.js:729:21)
        at Statement.<anonymous> (/home/tkh/gekko2/plugins/sqlite/reader.js:108:5)
    [tkh@tk44 gekko2]$ 

Seems to happen during a backtest.

**Comment by askmike** [comment]
@tkh23 Sorry about this, can you possible email me your local database file and config used? gekko@mvr.me

**Comment by tkh23** [comment]
Which file is the local database file? :|

**Comment by askmike** [comment]
inside the history folder there are some files with the name of the exchange in them. If you can mail those!

**Comment by tkh23** [comment]
[zip.zip](https://github.com/askmike/gekko/files/1177885/zip.zip)
Gmail is not allowing me to. Here the upload, just delete the reply when you are done (you can do that right?

**Comment by askmike** [comment]
Downloaded it now, will have a look at it asap

**Comment by askmike** [comment]
The problem was quite simple:

When running a backtest over the CLI you need to enable the paper trader plugin (in your config) to simulate trading. This error was caused by the performanceAnalyzer expecting some trader to have given it portfolio information, which did not happen because you did not have it enabled. I now updated the docs to better reflect what plugins you need to backtest over the CLI.
