### ISSUE TITLE
v0.5.0: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by acerolakirsche** [askmike/gekko#897]
Hi,
i got this error , if i run gekko in local server mode.
And after click on "scan available data":

<-- GET /api/imports
  --> GET /api/imports 200 41ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 4ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 4ms 12b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 3,527ms 31.17kb
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 3ms 2b
  <-- GET /api/imports
  --> GET /api/imports 200 6ms 2b
  <-- GET /api/gekkos
  --> GET /api/gekkos 200 3ms 2b
  <-- GET /api/apiKeys
  --> GET /api/apiKeys 200 2ms 12b
  <-- GET /api/exchanges
  --> GET /api/exchanges 200 12ms 31.17kb
  <-- POST /api/scansets
  xxx POST /api/scansets 500 15ms -

  TypeError: Cannot read property 'path' of undefined
      at module.exports (/home/pi/gekko/core/workers/datasetScan/parent.js:15:42)
      at /home/pi/gekko/node_modules/nodegit-promise/lib/node-extensions.js:24:20
      at tryCallTwo (/home/pi/gekko/node_modules/nodegit-promise/lib/core.js:45:5)
      at doResolve (/home/pi/gekko/node_modules/nodegit-promise/lib/core.js:173:13)
      at new Promise (/home/pi/gekko/node_modules/nodegit-promise/lib/core.js:65:3)
      at /home/pi/gekko/node_modules/nodegit-promise/lib/node-extensions.js:19:12
      at Object.route (/home/pi/gekko/web/routes/scanDatasets.js:16:21)
      at route.next (<anonymous>)
      at Object.dispatch (/home/pi/gekko/node_modules/koa-router/lib/router.js:334:12)
      at dispatch.next (<anonymous>)
      at onFulfilled (/home/pi/gekko/node_modules/co/index.js:65:19)
      at /home/pi/gekko/node_modules/co/index.js:54:5
      at Promise (<anonymous>)
      at Object.co (/home/pi/gekko/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/pi/gekko/node_modules/co/index.js:118:63)
      at next (/home/pi/gekko/node_modules/co/index.js:99:29)
      at onFulfilled (/home/pi/gekko/node_modules/co/index.js:69:7)
      at /home/pi/gekko/node_modules/co/index.js:54:5
      at Promise (<anonymous>)
      at Object.co (/home/pi/gekko/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/pi/gekko/node_modules/co/index.js:118:63)
      at next (/home/pi/gekko/node_modules/co/index.js:99:29)
      at onFulfilled (/home/pi/gekko/node_modules/co/index.js:69:7)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

an if i click on the button "importeur"
i got error message: "IMPORT ERROR: Child Process has died" on the browser.
And Error in Console:
Import 579609758026546 started
  --> POST /api/import 200 74ms 150b
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/pi/gekko/core/../plugins/undefined/writer'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at load (/home/pi/gekko/core/pluginUtil.js:90:25)
    at /home/pi/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/pi/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/pi/gekko/node_modules/async/dist/async.js:1034:9
    at _asyncMap (/home/pi/gekko/node_modules/async/dist/async.js:1154:5)
    at /home/pi/gekko/node_modules/async/dist/async.js:1240:16
RECEIVED ERROR IN IMPORT 579609758026546
Child process has died.

my Config:
// This config is used in both the
// frontend as well as the web server.

// see https://github.com/askmike/gekko/blob/stable/docs/installing_gekko_on_a_server.md

const CONFIG = {
    headless: true,
    api: {
        host: '0.0.0.0',
        port: 3000,
    },
    ui: {
        ssl: false,
        host: '192.168.178.74', // Set this to the IP of the machine that will run Gekko
        port: 3000,
        path: '/'
    }
}
if(typeof window === 'undefined')
  module.exports = CONFIG;
else
  window.CONFIG = CONFIG;

**Comment by askmike** [comment]
Your UIconfig is missing an `adapter` property: https://github.com/askmike/gekko/blob/stable/web/vue/UIconfig.js#L18

**Comment by acerolakirsche** [comment]
oh silly me. thx for the info!

**Comment by askmike** [comment]
I am guessing this is because you used the UIconfig found here: https://gekko.wizb.it/docs/installation/installing_gekko_on_a_server.html

These were outdated, but I have updated them now :)
