### ISSUE TITLE
Error: Kraken API returned error: Service:Unavailable

### ISSUE THREAD

**Issue by Tr4sK** [askmike/gekko#930]
Hi,
I’m often having some issue while requesting the Kraken API.
I didn’t found a similar issue so here is the debug log to give you some hint.

```log
2017-08-07 23:31:40 (DEBUG):	Processing 15 new trades. From 2017-08-07 21:31:37 UTC to 2017-08-07 21:31:44 UTC. (a few seconds)
2017-08-07 23:32:00 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
2017-08-07 23:32:01 (DEBUG):	Processing 8 new trades. From 2017-08-07 21:31:55 UTC to 2017-08-07 21:32:06 UTC. (a few seconds)
2017-08-07 23:32:20 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
2017-08-07 23:32:20 (DEBUG):	Processing 7 new trades. From 2017-08-07 21:32:17 UTC to 2017-08-07 21:32:32 UTC. (a few seconds)
2017-08-07 23:32:40 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
2017-08-07 23:32:40 (DEBUG):	kraken returned an error, retrying.. Error: Kraken API returned error: Service:Unavailable
    at Request._callback (/home/tr4sk/gekko/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/tr4sk/gekko/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/tr4sk/gekko/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/tr4sk/gekko/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2017-08-07 23:32:51 (DEBUG):	Processing 6 new trades. From 2017-08-07 21:32:42 UTC to 2017-08-07 21:33:04 UTC. (a few seconds)
2017-08-07 23:33:00 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
2017-08-07 23:33:00 (DEBUG):	Processing 3 new trades. From 2017-08-07 21:33:10 UTC to 2017-08-07 21:33:15 UTC. (a few seconds)
2017-08-07 23:33:20 (DEBUG):	Requested XBT/EUR trade data from Kraken ...
2017-08-07 23:33:20 (DEBUG):	Processing 11 new trades. From 2017-08-07 21:33:20 UTC to 2017-08-07 21:33:32 UTC. (a few seconds)
```

**Comment by askmike** [comment]
This should not be a big problem: Gekko merely logs the error will tries again :)
