### ISSUE TITLE
No getOrder function for btc-markets exchange

### ISSUE THREAD

**Issue by upsatish** [askmike/gekko#935]
The trader for btc-markets throws the following error

/home/ubuntu/gekko/plugins/trader/portfolioManager.js:355
    order => next => this.exchange.getOrder(order, next)
                                   ^

TypeError: this.exchange.getOrder is not a function
    at next (/home/ubuntu/gekko/plugins/trader/portfolioManager.js:355:36)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:3845:9
    at replenish (/home/ubuntu/gekko/node_modules/async/dist/async.js:1030:17)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:1034:9
    at eachOfLimit (/home/ubuntu/gekko/node_modules/async/dist/async.js:1061:22)
    at /home/ubuntu/gekko/node_modules/async/dist/async.js:1066:16
    at _parallel (/home/ubuntu/gekko/node_modules/async/dist/async.js:3844:5)
    at Object.series (/home/ubuntu/gekko/node_modules/async/dist/async.js:4663:3)
    at Manager.relayOrder (/home/ubuntu/gekko/plugins/trader/portfolioManager.js:358:9)
    at Manager.bound [as relayOrder] (/home/ubuntu/gekko/node_modules/lodash/dist/lodash.js:729:21)

**Comment by askmike** [comment]
In the works, see #936 for details.
