### ISSUE TITLE
GDAX - Backtesting in last 24h yields `TypeError: Cannot read property 'currency' of undefined`

### ISSUE THREAD

**Issue by GuyPaddock** [askmike/gekko#990]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
1. Deleted SQLite history database.
2. Imported data since 2017-08-14 at midnite UTC from GDAX using CLI.
3. Attempted to run a backtest using `daterange: 'scan'` from CLI.

* **Expected result** (what you hoped would happen)
Backtest would complete successfully.

* **Actual result** (unexpected outcome)
Fatal error occurred backtesting:
```
2017-08-16 23:33:10 (DEBUG):    calculated MACD properties for candle:
2017-08-16 23:33:10 (DEBUG):             short: 4278.49961348
2017-08-16 23:33:10 (DEBUG):             long: 4266.62376128
2017-08-16 23:33:10 (DEBUG):             macd: 11.87585219
2017-08-16 23:33:10 (DEBUG):             signal: 11.29378142
2017-08-16 23:33:10 (DEBUG):             macdiff: 0.58207078
2017-08-16 23:33:10 (DEBUG):    In no trend
/opt/teamcity/gekko/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'currency' of undefined
    at PerformanceAnalyzer.calculateReportStatistics (/opt/teamcity/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:133:29)
    at PerformanceAnalyzer.bound [as calculateReportStatistics] (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.finalize (/opt/teamcity/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:170:23)
    at PerformanceAnalyzer.bound [as finalize] (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /opt/teamcity/gekko/core/gekkoStream.js:44:9
    at Function.forEach (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:3298:15)
    at Gekko.shutdown (/opt/teamcity/gekko/core/gekkoStream.js:42:5)
    at Base.finish (/opt/teamcity/gekko/plugins/tradingAdvisor/baseTradingMethod.js:322:12)
    at Base.bound [as finish] (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Actor.finish (/opt/teamcity/gekko/plugins/tradingAdvisor/tradingAdvisor.js:80:15)
--> in Database#all('\n    SELECT * from candles_USD_BTC\n    WHERE start <= 1502938560 AND start >= 1502939160\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/opt/teamcity/gekko/plugins/sqlite/reader.js:100:11)
    at Reader.bound [as get] (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/opt/teamcity/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/opt/teamcity/gekko/core/markets/backtest.js:105:10)
    at bound (/opt/teamcity/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/opt/teamcity/gekko/plugins/sqlite/reader.js:110:5)
```
It looks like the specified data range (`start <= 1502938560 AND start >= 1502939160`) is missing when I open the SQLite DB in SQLite explorer.

* **Other information**
I've tried both the `develop` and `stable` branches.

**Comment by askmike** [comment]
Can you upload your config and your dataset (where this happens)?

**Comment by GuyPaddock** [comment]
Requested info is now attached:

[config.js.txt](https://github.com/askmike/gekko/files/1231286/config.js.txt)
[history.zip](https://github.com/askmike/gekko/files/1231290/history.zip)

**Comment by askmike** [comment]
Ah, I should properly check this in Gekko but the problem is simple:

You have configured the performanceAnalyzer, but there is no trading plugin to feed it data (in this case portfolioData). You either need the trader or the paperTrader plugin (since it's a backtest you need the paperTrader plugin). So: simply enable the paperTrader plugin and it works.

----

Note to self: Figure out why this is not caught by [these checks in the pipeline](https://github.com/askmike/gekko/blob/0e8f2b10115eb70fb56aca338f96a388504963ac/core/pipeline.js#L112-L131).

**Comment by GuyPaddock** [comment]
@askmike Aha! This explains why it works through the UI on the same data set.

**Comment by askmike** [comment]
The UI builds a config dynamically and runs a Gekko based on it. You can look at the generated config by inspecting the POST request in your browser's developer tools like so:

<img width="1398" alt="screen shot 2017-08-18 at 21 59 08" src="https://user-images.githubusercontent.com/969743/29477486-7d3cab18-8460-11e7-86fb-d999d08e2f2b.png">

(at the far bottom at request payload).
